help add_item
show_items
put item3
whoami
create_folder folder2
register_user user9 pass9
show_folders
sign_in a4 pa4
sign_out
register_admin user4 pass4
create_folder folder4
register_admin admin admin
cd folder1
help pwd
add_item_property item5 key1=val5 key5=val6 key3=val1 key1=val8 
which_group
ls
help rename_user
ls_folders
show_item_properties item3
show_item_properties item4
show_users
show_folders
add_item_property item1 key3=val7 key8=val10 key5=val4 key4=val6 
show_item_properties item2
add_item_property item2 key3=val3 key1=val4 key7=val5 key4=val6 
whoami
show_users
ls_folders
register_user user2 pass2
put item4
add_item item1 key6=val5 key4=val2 key4=val2 key3=val2 
sign_in user5 pass5
which_group
show_users
sign_out
show_users
buy
ls_folders
show_folders
ls
rename_user user4 <function generate_user at 0x027087F0>
register_admin admin admin
put item5
sign_out
pwd
add_item item4 key9=val8 key3=val3 key4=val8 key6=val1 
register_admin user5 pass5
sign_in admin admin
whoami
register_admin user7 pass7
register_user user9 pass9
sign_in a2 pa2
pwd
add_item item1 key3=val2 key7=val2 key5=val1 key8=val4 
buy
add_item item3 key9=val4 key6=val5 key3=val8 key3=val10 
add_item item1 key9=val6 key3=val1 key10=val3 key2=val4 
show_item_properties item5
show_users
show_item_properties item1
cd folder4
ls
ls
sign_in admin admin
sign_out
show_items
register_admin user9 pass9
show_users
which_group
current_folder
create_folder folder1
show_item_properties item3
cd folder1
rename_user user2 <function generate_user at 0x027087F0>
show_items
show_item_properties item2
show_items
current_folder
pwd
register_user user8 pass8
add_item_property item4 key10=val6 key5=val3 key3=val4 key3=val5 
show_folders
pwd
register_user user2 pass2
show_folders
whoami
put item5
show_users
show_users
pwd
put item2
ls_folders
whoami
show_folders
which_group
ls_folders
show_folders
current_folder
show_item_properties item5
add_item item2 key3=val5 key8=val10 key7=val1 key5=val9 
put item2
buy
show_items
buy
whoami
ls_folders
ls
put item4
show_items
sign_in user3 pass3
cd folder2
add_item_property item2 key7=val2 key3=val2 key5=val1 key7=val5 
whoami
buy
add_item_property item3 key6=val10 key5=val2 key10=val1 key6=val1 
show_users
which_group
put item4
show_folders
ls
put item2
rename_user user3 <function generate_user at 0x027087F0>
sign_in a2 pa2
register_user user7 pass7
pwd
whoami
ls_folders
create_folder folder4
ls
put item5
current_folder
put item5
register_user user3 pass3
show_users
show_folders
create_folder folder1
help buy
which_group
show_users
which_group
ls_folders
put item3
whoami
pwd
put item2
show_items
register_admin user8 pass8
register_user user2 pass2
sign_in a1 pa1
ls_folders
show_item_properties item5
pwd
current_folder
show_items
register_admin user3 pass3
whoami
whoami
show_item_properties item1
add_item_property item4 key10=val10 key1=val8 key9=val7 key3=val4 
buy
add_item_property item4 key6=val8 key3=val8 key4=val1 key9=val6 
register_user user5 pass5
rename_user user5 <function generate_user at 0x027087F0>
which_group
sign_in user9 pass9
add_item item1 key4=val8 key8=val7 key10=val2 key5=val2 
show_users
ls
sign_out
cd folder1
add_item item2 key1=val7 key2=val9 key6=val7 key9=val8 
register_user user6 pass6
show_folders
rename_user user4 <function generate_user at 0x027087F0>
show_item_properties item5
buy
sign_in a1 pa1
ls
create_folder folder1
current_folder
register_user user5 pass5
sign_in a1 pa1
create_folder folder4
cd folder3
show_folders
add_item_property item1 key4=val8 key10=val2 key2=val6 key2=val7 
create_folder folder5
whoami
register_user user4 pass4
rename_user user1 <function generate_user at 0x027087F0>
current_folder
buy
put item1
help exit
show_items
register_user user8 pass8
show_items
show_users
register_user user2 pass2
sign_in admin admin
create_folder folder1
show_folders
show_users
help view_order
whoami
show_users
buy
show_item_properties item4
pwd
show_item_properties item4
show_users
create_folder folder4
sign_in a2 pa2
rename_user user8 <function generate_user at 0x027087F0>
show_users
show_item_properties item4
add_item_property item4 key7=val10 key7=val8 key10=val4 key3=val9 
cd folder5
whoami
pwd
create_folder folder5
add_item_property item3 key10=val8 key7=val2 key8=val2 key7=val6 
rename_user user4 <function generate_user at 0x027087F0>
show_folders
which_group
sign_out
add_item item2 key6=val7 key3=val5 key5=val2 key4=val6 
ls
buy
show_users
current_folder
current_folder
pwd
show_users
register_admin user7 pass7
register_admin admin admin
sign_in a4 pa4
rename_user user4 <function generate_user at 0x027087F0>
current_folder
whoami
ls
cd folder2
show_item_properties item4
put item2
whoami
create_folder folder4
put item4
current_folder
add_item_property item3 key5=val5 key8=val4 key3=val9 key7=val8 
sign_in user6 pass6
create_folder folder4
sign_in user8 pass8
help history
show_folders
current_folder
show_item_properties item2
show_item_properties item5
current_folder
show_item_properties item5
show_item_properties item1
create_folder folder2
help ls
which_group
cd folder2
show_folders
show_items
rename_user user3 <function generate_user at 0x027087F0>
show_item_properties item3
add_item item3 key6=val7 key8=val8 key6=val5 key6=val6 
register_admin user5 pass5
show_items
register_user user6 pass6
buy
create_folder folder1
ls
add_item item5 key2=val5 key1=val3 key1=val6 key4=val5 
register_user user9 pass9
register_admin admin admin
show_item_properties item2
register_user user9 pass9
show_users
whoami
show_folders
sign_in a1 pa1
which_group
add_item item3 key10=val1 key6=val10 key7=val9 key5=val1 
put item2
help help
register_user user1 pass1
show_item_properties item3
pwd
rename_user user9 <function generate_user at 0x027087F0>
show_item_properties item3
sign_out
put item1
buy
add_item item1 key5=val3 key1=val8 key8=val7 key7=val6 
show_item_properties item3
sign_in user3 pass3
add_item item1 key3=val7 key2=val5 key9=val5 key9=val7 
show_item_properties item2
show_users
rename_user user8 <function generate_user at 0x027087F0>
which_group
rename_user user7 <function generate_user at 0x027087F0>
show_folders
ls
cd folder4
sign_out
register_user user5 pass5
create_folder folder4
sign_out
add_item item5 key6=val9 key8=val5 key3=val8 key4=val1 
sign_in a1 pa1
ls
show_items
ls
put item4
put item4
show_items
show_items
put item3
whoami
show_items
show_users
add_item_property item1 key3=val4 key8=val6 key8=val3 key10=val8 
show_folders
sign_in user4 pass4
buy
put item1
show_folders
put item1
buy
show_item_properties item3
add_item_property item2 key2=val7 key5=val4 key8=val8 key2=val8 
add_item_property item1 key9=val8 key8=val6 key7=val4 key1=val7 
help register_admin
put item1
current_folder
show_item_properties item4
cd folder4
show_users
whoami
show_item_properties item5
sign_in user6 pass6
pwd
which_group
sign_out
help which_group
whoami
current_folder
help rename_user
which_group
put item4
whoami
sign_out
show_users
pwd
show_items
add_item item4 key1=val3 key3=val10 key6=val1 key7=val7 
help rename_user
help which_group
sign_out
show_items
register_admin admin admin
buy
rename_user user8 <function generate_user at 0x027087F0>
pwd
cd folder1
sign_out
add_item_property item5 key7=val5 key7=val3 key10=val3 key7=val2 
show_item_properties item3
pwd
create_folder folder4
register_admin user2 pass2
show_item_properties item4
sign_in a1 pa1
create_folder folder4
sign_in user4 pass4
add_item item4 key7=val2 key5=val7 key4=val8 key8=val6 
register_user user9 pass9
ls
ls_folders
current_folder
add_item item1 key6=val4 key5=val3 key4=val2 key4=val3 
show_folders
add_item item4 key2=val10 key4=val5 key9=val4 key1=val5 
rename_user user2 <function generate_user at 0x027087F0>
sign_out
show_item_properties item4
buy
pwd
whoami
whoami
rename_user user3 <function generate_user at 0x027087F0>
show_item_properties item1
current_folder
add_item item1 key10=val7 key8=val6 key10=val2 key7=val10 
show_item_properties item5
rename_user user1 <function generate_user at 0x027087F0>
rename_user user3 <function generate_user at 0x027087F0>
ls
sign_in a3 pa3
whoami
show_folders
show_users
show_users
ls
add_item_property item3 key3=val9 key8=val5 key3=val9 key7=val5 
add_item_property item2 key9=val4 key3=val5 key10=val10 key9=val10 
add_item_property item2 key2=val7 key1=val7 key8=val4 key4=val5 
cd folder5
sign_in admin admin
help create_folder
add_item item5 key8=val3 key7=val7 key2=val3 key1=val3 
add_item_property item2 key3=val2 key9=val10 key4=val9 key8=val5 
show_items
help show_folders
ls_folders
sign_in a4 pa4
current_folder
help cd
rename_user user7 <function generate_user at 0x027087F0>
which_group
create_folder folder4
cd folder4
sign_in a4 pa4
pwd
sign_in a3 pa3
sign_in a1 pa1
add_item_property item1 key5=val6 key3=val1 key6=val1 key8=val6 
which_group
sign_out
sign_in a2 pa2
sign_in a4 pa4
put item4
current_folder
show_users
add_item_property item4 key4=val5 key5=val7 key2=val9 key9=val7 
which_group
register_admin user6 pass6
current_folder
register_user user6 pass6
register_user user3 pass3
register_admin admin admin
whoami
add_item item4 key3=val1 key3=val10 key5=val7 key2=val10 
which_group
cd folder5
ls
show_users
show_folders
sign_out
whoami
sign_in user1 pass1
buy
show_folders
show_items
which_group
cd folder3
cd folder2
add_item item1 key7=val10 key8=val7 key3=val1 key6=val4 
ls
current_folder
show_users
pwd
register_user user3 pass3
whoami
rename_user user0 <function generate_user at 0x027087F0>
register_admin user2 pass2
put item5
show_folders
put item4
ls
show_item_properties item3
current_folder
add_item item3 key10=val2 key8=val5 key7=val1 key7=val4 
buy
show_item_properties item1
register_admin user9 pass9
which_group
rename_user user3 <function generate_user at 0x027087F0>
put item5
sign_out
ls
show_items
show_item_properties item5
help sign_out
pwd
ls
current_folder
create_folder folder1
sign_out
help rename_user
help show_users
add_item item4 key8=val6 key8=val9 key6=val6 key6=val9 
sign_in a4 pa4
ls_folders
cd folder2
which_group
add_item item3 key4=val6 key1=val3 key5=val2 key1=val5 
show_users
current_folder
sign_out
pwd
create_folder folder1
sign_out
register_admin user7 pass7
cd folder5
add_item item4 key5=val8 key8=val10 key1=val8 key10=val8 
show_items
whoami
ls
cd folder2
register_admin admin admin
buy
ls
show_users
cd folder3
show_folders
add_item item5 key8=val7 key6=val8 key2=val9 key2=val6 
register_user user1 pass1
cd folder3
add_item_property item3 key10=val4 key4=val8 key5=val8 key3=val9 
sign_in user8 pass8
sign_in a2 pa2
cd folder5
cd folder3
add_item item4 key7=val4 key6=val4 key9=val3 key8=val2 
sign_in user4 pass4
ls_folders
pwd
show_folders
current_folder
current_folder
help create_folder
register_user admin admin
rename_user user8 <function generate_user at 0x027087F0>
register_user user2 pass2
add_item_property item2 key7=val2 key5=val7 key6=val10 key5=val9 
buy
register_admin user1 pass1
which_group
put item1
ls_folders
add_item item2 key10=val6 key2=val3 key4=val7 key5=val3 
buy
show_items
sign_out
pwd
add_item_property item4 key2=val4 key5=val7 key9=val2 key9=val6 
add_item_property item4 key7=val5 key1=val2 key6=val10 key6=val5 
show_items
sign_out
show_folders
create_folder folder3
pwd
show_folders
buy
buy
whoami
create_folder folder4
pwd
ls
rename_user user3 <function generate_user at 0x027087F0>
sign_out
sign_in a1 pa1
register_admin user8 pass8
add_item item2 key2=val10 key2=val4 key3=val1 key5=val4 
help show_items
whoami
show_item_properties item2
show_items
add_item item4 key6=val8 key10=val7 key1=val4 key2=val10 
current_folder
show_folders
sign_out
show_folders
put item1
add_item item1 key1=val3 key1=val2 key7=val4 key1=val10 
sign_in a2 pa2
create_folder folder4
show_folders
cd folder2
help delete_user
register_user user6 pass6
whoami
sign_in a3 pa3
show_items
cd folder4
show_folders
create_folder folder5
sign_out
put item2
add_item item3 key3=val7 key5=val5 key6=val9 key9=val6 
put item5
sign_in user6 pass6
create_folder folder4
put item5
rename_user user4 <function generate_user at 0x027087F0>
which_group
register_user user6 pass6
cd folder2
sign_in a4 pa4
show_item_properties item5
put item2
rename_user user9 <function generate_user at 0x027087F0>
add_item_property item3 key1=val10 key2=val1 key7=val10 key6=val4 
help create_folder
register_user user9 pass9
add_item_property item3 key6=val4 key9=val7 key10=val5 key7=val8 
rename_user user4 <function generate_user at 0x027087F0>
sign_in user3 pass3
show_folders
create_folder folder4
add_item_property item3 key5=val4 key5=val5 key6=val7 key5=val8 
sign_out
help create_folder
create_folder folder3
ls_folders
cd folder3
show_items
sign_out
ls
whoami
which_group
sign_out
put item1
show_folders
which_group
create_folder folder3
buy
register_user admin admin
add_item item3 key8=val9 key10=val2 key3=val7 key5=val10 
ls_folders
add_item_property item3 key7=val10 key10=val9 key6=val1 key10=val5 
pwd
sign_out
show_items
which_group
which_group
ls_folders
register_admin user4 pass4
show_item_properties item3
which_group
create_folder folder5
register_user user9 pass9
put item2
current_folder
cd folder1
pwd
current_folder
register_admin user6 pass6
show_items
current_folder
create_folder folder4
cd folder2
sign_out
show_folders
buy
show_item_properties item4
register_admin user5 pass5
sign_in user5 pass5
cd folder3
which_group
create_folder folder2
which_group
whoami
create_folder folder4
show_users
sign_in user6 pass6
add_item item2 key5=val7 key8=val1 key7=val7 key5=val5 
buy
sign_in user1 pass1
sign_out
register_user user4 pass4
sign_in a5 pa5
add_item item2 key2=val7 key9=val8 key1=val10 key10=val6 
sign_in user1 pass1
which_group
buy
show_users
help buy
rename_user user6 <function generate_user at 0x027087F0>
put item3
show_users
pwd
rename_user user8 <function generate_user at 0x027087F0>
create_folder folder2
add_item item5 key8=val6 key5=val9 key2=val9 key2=val10 
help show_folders
add_item item5 key6=val5 key1=val1 key2=val10 key1=val8 
current_folder
show_item_properties item5
cd folder1
show_folders
buy
show_items
add_item item1 key9=val7 key2=val8 key9=val9 key10=val1 
buy
pwd
register_user user6 pass6
show_item_properties item1
register_user user8 pass8
add_item item5 key8=val3 key3=val4 key5=val1 key5=val6 
ls_folders
put item3
sign_in a1 pa1
help show_item_properties
register_admin user9 pass9
whoami
sign_in user7 pass7
rename_user user9 <function generate_user at 0x027087F0>
show_users
register_admin user9 pass9
add_item item2 key2=val10 key8=val5 key6=val5 key1=val5 
buy
help register_user
add_item item4 key7=val8 key10=val4 key4=val3 key4=val6 
sign_in a5 pa5
ls
whoami
ls_folders
show_folders
register_admin user9 pass9
show_users
sign_out
buy
register_admin user4 pass4
cd folder1
show_users
current_folder
sign_out
current_folder
show_users
show_items
show_users
add_item_property item2 key4=val9 key7=val8 key9=val1 key7=val9 
help view_order
register_admin user5 pass5
put item4
add_item item5 key10=val9 key3=val9 key1=val3 key7=val3 
rename_user user9 <function generate_user at 0x027087F0>
create_folder folder3
add_item item5 key1=val1 key8=val10 key3=val5 key6=val10 
which_group
rename_user user3 <function generate_user at 0x027087F0>
ls_folders
show_items
whoami
register_user admin admin
register_admin user5 pass5
sign_in user6 pass6
add_item item3 key8=val7 key3=val10 key9=val9 key4=val8 
sign_in user1 pass1
sign_in user4 pass4
add_item item5 key8=val2 key9=val9 key8=val1 key6=val4 
add_item_property item1 key7=val5 key5=val8 key3=val6 key2=val10 
show_item_properties item2
sign_out
which_group
show_users
sign_out
sign_out
current_folder
register_user user1 pass1
put item2
show_item_properties item5
show_item_properties item1
show_users
ls_folders
show_users
sign_in user6 pass6
whoami
show_folders
whoami
register_user user8 pass8
ls_folders
cd folder4
cd folder2
register_user user8 pass8
which_group
cd folder2
put item2
register_admin user7 pass7
add_item_property item5 key7=val4 key1=val6 key3=val6 key2=val1 
add_item item1 key1=val6 key6=val1 key3=val9 key6=val10 
register_admin user4 pass4
rename_user user0 <function generate_user at 0x027087F0>
cd folder5
show_items
add_item_property item1 key6=val2 key10=val3 key9=val6 key5=val5 
which_group
sign_in a5 pa5
cd folder1
add_item_property item1 key6=val1 key5=val7 key5=val8 key4=val3 
help current_folder
show_item_properties item2
create_folder folder5
buy
sign_out
which_group
help add_item_property
show_item_properties item1
sign_in user3 pass3
sign_in user2 pass2
whoami
buy
sign_out
whoami
sign_in a2 pa2
register_user user2 pass2
add_item item2 key3=val6 key3=val10 key9=val2 key4=val6 
show_item_properties item3
create_folder folder5
current_folder
sign_in a1 pa1
register_admin user5 pass5
show_folders
create_folder folder3
sign_out
ls
create_folder folder4
put item2
add_item_property item5 key6=val2 key4=val10 key6=val8 key8=val8 
show_item_properties item2
put item3
current_folder
which_group
put item3
sign_in a5 pa5
sign_in user9 pass9
show_item_properties item2
show_item_properties item2
sign_in a3 pa3
put item4
put item5
ls_folders
cd folder5
whoami
register_user user4 pass4
show_items
sign_in user1 pass1
which_group
show_folders
put item1
show_folders
whoami
current_folder
show_items
show_users
sign_out
current_folder
show_items
show_item_properties item1
register_user admin admin
show_users
buy
show_users
show_items
current_folder
cd folder5
ls
pwd
which_group
add_item item5 key5=val2 key4=val2 key3=val4 key9=val8 
sign_out
add_item_property item4 key9=val5 key9=val9 key2=val1 key3=val4 
register_user user9 pass9
pwd
add_item_property item4 key7=val6 key6=val1 key10=val9 key9=val3 
add_item item4 key2=val1 key2=val10 key3=val4 key7=val2 
create_folder folder2
put item2
show_users
register_user user2 pass2
cd folder3
ls
sign_in user8 pass8
ls
whoami
cd folder1
add_item_property item3 key6=val1 key5=val9 key10=val8 key10=val3 
whoami
rename_user user7 <function generate_user at 0x027087F0>
help cd
help show_users
ls
ls
sign_out
whoami
whoami
show_users
buy
current_folder
add_item_property item5 key3=val5 key3=val7 key3=val10 key5=val6 
show_item_properties item1
help delete_user
help pwd
register_admin admin admin
rename_user user1 <function generate_user at 0x027087F0>
create_folder folder5
cd folder2
show_item_properties item2
sign_in a2 pa2
show_folders
which_group
add_item item2 key9=val1 key4=val9 key10=val4 key8=val2 
which_group
register_user user3 pass3
add_item_property item5 key3=val1 key5=val3 key8=val7 key1=val2 
whoami
pwd
cd folder5
ls
which_group
add_item item3 key6=val1 key2=val9 key5=val4 key3=val6 
sign_out
ls
which_group
register_user user3 pass3
which_group
show_items
show_users
whoami
buy
cd folder4
show_item_properties item1
add_item_property item2 key1=val7 key2=val7 key1=val6 key3=val2 
show_users
buy
add_item_property item4 key10=val3 key1=val2 key8=val6 key1=val8 
help current_folder
add_item item5 key8=val5 key10=val3 key3=val5 key5=val7 
help ls_folders
ls_folders
sign_in a5 pa5
show_folders
add_item_property item5 key6=val6 key2=val9 key2=val1 key6=val2 
whoami
help sign_in
put item2
buy
buy
buy
cd folder5
which_group
add_item item4 key5=val1 key10=val8 key2=val4 key1=val2 
register_user user2 pass2
ls_folders
sign_out
show_items
pwd
pwd
add_item item2 key3=val10 key6=val1 key5=val4 key3=val7 
sign_in user2 pass2
buy
add_item item5 key1=val10 key9=val4 key1=val4 key10=val4 
cd folder4
which_group
rename_user user9 <function generate_user at 0x027087F0>
buy
ls
sign_in a1 pa1
sign_in admin admin
rename_user user5 <function generate_user at 0x027087F0>
create_folder folder2
add_item_property item4 key1=val6 key3=val10 key8=val6 key2=val3 
which_group
whoami
help rename_user
show_item_properties item4
put item3
sign_in user6 pass6
which_group
cd folder1
sign_in user8 pass8
rename_user user7 <function generate_user at 0x027087F0>
rename_user user7 <function generate_user at 0x027087F0>
register_admin user9 pass9
create_folder folder5
buy
create_folder folder1
register_user user5 pass5
sign_in user7 pass7
show_folders
ls_folders
pwd
register_user admin admin
pwd
add_item_property item4 key1=val7 key7=val5 key7=val5 key5=val2 
pwd
show_items
put item5
show_items
ls_folders
show_item_properties item4
which_group
rename_user user6 <function generate_user at 0x027087F0>
rename_user user9 <function generate_user at 0x027087F0>
buy
show_users
cd folder1
add_item item1 key9=val9 key2=val6 key7=val8 key1=val9 
help whoami
ls_folders
show_item_properties item3
pwd
which_group
add_item_property item3 key1=val6 key8=val7 key5=val1 key3=val2 
pwd
current_folder
ls
ls_folders
add_item_property item2 key7=val9 key9=val8 key5=val10 key3=val2 
ls
ls
put item2
add_item item2 key1=val3 key6=val1 key3=val6 key5=val10 
help sign_in
whoami
help register_user
pwd
sign_in a5 pa5
show_item_properties item1
current_folder
buy
current_folder
buy
register_admin user6 pass6
add_item item2 key10=val6 key3=val3 key9=val2 key9=val1 
sign_in a3 pa3
register_user user4 pass4
show_folders
rename_user user8 <function generate_user at 0x027087F0>
rename_user user2 <function generate_user at 0x027087F0>
show_users
add_item_property item2 key7=val2 key10=val7 key6=val1 key3=val4 
buy
show_users
sign_out
buy
buy
create_folder folder4
pwd
sign_in user4 pass4
help exit
whoami
show_users
register_user user8 pass8
register_user user5 pass5
show_folders
sign_in a4 pa4
help put
sign_in user1 pass1
show_item_properties item1
create_folder folder1
ls
register_user user8 pass8
put item5
register_user user4 pass4
ls
sign_out
sign_in a1 pa1
cd folder1
ls
create_folder folder2
add_item item3 key9=val1 key7=val6 key10=val3 key5=val2 
show_users
ls_folders
cd folder3
show_items
sign_in user2 pass2
show_item_properties item4
register_admin user5 pass5
sign_out
show_items
put item3
ls_folders
sign_in a4 pa4
buy
show_items
show_item_properties item5
pwd
help register_admin
sign_out
sign_in a4 pa4
show_users
register_user user9 pass9
register_user user1 pass1
pwd
register_admin user1 pass1
sign_in a3 pa3
add_item_property item3 key5=val6 key4=val6 key3=val10 key6=val3 
create_folder folder3
help pwd
add_item_property item5 key10=val10 key1=val10 key9=val10 key4=val8 
create_folder folder5
add_item item2 key8=val3 key10=val9 key10=val1 key8=val7 
which_group
sign_in a1 pa1
create_folder folder4
register_admin user9 pass9
cd folder5
which_group
put item2
pwd
help register_user
register_user user2 pass2
ls
add_item item5 key2=val4 key10=val10 key8=val10 key5=val8 
show_users
current_folder
help ls
register_admin user5 pass5
show_items
show_folders
which_group
rename_user user3 <function generate_user at 0x027087F0>
show_folders
show_item_properties item4
sign_out
add_item item4 key8=val9 key2=val2 key3=val5 key1=val5 
buy
add_item item5 key4=val8 key9=val1 key7=val8 key1=val3 
which_group
ls_folders
add_item_property item4 key6=val5 key6=val1 key8=val6 key5=val8 
show_item_properties item5
which_group
show_items
add_item_property item4 key4=val5 key7=val4 key5=val9 key1=val6 
rename_user user4 <function generate_user at 0x027087F0>
show_item_properties item5
pwd
show_users
current_folder
buy
put item3
sign_in a1 pa1
pwd
pwd
show_items
register_admin user7 pass7
create_folder folder1
show_folders
which_group
cd folder4
sign_out
ls
create_folder folder3
show_items
create_folder folder4
which_group
add_item_property item1 key2=val5 key6=val9 key10=val4 key8=val6 
current_folder
add_item_property item2 key8=val10 key3=val7 key9=val1 key8=val4 
register_admin user3 pass3
register_admin user6 pass6
show_item_properties item2
show_users
sign_in a1 pa1
create_folder folder1
cd folder5
which_group
sign_in user8 pass8
sign_in user8 pass8
pwd
register_admin user8 pass8
show_item_properties item5
sign_in a5 pa5
ls_folders
register_admin admin admin
buy
pwd
sign_in a5 pa5
register_admin user8 pass8
cd folder5
ls_folders
ls_folders
ls
sign_out
show_item_properties item5
show_item_properties item4
help show_users
put item4
help history
which_group
add_item_property item5 key8=val4 key2=val10 key8=val7 key1=val8 
which_group
help show_users
buy
sign_in user1 pass1
create_folder folder1
show_users
sign_out
add_item item1 key8=val10 key9=val3 key8=val7 key1=val9 
buy
sign_in user5 pass5
sign_in a2 pa2
cd folder1
add_item_property item4 key7=val1 key9=val10 key4=val5 key5=val7 
help sign_in
cd folder2
cd folder4
which_group
help view_order
add_item item4 key4=val2 key6=val9 key5=val9 key7=val5 
current_folder
sign_out
register_user admin admin
register_admin user7 pass7
show_folders
ls_folders
sign_in a2 pa2
show_users
buy
buy
put item4
current_folder
show_items
create_folder folder2
whoami
which_group
show_items
sign_in user8 pass8
which_group
put item5
current_folder
help add_item
show_users
sign_in user5 pass5
help pwd
put item2
buy
rename_user user0 <function generate_user at 0x027087F0>
show_items
show_folders
cd folder1
sign_in user5 pass5
create_folder folder4
whoami
show_items
sign_in a5 pa5
show_items
whoami
help put
sign_in user8 pass8
current_folder
whoami
register_user user4 pass4
cd folder3
show_folders
buy
show_users
add_item_property item2 key6=val10 key2=val9 key2=val8 key9=val6 
which_group
show_item_properties item1
add_item item4 key3=val8 key1=val9 key8=val2 key7=val8 
ls
which_group
ls_folders
help sign_out
add_item_property item2 key2=val9 key10=val2 key5=val2 key5=val2 
show_items
help which_group
register_user admin admin
help cd
ls
show_users
which_group
ls_folders
register_admin user7 pass7
help add_item_property
help pwd
put item1
add_item item1 key2=val6 key3=val10 key2=val5 key2=val8 
cd folder3
show_item_properties item5
sign_out
buy
buy
sign_in user1 pass1
ls_folders
ls
which_group
show_users
pwd
add_item item3 key2=val9 key9=val4 key8=val5 key7=val7 
pwd
show_item_properties item2
sign_in a2 pa2
pwd
put item2
show_users
buy
put item1
current_folder
buy
register_admin user4 pass4
register_admin user6 pass6
buy
rename_user user2 <function generate_user at 0x027087F0>
show_items
help exit
show_folders
register_admin user5 pass5
put item5
create_folder folder2
register_user user5 pass5
register_admin user2 pass2
whoami
current_folder
ls_folders
buy
ls
which_group
current_folder
ls
add_item item4 key2=val10 key6=val7 key6=val4 key7=val7 
sign_in user7 pass7
sign_out
show_folders
add_item_property item5 key8=val10 key4=val4 key1=val7 key8=val4 
show_folders
buy
show_folders
sign_out
which_group
help exit
current_folder
sign_in a3 pa3
current_folder
show_folders
whoami
put item1
show_item_properties item1
put item5
put item3
sign_out
add_item_property item5 key3=val2 key6=val7 key10=val4 key2=val1 
add_item item3 key7=val1 key1=val8 key5=val7 key7=val10 
buy
which_group
register_admin admin admin
show_users
sign_in user4 pass4
rename_user user8 <function generate_user at 0x027087F0>
show_item_properties item4
which_group
sign_in user2 pass2
add_item_property item5 key4=val1 key5=val9 key3=val2 key1=val4 
buy
rename_user user2 <function generate_user at 0x027087F0>
sign_out
add_item_property item1 key3=val6 key7=val3 key9=val6 key8=val2 
add_item item3 key4=val7 key10=val6 key9=val10 key4=val10 
current_folder
ls
show_users
show_items
buy
register_user user4 pass4
show_folders
put item1
add_item_property item5 key3=val6 key8=val9 key1=val2 key2=val5 
add_item item2 key6=val6 key1=val5 key6=val4 key5=val1 
sign_out
pwd
put item1
sign_in a1 pa1
cd folder5
ls
ls_folders
show_items
sign_in user8 pass8
show_item_properties item2
sign_in a1 pa1
ls_folders
show_users
show_folders
show_folders
sign_in user9 pass9
register_user user8 pass8
help buy
sign_out
add_item item5 key8=val1 key4=val6 key7=val6 key5=val1 
sign_in user5 pass5
cd folder3
register_user user5 pass5
pwd
buy
add_item_property item4 key9=val9 key5=val10 key2=val6 key2=val6 
sign_in a3 pa3
sign_in user3 pass3
rename_user user1 <function generate_user at 0x027087F0>
rename_user user9 <function generate_user at 0x027087F0>
whoami
help register_admin
show_item_properties item3
show_folders
ls
register_admin user9 pass9
add_item item5 key10=val3 key2=val8 key4=val5 key1=val1 
create_folder folder2
sign_in a4 pa4
show_items
ls
sign_in user8 pass8
register_admin user7 pass7
put item5
put item3
show_items
sign_in a5 pa5
whoami
show_items
add_item item4 key9=val3 key3=val6 key5=val8 key4=val2 
create_folder folder3
show_folders
whoami
register_user admin admin
cd folder3
show_items
show_folders
current_folder
ls
create_folder folder5
create_folder folder5
whoami
ls
show_users
whoami
sign_in a2 pa2
sign_in a4 pa4
ls
show_folders
pwd
cd folder5
create_folder folder1
sign_out
sign_in a2 pa2
show_folders
register_admin user7 pass7
register_admin user2 pass2
sign_out
show_item_properties item1
create_folder folder5
register_user user5 pass5
register_admin user2 pass2
show_items
whoami
sign_out
whoami
whoami
rename_user user9 <function generate_user at 0x027087F0>
ls_folders
create_folder folder5
current_folder
add_item_property item3 key1=val7 key3=val3 key8=val7 key7=val8 
show_folders
sign_in a1 pa1
show_folders
rename_user user5 <function generate_user at 0x027087F0>
create_folder folder1
register_admin user6 pass6
rename_user user7 <function generate_user at 0x027087F0>
pwd
add_item item1 key7=val4 key2=val9 key9=val5 key9=val9 
buy
show_folders
sign_out
rename_user user2 <function generate_user at 0x027087F0>
show_items
register_user user2 pass2
add_item_property item3 key7=val3 key10=val2 key3=val3 key8=val7 
pwd
ls
cd folder1
register_user user3 pass3
register_admin user7 pass7
buy
show_users
pwd
create_folder folder1
ls
show_users
which_group
register_user user8 pass8
ls
cd folder4
add_item item1 key6=val2 key6=val6 key1=val8 key4=val7 
pwd
help current_folder
sign_in a1 pa1
buy
put item3
rename_user user1 <function generate_user at 0x027087F0>
buy
sign_in a4 pa4
pwd
sign_in a3 pa3
sign_in user3 pass3
which_group
register_admin user3 pass3
sign_in a1 pa1
sign_out
add_item item1 key4=val4 key3=val5 key2=val1 key8=val6 
add_item_property item2 key5=val3 key6=val7 key7=val5 key1=val10 
show_users
cd folder4
show_items
ls_folders
current_folder
register_admin user2 pass2
show_users
show_folders
pwd
sign_in user2 pass2
which_group
sign_out
whoami
show_users
cd folder3
ls
add_item_property item3 key7=val8 key6=val1 key7=val5 key10=val2 
register_admin user5 pass5
whoami
show_users
register_admin user3 pass3
whoami
whoami
sign_in a4 pa4
register_user user7 pass7
rename_user user5 <function generate_user at 0x027087F0>
ls_folders
register_admin user7 pass7
show_item_properties item3
sign_in user1 pass1
sign_in a2 pa2
create_folder folder2
whoami
sign_in a5 pa5
which_group
show_item_properties item5
add_item item3 key2=val9 key10=val5 key10=val6 key4=val2 
create_folder folder2
which_group
buy
show_users
add_item_property item5 key9=val5 key1=val2 key3=val10 key9=val4 
sign_out
create_folder folder4
add_item_property item2 key10=val3 key4=val4 key2=val4 key3=val4 
rename_user user0 <function generate_user at 0x027087F0>
whoami
show_items
add_item item3 key10=val6 key1=val1 key10=val5 key10=val5 
buy
put item5
rename_user user2 <function generate_user at 0x027087F0>
show_folders
register_user user1 pass1
register_admin user8 pass8
put item4
sign_out
sign_out
ls
rename_user user7 <function generate_user at 0x027087F0>
put item3
ls_folders
create_folder folder4
sign_in user9 pass9
put item4
rename_user user9 <function generate_user at 0x027087F0>
which_group
register_user user4 pass4
put item2
show_items
ls_folders
buy
show_folders
register_user user4 pass4
help current_folder
sign_out
register_admin user1 pass1
show_items
put item2
show_folders
cd folder5
which_group
show_items
sign_out
whoami
whoami
ls_folders
current_folder
show_item_properties item5
help help
show_folders
pwd
pwd
register_admin admin admin
put item4
sign_in user4 pass4
add_item_property item4 key5=val7 key2=val2 key2=val5 key6=val6 
sign_in a4 pa4
sign_in user3 pass3
show_users
show_users
ls
show_folders
register_admin user2 pass2
show_item_properties item2
which_group
create_folder folder1
register_user user7 pass7
sign_in a2 pa2
show_items
help whoami
current_folder
ls_folders
pwd
register_user user7 pass7
register_user user7 pass7
show_folders
put item2
which_group
register_admin user7 pass7
add_item_property item4 key2=val10 key1=val5 key2=val3 key9=val7 
ls
help add_item_property
show_item_properties item4
current_folder
add_item item4 key6=val10 key4=val1 key10=val10 key3=val2 
show_users
add_item_property item3 key1=val3 key7=val5 key5=val2 key7=val3 
ls
ls
add_item_property item3 key8=val1 key10=val6 key8=val8 key10=val6 
add_item_property item4 key8=val7 key5=val6 key5=val5 key1=val2 
register_user user7 pass7
ls
create_folder folder4
sign_in user5 pass5
add_item_property item2 key4=val9 key2=val7 key8=val8 key2=val5 
pwd
rename_user user1 <function generate_user at 0x027087F0>
pwd
register_admin user7 pass7
sign_out
put item3
register_admin user4 pass4
sign_out
register_admin user8 pass8
help sign_in
register_user user3 pass3
show_item_properties item3
current_folder
register_admin user5 pass5
show_users
show_folders
whoami
which_group
buy
register_admin admin admin
cd folder2
show_folders
register_user user4 pass4
register_admin user1 pass1
put item2
which_group
add_item item2 key6=val10 key1=val9 key4=val2 key3=val7 
show_users
sign_in a2 pa2
create_folder folder4
show_item_properties item5
add_item item3 key9=val4 key9=val4 key7=val4 key1=val10 
put item5
which_group
put item1
create_folder folder4
register_user user8 pass8
create_folder folder4
add_item_property item4 key10=val5 key6=val3 key6=val8 key8=val10 
ls_folders
show_items
ls
sign_out
sign_out
rename_user user4 <function generate_user at 0x027087F0>
sign_in a3 pa3
add_item_property item4 key6=val6 key1=val6 key4=val1 key7=val10 
cd folder1
show_item_properties item3
buy
cd folder3
ls_folders
current_folder
whoami
show_item_properties item1
cd folder2
ls_folders
current_folder
show_items
rename_user user0 <function generate_user at 0x027087F0>
show_item_properties item3
ls
show_item_properties item3
help rename_user
buy
current_folder
sign_out
show_items
show_users
help exit
buy
which_group
ls
cd folder5
register_admin user5 pass5
pwd
buy
pwd
help ls_folders
put item5
add_item_property item5 key3=val1 key7=val3 key5=val6 key10=val7 
which_group
sign_in a1 pa1
register_user user7 pass7
pwd
create_folder folder4
put item1
show_folders
help show_item_properties
pwd
current_folder
show_users
put item1
put item3
ls
buy
put item3
sign_out
register_user user8 pass8
pwd
sign_in user3 pass3
add_item item5 key3=val3 key10=val2 key1=val6 key5=val3 
sign_in a3 pa3
rename_user user6 <function generate_user at 0x027087F0>
buy
help help
which_group
current_folder
show_item_properties item4
help sign_out
add_item_property item3 key5=val10 key9=val8 key8=val8 key3=val4 
sign_in a1 pa1
add_item item5 key9=val10 key1=val4 key9=val10 key2=val10 
show_folders
help add_item_property
rename_user user1 <function generate_user at 0x027087F0>
current_folder
ls
help pwd
ls_folders
show_folders
whoami
buy
rename_user user1 <function generate_user at 0x027087F0>
buy
current_folder
put item1
sign_in a3 pa3
sign_in a5 pa5
whoami
ls_folders
create_folder folder4
help pwd
sign_out
ls
create_folder folder5
add_item item5 key7=val2 key6=val9 key1=val6 key5=val9 
rename_user user3 <function generate_user at 0x027087F0>
sign_in user9 pass9
register_admin user5 pass5
show_item_properties item1
ls
create_folder folder4
show_users
add_item_property item3 key6=val3 key4=val4 key4=val5 key8=val1 
rename_user user5 <function generate_user at 0x027087F0>
rename_user user9 <function generate_user at 0x027087F0>
which_group
show_item_properties item4
register_user user3 pass3
whoami
show_folders
add_item_property item1 key9=val10 key3=val6 key10=val1 key9=val5 
current_folder
create_folder folder2
cd folder5
register_user user3 pass3
show_folders
pwd
add_item_property item1 key5=val3 key8=val9 key6=val2 key7=val6 
ls
whoami
show_items
add_item item1 key6=val8 key1=val9 key2=val9 key3=val2 
which_group
register_admin user8 pass8
show_items
create_folder folder5
add_item_property item2 key7=val2 key9=val1 key1=val2 key1=val6 
register_admin user9 pass9
buy
show_folders
cd folder2
show_folders
create_folder folder3
sign_in user1 pass1
show_item_properties item1
show_users
current_folder
create_folder folder2
current_folder
sign_in a2 pa2
show_users
register_admin user3 pass3
pwd
cd folder2
register_admin admin admin
register_admin admin admin
ls_folders
put item1
add_item item5 key10=val8 key6=val7 key10=val1 key8=val10 
buy
put item1
show_users
help history
buy
show_folders
show_item_properties item4
sign_in user5 pass5
cd folder2
register_admin user5 pass5
current_folder
current_folder
current_folder
create_folder folder5
create_folder folder3
register_user user5 pass5
sign_in user4 pass4
current_folder
register_user user6 pass6
add_item item4 key7=val9 key8=val7 key4=val6 key5=val1 
rename_user user4 <function generate_user at 0x027087F0>
show_items
add_item item1 key9=val6 key4=val10 key10=val5 key9=val3 
pwd
add_item_property item1 key5=val9 key5=val1 key5=val1 key3=val9 
sign_out
show_users
register_admin user3 pass3
help exit
sign_in admin admin
register_admin user3 pass3
pwd
show_folders
show_users
sign_out
sign_out
add_item_property item3 key8=val9 key4=val1 key8=val4 key6=val9 
show_folders
ls
ls
add_item item1 key5=val9 key7=val6 key7=val1 key9=val5 
which_group
register_user user2 pass2
cd folder5
buy
which_group
help create_folder
rename_user user1 <function generate_user at 0x027087F0>
show_folders
current_folder
sign_in user4 pass4
add_item_property item5 key10=val8 key4=val8 key10=val10 key5=val3 
show_folders
rename_user user3 <function generate_user at 0x027087F0>
show_users
show_folders
buy
show_items
which_group
pwd
show_users
create_folder folder5
sign_out
sign_in a1 pa1
cd folder2
buy
show_items
cd folder4
current_folder
cd folder3
ls_folders
sign_in user4 pass4
cd folder2
ls_folders
register_user user5 pass5
put item4
add_item_property item2 key2=val10 key3=val2 key10=val8 key7=val2 
sign_in user6 pass6
current_folder
which_group
show_users
current_folder
ls
whoami
rename_user user7 <function generate_user at 0x027087F0>
help history
ls
current_folder
cd folder5
show_item_properties item5
sign_in user5 pass5
show_folders
add_item_property item5 key9=val10 key3=val6 key10=val3 key3=val7 
rename_user user6 <function generate_user at 0x027087F0>
ls
buy
help buy
show_folders
show_item_properties item1
create_folder folder1
pwd
show_item_properties item2
register_user user5 pass5
sign_in user3 pass3
put item5
show_item_properties item1
show_item_properties item5
current_folder
add_item item4 key8=val4 key1=val3 key5=val7 key5=val3 
sign_in user6 pass6
buy
sign_in a3 pa3
ls_folders
which_group
current_folder
register_admin user8 pass8
current_folder
create_folder folder5
add_item item5 key2=val2 key1=val9 key5=val10 key7=val10 
add_item_property item5 key8=val1 key6=val7 key4=val8 key10=val8 
cd folder3
sign_out
register_user user6 pass6
ls_folders
rename_user user4 <function generate_user at 0x027087F0>
create_folder folder2
sign_out
add_item_property item1 key4=val10 key5=val4 key4=val6 key4=val10 
which_group
ls_folders
show_users
whoami
show_users
rename_user user7 <function generate_user at 0x027087F0>
show_item_properties item4
put item4
help add_item
sign_in user5 pass5
pwd
sign_out
ls_folders
whoami
show_folders
show_users
register_user user6 pass6
buy
sign_out
create_folder folder5
help add_item_property
buy
register_user user8 pass8
show_item_properties item4
whoami
show_users
current_folder
show_items
add_item item3 key1=val10 key3=val2 key6=val2 key10=val8 
show_items
sign_in user5 pass5
add_item_property item2 key6=val8 key7=val1 key7=val7 key1=val7 
add_item item3 key8=val5 key2=val8 key8=val9 key1=val1 
add_item_property item3 key7=val5 key1=val1 key8=val10 key3=val5 
current_folder
cd folder2
help sign_out
rename_user user9 <function generate_user at 0x027087F0>
register_user user5 pass5
add_item item5 key7=val5 key3=val6 key1=val5 key1=val1 
sign_in user5 pass5
ls
add_item item2 key4=val7 key8=val6 key9=val7 key4=val9 
show_users
sign_out
help exit
sign_in a3 pa3
put item3
rename_user user2 <function generate_user at 0x027087F0>
show_items
help register_user
add_item_property item3 key6=val2 key4=val7 key9=val9 key7=val9 
put item1
sign_in user9 pass9
ls_folders
buy
help help
register_user user3 pass3
put item1
sign_in a4 pa4
add_item_property item4 key3=val9 key5=val9 key8=val5 key10=val8 
put item5
sign_in a5 pa5
register_user user1 pass1
register_admin user8 pass8
sign_in user1 pass1
ls_folders
ls
buy
cd folder5
which_group
show_folders
current_folder
cd folder4
put item4
whoami
whoami
ls_folders
whoami
sign_in a4 pa4
show_folders
show_item_properties item3
add_item item4 key10=val3 key10=val2 key4=val2 key2=val1 
show_items
put item5
show_users
add_item item5 key7=val10 key8=val1 key9=val10 key6=val6 
ls_folders
whoami
current_folder
help buy
buy
pwd
add_item_property item2 key8=val2 key10=val4 key1=val2 key1=val5 
help add_item
add_item item3 key7=val4 key4=val2 key6=val6 key9=val1 
show_folders
show_items
help view_order
ls_folders
cd folder1
add_item_property item4 key3=val2 key10=val8 key4=val8 key5=val8 
sign_out
register_user user1 pass1
put item4
register_admin user8 pass8
current_folder
sign_in a1 pa1
create_folder folder5
sign_out
show_folders
register_admin user8 pass8
which_group
help add_item_property
show_folders
sign_out
register_user admin admin
ls_folders
cd folder4
rename_user user2 <function generate_user at 0x027087F0>
buy
add_item item5 key3=val4 key3=val8 key7=val1 key1=val3 
add_item item4 key2=val5 key5=val5 key6=val3 key10=val7 
register_user user5 pass5
show_users
which_group
cd folder2
sign_in a1 pa1
put item4
register_user admin admin
add_item_property item4 key2=val6 key3=val8 key3=val2 key6=val5 
add_item_property item5 key8=val10 key3=val6 key6=val9 key9=val8 
show_items
pwd
current_folder
sign_in a5 pa5
ls
rename_user user0 <function generate_user at 0x027087F0>
whoami
sign_in a3 pa3
sign_out
add_item item3 key9=val10 key8=val1 key9=val10 key5=val1 
sign_out
whoami
show_items
rename_user user3 <function generate_user at 0x027087F0>
show_items
show_items
show_users
rename_user user8 <function generate_user at 0x027087F0>
show_folders
help create_folder
put item4
cd folder2
add_item item4 key4=val10 key4=val4 key2=val8 key2=val8 
whoami
show_item_properties item4
pwd
sign_out
show_item_properties item4
sign_out
register_admin user1 pass1
which_group
show_users
show_folders
show_folders
sign_in a2 pa2
current_folder
ls_folders
show_users
show_items
sign_out
help delete_user
sign_in user4 pass4
ls
register_user user1 pass1
ls
ls
cd folder3
sign_out
cd folder3
add_item_property item3 key5=val7 key9=val4 key6=val8 key9=val5 
rename_user user7 <function generate_user at 0x027087F0>
add_item item1 key8=val9 key4=val10 key8=val4 key6=val4 
sign_in user9 pass9
whoami
sign_in user3 pass3
register_admin user2 pass2
put item4
current_folder
help help
register_admin user3 pass3
add_item_property item3 key10=val10 key6=val8 key4=val7 key4=val6 
sign_in a2 pa2
rename_user user6 <function generate_user at 0x027087F0>
show_users
whoami
put item4
show_item_properties item1
show_users
sign_in a3 pa3
show_users
sign_in a4 pa4
which_group
add_item item1 key7=val1 key9=val8 key3=val5 key1=val10 
sign_out
add_item item2 key4=val5 key9=val9 key3=val1 key8=val7 
which_group
show_users
sign_out
buy
rename_user user0 <function generate_user at 0x027087F0>
current_folder
sign_in user2 pass2
show_items
whoami
buy
create_folder folder3
which_group
add_item_property item3 key8=val5 key1=val9 key10=val2 key8=val4 
register_admin user5 pass5
show_users
sign_in a2 pa2
add_item_property item5 key1=val7 key6=val9 key8=val5 key2=val8 
current_folder
cd folder4
whoami
show_items
register_admin user8 pass8
put item5
pwd
put item3
add_item item4 key1=val1 key2=val9 key4=val8 key1=val6 
show_item_properties item5
add_item_property item4 key9=val6 key10=val3 key4=val3 key8=val4 
put item2
help add_item_property
whoami
pwd
pwd
ls_folders
sign_in user6 pass6
sign_out
put item5
show_folders
show_users
register_user user3 pass3
sign_in user6 pass6
sign_out
whoami
show_users
ls
rename_user user6 <function generate_user at 0x027087F0>
current_folder
add_item_property item4 key7=val3 key5=val5 key10=val10 key1=val2 
show_items
ls_folders
pwd
current_folder
rename_user user6 <function generate_user at 0x027087F0>
help which_group
buy
help rename_user
create_folder folder4
show_items
add_item item2 key9=val3 key7=val7 key3=val10 key9=val8 
add_item item2 key6=val5 key2=val4 key9=val4 key3=val10 
show_item_properties item2
current_folder
buy
sign_in a5 pa5
show_users
add_item item3 key10=val4 key4=val7 key7=val4 key3=val7 
add_item item5 key3=val5 key6=val8 key6=val7 key3=val2 
which_group
sign_out
sign_in a2 pa2
help cd
register_admin user1 pass1
cd folder3
help delete_user
show_items
cd folder1
register_admin user6 pass6
show_item_properties item2
buy
help show_users
help rename_user
ls
sign_out
which_group
whoami
ls
show_folders
which_group
sign_in user5 pass5
sign_out
add_item item3 key8=val6 key3=val4 key4=val8 key8=val4 
current_folder
create_folder folder3
sign_in a5 pa5
ls
add_item item2 key2=val6 key8=val5 key7=val2 key8=val6 
register_user user8 pass8
show_item_properties item1
ls
show_folders
buy
help put
show_users
show_folders
sign_in user9 pass9
add_item_property item3 key2=val4 key9=val5 key6=val1 key2=val6 
current_folder
ls
register_user user9 pass9
sign_in user5 pass5
current_folder
current_folder
add_item_property item2 key5=val7 key1=val9 key5=val6 key4=val1 
rename_user user8 <function generate_user at 0x027087F0>
register_user user5 pass5
show_folders
cd folder5
cd folder3
current_folder
register_user admin admin
show_item_properties item1
ls
show_folders
ls
register_user user4 pass4
sign_in a4 pa4
ls
show_items
show_items
show_item_properties item4
show_item_properties item2
show_items
create_folder folder5
show_users
show_folders
help which_group
help delete_user
which_group
whoami
pwd
show_folders
sign_in user7 pass7
whoami
current_folder
register_admin user4 pass4
ls
ls
sign_in admin admin
ls_folders
ls
ls
put item1
put item1
help view_order
show_items
put item2
pwd
register_user user4 pass4
add_item_property item2 key2=val6 key2=val5 key3=val4 key5=val7 
show_item_properties item2
add_item_property item2 key10=val10 key7=val8 key4=val7 key5=val7 
register_user user1 pass1
cd folder3
sign_out
ls_folders
register_admin user5 pass5
create_folder folder5
cd folder2
put item1
sign_in a5 pa5
help add_item_property
cd folder4
sign_in a5 pa5
put item4
ls_folders
cd folder3
ls_folders
whoami
sign_out
show_items
whoami
put item4
whoami
sign_in a4 pa4
ls
show_folders
show_item_properties item5
sign_in a3 pa3
pwd
ls_folders
show_item_properties item5
register_admin user1 pass1
help rename_user
show_folders
whoami
register_admin user2 pass2
show_folders
buy
ls_folders
add_item item4 key6=val9 key8=val3 key8=val10 key5=val2 
show_folders
cd folder3
show_items
show_folders
add_item_property item4 key9=val1 key4=val5 key4=val10 key10=val6 
ls
sign_in a2 pa2
current_folder
show_item_properties item3
add_item item4 key6=val7 key10=val9 key8=val7 key5=val9 
which_group
put item1
sign_out
show_users
put item2
buy
register_admin admin admin
add_item item2 key1=val5 key10=val4 key9=val1 key1=val6 
help pwd
rename_user user7 <function generate_user at 0x027087F0>
ls
show_users
ls_folders
sign_in user2 pass2
register_user user1 pass1
whoami
sign_out
sign_in a3 pa3
cd folder3
register_user user1 pass1
rename_user user9 <function generate_user at 0x027087F0>
show_users
ls
ls_folders
pwd
show_users
create_folder folder4
sign_out
show_users
create_folder folder2
sign_in user1 pass1
add_item item5 key6=val7 key6=val4 key2=val2 key9=val3 
ls_folders
current_folder
register_user user9 pass9
ls
show_users
add_item item1 key1=val6 key2=val6 key5=val8 key1=val9 
sign_out
add_item item4 key9=val9 key1=val8 key9=val3 key5=val8 
show_item_properties item3
put item3
sign_in user1 pass1
current_folder
current_folder
pwd
show_items
pwd
cd folder4
ls_folders
show_users
show_item_properties item5
whoami
show_items
buy
which_group
sign_out
pwd
rename_user user6 <function generate_user at 0x027087F0>
whoami
whoami
pwd
pwd
sign_in user2 pass2
add_item item5 key4=val6 key1=val10 key9=val1 key8=val2 
whoami
put item2
register_user admin admin
show_folders
sign_out
buy
sign_out
sign_out
add_item_property item2 key8=val3 key6=val9 key9=val2 key1=val9 
put item1
rename_user user7 <function generate_user at 0x027087F0>
ls
whoami
sign_in user3 pass3
pwd
show_item_properties item5
sign_in user7 pass7
add_item item5 key6=val2 key2=val10 key4=val9 key8=val10 
rename_user user3 <function generate_user at 0x027087F0>
create_folder folder4
add_item_property item4 key1=val5 key1=val7 key3=val4 key9=val5 
add_item item4 key7=val8 key6=val3 key4=val9 key9=val1 
create_folder folder4
help register_admin
sign_in a4 pa4
register_user user1 pass1
show_items
sign_in a4 pa4
show_item_properties item1
register_admin user2 pass2
create_folder folder5
register_user user6 pass6
put item2
pwd
show_folders
sign_out
sign_in a1 pa1
ls_folders
cd folder2
create_folder folder2
put item5
sign_in a5 pa5
ls
register_user admin admin
rename_user user9 <function generate_user at 0x027087F0>
add_item_property item3 key5=val5 key8=val10 key1=val6 key2=val1 
help show_folders
ls_folders
show_item_properties item5
put item1
sign_in user9 pass9
show_item_properties item3
sign_in a2 pa2
show_users
sign_in user8 pass8
whoami
sign_in user5 pass5
show_users
help which_group
pwd
whoami
buy
create_folder folder4
pwd
put item4
register_user user8 pass8
add_item_property item4 key3=val8 key1=val8 key9=val3 key2=val8 
put item4
sign_out
cd folder3
rename_user user3 <function generate_user at 0x027087F0>
rename_user user6 <function generate_user at 0x027087F0>
show_item_properties item3
register_user admin admin
show_items
create_folder folder4
cd folder2
add_item_property item5 key1=val10 key3=val10 key4=val2 key4=val2 
put item4
current_folder
help show_items
add_item_property item1 key8=val8 key5=val7 key8=val2 key3=val9 
register_admin user5 pass5
buy
help buy
which_group
show_items
sign_out
ls
sign_out
sign_in a3 pa3
sign_out
sign_in a3 pa3
show_items
create_folder folder1
current_folder
ls
show_items
cd folder1
sign_out
which_group
sign_out
show_items
help view_order
add_item item5 key1=val5 key9=val10 key9=val5 key7=val1 
add_item item4 key1=val5 key6=val10 key7=val1 key10=val9 
whoami
register_user admin admin
buy
which_group
which_group
register_user admin admin
show_items
rename_user user7 <function generate_user at 0x027087F0>
show_folders
sign_in user7 pass7
sign_in user1 pass1
sign_out
rename_user user9 <function generate_user at 0x027087F0>
create_folder folder3
rename_user user6 <function generate_user at 0x027087F0>
add_item item5 key7=val1 key9=val6 key4=val4 key3=val1 
ls
put item4
sign_out
cd folder3
help register_user
ls_folders
sign_in a4 pa4
ls_folders
add_item item5 key3=val5 key10=val9 key2=val3 key5=val4 
add_item_property item3 key10=val2 key10=val10 key2=val4 key2=val5 
pwd
help delete_user
show_folders
help history
add_item item2 key9=val9 key9=val8 key5=val2 key8=val10 
show_users
rename_user user5 <function generate_user at 0x027087F0>
add_item item2 key8=val2 key7=val10 key10=val10 key6=val6 
add_item item4 key2=val10 key2=val9 key1=val7 key1=val5 
which_group
help sign_in
ls_folders
create_folder folder2
sign_out
help create_folder
show_users
ls
current_folder
rename_user user9 <function generate_user at 0x027087F0>
which_group
show_folders
show_item_properties item4
buy
add_item_property item5 key7=val9 key10=val3 key8=val4 key4=val7 
sign_out
register_user user8 pass8
pwd
sign_out
add_item item3 key9=val10 key6=val3 key5=val3 key9=val6 
sign_in a1 pa1
current_folder
put item4
current_folder
ls_folders
put item5
register_admin user3 pass3
which_group
sign_out
register_admin user2 pass2
pwd
rename_user user9 <function generate_user at 0x027087F0>
help whoami
buy
add_item item5 key9=val9 key9=val5 key7=val4 key1=val2 
show_item_properties item1
cd folder1
ls_folders
sign_in user5 pass5
show_folders
which_group
show_users
show_folders
current_folder
current_folder
show_items
register_user user7 pass7
create_folder folder1
register_user admin admin
add_item item2 key1=val7 key1=val6 key7=val3 key2=val3 
add_item item1 key3=val5 key2=val2 key6=val1 key2=val7 
show_folders
rename_user user9 <function generate_user at 0x027087F0>
ls_folders
show_item_properties item5
register_user user8 pass8
sign_in user8 pass8
rename_user user0 <function generate_user at 0x027087F0>
add_item_property item1 key1=val7 key1=val3 key1=val7 key5=val9 
put item4
add_item item1 key6=val5 key1=val4 key3=val10 key5=val4 
ls_folders
whoami
sign_in a1 pa1
show_folders
which_group
add_item item4 key3=val4 key3=val8 key5=val9 key5=val10 
show_item_properties item4
help buy
register_user user6 pass6
show_item_properties item3
sign_out
whoami
show_items
current_folder
add_item_property item4 key3=val8 key1=val9 key8=val2 key8=val10 
buy
show_items
cd folder2
sign_out
create_folder folder2
sign_in a4 pa4
cd folder2
help show_folders
show_users
show_users
which_group
whoami
show_users
sign_in a5 pa5
cd folder4
show_folders
create_folder folder1
show_users
ls_folders
show_folders
which_group
sign_out
cd folder2
sign_in a1 pa1
register_admin admin admin
buy
ls_folders
show_folders
which_group
create_folder folder3
help whoami
add_item_property item2 key6=val4 key9=val3 key9=val8 key1=val4 
current_folder
put item4
add_item item5 key10=val4 key2=val8 key9=val10 key5=val1 
create_folder folder2
show_item_properties item5
ls_folders
sign_out
show_users
show_items
add_item item1 key10=val1 key5=val5 key4=val1 key1=val1 
add_item item1 key6=val9 key7=val7 key8=val5 key7=val10 
show_users
ls_folders
sign_out
register_admin user5 pass5
show_items
ls
sign_in user8 pass8
help sign_in
whoami
help sign_in
ls_folders
pwd
sign_in a5 pa5
help sign_out
show_item_properties item1
show_folders
show_items
current_folder
create_folder folder3
register_admin user3 pass3
create_folder folder2
register_admin user1 pass1
sign_out
register_admin admin admin
ls_folders
put item4
show_users
show_item_properties item1
show_item_properties item4
help show_folders
put item3
whoami
sign_in a4 pa4
show_item_properties item4
rename_user user0 <function generate_user at 0x027087F0>
put item2
ls
rename_user user8 <function generate_user at 0x027087F0>
show_items
sign_in user9 pass9
cd folder2
add_item_property item3 key8=val9 key8=val5 key7=val4 key7=val8 
add_item item1 key3=val4 key10=val6 key8=val8 key5=val10 
cd folder4
add_item item1 key6=val4 key4=val8 key8=val3 key3=val8 
register_admin user1 pass1
show_users
show_users
current_folder
show_folders
register_user user2 pass2
which_group
add_item_property item5 key1=val8 key5=val3 key7=val1 key5=val9 
register_user user9 pass9
add_item item3 key8=val6 key8=val2 key4=val10 key6=val3 
sign_in a3 pa3
sign_in a3 pa3
current_folder
rename_user user7 <function generate_user at 0x027087F0>
create_folder folder3
current_folder
buy
show_folders
sign_out
buy
sign_out
show_items
show_items
sign_in user5 pass5
show_item_properties item3
rename_user user3 <function generate_user at 0x027087F0>
show_items
put item3
cd folder1
current_folder
register_admin user4 pass4
sign_in user2 pass2
put item5
create_folder folder1
show_folders
cd folder4
ls_folders
which_group
sign_in user6 pass6
whoami
buy
cd folder4
add_item item2 key8=val7 key1=val6 key3=val4 key10=val2 
register_admin user8 pass8
ls_folders
whoami
buy
add_item item4 key3=val4 key9=val5 key7=val5 key1=val2 
show_folders
ls_folders
show_item_properties item3
cd folder5
which_group
cd folder1
sign_in user4 pass4
cd folder3
whoami
register_admin admin admin
show_item_properties item1
current_folder
cd folder1
sign_in a1 pa1
sign_in user2 pass2
show_item_properties item1
sign_out
cd folder2
sign_in a2 pa2
ls
help sign_in
show_item_properties item3
ls_folders
ls_folders
show_item_properties item2
show_folders
show_items
ls_folders
buy
sign_in a3 pa3
ls
help view_order
cd folder4
put item3
show_item_properties item1
add_item item4 key2=val6 key4=val4 key3=val2 key6=val4 
pwd
sign_in a2 pa2
add_item_property item3 key3=val10 key7=val9 key3=val6 key9=val9 
register_admin user8 pass8
whoami
sign_in a3 pa3
show_folders
show_users
sign_out
help which_group
sign_out
put item1
put item2
help buy
put item2
add_item item2 key1=val6 key2=val10 key1=val10 key7=val5 
sign_in a3 pa3
add_item item3 key6=val10 key9=val8 key5=val2 key8=val1 
pwd
register_user admin admin
sign_out
register_user user7 pass7
ls_folders
pwd
register_user admin admin
register_user user2 pass2
which_group
pwd
add_item item1 key2=val1 key3=val5 key10=val3 key4=val5 
rename_user user3 <function generate_user at 0x027087F0>
create_folder folder4
show_item_properties item5
sign_in user9 pass9
create_folder folder1
ls_folders
show_users
sign_in a4 pa4
register_admin user3 pass3
add_item item5 key1=val6 key6=val7 key5=val4 key6=val7 
current_folder
show_items
sign_in a2 pa2
sign_in admin admin
help help
show_items
sign_in a3 pa3
show_item_properties item4
sign_in a4 pa4
register_admin user3 pass3
sign_in a3 pa3
sign_in a4 pa4
sign_in a5 pa5
add_item_property item1 key1=val4 key2=val10 key5=val1 key3=val8 
show_item_properties item1
show_users
sign_in user8 pass8
buy
help put
show_items
current_folder
show_item_properties item4
ls_folders
current_folder
add_item item5 key10=val2 key6=val8 key5=val2 key7=val5 
which_group
whoami
register_admin user7 pass7
show_users
show_folders
which_group
show_item_properties item4
add_item item1 key7=val10 key5=val3 key6=val6 key9=val7 
ls
put item3
pwd
add_item_property item5 key8=val9 key9=val10 key7=val10 key10=val5 
ls_folders
add_item item5 key3=val6 key7=val4 key9=val4 key7=val6 
whoami
help delete_user
ls_folders
sign_in user4 pass4
register_user user3 pass3
show_items
create_folder folder3
buy
current_folder
show_users
sign_in user3 pass3
rename_user user9 <function generate_user at 0x027087F0>
sign_in user9 pass9
rename_user user6 <function generate_user at 0x027087F0>
which_group
show_item_properties item1
whoami
cd folder5
ls_folders
rename_user user4 <function generate_user at 0x027087F0>
put item1
ls_folders
ls_folders
cd folder3
ls_folders
current_folder
register_user user4 pass4
sign_in a3 pa3
show_folders
create_folder folder4
buy
show_folders
cd folder2
register_admin user5 pass5
sign_in admin admin
ls
sign_in a1 pa1
show_items
register_user user5 pass5
sign_in user9 pass9
whoami
current_folder
show_items
sign_in admin admin
ls_folders
sign_in a2 pa2
whoami
current_folder
sign_out
which_group
add_item item3 key3=val4 key2=val2 key6=val2 key7=val1 
create_folder folder2
sign_out
show_items
register_admin user5 pass5
show_folders
add_item_property item1 key7=val7 key2=val9 key6=val3 key3=val4 
add_item item5 key7=val4 key5=val10 key4=val9 key5=val9 
help exit
pwd
put item1
cd folder4
add_item item3 key1=val6 key3=val1 key9=val9 key10=val9 
register_admin user5 pass5
show_items
cd folder4
pwd
which_group
ls_folders
create_folder folder2
sign_in a4 pa4
help which_group
register_user admin admin
rename_user user5 <function generate_user at 0x027087F0>
show_folders
register_user user5 pass5
current_folder
add_item_property item3 key8=val10 key10=val5 key8=val4 key8=val6 
put item1
show_users
add_item item5 key1=val5 key2=val1 key2=val3 key9=val9 
rename_user user9 <function generate_user at 0x027087F0>
add_item item2 key8=val1 key5=val8 key2=val4 key5=val2 
sign_in user5 pass5
help current_folder
ls
rename_user user6 <function generate_user at 0x027087F0>
add_item_property item3 key3=val7 key7=val2 key9=val7 key8=val9 
show_items
add_item_property item2 key5=val7 key6=val7 key6=val3 key6=val4 
current_folder
put item2
sign_in user5 pass5
help cd
ls_folders
pwd
ls_folders
pwd
sign_in user5 pass5
ls_folders
whoami
rename_user user9 <function generate_user at 0x027087F0>
whoami
show_items
register_user admin admin
create_folder folder3
show_users
cd folder2
help put
rename_user user8 <function generate_user at 0x027087F0>
sign_in a1 pa1
ls
put item3
put item4
ls_folders
sign_in user2 pass2
sign_out
buy
ls_folders
add_item item3 key2=val10 key2=val3 key5=val9 key4=val6 
pwd
put item3
show_items
sign_in user5 pass5
sign_in a2 pa2
buy
show_items
cd folder4
help show_users
cd folder3
create_folder folder1
show_items
sign_out
show_item_properties item5
cd folder2
register_admin user6 pass6
cd folder1
ls
cd folder1
show_item_properties item3
sign_in user5 pass5
rename_user user7 <function generate_user at 0x027087F0>
sign_out
buy
ls
sign_in user5 pass5
ls
create_folder folder5
ls_folders
ls
show_items
pwd
sign_in user7 pass7
sign_in a4 pa4
show_item_properties item2
show_users
help view_order
show_items
show_folders
ls_folders
ls
current_folder
ls_folders
show_items
help put
put item3
rename_user user3 <function generate_user at 0x027087F0>
register_admin admin admin
show_folders
sign_in user5 pass5
sign_in user2 pass2
whoami
sign_in a2 pa2
register_user user4 pass4
show_item_properties item3
rename_user user9 <function generate_user at 0x027087F0>
rename_user user0 <function generate_user at 0x027087F0>
ls
show_folders
current_folder
sign_in user8 pass8
pwd
ls_folders
add_item_property item1 key2=val6 key3=val5 key10=val1 key7=val2 
cd folder5
current_folder
current_folder
show_folders
show_folders
show_item_properties item3
sign_out
help delete_user
sign_in a1 pa1
which_group
buy
add_item item2 key10=val6 key4=val1 key8=val9 key6=val4 
pwd
ls
sign_in a2 pa2
put item4
register_user user8 pass8
show_item_properties item5
show_users
show_folders
buy
show_folders
rename_user user8 <function generate_user at 0x027087F0>
create_folder folder4
sign_out
register_admin user4 pass4
ls
help show_items
which_group
register_admin user1 pass1
put item2
show_items
show_item_properties item3
show_folders
whoami
put item2
create_folder folder4
current_folder
sign_in a3 pa3
help ls
cd folder2
sign_in user8 pass8
ls
buy
show_items
put item5
put item1
cd folder5
show_items
help help
sign_in user1 pass1
register_user user6 pass6
show_folders
put item3
sign_in user5 pass5
pwd
put item1
which_group
current_folder
buy
buy
show_users
whoami
ls_folders
create_folder folder4
show_items
sign_out
sign_in user7 pass7
create_folder folder1
help ls
add_item_property item1 key3=val4 key8=val2 key7=val4 key2=val3 
show_folders
pwd
help buy
ls
ls
buy
add_item_property item1 key4=val2 key5=val3 key5=val7 key2=val1 
cd folder1
pwd
show_items
ls_folders
show_folders
ls
ls
show_folders
show_items
whoami
sign_in user1 pass1
sign_out
put item4
which_group
create_folder folder3
show_items
buy
show_items
show_users
create_folder folder5
sign_in a5 pa5
which_group
buy
sign_out
sign_in admin admin
sign_out
add_item item4 key9=val3 key7=val8 key2=val7 key1=val9 
current_folder
buy
current_folder
put item3
help view_order
register_user user7 pass7
help add_item
register_admin user8 pass8
register_admin user3 pass3
rename_user user7 <function generate_user at 0x027087F0>
whoami
whoami
put item2
register_user user6 pass6
pwd
sign_out
put item2
which_group
help pwd
sign_in a5 pa5
sign_in a3 pa3
show_item_properties item1
show_items
ls
buy
whoami
sign_out
show_users
pwd
create_folder folder3
ls_folders
help show_item_properties
put item3
show_users
register_user user1 pass1
rename_user user3 <function generate_user at 0x027087F0>
sign_in user2 pass2
sign_in a1 pa1
pwd
show_folders
put item5
current_folder
register_user user3 pass3
create_folder folder1
add_item item5 key4=val5 key6=val4 key1=val8 key7=val3 
pwd
show_users
rename_user user5 <function generate_user at 0x027087F0>
create_folder folder3
show_item_properties item5
add_item_property item3 key9=val10 key5=val1 key3=val8 key4=val8 
cd folder2
which_group
pwd
create_folder folder4
show_users
help history
pwd
whoami
which_group
add_item_property item5 key6=val9 key1=val4 key8=val2 key6=val7 
show_users
current_folder
show_item_properties item3
register_user admin admin
sign_in user6 pass6
pwd
ls
register_user user6 pass6
current_folder
show_folders
current_folder
pwd
add_item_property item1 key6=val2 key9=val10 key7=val2 key2=val1 
register_user admin admin
show_items
ls_folders
sign_out
buy
sign_in a4 pa4
current_folder
show_folders
ls
sign_out
pwd
current_folder
show_item_properties item4
sign_in a5 pa5
show_users
show_items
add_item item4 key4=val9 key10=val2 key8=val4 key6=val2 
show_users
sign_in user6 pass6
sign_out
current_folder
register_admin user5 pass5
cd folder3
pwd
show_items
current_folder
which_group
buy
sign_in user2 pass2
current_folder
help add_item
show_items
add_item item5 key2=val3 key2=val2 key4=val2 key2=val4 
current_folder
create_folder folder4
current_folder
put item5
help whoami
register_user user4 pass4
put item2
pwd
show_users
put item4
ls
register_admin admin admin
help show_folders
ls_folders
cd folder1
pwd
show_items
sign_in user2 pass2
show_users
buy
sign_in a5 pa5
add_item item1 key3=val4 key10=val4 key5=val3 key5=val1 
ls
show_items
sign_in a4 pa4
show_folders
show_items
register_admin user2 pass2
rename_user user0 <function generate_user at 0x027087F0>
show_item_properties item1
pwd
sign_out
show_item_properties item2
current_folder
show_items
current_folder
show_users
which_group
which_group
show_item_properties item3
create_folder folder4
buy
create_folder folder1
ls
rename_user user9 <function generate_user at 0x027087F0>
ls
sign_in a5 pa5
ls_folders
cd folder3
ls_folders
whoami
sign_in user6 pass6
show_item_properties item1
show_folders
cd folder2
register_user user4 pass4
create_folder folder3
register_user user8 pass8
pwd
ls_folders
add_item item3 key10=val2 key6=val6 key4=val2 key8=val2 
register_user user9 pass9
add_item item2 key10=val1 key1=val6 key2=val8 key5=val6 
put item4
buy
pwd
current_folder
show_users
create_folder folder1
add_item item2 key1=val8 key7=val1 key8=val9 key7=val8 
show_item_properties item3
show_folders
sign_out
show_items
current_folder
create_folder folder4
whoami
put item4
ls
cd folder4
help ls
ls_folders
buy
show_folders
sign_out
show_items
buy
show_folders
pwd
show_users
sign_in a1 pa1
sign_out
register_admin user6 pass6
show_item_properties item1
sign_out
sign_in a1 pa1
put item2
sign_in user9 pass9
add_item_property item1 key8=val8 key2=val9 key2=val8 key1=val1 
sign_out
show_users
register_admin admin admin
create_folder folder3
put item2
cd folder1
show_folders
add_item item4 key9=val6 key4=val7 key5=val5 key6=val3 
sign_out
put item1
rename_user user8 <function generate_user at 0x027087F0>
register_admin user3 pass3
which_group
buy
show_users
register_user user7 pass7
whoami
create_folder folder5
put item2
buy
sign_in a1 pa1
buy
create_folder folder2
sign_in a2 pa2
which_group
put item1
show_item_properties item5
show_items
buy
which_group
buy
put item1
show_item_properties item5
sign_in admin admin
ls
sign_out
put item2
add_item item4 key10=val8 key8=val8 key4=val6 key4=val1 
cd folder3
help put
register_user user7 pass7
rename_user user5 <function generate_user at 0x027087F0>
sign_in user1 pass1
show_items
show_item_properties item4
current_folder
put item2
pwd
put item4
rename_user user3 <function generate_user at 0x027087F0>
rename_user user0 <function generate_user at 0x027087F0>
sign_in a2 pa2
put item5
whoami
sign_in a1 pa1
current_folder
register_user admin admin
show_item_properties item4
current_folder
buy
show_items
show_users
sign_in user3 pass3
register_admin user8 pass8
help register_admin
sign_in a4 pa4
put item3
ls_folders
put item2
register_admin user6 pass6
ls_folders
buy
ls_folders
create_folder folder3
show_folders
register_user user1 pass1
pwd
which_group
add_item_property item1 key10=val7 key8=val5 key3=val4 key10=val2 
show_folders
rename_user user7 <function generate_user at 0x027087F0>
show_folders
sign_out
create_folder folder5
add_item_property item4 key9=val6 key2=val1 key2=val5 key10=val3 
register_user admin admin
rename_user user6 <function generate_user at 0x027087F0>
buy
show_users
which_group
current_folder
put item1
ls_folders
whoami
ls_folders
sign_out
whoami
rename_user user2 <function generate_user at 0x027087F0>
pwd
whoami
show_items
help show_item_properties
help add_item
register_admin user3 pass3
pwd
pwd
pwd
put item2
cd folder3
add_item_property item3 key10=val8 key10=val9 key4=val7 key5=val9 
cd folder2
current_folder
sign_in a5 pa5
help show_folders
pwd
sign_in user7 pass7
pwd
add_item item1 key9=val1 key2=val4 key9=val9 key8=val2 
ls
current_folder
register_admin user7 pass7
sign_in a1 pa1
whoami
show_folders
ls_folders
whoami
sign_out
show_folders
add_item item2 key8=val1 key2=val10 key5=val3 key10=val1 
sign_in a3 pa3
sign_out
create_folder folder4
buy
whoami
register_admin user2 pass2
pwd
register_admin user7 pass7
ls
whoami
show_folders
which_group
show_item_properties item4
register_user user3 pass3
show_folders
whoami
register_user user2 pass2
show_users
current_folder
show_items
register_admin user6 pass6
register_admin admin admin
add_item_property item2 key4=val1 key2=val8 key10=val5 key2=val9 
show_items
sign_in user9 pass9
pwd
cd folder5
sign_in user7 pass7
ls
pwd
which_group
rename_user user5 <function generate_user at 0x027087F0>
register_admin user7 pass7
whoami
ls_folders
register_user user6 pass6
help add_item_property
ls
sign_in user5 pass5
register_admin user5 pass5
buy
current_folder
which_group
buy
help create_folder
register_user user1 pass1
register_admin user2 pass2
create_folder folder2
cd folder3
create_folder folder4
help cd
register_user user3 pass3
pwd
cd folder1
sign_out
show_item_properties item3
put item2
add_item item1 key8=val3 key7=val7 key7=val10 key8=val1 
add_item item2 key10=val5 key1=val9 key3=val3 key9=val2 
show_folders
buy
sign_in user5 pass5
add_item item4 key8=val5 key8=val5 key2=val9 key7=val2 
ls
register_admin user5 pass5
register_user user3 pass3
cd folder5
buy
put item5
whoami
buy
ls_folders
whoami
show_users
ls_folders
sign_in a2 pa2
register_user user2 pass2
sign_out
current_folder
register_admin user5 pass5
sign_in user7 pass7
add_item item3 key7=val5 key8=val7 key3=val5 key1=val5 
add_item_property item5 key3=val2 key1=val5 key3=val9 key1=val2 
whoami
add_item_property item3 key10=val7 key10=val4 key9=val9 key2=val10 
help add_item_property
which_group
show_folders
current_folder
ls_folders
rename_user user7 <function generate_user at 0x027087F0>
which_group
sign_in user3 pass3
current_folder
ls_folders
show_items
sign_in user8 pass8
cd folder4
add_item_property item2 key6=val2 key5=val3 key9=val10 key2=val3 
which_group
ls
add_item_property item3 key3=val4 key9=val3 key4=val8 key5=val1 
put item5
rename_user user0 <function generate_user at 0x027087F0>
help ls
put item2
register_user user6 pass6
add_item item4 key8=val5 key2=val10 key7=val1 key3=val1 
rename_user user8 <function generate_user at 0x027087F0>
help help
sign_in a3 pa3
buy
add_item_property item5 key7=val9 key10=val5 key9=val4 key7=val4 
which_group
whoami
add_item_property item2 key10=val3 key10=val3 key4=val3 key7=val9 
cd folder5
register_admin user7 pass7
show_folders
ls
pwd
current_folder
sign_out
show_users
show_users
show_item_properties item2
cd folder1
ls_folders
ls
pwd
sign_in a5 pa5
sign_out
which_group
pwd
ls_folders
ls
current_folder
pwd
which_group
buy
show_folders
help sign_out
whoami
create_folder folder4
create_folder folder2
show_users
show_items
show_item_properties item2
add_item_property item4 key3=val4 key10=val10 key7=val9 key2=val2 
help rename_user
show_item_properties item5
put item4
show_users
sign_in user3 pass3
sign_in a3 pa3
show_folders
put item5
show_items
show_users
current_folder
register_user user8 pass8
current_folder
create_folder folder4
create_folder folder3
show_items
buy
show_item_properties item5
ls_folders
rename_user user5 <function generate_user at 0x027087F0>
put item5
put item3
cd folder1
show_folders
sign_in user6 pass6
put item3
rename_user user8 <function generate_user at 0x027087F0>
which_group
show_folders
add_item item3 key10=val7 key8=val8 key10=val8 key5=val9 
buy
rename_user user6 <function generate_user at 0x027087F0>
buy
register_user user4 pass4
cd folder3
sign_out
show_users
current_folder
pwd
cd folder2
sign_in admin admin
whoami
ls
sign_in user4 pass4
show_users
add_item_property item2 key6=val10 key5=val5 key6=val7 key8=val10 
ls
whoami
show_folders
current_folder
show_items
create_folder folder4
which_group
add_item_property item5 key4=val5 key1=val6 key7=val6 key3=val8 
add_item item1 key8=val5 key10=val3 key10=val7 key1=val6 
which_group
ls
cd folder4
ls_folders
register_admin user8 pass8
create_folder folder4
put item3
show_folders
sign_in user6 pass6
cd folder2
which_group
cd folder1
sign_out
show_folders
sign_in user8 pass8
current_folder
register_user user3 pass3
sign_in a4 pa4
whoami
create_folder folder1
current_folder
ls_folders
help add_item_property
pwd
register_user user7 pass7
pwd
rename_user user0 <function generate_user at 0x027087F0>
sign_in admin admin
help register_user
show_users
register_user user8 pass8
sign_in a2 pa2
ls
cd folder2
ls_folders
show_items
put item3
show_items
current_folder
cd folder5
ls_folders
show_item_properties item5
cd folder5
show_folders
sign_out
add_item item2 key9=val9 key4=val1 key10=val7 key10=val3 
show_items
show_item_properties item4
show_item_properties item1
show_items
sign_in user7 pass7
rename_user user9 <function generate_user at 0x027087F0>
sign_in user1 pass1
create_folder folder2
register_admin user1 pass1
pwd
pwd
create_folder folder5
sign_in a1 pa1
show_item_properties item4
add_item item1 key6=val2 key3=val8 key7=val6 key6=val8 
add_item item2 key8=val3 key10=val2 key8=val4 key5=val9 
add_item_property item2 key8=val8 key7=val8 key2=val5 key5=val4 
show_item_properties item2
rename_user user9 <function generate_user at 0x027087F0>
pwd
put item3
ls
ls
current_folder
create_folder folder3
register_admin user1 pass1
ls_folders
show_items
pwd
add_item_property item2 key9=val4 key9=val6 key9=val5 key6=val6 
show_users
sign_in a1 pa1
show_items
which_group
current_folder
which_group
register_admin user2 pass2
show_users
put item5
show_users
add_item item5 key2=val2 key1=val3 key6=val7 key7=val8 
current_folder
show_folders
ls
buy
show_items
show_items
help cd
ls
ls
register_admin user4 pass4
buy
show_item_properties item3
add_item_property item5 key3=val4 key8=val10 key9=val2 key9=val9 
sign_out
sign_in a3 pa3
sign_out
show_folders
rename_user user9 <function generate_user at 0x027087F0>
buy
buy
put item5
create_folder folder3
sign_in a4 pa4
register_user user3 pass3
show_folders
register_admin user4 pass4
add_item item5 key5=val9 key2=val8 key7=val8 key6=val1 
ls_folders
sign_in a5 pa5
rename_user user4 <function generate_user at 0x027087F0>
help help
show_folders
put item1
register_user user7 pass7
whoami
ls_folders
sign_in user9 pass9
ls_folders
show_item_properties item1
sign_in a5 pa5
add_item_property item4 key3=val2 key7=val5 key10=val9 key7=val6 
help rename_user
sign_in user4 pass4
register_user admin admin
register_user user8 pass8
register_admin user4 pass4
ls
which_group
current_folder
whoami
put item2
whoami
current_folder
register_user user8 pass8
which_group
put item2
current_folder
rename_user user8 <function generate_user at 0x027087F0>
rename_user user2 <function generate_user at 0x027087F0>
sign_out
ls
whoami
rename_user user3 <function generate_user at 0x027087F0>
show_folders
whoami
sign_out
pwd
ls_folders
show_users
rename_user user3 <function generate_user at 0x027087F0>
show_items
sign_in a1 pa1
show_item_properties item2
register_admin user8 pass8
ls_folders
ls_folders
sign_in a3 pa3
add_item item3 key5=val2 key2=val1 key4=val5 key4=val10 
add_item_property item5 key1=val4 key4=val10 key7=val3 key8=val5 
sign_in admin admin
show_folders
add_item_property item2 key3=val6 key10=val8 key10=val3 key3=val10 
register_admin user8 pass8
pwd
whoami
show_item_properties item5
add_item_property item1 key9=val8 key1=val10 key10=val9 key3=val1 
sign_in user9 pass9
buy
which_group
register_admin user7 pass7
show_folders
register_admin admin admin
add_item_property item5 key2=val2 key7=val8 key2=val9 key7=val9 
current_folder
buy
rename_user user5 <function generate_user at 0x027087F0>
whoami
sign_out
cd folder5
show_items
sign_in a2 pa2
sign_in user6 pass6
add_item item5 key2=val9 key9=val7 key3=val2 key4=val10 
cd folder4
show_items
add_item_property item4 key10=val2 key7=val5 key8=val10 key8=val10 
register_admin user7 pass7
current_folder
sign_in a2 pa2
ls_folders
register_user user7 pass7
sign_in a5 pa5
rename_user user1 <function generate_user at 0x027087F0>
show_items
ls
show_users
which_group
pwd
show_folders
sign_in a3 pa3
ls
register_user user3 pass3
add_item_property item4 key5=val7 key1=val7 key4=val7 key7=val5 
cd folder4
show_folders
whoami
sign_in a3 pa3
cd folder3
which_group
register_admin user3 pass3
show_item_properties item3
current_folder
rename_user user6 <function generate_user at 0x027087F0>
buy
buy
add_item item1 key3=val3 key7=val5 key8=val7 key9=val7 
show_users
put item4
put item1
put item2
sign_out
register_admin admin admin
buy
pwd
add_item_property item2 key6=val4 key5=val3 key3=val2 key8=val5 
show_folders
current_folder
sign_in user4 pass4
help cd
show_items
register_admin user8 pass8
sign_in a5 pa5
create_folder folder2
cd folder2
ls_folders
sign_in user5 pass5
cd folder4
rename_user user6 <function generate_user at 0x027087F0>
sign_in user6 pass6
which_group
show_items
register_admin user8 pass8
create_folder folder3
cd folder2
sign_in a5 pa5
pwd
register_admin user9 pass9
pwd
sign_out
put item5
cd folder2
whoami
show_item_properties item3
add_item item3 key4=val5 key3=val7 key4=val1 key1=val5 
show_item_properties item4
add_item_property item5 key4=val6 key6=val5 key6=val3 key2=val3 
sign_in a4 pa4
buy
register_user user9 pass9
add_item item5 key4=val4 key8=val1 key1=val8 key6=val1 
sign_in user2 pass2
which_group
buy
which_group
register_user admin admin
show_item_properties item3
whoami
help add_item
help view_order
sign_in user6 pass6
rename_user user1 <function generate_user at 0x027087F0>
ls_folders
rename_user user9 <function generate_user at 0x027087F0>
sign_in user3 pass3
help put
put item1
buy
pwd
current_folder
show_users
register_user admin admin
sign_in a3 pa3
register_user user1 pass1
register_admin user4 pass4
register_admin user7 pass7
help view_order
put item2
register_admin user9 pass9
rename_user user0 <function generate_user at 0x027087F0>
whoami
show_items
rename_user user6 <function generate_user at 0x027087F0>
which_group
cd folder4
rename_user user0 <function generate_user at 0x027087F0>
pwd
sign_out
sign_in a1 pa1
sign_in a5 pa5
cd folder3
pwd
buy
ls
whoami
pwd
show_item_properties item5
whoami
show_folders
add_item_property item2 key10=val4 key6=val7 key10=val9 key3=val1 
buy
add_item item4 key5=val8 key2=val3 key1=val10 key2=val2 
rename_user user1 <function generate_user at 0x027087F0>
put item2
current_folder
current_folder
sign_in user3 pass3
help help
sign_in a5 pa5
create_folder folder4
add_item_property item2 key3=val7 key1=val6 key3=val7 key10=val1 
help help
pwd
ls_folders
current_folder
sign_in user1 pass1
rename_user user3 <function generate_user at 0x027087F0>
ls
current_folder
create_folder folder5
show_items
whoami
sign_out
show_users
which_group
register_user user4 pass4
sign_in a4 pa4
register_user user2 pass2
rename_user user7 <function generate_user at 0x027087F0>
which_group
pwd
buy
which_group
help add_item_property
show_item_properties item2
cd folder5
sign_in user1 pass1
show_users
sign_out
add_item item2 key3=val8 key2=val5 key7=val10 key9=val8 
ls_folders
sign_out
add_item_property item1 key6=val6 key8=val1 key1=val3 key1=val5 
sign_in a1 pa1
show_item_properties item1
show_folders
show_items
current_folder
show_users
add_item_property item1 key4=val5 key2=val9 key10=val1 key9=val1 
show_items
cd folder2
register_user user6 pass6
add_item item5 key4=val6 key8=val4 key7=val2 key9=val5 
sign_in user8 pass8
help rename_user
help show_folders
current_folder
help add_item_property
buy
current_folder
ls
whoami
rename_user user9 <function generate_user at 0x027087F0>
sign_out
add_item item3 key10=val7 key4=val7 key4=val5 key9=val4 
buy
sign_in a1 pa1
add_item item3 key3=val1 key7=val5 key9=val4 key6=val6 
add_item item1 key6=val3 key10=val8 key8=val5 key1=val9 
whoami
sign_in a2 pa2
register_user user7 pass7
create_folder folder3
sign_in user4 pass4
show_items
cd folder3
whoami
sign_in user9 pass9
register_admin admin admin
sign_in a4 pa4
sign_out
add_item item3 key4=val1 key6=val9 key6=val3 key2=val4 
which_group
whoami
register_admin user2 pass2
buy
sign_out
register_user user6 pass6
ls_folders
create_folder folder2
put item2
register_user user9 pass9
create_folder folder4
buy
create_folder folder4
add_item item4 key7=val5 key2=val7 key6=val7 key2=val6 
show_folders
rename_user user1 <function generate_user at 0x027087F0>
show_users
put item1
current_folder
ls_folders
show_items
sign_in a1 pa1
put item5
cd folder2
sign_out
which_group
sign_in a5 pa5
sign_in user5 pass5
sign_in user7 pass7
put item1
sign_out
sign_in user7 pass7
sign_in a5 pa5
sign_out
show_items
create_folder folder4
cd folder1
help delete_user
pwd
put item1
create_folder folder5
show_items
help create_folder
add_item_property item3 key10=val6 key6=val4 key8=val10 key7=val3 
rename_user user1 <function generate_user at 0x027087F0>
show_folders
add_item_property item4 key3=val4 key5=val1 key10=val3 key6=val8 
show_users
whoami
rename_user user6 <function generate_user at 0x027087F0>
ls
pwd
whoami
show_items
buy
show_items
sign_in a3 pa3
sign_out
buy
show_items
current_folder
pwd
add_item item1 key1=val2 key3=val2 key6=val1 key3=val9 
show_users
register_user user5 pass5
which_group
add_item_property item3 key3=val3 key8=val5 key6=val2 key2=val2 
add_item item4 key8=val1 key10=val9 key10=val4 key9=val9 
add_item_property item3 key4=val7 key1=val10 key10=val6 key1=val3 
sign_in user3 pass3
show_folders
put item4
rename_user user4 <function generate_user at 0x027087F0>
rename_user user0 <function generate_user at 0x027087F0>
sign_in user4 pass4
rename_user user0 <function generate_user at 0x027087F0>
sign_in a5 pa5
register_user admin admin
create_folder folder2
current_folder
show_users
rename_user user4 <function generate_user at 0x027087F0>
show_items
sign_out
add_item_property item3 key1=val10 key1=val5 key7=val4 key1=val4 
show_users
show_users
help rename_user
current_folder
rename_user user9 <function generate_user at 0x027087F0>
which_group
whoami
create_folder folder1
sign_in a1 pa1
sign_in a4 pa4
add_item item3 key9=val4 key2=val4 key2=val1 key3=val4 
add_item item1 key2=val7 key10=val2 key3=val3 key7=val6 
create_folder folder2
ls
add_item_property item5 key6=val8 key9=val2 key1=val8 key8=val7 
show_users
rename_user user4 <function generate_user at 0x027087F0>
buy
sign_out
show_items
register_admin user9 pass9
register_admin user6 pass6
whoami
show_items
sign_out
register_admin user1 pass1
sign_out
help put
create_folder folder4
put item3
show_item_properties item1
current_folder
buy
register_admin user4 pass4
show_folders
sign_in user8 pass8
rename_user user3 <function generate_user at 0x027087F0>
pwd
show_folders
whoami
help view_order
register_user user6 pass6
show_items
current_folder
sign_in a4 pa4
ls
show_users
sign_in user9 pass9
add_item item3 key6=val8 key1=val10 key5=val4 key1=val10 
which_group
help add_item
put item2
show_items
create_folder folder4
cd folder1
rename_user user9 <function generate_user at 0x027087F0>
sign_out
ls_folders
show_folders
buy
which_group
add_item_property item1 key10=val9 key1=val7 key6=val5 key4=val3 
current_folder
add_item item1 key3=val6 key1=val3 key6=val1 key6=val5 
sign_in admin admin
help help
ls_folders
show_users
put item2
sign_in a3 pa3
show_folders
register_user admin admin
register_user user5 pass5
add_item_property item4 key5=val1 key9=val8 key5=val3 key9=val8 
show_users
sign_in user6 pass6
cd folder2
show_folders
cd folder2
whoami
show_item_properties item3
buy
cd folder3
help show_items
ls
cd folder4
current_folder
ls_folders
put item5
ls
ls_folders
which_group
add_item item4 key4=val2 key8=val3 key8=val5 key10=val5 
register_admin user1 pass1
show_folders
show_users
show_users
ls
register_admin user9 pass9
add_item item1 key6=val5 key3=val9 key4=val8 key7=val9 
sign_in user5 pass5
ls_folders
ls
create_folder folder4
put item3
register_admin user4 pass4
pwd
show_items
ls
which_group
which_group
ls_folders
add_item item2 key3=val6 key5=val7 key9=val7 key8=val7 
cd folder1
whoami
create_folder folder1
pwd
ls
current_folder
show_items
sign_out
ls_folders
show_folders
rename_user user0 <function generate_user at 0x027087F0>
which_group
register_user user6 pass6
put item4
which_group
buy
current_folder
which_group
show_item_properties item5
sign_out
ls
ls
whoami
show_item_properties item5
whoami
add_item_property item5 key5=val1 key2=val7 key9=val2 key2=val6 
register_user user4 pass4
which_group
pwd
register_admin user1 pass1
add_item_property item2 key3=val4 key1=val6 key6=val8 key5=val8 
ls
show_item_properties item3
ls
current_folder
which_group
create_folder folder3
sign_in admin admin
create_folder folder3
sign_in user8 pass8
buy
current_folder
help show_users
register_admin admin admin
ls_folders
cd folder4
sign_in a1 pa1
show_folders
sign_in a3 pa3
pwd
sign_in a5 pa5
show_item_properties item1
sign_in user2 pass2
sign_out
whoami
show_item_properties item2
create_folder folder3
cd folder2
register_admin user8 pass8
show_folders
current_folder
rename_user user5 <function generate_user at 0x027087F0>
which_group
cd folder4
current_folder
put item2
show_item_properties item3
show_items
which_group
buy
rename_user user1 <function generate_user at 0x027087F0>
ls_folders
current_folder
sign_in user6 pass6
buy
buy
help cd
show_users
register_user user6 pass6
add_item item3 key1=val5 key9=val1 key9=val10 key2=val8 
cd folder1
ls_folders
sign_out
show_item_properties item5
sign_in a4 pa4
ls
sign_in user4 pass4
register_user admin admin
sign_in a2 pa2
register_user admin admin
create_folder folder3
help help
add_item item3 key1=val4 key2=val9 key2=val2 key1=val6 
create_folder folder5
ls
buy
show_users
sign_out
buy
register_user user6 pass6
buy
add_item item5 key9=val10 key5=val4 key2=val3 key6=val3 
sign_out
ls
rename_user user6 <function generate_user at 0x027087F0>
add_item item3 key7=val10 key10=val10 key2=val6 key1=val4 
pwd
cd folder5
add_item_property item5 key8=val1 key1=val4 key7=val7 key1=val8 
whoami
rename_user user6 <function generate_user at 0x027087F0>
add_item item1 key4=val5 key4=val5 key7=val1 key10=val3 
ls
current_folder
sign_in user2 pass2
buy
rename_user user5 <function generate_user at 0x027087F0>
whoami
help whoami
add_item item2 key6=val4 key4=val10 key6=val5 key4=val5 
whoami
which_group
cd folder4
add_item_property item2 key6=val5 key3=val10 key6=val7 key5=val5 
rename_user user1 <function generate_user at 0x027087F0>
pwd
show_items
show_item_properties item1
add_item_property item1 key5=val7 key1=val1 key6=val10 key3=val7 
buy
cd folder5
show_item_properties item4
current_folder
sign_in a4 pa4
help history
create_folder folder4
add_item_property item3 key5=val9 key6=val9 key4=val5 key8=val9 
sign_in user7 pass7
add_item_property item4 key10=val6 key6=val2 key3=val3 key8=val1 
sign_in a3 pa3
pwd
add_item_property item3 key1=val9 key7=val4 key2=val2 key6=val6 
sign_in a2 pa2
sign_in user1 pass1
add_item item4 key6=val4 key1=val10 key4=val1 key6=val9 
sign_in a1 pa1
add_item item4 key10=val6 key9=val1 key10=val5 key4=val3 
help show_users
current_folder
show_item_properties item5
ls_folders
whoami
show_item_properties item4
register_user admin admin
sign_in user7 pass7
cd folder5
register_admin user4 pass4
cd folder1
cd folder3
add_item_property item4 key5=val4 key7=val5 key6=val1 key10=val8 
sign_out
cd folder2
buy
create_folder folder5
add_item item1 key10=val10 key4=val8 key9=val8 key7=val5 
sign_in user7 pass7
register_user admin admin
cd folder1
show_item_properties item1
show_items
show_folders
which_group
which_group
show_item_properties item2
sign_in a5 pa5
ls
help show_item_properties
ls_folders
add_item_property item1 key8=val9 key9=val8 key1=val4 key1=val10 
rename_user user6 <function generate_user at 0x027087F0>
sign_out
create_folder folder4
show_items
register_user user3 pass3
show_items
show_folders
show_item_properties item4
register_admin user4 pass4
add_item_property item3 key5=val3 key5=val4 key2=val6 key10=val3 
show_users
whoami
create_folder folder4
add_item_property item3 key2=val3 key3=val3 key10=val10 key3=val8 
rename_user user2 <function generate_user at 0x027087F0>
show_item_properties item1
help put
current_folder
show_items
sign_in user6 pass6
which_group
register_user user4 pass4
add_item_property item2 key8=val10 key5=val8 key7=val9 key3=val4 
register_admin user3 pass3
add_item_property item1 key4=val1 key5=val6 key6=val2 key3=val8 
pwd
whoami
rename_user user5 <function generate_user at 0x027087F0>
register_admin user3 pass3
sign_out
show_folders
create_folder folder4
register_user user2 pass2
sign_in a1 pa1
ls
sign_out
show_folders
create_folder folder4
pwd
register_user user8 pass8
sign_in user8 pass8
sign_out
sign_out
sign_in a3 pa3
sign_in user4 pass4
show_users
help add_item_property
put item3
whoami
cd folder3
put item2
ls
ls_folders
sign_out
rename_user user5 <function generate_user at 0x027087F0>
help put
put item1
sign_in a3 pa3
add_item item4 key9=val8 key8=val9 key6=val1 key8=val10 
show_item_properties item5
pwd
which_group
help sign_out
sign_in a2 pa2
register_admin user8 pass8
register_user user1 pass1
sign_in user9 pass9
rename_user user2 <function generate_user at 0x027087F0>
show_users
sign_in a4 pa4
pwd
show_items
ls_folders
sign_in user4 pass4
register_user user3 pass3
help sign_out
add_item_property item1 key4=val6 key9=val3 key6=val3 key5=val8 
register_user user5 pass5
show_users
sign_in user2 pass2
add_item item3 key6=val3 key5=val5 key4=val10 key1=val6 
register_user user3 pass3
create_folder folder3
ls
sign_in user8 pass8
put item3
ls
register_user user9 pass9
create_folder folder4
ls
rename_user user5 <function generate_user at 0x027087F0>
sign_in user5 pass5
add_item_property item2 key4=val9 key10=val2 key2=val5 key7=val8 
show_items
buy
show_items
pwd
put item2
register_user user4 pass4
rename_user user6 <function generate_user at 0x027087F0>
add_item item4 key10=val7 key7=val2 key4=val2 key4=val3 
ls
cd folder1
pwd
sign_in user5 pass5
sign_out
show_item_properties item1
add_item_property item3 key5=val4 key8=val3 key6=val6 key9=val5 
sign_in user4 pass4
pwd
ls
sign_out
cd folder2
buy
ls
cd folder5
add_item_property item4 key4=val7 key2=val3 key2=val5 key1=val5 
sign_out
buy
register_admin user9 pass9
sign_in user4 pass4
show_item_properties item5
ls
sign_out
which_group
show_users
sign_out
current_folder
whoami
sign_out
add_item_property item5 key7=val4 key7=val9 key8=val4 key7=val8 
show_items
which_group
sign_in a3 pa3
add_item item4 key6=val2 key7=val9 key8=val4 key9=val7 
show_item_properties item4
add_item_property item5 key10=val5 key1=val5 key3=val7 key3=val4 
sign_in a5 pa5
sign_in user7 pass7
sign_out
cd folder5
add_item item3 key1=val1 key3=val2 key2=val6 key9=val6 
show_users
register_admin user9 pass9
ls
current_folder
buy
register_user user8 pass8
help add_item_property
ls_folders
sign_in a2 pa2
sign_in a5 pa5
buy
register_admin user3 pass3
buy
put item4
create_folder folder1
help pwd
rename_user user2 <function generate_user at 0x027087F0>
sign_in user5 pass5
show_folders
sign_in user2 pass2
show_users
sign_in a2 pa2
ls
show_item_properties item4
sign_in user5 pass5
which_group
pwd
show_folders
register_admin user2 pass2
add_item item2 key4=val5 key3=val9 key2=val3 key5=val10 
current_folder
show_items
show_folders
sign_out
show_items
show_items
ls
cd folder2
rename_user user9 <function generate_user at 0x027087F0>
sign_in user8 pass8
sign_in user4 pass4
ls_folders
buy
sign_in user1 pass1
current_folder
sign_in a3 pa3
show_users
pwd
show_item_properties item2
sign_in a3 pa3
show_items
register_admin user3 pass3
put item3
sign_out
show_folders
register_user admin admin
ls_folders
rename_user user0 <function generate_user at 0x027087F0>
buy
sign_in a5 pa5
put item5
put item4
add_item_property item2 key10=val8 key3=val8 key7=val9 key8=val5 
show_users
sign_in a1 pa1
ls_folders
buy
rename_user user0 <function generate_user at 0x027087F0>
cd folder4
show_folders
sign_in user6 pass6
show_folders
whoami
whoami
cd folder2
create_folder folder1
register_admin user2 pass2
rename_user user8 <function generate_user at 0x027087F0>
show_users
register_admin user4 pass4
rename_user user5 <function generate_user at 0x027087F0>
add_item_property item4 key5=val8 key1=val5 key8=val5 key8=val10 
buy
rename_user user7 <function generate_user at 0x027087F0>
add_item_property item3 key7=val10 key9=val2 key8=val8 key8=val10 
buy
help pwd
buy
which_group
pwd
current_folder
show_item_properties item3
show_item_properties item4
add_item_property item4 key8=val5 key1=val9 key10=val3 key6=val2 
sign_in user1 pass1
current_folder
help cd
current_folder
current_folder
buy
register_admin user3 pass3
show_items
buy
sign_out
cd folder1
whoami
register_user user6 pass6
register_user user5 pass5
sign_in user4 pass4
current_folder
show_folders
which_group
whoami
create_folder folder5
cd folder1
create_folder folder2
cd folder4
show_items
add_item_property item3 key7=val3 key3=val6 key1=val7 key4=val10 
current_folder
add_item_property item4 key4=val3 key2=val7 key4=val9 key4=val7 
show_items
current_folder
ls
sign_in a2 pa2
cd folder3
show_items
ls
sign_out
help rename_user
register_user user5 pass5
show_item_properties item2
show_items
add_item_property item5 key1=val6 key1=val1 key6=val4 key9=val1 
show_items
ls
buy
register_user user8 pass8
create_folder folder4
whoami
ls
sign_in user2 pass2
put item4
buy
sign_out
help sign_in
register_user user9 pass9
which_group
whoami
register_user user2 pass2
show_folders
show_item_properties item1
add_item item3 key7=val3 key10=val4 key6=val10 key2=val1 
sign_in a4 pa4
cd folder3
show_users
create_folder folder5
whoami
buy
pwd
ls
sign_out
show_items
sign_out
add_item_property item2 key10=val6 key3=val1 key1=val5 key2=val1 
show_item_properties item2
register_admin user1 pass1
sign_in a2 pa2
cd folder2
pwd
ls
put item5
register_user user6 pass6
register_admin user1 pass1
help add_item
ls_folders
buy
register_user user4 pass4
sign_in user6 pass6
buy
show_folders
register_user user3 pass3
put item3
which_group
add_item_property item1 key7=val10 key8=val2 key4=val6 key2=val9 
ls_folders
show_items
cd folder4
add_item item1 key7=val4 key6=val5 key5=val7 key6=val5 
put item3
register_admin user1 pass1
show_item_properties item3
whoami
show_folders
which_group
sign_in admin admin
show_items
cd folder3
cd folder2
sign_in a2 pa2
buy
help put
add_item_property item5 key2=val6 key2=val7 key8=val3 key10=val4 
put item2
sign_out
show_item_properties item4
help add_item
show_items
whoami
rename_user user1 <function generate_user at 0x027087F0>
whoami
add_item_property item1 key7=val2 key8=val7 key3=val6 key6=val4 
cd folder1
sign_in user5 pass5
put item5
add_item_property item4 key2=val3 key3=val8 key5=val7 key7=val1 
sign_in user1 pass1
sign_out
ls
ls
ls
register_user admin admin
ls_folders
sign_in user8 pass8
rename_user user2 <function generate_user at 0x027087F0>
cd folder2
cd folder2
current_folder
which_group
show_users
show_item_properties item2
which_group
cd folder4
show_users
rename_user user8 <function generate_user at 0x027087F0>
register_admin user3 pass3
show_folders
sign_in admin admin
ls
show_items
pwd
register_user user5 pass5
register_admin admin admin
ls_folders
cd folder4
ls_folders
add_item_property item3 key5=val4 key3=val4 key4=val6 key5=val9 
add_item item3 key9=val1 key3=val8 key7=val3 key4=val9 
add_item_property item5 key9=val2 key7=val10 key1=val7 key9=val1 
create_folder folder5
sign_out
help which_group
pwd
show_folders
help show_users
pwd
buy
sign_in user5 pass5
sign_in admin admin
add_item item1 key3=val1 key2=val3 key5=val10 key7=val1 
show_items
ls
pwd
create_folder folder3
show_users
register_admin admin admin
cd folder1
show_items
show_items
put item5
sign_in admin admin
which_group
put item4
which_group
ls
show_item_properties item2
ls_folders
add_item_property item3 key8=val1 key2=val2 key10=val7 key6=val5 
current_folder
show_users
buy
put item5
help create_folder
rename_user user9 <function generate_user at 0x027087F0>
register_user user3 pass3
show_item_properties item5
create_folder folder5
whoami
current_folder
rename_user user8 <function generate_user at 0x027087F0>
whoami
whoami
show_folders
create_folder folder5
show_item_properties item4
buy
rename_user user6 <function generate_user at 0x027087F0>
sign_in admin admin
show_items
show_users
register_user user4 pass4
show_folders
help help
create_folder folder1
sign_in user2 pass2
rename_user user4 <function generate_user at 0x027087F0>
whoami
cd folder5
add_item item2 key4=val9 key1=val1 key2=val9 key9=val8 
current_folder
pwd
add_item item4 key5=val7 key10=val8 key3=val5 key9=val3 
put item2
whoami
register_admin user5 pass5
register_user user9 pass9
ls_folders
show_items
ls
ls
ls
help help
buy
sign_in user6 pass6
which_group
sign_out
pwd
create_folder folder2
sign_in a4 pa4
show_items
sign_in user9 pass9
add_item_property item2 key5=val3 key2=val1 key7=val7 key7=val2 
add_item_property item1 key10=val8 key5=val4 key4=val1 key10=val7 
buy
put item1
sign_in a1 pa1
sign_in user5 pass5
help sign_out
add_item item2 key7=val8 key4=val8 key4=val9 key1=val1 
sign_in a2 pa2
buy
sign_in user8 pass8
help ls_folders
sign_in user1 pass1
help exit
show_items
current_folder
register_admin user3 pass3
help buy
pwd
ls_folders
add_item_property item1 key8=val7 key7=val8 key9=val7 key7=val4 
cd folder5
sign_in user3 pass3
cd folder4
buy
help ls_folders
show_folders
sign_in user1 pass1
buy
current_folder
cd folder4
help cd
pwd
show_users
show_items
show_items
register_user user7 pass7
show_folders
register_admin user4 pass4
sign_in user8 pass8
sign_in admin admin
create_folder folder5
rename_user user4 <function generate_user at 0x027087F0>
show_item_properties item4
current_folder
show_users
show_folders
current_folder
ls
cd folder4
put item2
sign_in user2 pass2
sign_in a5 pa5
show_users
register_admin user2 pass2
sign_in user4 pass4
rename_user user7 <function generate_user at 0x027087F0>
add_item_property item5 key6=val9 key9=val10 key3=val7 key1=val3 
add_item_property item4 key1=val3 key7=val9 key1=val10 key4=val9 
show_item_properties item3
pwd
show_users
ls_folders
add_item_property item2 key1=val3 key5=val7 key9=val6 key1=val5 
ls
cd folder5
add_item_property item1 key10=val2 key3=val5 key9=val3 key1=val4 
show_users
add_item_property item3 key9=val2 key7=val4 key3=val6 key9=val1 
whoami
show_folders
which_group
register_user user5 pass5
add_item item1 key4=val5 key1=val5 key2=val6 key8=val3 
show_users
register_user user4 pass4
ls
which_group
register_admin admin admin
help delete_user
sign_in a5 pa5
which_group
add_item_property item1 key1=val4 key10=val10 key4=val7 key4=val6 
add_item item5 key8=val2 key4=val5 key8=val3 key10=val1 
pwd
register_user user5 pass5
ls_folders
register_admin user7 pass7
add_item_property item2 key1=val9 key10=val9 key1=val8 key10=val4 
register_admin user7 pass7
current_folder
current_folder
whoami
add_item item4 key1=val8 key10=val9 key7=val1 key10=val6 
show_users
show_folders
register_admin user3 pass3
whoami
register_user user5 pass5
show_items
ls
cd folder1
cd folder3
ls_folders
buy
rename_user user7 <function generate_user at 0x027087F0>
ls_folders
whoami
show_item_properties item3
rename_user user9 <function generate_user at 0x027087F0>
register_admin user5 pass5
rename_user user1 <function generate_user at 0x027087F0>
register_user user5 pass5
sign_in a2 pa2
add_item item5 key3=val1 key3=val3 key3=val4 key9=val5 
create_folder folder2
create_folder folder4
register_user user2 pass2
register_admin user5 pass5
ls
sign_in user7 pass7
show_item_properties item1
add_item_property item1 key7=val6 key4=val1 key6=val2 key8=val1 
show_users
show_items
current_folder
help show_users
add_item item1 key4=val3 key4=val8 key7=val10 key10=val9 
show_items
sign_in a5 pa5
sign_in a5 pa5
buy
register_admin user1 pass1
rename_user user4 <function generate_user at 0x027087F0>
show_item_properties item1
sign_in a1 pa1
create_folder folder4
whoami
rename_user user7 <function generate_user at 0x027087F0>
which_group
put item3
ls_folders
cd folder4
cd folder2
add_item item4 key8=val1 key1=val3 key3=val6 key6=val4 
register_user user6 pass6
add_item item5 key9=val8 key8=val6 key6=val7 key10=val8 
show_item_properties item2
add_item item1 key8=val1 key4=val7 key6=val9 key10=val2 
show_items
ls_folders
current_folder
show_item_properties item4
add_item_property item4 key10=val1 key4=val8 key5=val4 key3=val9 
ls_folders
add_item_property item5 key5=val9 key4=val7 key5=val2 key7=val6 
buy
add_item_property item3 key6=val7 key8=val4 key7=val5 key1=val2 
sign_in a5 pa5
sign_in user8 pass8
add_item item3 key3=val8 key2=val10 key8=val6 key5=val4 
register_admin user4 pass4
add_item item4 key8=val7 key4=val1 key9=val2 key8=val5 
register_admin user5 pass5
show_items
show_folders
sign_in user6 pass6
add_item_property item3 key6=val8 key5=val8 key3=val5 key4=val1 
rename_user user6 <function generate_user at 0x027087F0>
sign_in a1 pa1
show_items
which_group
create_folder folder2
register_admin user5 pass5
register_user user2 pass2
ls_folders
which_group
register_user user5 pass5
add_item item4 key6=val6 key5=val7 key6=val10 key6=val7 
rename_user user3 <function generate_user at 0x027087F0>
show_folders
show_users
put item5
show_items
register_user user7 pass7
add_item item5 key3=val4 key4=val2 key6=val1 key10=val7 
rename_user user6 <function generate_user at 0x027087F0>
sign_out
current_folder
sign_out
show_users
sign_out
which_group
current_folder
register_admin user3 pass3
sign_in a3 pa3
rename_user user6 <function generate_user at 0x027087F0>
which_group
put item2
show_item_properties item4
show_items
sign_in admin admin
cd folder2
help history
sign_out
show_items
whoami
cd folder5
ls
current_folder
rename_user user8 <function generate_user at 0x027087F0>
help add_item_property
pwd
put item1
add_item item5 key1=val6 key8=val3 key1=val7 key8=val6 
put item4
show_item_properties item3
add_item_property item4 key8=val2 key8=val1 key9=val3 key4=val7 
which_group
pwd
add_item_property item1 key8=val3 key8=val1 key7=val1 key7=val8 
create_folder folder3
show_items
register_user user2 pass2
register_admin user9 pass9
sign_out
pwd
pwd
ls_folders
add_item_property item2 key6=val6 key9=val8 key1=val5 key4=val7 
show_users
ls
rename_user user6 <function generate_user at 0x027087F0>
pwd
current_folder
register_user user9 pass9
put item4
add_item_property item4 key5=val10 key2=val3 key9=val7 key7=val10 
add_item_property item3 key8=val3 key10=val10 key1=val10 key1=val9 
cd folder5
show_item_properties item4
buy
add_item_property item2 key10=val1 key6=val8 key6=val7 key8=val2 
cd folder5
put item2
sign_in user6 pass6
add_item_property item2 key8=val6 key3=val4 key9=val4 key3=val1 
add_item_property item2 key10=val2 key2=val6 key9=val9 key5=val8 
whoami
sign_in user8 pass8
buy
sign_out
show_item_properties item4
sign_out
whoami
sign_out
create_folder folder4
register_user user6 pass6
add_item_property item1 key1=val2 key10=val2 key8=val9 key6=val5 
which_group
sign_in a2 pa2
create_folder folder1
which_group
which_group
current_folder
register_admin user6 pass6
show_item_properties item1
create_folder folder5
add_item item2 key6=val4 key4=val6 key1=val10 key10=val1 
pwd
sign_in user4 pass4
current_folder
sign_in a1 pa1
show_items
rename_user user8 <function generate_user at 0x027087F0>
show_item_properties item3
sign_in a5 pa5
buy
sign_in user4 pass4
whoami
create_folder folder2
ls
rename_user user5 <function generate_user at 0x027087F0>
show_users
current_folder
buy
register_admin user5 pass5
ls_folders
show_items
rename_user user3 <function generate_user at 0x027087F0>
pwd
create_folder folder2
help rename_user
show_users
register_user user2 pass2
show_users
whoami
add_item item3 key4=val5 key9=val9 key3=val7 key6=val9 
show_items
add_item_property item4 key8=val7 key4=val10 key7=val4 key10=val7 
register_user user6 pass6
register_admin user9 pass9
sign_in user3 pass3
create_folder folder4
create_folder folder5
show_item_properties item2
show_users
cd folder2
help register_user
current_folder
which_group
buy
pwd
sign_out
put item1
register_user user2 pass2
show_folders
rename_user user4 <function generate_user at 0x027087F0>
ls_folders
add_item_property item2 key10=val7 key5=val2 key8=val2 key7=val9 
sign_in a4 pa4
current_folder
ls_folders
show_item_properties item3
show_users
sign_out
put item4
add_item item3 key7=val9 key9=val10 key7=val2 key8=val1 
put item2
rename_user user2 <function generate_user at 0x027087F0>
rename_user user8 <function generate_user at 0x027087F0>
register_user user1 pass1
register_admin user1 pass1
put item3
which_group
ls
create_folder folder3
rename_user user0 <function generate_user at 0x027087F0>
whoami
add_item item5 key1=val8 key3=val2 key4=val5 key3=val5 
pwd
add_item_property item2 key2=val9 key9=val1 key7=val8 key6=val9 
current_folder
help ls_folders
register_admin user9 pass9
put item5
buy
show_item_properties item3
show_item_properties item2
sign_out
show_item_properties item3
current_folder
ls_folders
add_item item4 key3=val3 key6=val6 key3=val3 key8=val8 
put item4
register_user user8 pass8
show_items
ls
show_users
sign_in user3 pass3
which_group
whoami
rename_user user0 <function generate_user at 0x027087F0>
show_users
sign_in user6 pass6
create_folder folder4
ls_folders
ls
show_users
rename_user user5 <function generate_user at 0x027087F0>
cd folder2
ls
buy
rename_user user1 <function generate_user at 0x027087F0>
current_folder
sign_in a3 pa3
show_items
show_users
whoami
sign_in a4 pa4
sign_out
show_items
sign_in a2 pa2
register_admin user1 pass1
show_folders
sign_in a3 pa3
current_folder
current_folder
register_admin user1 pass1
rename_user user0 <function generate_user at 0x027087F0>
show_items
current_folder
show_items
buy
ls
current_folder
add_item_property item1 key4=val3 key4=val5 key6=val8 key8=val10 
sign_in a5 pa5
show_items
sign_out
buy
sign_in user9 pass9
ls_folders
ls_folders
sign_out
buy
pwd
ls
create_folder folder1
cd folder3
add_item item4 key10=val6 key6=val6 key8=val1 key7=val6 
sign_in user9 pass9
cd folder2
register_user user7 pass7
ls
cd folder1
sign_in user1 pass1
ls_folders
register_user user9 pass9
which_group
show_users
rename_user user8 <function generate_user at 0x027087F0>
register_user user6 pass6
help current_folder
ls
pwd
show_folders
register_admin user4 pass4
pwd
add_item_property item3 key2=val3 key7=val9 key10=val3 key8=val9 
show_users
show_item_properties item2
ls
sign_in a1 pa1
ls
register_user user4 pass4
show_items
show_items
whoami
show_users
register_user admin admin
ls_folders
show_item_properties item5
buy
buy
buy
sign_in user5 pass5
create_folder folder3
register_user user2 pass2
add_item item2 key5=val7 key6=val9 key1=val7 key4=val1 
which_group
put item3
add_item item4 key6=val9 key3=val6 key1=val3 key4=val7 
add_item_property item4 key6=val3 key1=val1 key2=val7 key1=val10 
show_item_properties item5
put item2
register_user user6 pass6
which_group
show_folders
help show_items
whoami
pwd
cd folder2
add_item item4 key3=val9 key7=val9 key10=val4 key6=val9 
pwd
whoami
cd folder3
put item2
add_item item1 key7=val2 key9=val6 key2=val10 key2=val6 
show_item_properties item4
which_group
whoami
buy
show_folders
show_items
put item1
show_users
current_folder
help view_order
show_folders
register_user user8 pass8
sign_in a2 pa2
show_item_properties item5
rename_user user9 <function generate_user at 0x027087F0>
create_folder folder2
show_users
buy
pwd
rename_user user5 <function generate_user at 0x027087F0>
show_folders
sign_in user5 pass5
pwd
add_item_property item4 key8=val2 key10=val2 key3=val10 key4=val4 
ls_folders
register_admin user1 pass1
show_folders
rename_user user7 <function generate_user at 0x027087F0>
add_item item5 key2=val9 key1=val9 key2=val5 key5=val10 
whoami
cd folder2
sign_in a3 pa3
pwd
sign_in user8 pass8
buy
cd folder1
ls
current_folder
pwd
which_group
which_group
add_item_property item2 key5=val4 key2=val9 key1=val8 key2=val7 
put item4
sign_in user4 pass4
current_folder
create_folder folder4
current_folder
put item1
sign_in a4 pa4
rename_user user5 <function generate_user at 0x027087F0>
buy
sign_in user9 pass9
register_admin user7 pass7
show_folders
show_items
pwd
sign_out
buy
register_user user6 pass6
add_item_property item2 key3=val6 key1=val6 key3=val1 key6=val1 
show_item_properties item2
ls_folders
rename_user user0 <function generate_user at 0x027087F0>
register_user user3 pass3
add_item_property item2 key4=val7 key1=val8 key6=val1 key6=val9 
show_users
which_group
show_users
sign_in user9 pass9
whoami
pwd
register_admin user5 pass5
register_user user9 pass9
cd folder1
help pwd
ls
ls_folders
current_folder
add_item_property item2 key3=val8 key6=val2 key1=val5 key1=val4 
register_admin user6 pass6
show_users
create_folder folder1
show_item_properties item4
show_items
register_admin user3 pass3
sign_in a5 pa5
show_items
show_items
show_users
sign_in a1 pa1
add_item item5 key8=val9 key1=val10 key4=val10 key4=val3 
cd folder4
cd folder1
which_group
put item1
show_item_properties item3
add_item_property item5 key9=val4 key2=val1 key6=val9 key10=val1 
pwd
sign_in admin admin
help show_users
ls_folders
show_item_properties item2
create_folder folder1
rename_user user5 <function generate_user at 0x027087F0>
ls
current_folder
sign_in user6 pass6
add_item_property item5 key5=val4 key7=val5 key4=val5 key2=val2 
register_admin user1 pass1
add_item item3 key5=val9 key10=val5 key3=val1 key6=val9 
show_item_properties item1
sign_out
pwd
register_admin user3 pass3
show_items
add_item item3 key7=val4 key9=val4 key8=val3 key9=val2 
rename_user user6 <function generate_user at 0x027087F0>
put item1
ls
show_item_properties item4
help view_order
cd folder3
add_item_property item5 key3=val3 key6=val8 key3=val4 key8=val6 
show_folders
add_item_property item2 key10=val5 key3=val9 key2=val8 key1=val7 
put item5
current_folder
sign_out
sign_out
register_user user2 pass2
current_folder
ls_folders
rename_user user6 <function generate_user at 0x027087F0>
help show_items
ls
register_user admin admin
current_folder
cd folder3
sign_in a5 pa5
buy
buy
add_item_property item4 key6=val2 key2=val5 key3=val7 key4=val7 
create_folder folder4
cd folder1
register_user user3 pass3
buy
show_items
rename_user user3 <function generate_user at 0x027087F0>
register_user user1 pass1
register_user user1 pass1
sign_in a3 pa3
sign_in user4 pass4
show_items
create_folder folder4
add_item_property item3 key6=val7 key6=val8 key1=val9 key10=val8 
register_admin admin admin
current_folder
show_item_properties item2
sign_in a5 pa5
show_folders
sign_in a3 pa3
sign_in a3 pa3
register_user admin admin
show_items
sign_in user6 pass6
ls_folders
sign_out
ls_folders
sign_out
ls
whoami
put item5
add_item_property item2 key8=val3 key9=val4 key8=val4 key6=val10 
rename_user user9 <function generate_user at 0x027087F0>
sign_out
help history
sign_in a3 pa3
register_user user6 pass6
current_folder
sign_in user5 pass5
whoami
pwd
sign_in a2 pa2
show_item_properties item2
show_folders
show_folders
show_item_properties item4
create_folder folder4
show_items
sign_in a2 pa2
sign_in user8 pass8
show_item_properties item1
show_items
add_item item3 key4=val2 key3=val8 key3=val1 key1=val1 
cd folder2
buy
current_folder
help register_admin
sign_in a2 pa2
pwd
register_admin user6 pass6
add_item item4 key4=val10 key1=val4 key2=val2 key2=val3 
add_item item3 key6=val9 key2=val4 key1=val4 key6=val5 
add_item_property item1 key1=val4 key3=val6 key2=val8 key10=val4 
cd folder2
sign_in user8 pass8
add_item_property item2 key10=val1 key10=val2 key7=val1 key3=val6 
add_item item5 key8=val6 key7=val4 key7=val5 key7=val4 
cd folder2
pwd
sign_in user5 pass5
show_item_properties item4
sign_out
show_item_properties item2
whoami
sign_in user6 pass6
current_folder
register_admin user8 pass8
ls
show_users
show_users
whoami
put item2
sign_in a1 pa1
which_group
show_folders
show_items
ls
which_group
help whoami
show_items
pwd
help rename_user
add_item_property item5 key8=val1 key2=val6 key1=val8 key2=val3 
help register_user
which_group
whoami
cd folder4
show_users
whoami
put item3
sign_in a4 pa4
put item5
add_item item1 key8=val6 key2=val3 key5=val5 key6=val3 
sign_in a2 pa2
register_user user5 pass5
add_item_property item4 key3=val9 key6=val3 key4=val7 key4=val4 
ls_folders
sign_in user2 pass2
create_folder folder5
show_users
show_users
sign_in admin admin
show_folders
register_admin admin admin
create_folder folder1
add_item_property item2 key4=val1 key9=val9 key7=val3 key4=val7 
put item2
show_folders
sign_in a5 pa5
whoami
create_folder folder1
rename_user user5 <function generate_user at 0x027087F0>
sign_out
show_folders
buy
sign_out
register_user user9 pass9
cd folder4
buy
help show_item_properties
sign_in user1 pass1
ls
rename_user user6 <function generate_user at 0x027087F0>
create_folder folder5
put item5
sign_in a3 pa3
rename_user user2 <function generate_user at 0x027087F0>
ls
rename_user user0 <function generate_user at 0x027087F0>
register_user user1 pass1
current_folder
add_item_property item1 key8=val5 key8=val2 key4=val5 key2=val9 
register_user user8 pass8
buy
show_users
which_group
create_folder folder2
buy
show_users
show_users
register_admin user9 pass9
which_group
sign_in user7 pass7
add_item_property item2 key1=val6 key4=val2 key6=val10 key5=val3 
which_group
rename_user user3 <function generate_user at 0x027087F0>
buy
show_items
register_admin admin admin
whoami
add_item_property item2 key2=val8 key4=val8 key9=val3 key4=val9 
sign_in user7 pass7
cd folder1
buy
cd folder4
sign_out
put item5
show_item_properties item2
add_item item1 key3=val4 key6=val9 key2=val9 key4=val5 
whoami
whoami
create_folder folder1
sign_in user9 pass9
ls_folders
sign_out
show_users
register_admin user1 pass1
rename_user user6 <function generate_user at 0x027087F0>
whoami
sign_in a5 pa5
ls
cd folder4
put item2
sign_in a2 pa2
ls
register_admin user1 pass1
show_items
register_admin user8 pass8
put item5
ls_folders
put item5
current_folder
buy
help current_folder
create_folder folder1
which_group
help whoami
ls_folders
sign_in a2 pa2
sign_in a3 pa3
register_user user1 pass1
register_admin admin admin
buy
sign_out
show_items
sign_in user3 pass3
show_item_properties item2
sign_in user5 pass5
show_item_properties item5
sign_in user5 pass5
sign_in admin admin
show_item_properties item3
show_folders
current_folder
cd folder5
add_item_property item3 key6=val3 key3=val1 key4=val4 key3=val1 
buy
pwd
help show_items
add_item item1 key8=val8 key6=val4 key3=val1 key6=val6 
sign_in user9 pass9
current_folder
current_folder
show_items
show_item_properties item5
show_folders
which_group
ls_folders
sign_in a2 pa2
rename_user user8 <function generate_user at 0x027087F0>
add_item item1 key6=val8 key10=val7 key7=val5 key10=val9 
buy
ls_folders
register_user user5 pass5
show_folders
sign_in a3 pa3
register_user user7 pass7
add_item item1 key2=val3 key3=val7 key9=val5 key8=val2 
help current_folder
put item1
create_folder folder4
show_folders
sign_in user2 pass2
add_item_property item5 key3=val5 key6=val5 key8=val6 key2=val10 
pwd
whoami
ls
add_item_property item3 key9=val7 key10=val2 key6=val4 key7=val5 
ls
rename_user user8 <function generate_user at 0x027087F0>
add_item item1 key9=val2 key7=val3 key7=val9 key6=val7 
ls_folders
create_folder folder1
sign_in admin admin
buy
sign_in a1 pa1
create_folder folder4
create_folder folder1
create_folder folder5
register_user user3 pass3
add_item item2 key7=val6 key8=val6 key10=val7 key1=val6 
sign_in user5 pass5
ls
ls
show_folders
ls
sign_in user5 pass5
add_item_property item2 key9=val9 key7=val6 key5=val3 key6=val5 
pwd
rename_user user9 <function generate_user at 0x027087F0>
sign_out
buy
pwd
show_folders
sign_in user4 pass4
add_item_property item4 key7=val5 key4=val7 key6=val2 key8=val8 
ls_folders
sign_out
add_item_property item3 key8=val9 key2=val1 key1=val8 key6=val1 
ls_folders
rename_user user4 <function generate_user at 0x027087F0>
sign_in user8 pass8
whoami
pwd
whoami
sign_in user1 pass1
cd folder5
register_admin user6 pass6
sign_out
put item1
sign_out
register_admin user2 pass2
buy
current_folder
ls_folders
add_item_property item1 key10=val4 key8=val9 key7=val4 key3=val5 
sign_in user2 pass2
show_folders
buy
buy
put item3
show_folders
pwd
show_users
add_item_property item5 key3=val3 key8=val8 key4=val1 key8=val4 
ls_folders
show_item_properties item2
put item1
show_items
rename_user user2 <function generate_user at 0x027087F0>
register_admin user1 pass1
register_admin admin admin
register_user user8 pass8
ls
show_users
show_items
pwd
show_items
register_user user8 pass8
whoami
sign_out
rename_user user2 <function generate_user at 0x027087F0>
help register_user
register_admin user3 pass3
register_user admin admin
show_item_properties item1
show_folders
sign_in a5 pa5
whoami
add_item item2 key7=val6 key8=val10 key8=val8 key3=val3 
which_group
whoami
sign_in user9 pass9
show_items
show_folders
sign_in a3 pa3
sign_in user9 pass9
show_item_properties item5
show_users
ls_folders
register_admin user2 pass2
add_item_property item1 key9=val1 key3=val7 key2=val1 key7=val1 
ls
cd folder5
show_users
add_item_property item2 key7=val6 key6=val4 key4=val3 key10=val4 
show_items
pwd
register_user user9 pass9
pwd
put item3
pwd
put item3
which_group
cd folder5
pwd
ls
show_users
pwd
add_item_property item5 key7=val5 key9=val2 key9=val3 key6=val2 
ls
sign_in a1 pa1
create_folder folder3
ls_folders
sign_out
show_users
register_user user5 pass5
pwd
help exit
buy
show_users
sign_in a3 pa3
add_item item1 key8=val9 key7=val6 key3=val4 key3=val3 
sign_in a4 pa4
add_item item1 key3=val9 key4=val8 key1=val5 key2=val3 
add_item item4 key7=val6 key8=val7 key1=val9 key7=val6 
sign_out
buy
create_folder folder4
cd folder5
add_item item3 key7=val5 key4=val5 key5=val10 key4=val10 
pwd
show_users
show_users
show_users
help put
show_item_properties item2
sign_out
sign_in a2 pa2
show_folders
register_user user2 pass2
pwd
cd folder3
sign_in user5 pass5
show_items
whoami
sign_in a4 pa4
show_item_properties item2
pwd
put item1
show_items
add_item item3 key6=val5 key5=val10 key7=val7 key7=val9 
help sign_in
sign_out
sign_out
whoami
pwd
sign_in a3 pa3
whoami
pwd
help view_order
whoami
ls_folders
buy
register_admin user3 pass3
sign_out
help delete_user
sign_in admin admin
sign_in user1 pass1
whoami
help exit
rename_user user7 <function generate_user at 0x027087F0>
create_folder folder1
register_admin user6 pass6
show_items
cd folder1
add_item item1 key8=val3 key1=val6 key10=val2 key5=val5 
buy
sign_out
add_item item5 key2=val4 key1=val2 key5=val10 key9=val10 
sign_in a1 pa1
whoami
add_item_property item5 key6=val4 key10=val8 key5=val9 key8=val7 
whoami
sign_out
sign_in user6 pass6
show_folders
buy
sign_in a4 pa4
register_user user7 pass7
show_items
add_item_property item5 key5=val9 key7=val10 key7=val9 key10=val2 
sign_in user3 pass3
cd folder3
add_item_property item5 key1=val4 key2=val4 key4=val10 key7=val9 
whoami
sign_in a4 pa4
create_folder folder2
whoami
help help
show_item_properties item5
show_users
sign_out
show_items
buy
register_admin user3 pass3
register_admin user1 pass1
help pwd
sign_in user9 pass9
sign_in user5 pass5
rename_user user7 <function generate_user at 0x027087F0>
help pwd
show_users
add_item item5 key7=val7 key10=val7 key1=val8 key10=val8 
rename_user user3 <function generate_user at 0x027087F0>
whoami
put item4
cd folder3
which_group
cd folder3
sign_in user5 pass5
which_group
ls
add_item_property item4 key1=val7 key8=val8 key4=val6 key3=val4 
cd folder2
whoami
show_folders
rename_user user2 <function generate_user at 0x027087F0>
help ls_folders
add_item_property item5 key2=val9 key3=val3 key8=val8 key8=val2 
add_item item2 key8=val1 key3=val3 key5=val2 key5=val2 
help history
pwd
show_folders
show_item_properties item4
sign_in user2 pass2
which_group
whoami
rename_user user3 <function generate_user at 0x027087F0>
pwd
ls_folders
which_group
sign_out
sign_in a5 pa5
register_admin user7 pass7
show_items
add_item item3 key7=val7 key1=val1 key10=val7 key1=val3 
add_item_property item3 key10=val1 key2=val10 key3=val7 key2=val4 
pwd
show_items
sign_in user5 pass5
current_folder
pwd
register_user user1 pass1
sign_out
cd folder5
show_item_properties item4
sign_in a5 pa5
ls_folders
which_group
ls
register_admin user3 pass3
show_item_properties item2
which_group
sign_in a5 pa5
sign_in user1 pass1
sign_in user9 pass9
ls
help sign_out
rename_user user3 <function generate_user at 0x027087F0>
add_item_property item1 key1=val1 key1=val3 key3=val9 key8=val9 
help current_folder
sign_in user9 pass9
current_folder
sign_in a1 pa1
current_folder
current_folder
which_group
sign_in a1 pa1
add_item_property item4 key10=val2 key6=val8 key7=val3 key2=val2 
register_admin user2 pass2
show_users
show_item_properties item3
show_folders
sign_in user4 pass4
show_users
ls
help history
add_item_property item3 key3=val5 key5=val7 key9=val6 key3=val8 
pwd
sign_in user3 pass3
help rename_user
pwd
add_item item5 key7=val2 key8=val8 key4=val6 key5=val3 
show_items
sign_in user5 pass5
rename_user user1 <function generate_user at 0x027087F0>
add_item_property item5 key5=val5 key3=val9 key1=val6 key4=val9 
ls_folders
which_group
show_users
buy
register_admin user4 pass4
add_item_property item1 key2=val7 key5=val5 key1=val7 key8=val8 
register_admin admin admin
sign_in user6 pass6
current_folder
add_item item5 key9=val9 key8=val6 key6=val9 key1=val2 
show_users
show_item_properties item3
create_folder folder5
add_item item1 key5=val4 key4=val10 key5=val3 key9=val3 
sign_out
show_items
pwd
put item1
show_item_properties item1
sign_in user6 pass6
cd folder2
show_users
buy
show_users
buy
add_item item1 key10=val2 key4=val7 key3=val6 key4=val1 
whoami
sign_in user4 pass4
show_folders
help add_item_property
cd folder4
buy
current_folder
add_item_property item2 key5=val4 key8=val7 key3=val3 key7=val10 
sign_out
put item1
buy
which_group
sign_in user6 pass6
sign_out
rename_user user7 <function generate_user at 0x027087F0>
register_admin admin admin
create_folder folder1
current_folder
show_items
show_folders
sign_in user2 pass2
sign_out
whoami
register_admin user7 pass7
ls
help ls_folders
register_user user7 pass7
current_folder
show_folders
help which_group
put item2
whoami
add_item item5 key6=val8 key6=val5 key2=val4 key4=val1 
add_item_property item5 key9=val1 key7=val3 key2=val3 key1=val6 
show_item_properties item2
sign_in user1 pass1
create_folder folder5
sign_in admin admin
buy
put item3
add_item_property item2 key4=val10 key7=val10 key4=val6 key2=val4 
show_folders
buy
put item4
cd folder4
show_items
current_folder
sign_in user7 pass7
register_admin user2 pass2
show_item_properties item1
create_folder folder3
pwd
sign_in user2 pass2
current_folder
put item4
help history
whoami
put item3
show_items
which_group
sign_in user5 pass5
sign_out
show_users
show_folders
put item1
whoami
show_users
add_item_property item2 key10=val9 key7=val7 key10=val1 key1=val8 
which_group
add_item_property item1 key2=val6 key9=val5 key4=val2 key3=val5 
ls
rename_user user6 <function generate_user at 0x027087F0>
pwd
show_item_properties item3
ls_folders
pwd
which_group
current_folder
sign_in user8 pass8
show_folders
sign_in user8 pass8
sign_in user7 pass7
put item2
rename_user user0 <function generate_user at 0x027087F0>
ls
add_item item2 key4=val10 key3=val2 key8=val1 key9=val9 
ls_folders
sign_in a5 pa5
show_items
buy
sign_in user5 pass5
rename_user user2 <function generate_user at 0x027087F0>
put item1
show_item_properties item1
show_users
pwd
rename_user user2 <function generate_user at 0x027087F0>
ls
which_group
sign_in a1 pa1
ls_folders
cd folder2
cd folder4
sign_out
create_folder folder1
which_group
ls_folders
pwd
sign_in user9 pass9
show_items
cd folder1
put item1
show_users
show_items
show_items
add_item_property item5 key6=val2 key2=val5 key6=val9 key9=val2 
show_folders
buy
show_items
ls
show_items
sign_in user7 pass7
current_folder
cd folder4
current_folder
create_folder folder3
register_user user3 pass3
ls_folders
current_folder
show_users
add_item_property item4 key4=val8 key9=val10 key5=val7 key5=val7 
which_group
register_user user8 pass8
rename_user user8 <function generate_user at 0x027087F0>
help whoami
sign_out
sign_in a1 pa1
ls_folders
register_admin user6 pass6
pwd
cd folder3
sign_out
rename_user user1 <function generate_user at 0x027087F0>
put item3
rename_user user6 <function generate_user at 0x027087F0>
sign_in a5 pa5
current_folder
cd folder2
sign_in user5 pass5
show_users
ls_folders
show_items
add_item item3 key8=val9 key4=val2 key7=val2 key6=val4 
sign_in a2 pa2
ls
whoami
add_item_property item2 key7=val2 key10=val3 key4=val4 key1=val2 
pwd
put item3
pwd
sign_in user6 pass6
sign_out
pwd
show_folders
current_folder
register_admin user1 pass1
rename_user user9 <function generate_user at 0x027087F0>
current_folder
register_user user3 pass3
add_item_property item3 key10=val8 key4=val6 key3=val10 key7=val1 
help current_folder
show_item_properties item2
cd folder1
show_folders
rename_user user0 <function generate_user at 0x027087F0>
add_item item1 key6=val8 key8=val1 key6=val8 key3=val1 
show_users
create_folder folder5
ls_folders
help current_folder
ls_folders
put item1
register_user user4 pass4
show_items
put item4
register_user user7 pass7
sign_in user5 pass5
create_folder folder4
register_user user5 pass5
sign_out
show_items
cd folder1
cd folder2
sign_in a4 pa4
create_folder folder2
current_folder
which_group
show_item_properties item3
buy
ls_folders
add_item_property item1 key10=val5 key5=val1 key5=val1 key6=val1 
add_item item5 key8=val6 key6=val10 key9=val5 key4=val4 
add_item_property item3 key6=val3 key1=val3 key4=val4 key1=val8 
sign_out
add_item_property item1 key9=val8 key6=val4 key6=val5 key10=val9 
buy
create_folder folder4
ls_folders
current_folder
register_user user1 pass1
sign_in a3 pa3
whoami
current_folder
register_user user5 pass5
help which_group
whoami
ls_folders
sign_in user8 pass8
ls
whoami
rename_user user2 <function generate_user at 0x027087F0>
show_users
pwd
register_admin user9 pass9
ls_folders
which_group
show_folders
register_admin user5 pass5
sign_in user2 pass2
show_item_properties item5
cd folder1
help sign_in
ls
add_item_property item5 key8=val2 key10=val3 key9=val9 key6=val5 
help current_folder
sign_out
buy
put item2
show_users
put item2
show_folders
put item5
put item2
register_admin user3 pass3
pwd
sign_in a1 pa1
sign_in user4 pass4
rename_user user9 <function generate_user at 0x027087F0>
register_admin user5 pass5
whoami
cd folder1
ls
ls
add_item_property item1 key6=val9 key9=val8 key10=val7 key5=val4 
buy
current_folder
show_users
show_users
register_user user9 pass9
show_item_properties item5
sign_out
show_folders
add_item_property item1 key3=val8 key2=val7 key2=val10 key3=val6 
ls
pwd
register_admin user7 pass7
help history
sign_in user8 pass8
ls_folders
pwd
register_user user5 pass5
current_folder
sign_in user4 pass4
show_item_properties item2
show_item_properties item1
which_group
put item5
current_folder
add_item_property item3 key10=val2 key3=val3 key1=val4 key1=val8 
pwd
buy
current_folder
ls_folders
show_item_properties item2
pwd
add_item item1 key7=val1 key8=val5 key3=val6 key3=val5 
pwd
buy
show_folders
add_item item4 key1=val4 key9=val4 key3=val4 key4=val3 
show_item_properties item2
add_item item3 key4=val10 key3=val8 key6=val6 key7=val2 
put item1
which_group
sign_out
whoami
ls
show_folders
register_admin user9 pass9
add_item_property item3 key1=val10 key7=val5 key9=val2 key5=val8 
show_item_properties item3
which_group
cd folder1
ls
sign_in user6 pass6
create_folder folder1
sign_in user9 pass9
create_folder folder4
rename_user user5 <function generate_user at 0x027087F0>
register_admin user7 pass7
put item1
ls_folders
sign_out
current_folder
which_group
pwd
sign_in a5 pa5
current_folder
current_folder
ls
register_admin user2 pass2
show_users
show_users
show_folders
help view_order
buy
rename_user user5 <function generate_user at 0x027087F0>
whoami
add_item_property item1 key7=val1 key1=val3 key5=val4 key5=val8 
cd folder5
ls_folders
sign_in user9 pass9
add_item_property item2 key3=val7 key7=val6 key4=val3 key3=val2 
create_folder folder5
register_user user1 pass1
ls
buy
show_items
current_folder
ls
ls_folders
register_admin user3 pass3
show_items
current_folder
pwd
buy
sign_in user7 pass7
rename_user user4 <function generate_user at 0x027087F0>
buy
help current_folder
ls_folders
ls
show_items
ls_folders
buy
sign_in user7 pass7
show_folders
register_admin admin admin
current_folder
cd folder1
add_item_property item1 key8=val3 key6=val4 key3=val9 key8=val1 
sign_out
pwd
which_group
show_item_properties item5
ls_folders
show_item_properties item3
help help
help add_item
rename_user user6 <function generate_user at 0x027087F0>
register_user user8 pass8
show_item_properties item3
show_items
sign_in a5 pa5
show_items
ls_folders
show_users
sign_out
add_item item1 key5=val10 key6=val3 key5=val8 key9=val9 
add_item item1 key4=val8 key9=val8 key1=val5 key6=val5 
add_item_property item3 key8=val8 key7=val1 key4=val7 key4=val2 
put item2
whoami
sign_in user5 pass5
show_item_properties item5
which_group
show_users
add_item item5 key8=val4 key8=val4 key5=val8 key6=val8 
register_user user5 pass5
whoami
add_item_property item3 key8=val2 key9=val7 key1=val4 key10=val2 
cd folder4
add_item item5 key5=val2 key2=val2 key10=val7 key5=val9 
sign_in a3 pa3
show_folders
add_item item3 key5=val6 key7=val10 key2=val9 key8=val6 
show_item_properties item1
sign_out
pwd
ls
which_group
register_user user6 pass6
sign_in user6 pass6
show_item_properties item1
show_item_properties item5
put item4
show_users
add_item item2 key4=val8 key3=val8 key10=val8 key5=val7 
whoami
sign_out
sign_in user6 pass6
add_item item3 key3=val9 key7=val5 key9=val6 key5=val9 
current_folder
show_users
show_folders
register_admin user1 pass1
ls
whoami
add_item_property item5 key10=val7 key6=val3 key9=val9 key6=val8 
sign_out
buy
rename_user user3 <function generate_user at 0x027087F0>
rename_user user9 <function generate_user at 0x027087F0>
whoami
add_item item3 key6=val6 key2=val5 key9=val9 key3=val8 
current_folder
rename_user user0 <function generate_user at 0x027087F0>
which_group
add_item item4 key5=val3 key3=val8 key9=val4 key3=val9 
show_items
show_items
add_item_property item4 key7=val2 key8=val7 key10=val9 key8=val5 
put item1
sign_out
ls
sign_in a3 pa3
sign_out
sign_in user1 pass1
show_item_properties item1
show_users
show_items
add_item_property item2 key10=val6 key8=val3 key9=val2 key5=val6 
help help
add_item_property item1 key9=val4 key10=val7 key4=val7 key6=val10 
which_group
show_users
sign_out
show_item_properties item3
help register_user
sign_out
pwd
sign_out
whoami
add_item item5 key5=val6 key2=val10 key2=val2 key2=val2 
ls_folders
create_folder folder5
show_item_properties item2
register_user user5 pass5
ls
help view_order
register_user admin admin
which_group
current_folder
put item2
sign_in user8 pass8
show_users
register_user user1 pass1
cd folder1
help delete_user
ls_folders
add_item_property item1 key9=val6 key8=val10 key7=val6 key7=val5 
current_folder
whoami
current_folder
which_group
which_group
register_user user3 pass3
ls
show_items
help current_folder
sign_out
help register_admin
sign_in a4 pa4
current_folder
add_item_property item2 key8=val3 key4=val9 key7=val6 key7=val2 
sign_in a3 pa3
ls_folders
ls_folders
whoami
register_admin user9 pass9
show_folders
add_item item4 key2=val7 key1=val10 key8=val9 key7=val6 
current_folder
create_folder folder1
create_folder folder4
whoami
help add_item_property
add_item_property item5 key8=val1 key7=val9 key8=val10 key7=val2 
sign_in user8 pass8
rename_user user1 <function generate_user at 0x027087F0>
register_user user3 pass3
pwd
show_items
show_users
show_item_properties item3
which_group
whoami
register_user user4 pass4
put item4
show_users
add_item item5 key10=val9 key9=val3 key1=val5 key6=val10 
add_item_property item4 key1=val1 key2=val7 key1=val6 key10=val1 
help show_folders
pwd
show_items
ls_folders
rename_user user1 <function generate_user at 0x027087F0>
sign_in user2 pass2
put item3
ls
show_users
register_admin user8 pass8
ls
pwd
create_folder folder4
current_folder
register_admin user5 pass5
register_admin admin admin
register_admin user1 pass1
cd folder3
show_item_properties item3
ls
create_folder folder2
cd folder3
register_admin user2 pass2
sign_out
whoami
cd folder5
whoami
show_item_properties item1
sign_out
show_folders
sign_out
whoami
rename_user user9 <function generate_user at 0x027087F0>
show_folders
sign_in a5 pa5
show_item_properties item1
register_user user1 pass1
sign_in user6 pass6
pwd
ls
add_item_property item2 key7=val6 key4=val3 key2=val10 key7=val2 
which_group
which_group
create_folder folder2
buy
sign_in user8 pass8
ls
sign_out
show_items
show_users
register_admin user3 pass3
show_item_properties item5
ls
pwd
create_folder folder3
create_folder folder2
create_folder folder1
current_folder
pwd
pwd
register_user admin admin
cd folder3
current_folder
current_folder
register_user user7 pass7
show_users
sign_out
show_folders
show_item_properties item3
sign_in admin admin
cd folder2
buy
pwd
ls
current_folder
register_user user8 pass8
ls_folders
register_admin user8 pass8
show_folders
show_folders
show_items
show_item_properties item3
help show_folders
which_group
register_user user2 pass2
rename_user user0 <function generate_user at 0x027087F0>
put item5
add_item item5 key3=val9 key8=val7 key7=val2 key6=val1 
which_group
buy
sign_in a4 pa4
register_user user1 pass1
show_item_properties item3
whoami
add_item item1 key1=val7 key4=val5 key1=val5 key1=val2 
create_folder folder4
show_users
ls_folders
show_folders
sign_in user9 pass9
pwd
which_group
ls
show_items
register_user user7 pass7
show_folders
add_item item1 key6=val1 key9=val5 key7=val5 key3=val8 
register_user user5 pass5
rename_user user8 <function generate_user at 0x027087F0>
ls_folders
buy
buy
sign_out
help ls
ls
whoami
show_item_properties item3
whoami
show_users
cd folder4
ls
show_folders
rename_user user1 <function generate_user at 0x027087F0>
sign_in user4 pass4
ls
pwd
which_group
ls
sign_in user5 pass5
current_folder
rename_user user8 <function generate_user at 0x027087F0>
register_admin user9 pass9
which_group
create_folder folder1
show_items
ls_folders
show_item_properties item1
show_folders
pwd
put item4
ls_folders
sign_in user6 pass6
show_folders
current_folder
put item1
whoami
show_users
create_folder folder2
add_item item2 key10=val2 key2=val2 key3=val8 key1=val10 
show_users
show_item_properties item1
register_admin admin admin
put item4
create_folder folder4
register_user user5 pass5
current_folder
show_users
ls_folders
sign_in user3 pass3
show_items
register_admin user4 pass4
cd folder2
add_item item1 key3=val2 key4=val8 key1=val2 key2=val3 
add_item_property item3 key3=val2 key5=val5 key3=val4 key8=val3 
sign_out
register_user user1 pass1
register_user user7 pass7
sign_in a2 pa2
which_group
current_folder
create_folder folder1
register_admin user9 pass9
show_folders
register_user user3 pass3
add_item_property item1 key7=val7 key5=val10 key9=val4 key9=val8 
current_folder
register_admin admin admin
put item2
show_users
sign_out
show_folders
add_item_property item5 key2=val5 key4=val5 key4=val10 key3=val4 
ls
register_admin user1 pass1
show_users
put item2
buy
sign_in a5 pa5
add_item_property item2 key2=val3 key5=val1 key3=val4 key6=val8 
show_item_properties item2
register_admin user6 pass6
buy
buy
buy
put item3
sign_in a3 pa3
current_folder
buy
cd folder3
show_items
ls_folders
current_folder
pwd
whoami
buy
show_folders
show_users
sign_in a5 pa5
sign_in user9 pass9
buy
add_item_property item3 key10=val1 key9=val6 key5=val3 key3=val4 
help show_folders
create_folder folder1
current_folder
sign_out
register_admin user9 pass9
buy
ls
ls_folders
whoami
which_group
help register_user
buy
show_items
add_item_property item5 key8=val6 key6=val2 key4=val4 key4=val4 
add_item item2 key9=val10 key10=val3 key9=val7 key8=val7 
ls
ls
rename_user user9 <function generate_user at 0x027087F0>
show_users
buy
whoami
ls
sign_in a1 pa1
cd folder5
rename_user user4 <function generate_user at 0x027087F0>
show_items
current_folder
cd folder4
show_users
show_folders
show_item_properties item1
sign_in a5 pa5
ls_folders
show_folders
cd folder5
sign_out
show_items
ls
sign_out
put item1
show_items
show_items
cd folder3
rename_user user2 <function generate_user at 0x027087F0>
pwd
buy
put item1
buy
sign_out
cd folder2
show_items
pwd
ls
show_users
show_items
rename_user user6 <function generate_user at 0x027087F0>
rename_user user3 <function generate_user at 0x027087F0>
ls_folders
show_item_properties item4
create_folder folder4
ls_folders
current_folder
rename_user user8 <function generate_user at 0x027087F0>
register_user user9 pass9
show_items
sign_out
show_folders
show_item_properties item3
rename_user user2 <function generate_user at 0x027087F0>
show_item_properties item1
sign_in user3 pass3
put item3
current_folder
cd folder5
sign_out
ls_folders
show_items
ls_folders
sign_in user4 pass4
current_folder
rename_user user9 <function generate_user at 0x027087F0>
sign_in a1 pa1
show_item_properties item4
sign_out
current_folder
cd folder2
create_folder folder3
sign_out
sign_out
buy
show_users
cd folder1
add_item_property item5 key3=val6 key8=val9 key4=val8 key6=val1 
sign_in user7 pass7
pwd
register_admin user9 pass9
sign_in user2 pass2
register_admin user5 pass5
rename_user user2 <function generate_user at 0x027087F0>
show_item_properties item2
help buy
register_admin user6 pass6
register_admin user3 pass3
register_admin user9 pass9
register_user user2 pass2
rename_user user5 <function generate_user at 0x027087F0>
sign_out
show_users
register_user user2 pass2
pwd
show_users
show_folders
put item3
show_folders
sign_out
sign_out
ls
buy
show_users
which_group
sign_in admin admin
which_group
show_items
register_user user3 pass3
sign_in a3 pa3
ls
buy
current_folder
add_item_property item2 key10=val3 key9=val5 key5=val6 key8=val5 
sign_in user3 pass3
sign_out
sign_in a4 pa4
sign_out
sign_out
which_group
sign_in user3 pass3
current_folder
cd folder4
add_item_property item4 key1=val7 key4=val1 key4=val5 key8=val5 
whoami
buy
add_item_property item1 key9=val5 key6=val2 key7=val10 key10=val4 
ls
show_items
rename_user user2 <function generate_user at 0x027087F0>
rename_user user0 <function generate_user at 0x027087F0>
rename_user user6 <function generate_user at 0x027087F0>
register_user user2 pass2
put item2
buy
show_users
add_item_property item5 key3=val4 key7=val10 key6=val5 key6=val3 
ls_folders
which_group
show_users
add_item_property item4 key8=val10 key9=val7 key2=val3 key9=val2 
register_admin user6 pass6
sign_out
which_group
pwd
show_item_properties item4
show_folders
show_item_properties item4
add_item_property item1 key6=val3 key10=val3 key4=val8 key3=val9 
create_folder folder3
create_folder folder2
show_users
create_folder folder1
which_group
put item3
whoami
sign_in a2 pa2
ls
register_user user2 pass2
sign_in user9 pass9
help register_user
create_folder folder4
cd folder5
create_folder folder4
ls
add_item_property item2 key5=val8 key2=val7 key10=val10 key6=val3 
whoami
ls
create_folder folder2
current_folder
rename_user user5 <function generate_user at 0x027087F0>
sign_in admin admin
show_items
which_group
current_folder
pwd
help exit
show_item_properties item1
rename_user user9 <function generate_user at 0x027087F0>
help history
ls_folders
ls_folders
show_items
ls_folders
current_folder
show_item_properties item4
sign_in a3 pa3
show_items
show_users
show_item_properties item4
which_group
pwd
buy
sign_in user2 pass2
sign_out
add_item item1 key3=val4 key6=val3 key6=val3 key9=val2 
show_items
which_group
create_folder folder5
put item5
add_item_property item2 key5=val7 key3=val3 key5=val1 key10=val1 
show_users
add_item_property item2 key3=val7 key5=val3 key1=val9 key1=val4 
current_folder
cd folder2
sign_out
which_group
create_folder folder5
add_item item3 key3=val4 key7=val3 key4=val4 key8=val2 
register_admin user4 pass4
show_folders
ls
show_items
show_users
ls
which_group
which_group
show_items
cd folder1
ls_folders
pwd
ls_folders
sign_in a2 pa2
register_admin user4 pass4
sign_in user9 pass9
whoami
current_folder
add_item_property item4 key10=val4 key9=val7 key3=val8 key4=val1 
add_item_property item2 key4=val3 key1=val2 key4=val3 key9=val5 
sign_in user6 pass6
add_item item4 key6=val3 key2=val7 key5=val10 key9=val5 
show_item_properties item2
pwd
rename_user user5 <function generate_user at 0x027087F0>
register_admin user4 pass4
ls
rename_user user9 <function generate_user at 0x027087F0>
cd folder2
register_admin admin admin
pwd
sign_out
put item4
ls
cd folder1
sign_in a3 pa3
sign_out
current_folder
put item2
current_folder
pwd
cd folder3
whoami
ls_folders
ls_folders
cd folder4
register_admin user5 pass5
which_group
add_item item2 key6=val9 key10=val4 key1=val6 key9=val5 
ls_folders
put item3
rename_user user3 <function generate_user at 0x027087F0>
pwd
register_user user3 pass3
put item4
current_folder
which_group
add_item item3 key2=val8 key5=val8 key5=val2 key2=val4 
ls
pwd
add_item_property item4 key1=val5 key6=val4 key8=val1 key4=val3 
whoami
show_item_properties item1
help show_items
show_users
buy
sign_in user1 pass1
which_group
which_group
show_folders
rename_user user8 <function generate_user at 0x027087F0>
sign_out
whoami
show_folders
sign_out
pwd
help add_item
create_folder folder4
show_item_properties item3
buy
current_folder
show_folders
help show_folders
whoami
ls
register_user user7 pass7
show_folders
register_user user2 pass2
register_admin admin admin
help delete_user
register_admin user2 pass2
rename_user user2 <function generate_user at 0x027087F0>
sign_out
register_admin user3 pass3
whoami
ls_folders
current_folder
put item1
show_folders
buy
put item1
show_items
help exit
current_folder
rename_user user9 <function generate_user at 0x027087F0>
current_folder
register_admin user1 pass1
ls
help current_folder
show_folders
which_group
pwd
rename_user user8 <function generate_user at 0x027087F0>
show_folders
register_admin user9 pass9
show_users
ls_folders
add_item item1 key4=val1 key8=val2 key5=val1 key3=val2 
current_folder
help history
cd folder1
cd folder3
show_item_properties item3
show_users
ls
pwd
ls
register_user user7 pass7
ls
rename_user user1 <function generate_user at 0x027087F0>
whoami
ls_folders
buy
add_item item2 key4=val9 key8=val10 key1=val8 key6=val10 
register_user user2 pass2
ls
help create_folder
which_group
whoami
register_user user4 pass4
register_user admin admin
pwd
sign_in user8 pass8
which_group
show_users
show_folders
whoami
whoami
sign_out
whoami
ls_folders
current_folder
whoami
ls
whoami
create_folder folder3
create_folder folder2
add_item_property item3 key8=val5 key3=val1 key7=val3 key1=val9 
show_items
show_items
register_admin user7 pass7
which_group
create_folder folder5
put item3
show_item_properties item5
sign_out
sign_in user3 pass3
help sign_in
add_item item4 key6=val8 key4=val8 key1=val9 key3=val1 
current_folder
rename_user user7 <function generate_user at 0x027087F0>
current_folder
which_group
buy
rename_user user9 <function generate_user at 0x027087F0>
pwd
cd folder3
help show_item_properties
put item3
sign_in user8 pass8
cd folder2
ls
add_item_property item2 key8=val10 key5=val10 key1=val1 key3=val6 
show_item_properties item2
show_folders
put item5
put item1
sign_in user9 pass9
sign_in a5 pa5
ls_folders
which_group
help history
show_item_properties item4
show_items
pwd
whoami
current_folder
cd folder3
ls_folders
show_items
ls
current_folder
show_users
show_item_properties item1
which_group
create_folder folder2
pwd
sign_out
sign_in user4 pass4
show_items
show_folders
help add_item
pwd
rename_user user5 <function generate_user at 0x027087F0>
add_item_property item1 key6=val8 key5=val1 key3=val3 key2=val6 
add_item item3 key9=val9 key4=val10 key1=val9 key1=val1 
register_user user6 pass6
add_item_property item5 key3=val10 key9=val7 key10=val2 key4=val4 
register_admin user3 pass3
current_folder
add_item_property item4 key3=val1 key2=val1 key9=val4 key10=val3 
sign_out
add_item item4 key4=val2 key5=val9 key10=val5 key1=val6 
ls_folders
put item1
help show_item_properties
create_folder folder2
register_admin user9 pass9
sign_in user7 pass7
sign_out
which_group
ls_folders
show_folders
show_items
whoami
whoami
add_item_property item4 key4=val2 key9=val4 key1=val2 key10=val8 
rename_user user2 <function generate_user at 0x027087F0>
help history
cd folder1
ls
help history
register_user user1 pass1
current_folder
ls_folders
whoami
pwd
register_admin user6 pass6
show_folders
show_users
register_user user2 pass2
show_item_properties item4
pwd
show_items
current_folder
show_items
show_items
create_folder folder1
rename_user user3 <function generate_user at 0x027087F0>
sign_in a4 pa4
put item5
cd folder1
sign_in a4 pa4
buy
put item2
add_item_property item1 key1=val5 key1=val6 key3=val2 key2=val7 
show_item_properties item1
cd folder4
sign_out
current_folder
show_item_properties item5
show_folders
add_item item2 key3=val8 key6=val9 key6=val2 key9=val7 
rename_user user1 <function generate_user at 0x027087F0>
put item4
cd folder3
pwd
sign_in a2 pa2
sign_out
pwd
ls_folders
current_folder
show_folders
ls
sign_out
show_users
show_items
register_user user5 pass5
create_folder folder4
which_group
pwd
show_item_properties item2
ls
create_folder folder5
rename_user user7 <function generate_user at 0x027087F0>
show_folders
ls
which_group
register_admin user8 pass8
add_item item1 key2=val5 key9=val3 key7=val9 key8=val2 
show_items
sign_in user5 pass5
add_item item4 key3=val1 key2=val8 key5=val7 key3=val4 
buy
add_item_property item5 key2=val1 key2=val6 key9=val2 key1=val9 
help ls
sign_out
sign_out
whoami
ls
buy
show_item_properties item4
show_users
show_users
cd folder3
buy
sign_in a2 pa2
register_user user6 pass6
help pwd
add_item_property item1 key3=val3 key5=val7 key3=val10 key2=val2 
show_items
rename_user user0 <function generate_user at 0x027087F0>
whoami
put item4
ls
add_item_property item1 key8=val6 key5=val9 key5=val3 key4=val8 
sign_in user7 pass7
ls_folders
create_folder folder3
add_item_property item4 key4=val10 key1=val3 key7=val6 key9=val10 
register_admin user6 pass6
sign_in user5 pass5
sign_in user9 pass9
show_folders
sign_in user5 pass5
create_folder folder5
register_user user6 pass6
help sign_in
current_folder
ls
sign_in user8 pass8
ls
which_group
buy
show_folders
add_item item1 key8=val5 key7=val9 key3=val7 key7=val7 
help buy
sign_in a1 pa1
show_folders
current_folder
ls_folders
ls_folders
show_item_properties item4
rename_user user4 <function generate_user at 0x027087F0>
register_user user8 pass8
show_users
ls
add_item item5 key10=val8 key2=val1 key4=val9 key6=val4 
cd folder5
sign_in a1 pa1
sign_out
show_items
help history
add_item_property item1 key1=val6 key3=val8 key1=val8 key10=val6 
sign_out
add_item item2 key8=val8 key5=val4 key5=val1 key9=val5 
current_folder
current_folder
help create_folder
register_admin user9 pass9
whoami
pwd
register_admin user3 pass3
show_folders
current_folder
which_group
current_folder
put item4
sign_out
ls
show_items
create_folder folder5
sign_in user3 pass3
add_item item4 key4=val7 key8=val7 key4=val2 key3=val9 
current_folder
cd folder3
show_item_properties item3
sign_in user6 pass6
help buy
sign_in user9 pass9
create_folder folder3
sign_in a3 pa3
show_items
put item1
show_folders
current_folder
add_item item1 key10=val5 key8=val5 key7=val8 key10=val1 
register_admin user5 pass5
sign_out
current_folder
whoami
register_user user6 pass6
sign_out
ls_folders
buy
rename_user user5 <function generate_user at 0x027087F0>
rename_user user8 <function generate_user at 0x027087F0>
pwd
show_items
register_user user3 pass3
show_items
show_folders
ls
create_folder folder5
pwd
rename_user user5 <function generate_user at 0x027087F0>
show_folders
create_folder folder1
show_folders
show_items
pwd
sign_in user6 pass6
register_user user7 pass7
pwd
pwd
put item2
ls
ls_folders
help show_folders
which_group
add_item item5 key2=val4 key6=val8 key6=val1 key4=val1 
ls_folders
sign_in admin admin
rename_user user8 <function generate_user at 0x027087F0>
ls
show_item_properties item2
register_user user1 pass1
which_group
cd folder2
pwd
show_item_properties item3
whoami
sign_in user3 pass3
ls_folders
sign_in user3 pass3
add_item_property item2 key1=val8 key9=val1 key1=val7 key10=val3 
ls
ls
current_folder
buy
create_folder folder1
show_users
help ls
show_folders
sign_out
ls_folders
sign_out
sign_in user3 pass3
register_user admin admin
help ls_folders
help show_item_properties
ls_folders
buy
current_folder
show_item_properties item5
sign_in a5 pa5
current_folder
sign_out
ls
sign_in a3 pa3
whoami
sign_in admin admin
show_users
create_folder folder5
ls_folders
register_admin user9 pass9
pwd
ls_folders
whoami
cd folder2
add_item_property item2 key3=val3 key9=val4 key4=val4 key8=val5 
register_user user4 pass4
add_item item4 key3=val4 key7=val2 key8=val2 key3=val9 
whoami
sign_out
sign_in user7 pass7
sign_in user5 pass5
register_user user3 pass3
show_folders
register_user user1 pass1
show_items
register_admin user4 pass4
ls
whoami
ls
add_item item4 key5=val3 key2=val10 key7=val6 key6=val5 
buy
add_item item4 key10=val3 key4=val4 key5=val5 key3=val6 
buy
help sign_in
rename_user user0 <function generate_user at 0x027087F0>
current_folder
ls_folders
help pwd
put item2
create_folder folder1
show_users
current_folder
sign_out
ls_folders
help rename_user
sign_in a2 pa2
buy
add_item item1 key5=val9 key6=val3 key9=val7 key7=val8 
register_user user7 pass7
show_folders
cd folder1
register_user user3 pass3
buy
pwd
whoami
ls_folders
current_folder
pwd
create_folder folder2
buy
sign_in admin admin
register_user user4 pass4
which_group
ls_folders
show_users
sign_in user5 pass5
show_items
ls
which_group
ls
which_group
sign_out
show_folders
ls
register_admin user9 pass9
add_item_property item5 key5=val3 key3=val10 key1=val4 key1=val8 
register_user user5 pass5
which_group
current_folder
show_item_properties item5
ls
current_folder
put item4
register_user user4 pass4
rename_user user9 <function generate_user at 0x027087F0>
whoami
put item3
sign_in admin admin
pwd
ls_folders
show_users
register_admin user8 pass8
add_item_property item5 key3=val7 key8=val10 key2=val7 key7=val7 
create_folder folder4
put item4
show_folders
ls_folders
show_folders
show_users
add_item item2 key4=val5 key4=val5 key7=val3 key8=val6 
current_folder
whoami
ls
add_item_property item2 key1=val7 key1=val2 key4=val3 key6=val1 
pwd
pwd
add_item_property item4 key4=val8 key10=val4 key7=val5 key10=val7 
sign_out
ls
sign_in user7 pass7
add_item_property item5 key10=val2 key1=val10 key8=val7 key3=val7 
show_item_properties item5
cd folder2
add_item_property item4 key10=val7 key3=val10 key7=val1 key10=val2 
ls
add_item item2 key1=val10 key6=val5 key1=val4 key5=val8 
show_item_properties item1
add_item_property item4 key8=val1 key1=val1 key5=val5 key6=val2 
register_user user2 pass2
ls
cd folder4
show_items
rename_user user4 <function generate_user at 0x027087F0>
add_item item5 key3=val2 key4=val6 key6=val6 key9=val7 
put item4
show_folders
create_folder folder3
pwd
add_item item2 key8=val8 key9=val5 key1=val5 key10=val6 
ls
which_group
ls_folders
show_items
current_folder
help put
ls
which_group
add_item item4 key7=val7 key1=val8 key7=val2 key10=val9 
help cd
sign_in a2 pa2
buy
show_items
ls_folders
create_folder folder5
sign_in user3 pass3
pwd
put item3
show_item_properties item3
ls_folders
show_folders
ls_folders
ls
rename_user user9 <function generate_user at 0x027087F0>
add_item_property item2 key8=val6 key2=val1 key3=val4 key7=val10 
show_folders
current_folder
add_item_property item2 key1=val9 key1=val6 key3=val8 key10=val6 
buy
register_user user1 pass1
cd folder1
sign_out
show_item_properties item5
pwd
buy
put item5
current_folder
sign_in a4 pa4
ls_folders
cd folder1
register_user user1 pass1
help history
show_item_properties item2
current_folder
rename_user user7 <function generate_user at 0x027087F0>
buy
current_folder
ls_folders
current_folder
rename_user user1 <function generate_user at 0x027087F0>
sign_in a2 pa2
add_item item3 key10=val3 key10=val9 key5=val8 key2=val1 
register_admin user4 pass4
create_folder folder1
ls_folders
show_users
show_items
put item2
add_item item2 key1=val4 key3=val4 key6=val5 key10=val8 
whoami
register_user user7 pass7
put item4
show_users
help buy
buy
sign_in admin admin
create_folder folder5
which_group
add_item_property item3 key5=val2 key7=val3 key5=val2 key2=val3 
buy
add_item item5 key8=val1 key4=val3 key8=val8 key2=val2 
register_user user9 pass9
ls
sign_in a5 pa5
show_folders
add_item item1 key2=val9 key4=val10 key6=val5 key10=val2 
show_item_properties item5
cd folder3
show_items
cd folder3
show_items
current_folder
show_items
which_group
current_folder
ls_folders
show_item_properties item2
whoami
put item2
whoami
buy
current_folder
help sign_out
cd folder4
whoami
show_item_properties item3
rename_user user6 <function generate_user at 0x027087F0>
create_folder folder4
pwd
which_group
sign_in a2 pa2
cd folder4
pwd
register_admin user5 pass5
ls_folders
current_folder
show_users
sign_in a1 pa1
sign_in a1 pa1
which_group
show_folders
show_items
current_folder
sign_out
add_item item2 key8=val10 key6=val9 key9=val3 key6=val8 
ls_folders
current_folder
rename_user user2 <function generate_user at 0x027087F0>
register_user user8 pass8
sign_in a5 pa5
show_items
add_item item5 key9=val4 key2=val9 key6=val9 key3=val6 
show_item_properties item5
put item5
rename_user user5 <function generate_user at 0x027087F0>
show_item_properties item3
pwd
current_folder
register_admin user9 pass9
cd folder4
whoami
whoami
pwd
register_user user8 pass8
help show_item_properties
sign_in user9 pass9
register_admin admin admin
show_folders
sign_in user5 pass5
show_item_properties item2
current_folder
create_folder folder2
sign_out
ls_folders
sign_in a2 pa2
add_item_property item2 key10=val6 key1=val7 key8=val9 key10=val8 
add_item_property item3 key7=val8 key4=val4 key2=val8 key7=val7 
pwd
add_item_property item1 key3=val10 key8=val2 key5=val3 key2=val10 
show_folders
which_group
put item5
whoami
put item5
which_group
buy
buy
show_folders
sign_in a5 pa5
register_user user3 pass3
show_users
pwd
sign_out
whoami
buy
register_admin user4 pass4
add_item_property item4 key5=val7 key8=val5 key9=val6 key9=val4 
add_item_property item4 key2=val8 key10=val4 key1=val6 key5=val5 
put item3
buy
ls_folders
current_folder
register_user admin admin
add_item item4 key8=val1 key5=val2 key1=val4 key7=val10 
sign_in user1 pass1
rename_user user7 <function generate_user at 0x027087F0>
ls
ls_folders
show_folders
cd folder3
buy
add_item item3 key4=val1 key3=val4 key4=val8 key7=val2 
cd folder5
show_folders
show_folders
which_group
register_admin user2 pass2
sign_in a2 pa2
show_users
sign_out
cd folder5
whoami
create_folder folder3
sign_in user8 pass8
create_folder folder4
create_folder folder5
create_folder folder1
show_users
add_item_property item3 key10=val8 key2=val4 key5=val3 key8=val5 
show_item_properties item2
show_folders
help add_item_property
add_item item5 key2=val9 key1=val4 key3=val9 key7=val7 
create_folder folder2
current_folder
add_item_property item2 key10=val8 key6=val1 key2=val2 key1=val10 
sign_in a5 pa5
put item5
add_item_property item3 key7=val3 key7=val4 key6=val10 key7=val8 
add_item_property item3 key1=val2 key4=val2 key1=val3 key2=val5 
register_user user3 pass3
whoami
help sign_out
rename_user user2 <function generate_user at 0x027087F0>
show_folders
create_folder folder5
sign_out
whoami
show_items
sign_in admin admin
register_user user6 pass6
show_users
whoami
show_item_properties item2
add_item_property item3 key1=val1 key10=val9 key3=val8 key6=val8 
register_admin user6 pass6
pwd
ls_folders
add_item item4 key6=val9 key4=val7 key2=val2 key6=val9 
register_user admin admin
rename_user user1 <function generate_user at 0x027087F0>
cd folder5
cd folder4
pwd
create_folder folder5
buy
rename_user user1 <function generate_user at 0x027087F0>
put item3
rename_user user6 <function generate_user at 0x027087F0>
create_folder folder3
register_admin user7 pass7
sign_out
add_item item5 key6=val9 key3=val4 key1=val3 key9=val6 
cd folder5
buy
put item1
rename_user user0 <function generate_user at 0x027087F0>
whoami
buy
show_items
show_users
sign_in user4 pass4
show_item_properties item3
pwd
show_folders
create_folder folder1
which_group
sign_in user7 pass7
register_user admin admin
whoami
help history
add_item_property item2 key6=val5 key4=val8 key2=val2 key6=val7 
add_item item5 key1=val7 key8=val10 key10=val7 key9=val10 
show_folders
ls
rename_user user0 <function generate_user at 0x027087F0>
show_users
register_user user5 pass5
current_folder
add_item_property item3 key10=val5 key4=val8 key8=val3 key9=val1 
buy
pwd
current_folder
cd folder2
cd folder2
create_folder folder4
show_items
ls_folders
register_user user2 pass2
show_users
register_admin user7 pass7
ls
register_user admin admin
which_group
ls_folders
sign_in a3 pa3
sign_in a4 pa4
add_item item4 key6=val10 key5=val9 key4=val7 key2=val1 
add_item_property item1 key9=val8 key8=val4 key8=val5 key8=val6 
register_user user3 pass3
buy
show_items
rename_user user9 <function generate_user at 0x027087F0>
add_item_property item1 key8=val1 key1=val2 key6=val7 key4=val4 
pwd
add_item item2 key6=val10 key7=val9 key6=val8 key4=val4 
help sign_out
add_item_property item2 key7=val7 key5=val8 key8=val5 key5=val1 
current_folder
sign_in admin admin
ls_folders
put item5
show_folders
add_item item4 key6=val7 key9=val3 key7=val5 key2=val9 
help buy
pwd
whoami
register_user user5 pass5
ls
current_folder
sign_out
sign_in user9 pass9
register_user user4 pass4
help show_item_properties
buy
create_folder folder5
help add_item
ls
register_user user4 pass4
show_item_properties item3
sign_in user9 pass9
which_group
put item3
add_item item4 key1=val5 key6=val10 key10=val3 key6=val9 
put item2
pwd
show_folders
create_folder folder5
add_item_property item4 key2=val8 key8=val8 key6=val10 key4=val1 
ls
ls_folders
show_users
pwd
show_item_properties item2
create_folder folder5
show_folders
create_folder folder4
create_folder folder5
which_group
rename_user user4 <function generate_user at 0x027087F0>
register_admin admin admin
sign_in a1 pa1
whoami
which_group
register_admin user4 pass4
show_items
ls_folders
buy
rename_user user1 <function generate_user at 0x027087F0>
current_folder
ls_folders
which_group
buy
show_users
put item5
show_folders
show_item_properties item4
add_item_property item5 key1=val2 key8=val5 key2=val1 key2=val4 
sign_in admin admin
put item5
show_users
ls
create_folder folder5
cd folder3
pwd
whoami
ls_folders
cd folder1
whoami
sign_in admin admin
add_item item3 key5=val9 key4=val1 key4=val2 key6=val2 
which_group
cd folder4
current_folder
register_admin user7 pass7
sign_out
ls_folders
sign_in a1 pa1
current_folder
sign_out
ls_folders
register_admin user3 pass3
which_group
show_folders
ls
show_item_properties item5
show_users
show_folders
sign_in user3 pass3
ls_folders
sign_in user9 pass9
show_items
sign_out
whoami
register_user admin admin
register_user user2 pass2
ls_folders
cd folder2
ls_folders
ls_folders
register_admin user3 pass3
pwd
ls
ls_folders
current_folder
ls_folders
show_folders
add_item item1 key7=val9 key8=val4 key3=val8 key5=val3 
show_item_properties item1
pwd
sign_out
cd folder1
ls_folders
sign_out
add_item_property item2 key5=val5 key10=val1 key10=val4 key9=val4 
rename_user user0 <function generate_user at 0x027087F0>
cd folder2
ls_folders
sign_in user2 pass2
pwd
buy
register_user user4 pass4
show_folders
cd folder4
sign_in a3 pa3
pwd
put item4
register_admin user1 pass1
put item2
sign_in a4 pa4
sign_in a2 pa2
add_item item5 key2=val6 key7=val9 key3=val3 key7=val2 
buy
buy
ls_folders
register_admin user2 pass2
show_items
help add_item
ls_folders
register_admin user3 pass3
whoami
show_users
sign_in user6 pass6
help sign_in
sign_in user3 pass3
sign_out
rename_user user2 <function generate_user at 0x027087F0>
whoami
help add_item
current_folder
whoami
sign_in user2 pass2
show_folders
show_items
register_user user7 pass7
which_group
add_item item1 key4=val3 key9=val9 key3=val9 key6=val2 
show_folders
add_item item2 key4=val7 key2=val8 key9=val6 key3=val10 
add_item item4 key2=val9 key8=val7 key1=val4 key2=val8 
help put
sign_in a5 pa5
put item2
pwd
show_folders
add_item_property item2 key4=val1 key5=val5 key8=val3 key10=val5 
add_item item1 key7=val3 key8=val3 key7=val3 key8=val7 
sign_in user4 pass4
ls_folders
show_items
whoami
register_admin user4 pass4
register_user user9 pass9
sign_out
help sign_in
show_item_properties item4
sign_in user3 pass3
show_users
ls_folders
rename_user user6 <function generate_user at 0x027087F0>
ls
show_items
whoami
current_folder
show_items
show_item_properties item5
which_group
help sign_out
create_folder folder5
create_folder folder4
create_folder folder2
current_folder
sign_out
which_group
create_folder folder5
rename_user user6 <function generate_user at 0x027087F0>
show_users
buy
help ls
show_items
show_users
rename_user user8 <function generate_user at 0x027087F0>
buy
rename_user user7 <function generate_user at 0x027087F0>
sign_out
sign_in user2 pass2
whoami
ls
register_user user4 pass4
ls_folders
show_folders
help show_folders
add_item item4 key7=val3 key2=val8 key8=val2 key9=val9 
show_items
sign_in a5 pa5
help ls
show_items
add_item item1 key2=val9 key2=val1 key9=val10 key7=val6 
sign_in a5 pa5
show_item_properties item5
show_users
rename_user user3 <function generate_user at 0x027087F0>
buy
sign_out
ls
ls
show_items
pwd
sign_in a5 pa5
show_users
register_admin user5 pass5
sign_in a2 pa2
create_folder folder1
show_folders
help add_item
which_group
pwd
rename_user user0 <function generate_user at 0x027087F0>
buy
register_admin user3 pass3
create_folder folder3
put item3
sign_out
register_user user7 pass7
buy
current_folder
create_folder folder4
help pwd
ls
cd folder2
ls_folders
sign_out
rename_user user8 <function generate_user at 0x027087F0>
sign_in a4 pa4
buy
show_items
register_user user4 pass4
ls
help show_items
ls
show_items
which_group
which_group
register_user user7 pass7
which_group
sign_in a4 pa4
buy
create_folder folder2
rename_user user1 <function generate_user at 0x027087F0>
help add_item_property
ls_folders
whoami
register_user user3 pass3
sign_out
show_folders
sign_in a1 pa1
put item5
sign_out
add_item_property item1 key3=val4 key5=val6 key10=val6 key8=val9 
show_item_properties item4
ls_folders
ls_folders
cd folder4
show_item_properties item4
sign_in a1 pa1
sign_in a1 pa1
put item4
pwd
which_group
sign_in user8 pass8
whoami
register_admin user7 pass7
show_folders
show_item_properties item2
sign_in user3 pass3
show_folders
register_user user6 pass6
add_item item4 key6=val4 key9=val3 key7=val3 key5=val6 
whoami
show_items
sign_out
pwd
create_folder folder4
register_user user2 pass2
sign_in user7 pass7
add_item item4 key8=val6 key8=val3 key3=val8 key4=val6 
show_users
show_users
show_folders
show_folders
whoami
show_items
current_folder
buy
show_folders
sign_out
pwd
show_items
whoami
whoami
rename_user user2 <function generate_user at 0x027087F0>
current_folder
put item1
show_folders
pwd
create_folder folder2
sign_out
register_admin user8 pass8
ls_folders
buy
sign_in a1 pa1
show_items
sign_out
show_users
help sign_in
show_folders
which_group
rename_user user1 <function generate_user at 0x027087F0>
put item4
show_folders
show_users
which_group
show_item_properties item2
which_group
which_group
show_items
register_user user9 pass9
register_user user8 pass8
create_folder folder1
sign_in a4 pa4
current_folder
put item2
ls_folders
sign_out
rename_user user4 <function generate_user at 0x027087F0>
register_admin user9 pass9
show_item_properties item2
sign_in user6 pass6
show_items
sign_out
sign_out
sign_out
register_user user5 pass5
show_users
whoami
cd folder5
show_item_properties item4
add_item item2 key10=val3 key1=val9 key6=val7 key1=val10 
ls_folders
show_item_properties item2
which_group
sign_out
sign_in a4 pa4
ls
show_items
pwd
add_item item3 key5=val4 key2=val4 key3=val8 key6=val10 
show_folders
register_user user3 pass3
ls_folders
register_admin user8 pass8
register_admin user6 pass6
put item1
register_admin user1 pass1
whoami
ls
help add_item
create_folder folder1
current_folder
current_folder
sign_in a5 pa5
which_group
add_item item2 key5=val3 key2=val9 key9=val10 key1=val1 
ls
whoami
create_folder folder5
sign_in a5 pa5
show_item_properties item5
rename_user user0 <function generate_user at 0x027087F0>
add_item item2 key4=val6 key8=val8 key10=val6 key6=val1 
add_item_property item5 key3=val2 key8=val8 key10=val7 key10=val1 
buy
add_item item1 key9=val7 key8=val4 key10=val9 key4=val2 
register_admin admin admin
create_folder folder2
register_admin user1 pass1
sign_in a5 pa5
rename_user user2 <function generate_user at 0x027087F0>
add_item_property item2 key9=val9 key7=val1 key1=val8 key1=val8 
pwd
ls_folders
create_folder folder3
register_admin user2 pass2
show_item_properties item4
show_items
sign_in user6 pass6
show_folders
add_item_property item2 key5=val10 key7=val6 key1=val7 key2=val9 
help show_users
sign_in user7 pass7
cd folder4
cd folder4
put item1
show_items
rename_user user4 <function generate_user at 0x027087F0>
sign_in a3 pa3
sign_out
which_group
create_folder folder4
help history
help pwd
show_folders
add_item_property item3 key5=val7 key8=val4 key6=val6 key5=val10 
add_item_property item1 key9=val3 key3=val4 key1=val10 key10=val8 
show_users
create_folder folder3
show_items
rename_user user0 <function generate_user at 0x027087F0>
show_users
buy
which_group
register_user user7 pass7
create_folder folder3
cd folder2
sign_in user9 pass9
buy
rename_user user0 <function generate_user at 0x027087F0>
put item2
buy
show_items
show_items
add_item_property item3 key1=val8 key4=val10 key2=val7 key8=val8 
add_item_property item4 key8=val7 key2=val5 key6=val6 key4=val9 
register_user user1 pass1
current_folder
pwd
rename_user user8 <function generate_user at 0x027087F0>
add_item_property item1 key8=val6 key6=val3 key7=val1 key10=val4 
register_admin user6 pass6
current_folder
show_users
add_item_property item1 key4=val1 key6=val1 key7=val1 key5=val9 
current_folder
show_items
rename_user user4 <function generate_user at 0x027087F0>
show_folders
current_folder
register_user user2 pass2
show_items
show_users
put item4
show_users
help which_group
ls_folders
sign_in user8 pass8
add_item item4 key7=val7 key6=val1 key8=val8 key10=val7 
which_group
show_folders
whoami
help add_item_property
ls
add_item_property item3 key4=val9 key6=val7 key10=val5 key10=val10 
show_users
register_user user2 pass2
add_item item4 key5=val8 key1=val8 key5=val7 key8=val8 
which_group
rename_user user4 <function generate_user at 0x027087F0>
ls_folders
show_item_properties item3
create_folder folder2
pwd
show_item_properties item1
cd folder2
sign_out
sign_in user4 pass4
which_group
add_item item4 key10=val8 key1=val8 key4=val4 key7=val3 
rename_user user9 <function generate_user at 0x027087F0>
sign_in a4 pa4
ls
show_users
pwd
sign_in user5 pass5
register_admin user1 pass1
rename_user user3 <function generate_user at 0x027087F0>
ls_folders
which_group
sign_out
sign_in admin admin
ls_folders
ls
register_admin user2 pass2
which_group
add_item_property item5 key1=val10 key2=val1 key10=val3 key7=val4 
show_users
which_group
register_user admin admin
ls_folders
show_items
show_users
show_items
register_admin admin admin
buy
add_item_property item4 key7=val3 key10=val10 key3=val2 key9=val2 
add_item item1 key3=val9 key1=val9 key7=val6 key2=val3 
put item2
current_folder
create_folder folder4
sign_in user6 pass6
show_item_properties item3
whoami
help show_users
add_item item2 key9=val10 key8=val4 key8=val8 key3=val9 
sign_in user8 pass8
buy
current_folder
sign_in admin admin
which_group
cd folder4
show_folders
show_folders
create_folder folder4
create_folder folder3
help sign_out
help pwd
show_users
current_folder
add_item item5 key1=val4 key10=val8 key5=val9 key3=val9 
put item1
ls_folders
cd folder5
cd folder5
which_group
add_item item2 key4=val10 key8=val3 key4=val7 key2=val6 
show_items
sign_out
sign_in a2 pa2
cd folder1
sign_out
pwd
sign_out
buy
register_admin user9 pass9
add_item_property item1 key8=val7 key7=val3 key2=val1 key5=val6 
ls
show_items
current_folder
which_group
add_item_property item1 key10=val6 key7=val8 key9=val2 key7=val3 
register_user user2 pass2
ls
ls_folders
sign_out
show_users
buy
show_folders
sign_in a1 pa1
sign_in user2 pass2
sign_in user3 pass3
cd folder2
add_item item1 key2=val3 key7=val4 key9=val10 key2=val7 
buy
ls_folders
register_user user7 pass7
cd folder5
create_folder folder1
show_folders
show_item_properties item1
current_folder
register_user user6 pass6
sign_in a2 pa2
which_group
register_admin admin admin
whoami
put item4
show_folders
cd folder1
put item5
put item5
which_group
register_admin user3 pass3
put item5
which_group
sign_in a2 pa2
show_users
ls
show_item_properties item5
add_item item1 key4=val5 key4=val3 key3=val4 key10=val8 
sign_out
ls
sign_out
put item3
register_admin admin admin
whoami
cd folder2
show_items
ls
add_item_property item2 key8=val3 key6=val2 key8=val1 key3=val3 
add_item_property item4 key3=val9 key10=val1 key2=val6 key7=val9 
show_users
show_users
show_item_properties item2
buy
which_group
put item2
register_admin user7 pass7
cd folder3
help put
ls
pwd
cd folder1
help show_users
whoami
which_group
register_user user7 pass7
sign_out
rename_user user8 <function generate_user at 0x027087F0>
create_folder folder4
ls
ls
show_users
buy
buy
ls
whoami
show_item_properties item2
sign_out
show_users
cd folder5
which_group
create_folder folder1
sign_in user8 pass8
show_items
sign_in user9 pass9
current_folder
add_item item4 key6=val10 key1=val5 key2=val1 key3=val10 
help register_admin
current_folder
sign_in user7 pass7
help pwd
pwd
current_folder
register_user user8 pass8
ls
which_group
put item1
ls
ls
whoami
rename_user user6 <function generate_user at 0x027087F0>
sign_in a4 pa4
rename_user user8 <function generate_user at 0x027087F0>
show_item_properties item4
rename_user user1 <function generate_user at 0x027087F0>
whoami
which_group
add_item item3 key10=val10 key10=val8 key10=val5 key3=val1 
register_user user9 pass9
show_users
ls
sign_in user6 pass6
pwd
ls
cd folder3
sign_out
show_users
cd folder4
show_items
buy
help exit
pwd
ls_folders
register_user user1 pass1
sign_out
register_user user2 pass2
which_group
create_folder folder4
whoami
show_items
ls
show_item_properties item1
register_user user3 pass3
buy
add_item item5 key5=val10 key3=val4 key10=val5 key2=val5 
rename_user user7 <function generate_user at 0x027087F0>
sign_out
register_user user2 pass2
pwd
whoami
show_users
which_group
put item2
help add_item
pwd
register_user user7 pass7
show_users
which_group
register_admin user9 pass9
add_item_property item1 key1=val5 key4=val7 key2=val6 key1=val6 
ls_folders
create_folder folder3
sign_in user2 pass2
cd folder2
whoami
put item5
ls_folders
put item4
show_users
help create_folder
register_admin user8 pass8
show_users
create_folder folder5
create_folder folder4
which_group
whoami
buy
show_folders
sign_in admin admin
current_folder
create_folder folder1
add_item_property item3 key8=val2 key7=val8 key4=val7 key10=val3 
which_group
cd folder5
sign_out
ls
pwd
add_item_property item5 key9=val9 key1=val2 key9=val1 key10=val10 
add_item_property item2 key2=val1 key4=val2 key10=val3 key9=val8 
ls_folders
current_folder
show_item_properties item4
help add_item
show_item_properties item1
help show_item_properties
ls
show_users
show_item_properties item4
sign_in user1 pass1
create_folder folder3
show_users
create_folder folder4
register_admin user1 pass1
sign_out
put item1
create_folder folder4
sign_out
show_users
sign_in user5 pass5
buy
create_folder folder2
whoami
pwd
create_folder folder1
cd folder2
current_folder
sign_in user7 pass7
add_item item4 key7=val2 key8=val10 key4=val4 key7=val8 
show_folders
pwd
sign_in user1 pass1
pwd
show_users
show_users
ls
show_users
sign_out
ls_folders
rename_user user9 <function generate_user at 0x027087F0>
add_item item1 key10=val9 key3=val5 key6=val1 key3=val10 
register_admin user8 pass8
put item3
current_folder
whoami
which_group
ls
register_user admin admin
create_folder folder1
which_group
add_item_property item1 key7=val9 key4=val8 key10=val9 key1=val8 
sign_out
cd folder5
sign_in a1 pa1
pwd
show_users
which_group
ls_folders
show_items
sign_out
register_user user1 pass1
show_item_properties item2
sign_in user2 pass2
show_folders
show_item_properties item1
buy
ls
rename_user user7 <function generate_user at 0x027087F0>
pwd
create_folder folder5
show_item_properties item1
sign_in a3 pa3
ls
add_item item5 key4=val9 key10=val9 key4=val4 key4=val4 
show_item_properties item1
show_users
ls_folders
