create_folder folder3
sign_in a4 pa4
create_folder folder2
help register_admin
create_folder folder2
show_folders
pwd
create_folder folder1
show_folders
help history
sign_out
rename_user user1 <function generate_user at 0x027087F0>
whoami
sign_in a1 pa1
current_folder
sign_in user3 pass3
sign_out
help register_admin
show_items
register_admin user8 pass8
show_items
show_folders
sign_in user1 pass1
sign_out
which_group
cd folder5
register_user user1 pass1
ls
add_item_property item4 key2=val9 key1=val4 key3=val2 key5=val4 
show_items
register_user admin admin
whoami
ls_folders
ls_folders
register_user user4 pass4
ls
pwd
whoami
create_folder folder2
help register_admin
which_group
which_group
sign_in a1 pa1
buy
register_user user3 pass3
show_users
cd folder3
put item5
sign_out
register_user user1 pass1
register_admin user4 pass4
ls_folders
sign_in user8 pass8
register_admin user3 pass3
help show_folders
register_admin user4 pass4
ls
which_group
cd folder5
show_items
register_admin user7 pass7
show_folders
buy
show_users
rename_user user2 <function generate_user at 0x027087F0>
show_item_properties item2
ls_folders
register_user user7 pass7
rename_user user2 <function generate_user at 0x027087F0>
rename_user user5 <function generate_user at 0x027087F0>
show_items
cd folder2
pwd
sign_in user4 pass4
show_item_properties item5
sign_in admin admin
put item5
show_users
ls_folders
whoami
help sign_in
cd folder4
show_folders
add_item_property item3 key1=val3 key6=val5 key7=val8 key10=val5 
help exit
sign_in user4 pass4
show_folders
create_folder folder5
ls
show_items
ls
add_item_property item4 key2=val9 key3=val8 key2=val2 key9=val9 
which_group
create_folder folder2
show_item_properties item5
show_items
help show_item_properties
ls_folders
put item5
register_user user1 pass1
ls_folders
sign_out
rename_user user5 <function generate_user at 0x027087F0>
pwd
add_item_property item5 key3=val4 key3=val4 key6=val3 key6=val10 
cd folder1
help put
register_user user9 pass9
add_item_property item3 key5=val9 key5=val4 key6=val4 key3=val8 
whoami
sign_in a3 pa3
show_items
show_users
whoami
whoami
current_folder
add_item item1 key5=val10 key10=val6 key6=val8 key4=val6 
show_users
register_user user5 pass5
add_item_property item5 key4=val2 key1=val9 key9=val10 key4=val4 
create_folder folder4
current_folder
buy
ls_folders
buy
show_folders
show_folders
add_item item5 key1=val10 key6=val1 key1=val6 key4=val3 
ls_folders
show_items
sign_in user5 pass5
help show_item_properties
ls
cd folder5
put item1
whoami
register_admin user6 pass6
create_folder folder2
current_folder
which_group
show_users
ls
pwd
show_users
which_group
sign_out
rename_user user3 <function generate_user at 0x027087F0>
help ls_folders
register_user user8 pass8
add_item_property item1 key8=val8 key5=val1 key2=val2 key7=val8 
pwd
show_item_properties item3
sign_in user9 pass9
which_group
sign_in user2 pass2
sign_in user5 pass5
create_folder folder5
buy
ls
create_folder folder2
put item2
sign_in a3 pa3
register_user user6 pass6
current_folder
register_user admin admin
whoami
rename_user user5 <function generate_user at 0x027087F0>
show_items
register_user user3 pass3
add_item_property item2 key8=val9 key8=val5 key6=val5 key9=val1 
rename_user user8 <function generate_user at 0x027087F0>
sign_in a2 pa2
show_item_properties item3
buy
rename_user user0 <function generate_user at 0x027087F0>
ls_folders
add_item_property item3 key1=val9 key3=val1 key5=val5 key10=val4 
put item4
sign_in user3 pass3
ls
sign_in a4 pa4
show_item_properties item5
cd folder1
put item2
sign_in user2 pass2
sign_in admin admin
create_folder folder2
whoami
put item1
sign_out
create_folder folder2
put item5
create_folder folder2
which_group
buy
current_folder
register_user user8 pass8
sign_in a1 pa1
show_folders
add_item_property item4 key8=val2 key6=val8 key6=val8 key9=val9 
create_folder folder3
show_folders
whoami
ls
create_folder folder3
ls
help rename_user
register_admin user5 pass5
register_admin user3 pass3
pwd
which_group
add_item item4 key3=val6 key10=val7 key5=val4 key5=val3 
ls
register_admin user2 pass2
sign_in user2 pass2
whoami
help pwd
buy
register_user user9 pass9
buy
show_items
add_item_property item3 key2=val10 key6=val7 key8=val7 key7=val9 
register_user user8 pass8
register_admin user1 pass1
sign_in a2 pa2
show_item_properties item3
register_user user2 pass2
which_group
show_items
put item3
put item2
show_item_properties item5
ls
whoami
help rename_user
sign_out
create_folder folder2
add_item item1 key6=val4 key7=val6 key5=val5 key2=val7 
show_item_properties item1
register_admin user8 pass8
put item2
cd folder5
create_folder folder5
pwd
show_item_properties item1
add_item item4 key4=val6 key9=val5 key7=val3 key9=val7 
rename_user user3 <function generate_user at 0x027087F0>
sign_in user5 pass5
show_users
show_folders
show_users
register_user user5 pass5
add_item item1 key7=val1 key5=val2 key4=val4 key2=val2 
add_item item4 key6=val3 key8=val7 key1=val1 key1=val3 
which_group
add_item_property item3 key5=val10 key7=val7 key8=val9 key3=val1 
create_folder folder4
cd folder2
put item4
help register_user
show_item_properties item2
rename_user user4 <function generate_user at 0x027087F0>
buy
ls
register_user user8 pass8
whoami
cd folder5
add_item item5 key2=val5 key5=val5 key9=val4 key3=val4 
register_admin user7 pass7
add_item_property item5 key5=val4 key7=val1 key2=val1 key4=val7 
pwd
sign_in a1 pa1
pwd
pwd
buy
show_folders
sign_in a4 pa4
put item3
ls_folders
rename_user user9 <function generate_user at 0x027087F0>
ls_folders
add_item_property item5 key6=val5 key5=val8 key5=val1 key6=val8 
ls
add_item_property item3 key2=val5 key3=val10 key3=val9 key8=val9 
show_folders
pwd
buy
put item4
show_folders
ls_folders
show_users
cd folder3
show_users
show_users
put item4
show_item_properties item2
cd folder4
show_item_properties item2
current_folder
put item3
whoami
show_folders
cd folder3
ls
ls
pwd
show_folders
register_user user7 pass7
add_item_property item4 key4=val7 key8=val2 key9=val8 key3=val7 
add_item item3 key10=val3 key3=val8 key8=val1 key3=val3 
ls
whoami
create_folder folder1
current_folder
add_item_property item3 key1=val9 key9=val8 key4=val6 key3=val1 
which_group
show_item_properties item4
add_item_property item2 key8=val5 key2=val9 key6=val2 key10=val6 
rename_user user8 <function generate_user at 0x027087F0>
add_item item3 key10=val6 key8=val8 key5=val1 key2=val10 
pwd
cd folder5
register_admin user2 pass2
register_user user2 pass2
ls_folders
buy
register_user user1 pass1
ls_folders
current_folder
add_item_property item4 key7=val3 key4=val10 key6=val7 key7=val3 
show_folders
current_folder
whoami
register_admin user5 pass5
show_items
add_item_property item3 key6=val4 key3=val5 key9=val2 key9=val4 
whoami
add_item item3 key3=val3 key3=val10 key3=val2 key7=val1 
put item2
rename_user user8 <function generate_user at 0x027087F0>
sign_out
whoami
ls
show_item_properties item4
register_user user8 pass8
show_items
add_item_property item5 key5=val5 key3=val10 key3=val10 key8=val9 
whoami
create_folder folder4
rename_user user9 <function generate_user at 0x027087F0>
cd folder2
sign_in a4 pa4
show_items
show_users
buy
help history
sign_in user7 pass7
current_folder
sign_out
cd folder4
add_item item3 key4=val3 key10=val7 key2=val6 key6=val7 
add_item_property item3 key2=val3 key2=val4 key7=val1 key6=val7 
rename_user user2 <function generate_user at 0x027087F0>
show_folders
register_admin admin admin
whoami
rename_user user6 <function generate_user at 0x027087F0>
register_user user5 pass5
show_folders
help delete_user
create_folder folder2
show_users
help put
ls_folders
add_item_property item4 key1=val6 key4=val8 key4=val8 key9=val10 
rename_user user7 <function generate_user at 0x027087F0>
buy
which_group
create_folder folder1
help cd
show_item_properties item1
show_users
help pwd
ls
rename_user user0 <function generate_user at 0x027087F0>
show_folders
current_folder
whoami
ls
ls_folders
cd folder1
sign_in a3 pa3
pwd
cd folder5
help show_users
pwd
cd folder5
show_folders
which_group
help history
show_folders
sign_out
register_admin admin admin
pwd
show_items
register_admin user8 pass8
add_item_property item1 key2=val10 key2=val6 key1=val8 key7=val6 
which_group
ls_folders
create_folder folder2
add_item item2 key10=val3 key4=val2 key2=val7 key6=val10 
ls
which_group
ls
put item3
register_user admin admin
register_admin user1 pass1
pwd
show_folders
add_item item1 key4=val5 key1=val8 key6=val1 key10=val4 
put item3
show_folders
show_item_properties item4
which_group
show_users
which_group
show_users
sign_out
ls
register_admin user7 pass7
create_folder folder4
create_folder folder5
buy
whoami
sign_out
create_folder folder3
current_folder
register_admin user3 pass3
buy
whoami
whoami
show_users
rename_user user9 <function generate_user at 0x027087F0>
cd folder3
current_folder
rename_user user4 <function generate_user at 0x027087F0>
add_item item5 key9=val1 key2=val2 key1=val2 key6=val1 
show_items
sign_out
help ls_folders
sign_in a5 pa5
sign_out
register_admin user1 pass1
create_folder folder3
pwd
show_users
pwd
sign_in a3 pa3
register_user user8 pass8
rename_user user2 <function generate_user at 0x027087F0>
add_item_property item5 key7=val6 key8=val5 key10=val8 key4=val1 
add_item item4 key9=val2 key8=val6 key4=val6 key4=val3 
register_user user9 pass9
rename_user user8 <function generate_user at 0x027087F0>
help buy
put item1
register_user user9 pass9
current_folder
show_folders
show_item_properties item2
cd folder2
pwd
show_folders
show_users
add_item_property item5 key5=val3 key7=val5 key5=val1 key5=val1 
show_users
sign_out
show_items
show_folders
help current_folder
show_users
cd folder3
create_folder folder3
which_group
show_folders
sign_in a5 pa5
add_item_property item2 key3=val1 key8=val7 key7=val6 key8=val6 
help current_folder
show_folders
rename_user user3 <function generate_user at 0x027087F0>
ls_folders
ls_folders
pwd
create_folder folder2
sign_in a1 pa1
sign_in a2 pa2
sign_out
whoami
sign_in a3 pa3
show_items
pwd
add_item_property item5 key7=val10 key7=val7 key1=val1 key9=val10 
create_folder folder2
cd folder2
current_folder
register_user user5 pass5
help history
which_group
buy
current_folder
whoami
register_user user5 pass5
help help
show_folders
sign_in user7 pass7
create_folder folder3
add_item item2 key3=val7 key7=val8 key2=val8 key4=val4 
ls_folders
whoami
which_group
create_folder folder3
show_users
whoami
add_item_property item3 key10=val4 key7=val9 key1=val9 key6=val3 
show_folders
sign_out
register_admin user1 pass1
current_folder
ls
current_folder
put item4
put item4
sign_in a2 pa2
which_group
rename_user user8 <function generate_user at 0x027087F0>
sign_in a5 pa5
pwd
show_users
add_item_property item3 key3=val2 key6=val7 key10=val10 key6=val1 
register_user user6 pass6
show_folders
ls_folders
which_group
sign_in user7 pass7
buy
ls
create_folder folder2
pwd
put item5
buy
put item3
rename_user user0 <function generate_user at 0x027087F0>
cd folder3
rename_user user8 <function generate_user at 0x027087F0>
ls
show_users
register_user user2 pass2
current_folder
put item2
add_item_property item1 key6=val5 key9=val5 key3=val7 key6=val1 
pwd
sign_in user6 pass6
show_item_properties item3
show_users
buy
buy
register_user user8 pass8
create_folder folder3
show_items
cd folder3
show_users
cd folder2
sign_in a4 pa4
show_folders
register_user user8 pass8
register_user user5 pass5
cd folder4
show_users
add_item item4 key8=val8 key6=val2 key1=val4 key4=val2 
cd folder1
rename_user user0 <function generate_user at 0x027087F0>
help current_folder
show_items
pwd
sign_out
show_item_properties item5
show_folders
show_folders
add_item item1 key2=val4 key8=val3 key5=val1 key6=val2 
register_admin user1 pass1
sign_in a3 pa3
rename_user user6 <function generate_user at 0x027087F0>
ls
create_folder folder3
help add_item
add_item item4 key7=val8 key9=val8 key10=val6 key4=val5 
rename_user user8 <function generate_user at 0x027087F0>
sign_out
rename_user user2 <function generate_user at 0x027087F0>
show_item_properties item2
add_item_property item3 key6=val4 key5=val1 key8=val2 key9=val5 
show_folders
sign_in a4 pa4
help create_folder
sign_in a3 pa3
ls_folders
show_folders
rename_user user2 <function generate_user at 0x027087F0>
sign_in a2 pa2
create_folder folder4
sign_out
add_item item3 key8=val2 key8=val6 key9=val5 key5=val9 
cd folder2
sign_in user5 pass5
sign_out
show_items
pwd
ls_folders
create_folder folder1
show_folders
show_users
current_folder
help view_order
add_item_property item1 key4=val9 key7=val9 key4=val6 key7=val1 
register_user user9 pass9
put item3
add_item item4 key5=val8 key8=val7 key7=val6 key5=val6 
ls
register_admin user7 pass7
current_folder
current_folder
ls_folders
ls_folders
pwd
sign_in user4 pass4
current_folder
sign_in a5 pa5
whoami
show_items
rename_user user7 <function generate_user at 0x027087F0>
create_folder folder5
show_items
buy
create_folder folder1
create_folder folder2
whoami
add_item item3 key8=val5 key10=val3 key4=val4 key7=val10 
sign_in user6 pass6
which_group
current_folder
ls_folders
register_user user6 pass6
add_item item3 key6=val4 key8=val1 key7=val4 key1=val10 
show_users
create_folder folder4
sign_out
add_item_property item5 key5=val3 key2=val2 key4=val1 key7=val2 
show_users
add_item item1 key8=val9 key9=val3 key1=val1 key4=val9 
help help
show_folders
put item5
add_item_property item2 key3=val7 key10=val10 key7=val4 key10=val2 
current_folder
ls
current_folder
help show_folders
create_folder folder5
sign_in a3 pa3
add_item_property item5 key7=val9 key2=val4 key10=val8 key5=val7 
sign_out
show_item_properties item4
whoami
show_item_properties item5
rename_user user3 <function generate_user at 0x027087F0>
whoami
show_items
sign_in a5 pa5
add_item_property item3 key10=val9 key8=val6 key2=val7 key4=val10 
register_admin user9 pass9
ls
help whoami
buy
current_folder
help pwd
sign_out
show_item_properties item2
ls_folders
buy
show_users
help rename_user
put item4
register_admin user8 pass8
which_group
add_item item2 key6=val5 key7=val3 key2=val2 key6=val8 
add_item item1 key7=val8 key10=val1 key4=val1 key4=val3 
sign_out
whoami
put item3
ls_folders
register_admin admin admin
buy
put item3
sign_in user4 pass4
ls_folders
ls
put item2
add_item item3 key6=val6 key9=val6 key10=val10 key4=val9 
rename_user user0 <function generate_user at 0x027087F0>
sign_in a1 pa1
sign_in user5 pass5
add_item item5 key10=val5 key2=val6 key4=val10 key1=val7 
show_item_properties item5
show_users
ls_folders
show_folders
add_item item2 key10=val4 key3=val5 key9=val5 key1=val2 
sign_out
pwd
show_folders
create_folder folder5
register_user user5 pass5
help exit
rename_user user3 <function generate_user at 0x027087F0>
show_folders
show_item_properties item3
pwd
create_folder folder3
ls_folders
register_user admin admin
sign_in user7 pass7
sign_out
sign_out
current_folder
sign_in user3 pass3
buy
ls
sign_out
create_folder folder3
add_item item3 key2=val3 key9=val1 key3=val5 key7=val10 
buy
show_item_properties item3
which_group
create_folder folder4
show_folders
which_group
which_group
which_group
cd folder4
sign_in user7 pass7
put item4
register_admin user9 pass9
pwd
show_users
add_item_property item3 key10=val6 key4=val1 key10=val9 key6=val5 
pwd
show_item_properties item2
ls
register_user user8 pass8
register_admin admin admin
sign_in a1 pa1
ls_folders
show_folders
add_item item3 key7=val5 key4=val4 key6=val4 key9=val6 
show_items
sign_out
show_users
buy
show_items
sign_in user5 pass5
sign_in user9 pass9
add_item_property item3 key9=val10 key8=val8 key7=val8 key3=val6 
show_users
show_folders
whoami
add_item_property item5 key7=val2 key10=val7 key2=val4 key8=val6 
which_group
show_items
show_folders
show_item_properties item5
rename_user user3 <function generate_user at 0x027087F0>
cd folder2
show_folders
which_group
create_folder folder5
show_items
create_folder folder5
show_users
show_folders
register_user user6 pass6
create_folder folder3
buy
put item5
sign_in a5 pa5
create_folder folder5
register_admin user8 pass8
rename_user user1 <function generate_user at 0x027087F0>
show_items
sign_in user3 pass3
show_items
register_user admin admin
sign_out
ls
which_group
sign_in a4 pa4
put item5
rename_user user1 <function generate_user at 0x027087F0>
whoami
buy
pwd
pwd
create_folder folder3
put item2
help register_user
register_user user5 pass5
show_item_properties item1
show_folders
show_item_properties item2
sign_in user9 pass9
sign_out
ls
create_folder folder3
put item5
rename_user user6 <function generate_user at 0x027087F0>
current_folder
pwd
whoami
pwd
which_group
add_item item3 key4=val5 key5=val9 key7=val5 key9=val9 
which_group
show_item_properties item5
show_item_properties item5
show_item_properties item5
add_item_property item3 key9=val4 key7=val2 key3=val5 key8=val1 
show_folders
ls_folders
cd folder1
which_group
add_item item3 key9=val8 key10=val7 key2=val5 key7=val4 
add_item_property item2 key7=val10 key9=val7 key2=val2 key4=val8 
show_item_properties item2
ls_folders
register_user user7 pass7
whoami
put item5
add_item_property item5 key5=val5 key2=val9 key10=val5 key1=val4 
ls_folders
show_items
pwd
sign_in user5 pass5
show_folders
create_folder folder3
whoami
show_items
which_group
show_folders
rename_user user3 <function generate_user at 0x027087F0>
show_items
register_user user6 pass6
sign_in a1 pa1
whoami
current_folder
create_folder folder5
sign_in user7 pass7
current_folder
whoami
ls
sign_in a3 pa3
create_folder folder5
add_item item3 key5=val5 key7=val2 key1=val2 key8=val4 
add_item_property item2 key8=val6 key10=val7 key1=val9 key1=val1 
sign_out
ls_folders
add_item_property item3 key5=val2 key2=val3 key8=val10 key4=val6 
ls_folders
add_item_property item4 key1=val7 key1=val7 key7=val7 key1=val4 
register_user user4 pass4
sign_in a1 pa1
register_user user7 pass7
register_user user3 pass3
sign_in a5 pa5
add_item_property item1 key7=val8 key2=val3 key7=val1 key9=val7 
show_items
sign_in user3 pass3
show_items
ls_folders
sign_out
buy
sign_out
register_admin user5 pass5
whoami
create_folder folder3
show_folders
show_folders
sign_out
put item2
help current_folder
create_folder folder3
buy
cd folder1
sign_in user5 pass5
register_user admin admin
buy
sign_in user8 pass8
show_folders
put item4
sign_in a3 pa3
rename_user user9 <function generate_user at 0x027087F0>
show_items
pwd
whoami
show_folders
put item3
pwd
sign_in user4 pass4
create_folder folder4
ls
register_admin user1 pass1
current_folder
show_item_properties item1
pwd
put item3
cd folder2
sign_in user5 pass5
add_item item5 key2=val2 key10=val4 key6=val10 key4=val5 
pwd
whoami
cd folder3
show_items
ls_folders
show_items
register_admin user5 pass5
register_admin user1 pass1
register_admin admin admin
sign_in a5 pa5
rename_user user0 <function generate_user at 0x027087F0>
sign_in a5 pa5
rename_user user6 <function generate_user at 0x027087F0>
create_folder folder1
rename_user user6 <function generate_user at 0x027087F0>
ls_folders
show_item_properties item1
sign_in a3 pa3
sign_in a1 pa1
add_item_property item1 key10=val2 key5=val8 key4=val5 key8=val3 
sign_out
pwd
show_folders
register_user user2 pass2
show_users
ls_folders
show_items
ls_folders
show_items
help delete_user
whoami
add_item item4 key10=val4 key4=val4 key6=val4 key1=val7 
add_item item4 key6=val9 key1=val4 key7=val5 key5=val8 
pwd
register_user admin admin
pwd
whoami
sign_out
add_item_property item3 key4=val5 key7=val6 key3=val8 key9=val8 
rename_user user5 <function generate_user at 0x027087F0>
show_items
create_folder folder2
show_items
show_folders
help rename_user
whoami
ls_folders
register_admin user5 pass5
put item2
register_user user4 pass4
show_folders
sign_out
register_admin user8 pass8
help show_items
register_admin user9 pass9
show_users
add_item_property item4 key3=val3 key8=val7 key3=val9 key4=val5 
pwd
show_items
register_admin user1 pass1
sign_in user1 pass1
pwd
ls_folders
help sign_in
buy
sign_out
sign_in a4 pa4
register_user user1 pass1
whoami
rename_user user3 <function generate_user at 0x027087F0>
create_folder folder3
ls
current_folder
which_group
rename_user user9 <function generate_user at 0x027087F0>
sign_in a5 pa5
sign_in a3 pa3
show_folders
which_group
add_item item3 key7=val10 key6=val2 key5=val9 key6=val8 
cd folder3
which_group
create_folder folder5
show_item_properties item1
help put
sign_in user3 pass3
show_item_properties item1
register_user user1 pass1
show_items
pwd
sign_in user9 pass9
buy
current_folder
show_items
cd folder4
put item5
add_item_property item3 key10=val9 key4=val6 key8=val7 key8=val8 
sign_in a3 pa3
which_group
show_folders
add_item_property item4 key9=val3 key3=val1 key4=val7 key4=val6 
ls
sign_out
register_admin user7 pass7
add_item item5 key1=val4 key1=val3 key3=val7 key3=val2 
which_group
add_item item5 key8=val8 key5=val5 key1=val4 key9=val8 
pwd
register_admin user2 pass2
ls
add_item item1 key10=val10 key9=val4 key3=val4 key1=val3 
pwd
whoami
add_item_property item4 key10=val2 key3=val2 key3=val7 key9=val1 
register_user user4 pass4
ls_folders
sign_in user5 pass5
ls_folders
show_item_properties item4
show_folders
register_admin user8 pass8
show_users
ls
whoami
show_folders
ls_folders
register_user user9 pass9
whoami
add_item_property item4 key3=val1 key7=val6 key1=val8 key4=val9 
ls_folders
buy
which_group
sign_in a5 pa5
show_users
show_folders
ls
put item1
add_item item1 key6=val8 key10=val6 key7=val4 key8=val9 
register_user user5 pass5
ls_folders
current_folder
put item3
show_users
pwd
sign_in user1 pass1
add_item item2 key5=val6 key3=val3 key10=val1 key10=val6 
show_users
help put
sign_in a3 pa3
add_item item2 key8=val2 key7=val8 key6=val1 key8=val8 
buy
buy
sign_in user1 pass1
register_user user8 pass8
register_user user1 pass1
show_items
sign_out
add_item_property item3 key4=val4 key1=val7 key10=val1 key8=val10 
register_user user5 pass5
create_folder folder1
rename_user user1 <function generate_user at 0x027087F0>
buy
pwd
sign_in user9 pass9
register_admin user8 pass8
show_items
ls
show_item_properties item3
add_item item2 key10=val1 key10=val5 key1=val7 key7=val3 
show_folders
show_folders
register_user user6 pass6
pwd
cd folder1
cd folder4
whoami
sign_in a2 pa2
show_users
ls
ls_folders
show_items
whoami
add_item item4 key7=val2 key2=val9 key6=val1 key9=val6 
put item5
show_item_properties item2
sign_out
cd folder1
whoami
show_item_properties item5
put item5
ls_folders
which_group
rename_user user3 <function generate_user at 0x027087F0>
rename_user user1 <function generate_user at 0x027087F0>
rename_user user7 <function generate_user at 0x027087F0>
current_folder
sign_in user2 pass2
current_folder
cd folder5
cd folder1
pwd
buy
register_user user9 pass9
create_folder folder2
add_item item4 key6=val10 key7=val3 key7=val2 key7=val3 
put item4
ls
show_item_properties item1
add_item item2 key5=val10 key4=val1 key10=val9 key6=val7 
which_group
whoami
show_items
add_item_property item2 key4=val10 key3=val6 key2=val5 key1=val3 
sign_out
ls
show_folders
buy
cd folder1
help show_item_properties
register_user admin admin
sign_out
create_folder folder4
put item4
register_user user2 pass2
sign_in admin admin
put item4
put item4
help show_users
ls
cd folder2
add_item_property item5 key7=val10 key9=val9 key8=val4 key8=val4 
help delete_user
ls
show_items
ls_folders
whoami
register_user admin admin
current_folder
create_folder folder3
cd folder4
show_folders
register_user admin admin
rename_user user2 <function generate_user at 0x027087F0>
show_folders
ls
sign_out
whoami
ls
register_admin user4 pass4
which_group
show_folders
whoami
help add_item_property
current_folder
create_folder folder3
register_user user9 pass9
show_folders
add_item item1 key3=val10 key4=val4 key7=val5 key9=val3 
ls_folders
create_folder folder3
current_folder
add_item item5 key10=val7 key7=val9 key1=val1 key8=val10 
show_items
whoami
rename_user user0 <function generate_user at 0x027087F0>
show_items
sign_in user1 pass1
sign_in user6 pass6
current_folder
current_folder
show_items
pwd
sign_out
help exit
ls
show_item_properties item3
register_admin user2 pass2
whoami
show_items
buy
create_folder folder1
sign_in user8 pass8
ls
buy
current_folder
cd folder1
register_user user5 pass5
register_user user2 pass2
add_item item5 key1=val1 key8=val9 key1=val6 key3=val5 
register_admin user4 pass4
whoami
sign_in admin admin
sign_out
show_items
pwd
which_group
buy
current_folder
which_group
sign_in a5 pa5
show_items
sign_in user4 pass4
register_user user9 pass9
add_item_property item1 key10=val8 key10=val8 key4=val8 key3=val5 
cd folder1
show_item_properties item3
register_admin user8 pass8
show_folders
register_admin user7 pass7
sign_out
rename_user user3 <function generate_user at 0x027087F0>
cd folder5
ls_folders
ls_folders
buy
register_user user7 pass7
ls
show_folders
register_admin user7 pass7
pwd
show_items
show_users
show_users
rename_user user2 <function generate_user at 0x027087F0>
help ls_folders
sign_out
add_item item3 key5=val5 key3=val7 key8=val2 key4=val1 
put item4
ls_folders
help ls
pwd
register_user user8 pass8
show_folders
register_admin user3 pass3
help ls_folders
cd folder3
add_item_property item2 key6=val2 key1=val9 key6=val3 key9=val1 
show_users
register_admin user1 pass1
rename_user user8 <function generate_user at 0x027087F0>
cd folder3
show_folders
show_item_properties item4
ls_folders
add_item_property item2 key6=val7 key3=val10 key2=val2 key2=val4 
put item1
show_users
cd folder2
show_users
pwd
show_users
help register_user
show_items
show_items
add_item item2 key7=val10 key5=val2 key2=val9 key4=val6 
create_folder folder3
register_admin user3 pass3
add_item_property item2 key1=val5 key10=val5 key2=val3 key6=val9 
rename_user user5 <function generate_user at 0x027087F0>
sign_out
ls
cd folder1
register_admin admin admin
show_users
create_folder folder1
current_folder
cd folder5
cd folder5
which_group
rename_user user2 <function generate_user at 0x027087F0>
sign_out
show_item_properties item2
sign_in a1 pa1
show_item_properties item5
show_folders
put item3
show_item_properties item3
add_item_property item3 key10=val2 key7=val1 key2=val9 key6=val3 
pwd
register_user user4 pass4
register_user user8 pass8
put item4
show_items
show_item_properties item3
show_items
rename_user user6 <function generate_user at 0x027087F0>
ls
put item2
rename_user user7 <function generate_user at 0x027087F0>
create_folder folder3
whoami
show_items
add_item item5 key3=val6 key9=val6 key4=val8 key9=val9 
sign_in a1 pa1
ls
cd folder5
show_item_properties item1
buy
cd folder3
add_item item4 key7=val2 key8=val4 key10=val1 key8=val3 
add_item_property item3 key4=val8 key6=val9 key2=val7 key2=val9 
sign_in user2 pass2
add_item_property item5 key2=val9 key5=val4 key4=val2 key2=val8 
add_item item2 key6=val5 key1=val2 key6=val8 key9=val8 
which_group
add_item item1 key1=val3 key2=val9 key8=val10 key8=val10 
current_folder
show_folders
show_folders
current_folder
register_admin user9 pass9
create_folder folder5
put item3
put item2
pwd
show_item_properties item2
show_users
register_admin user8 pass8
create_folder folder3
create_folder folder1
cd folder5
sign_in user7 pass7
whoami
show_items
show_users
ls_folders
sign_in user6 pass6
register_admin user6 pass6
create_folder folder5
put item4
which_group
which_group
which_group
whoami
sign_in admin admin
register_user user8 pass8
whoami
sign_in user3 pass3
register_admin user3 pass3
register_admin user3 pass3
ls
sign_in a5 pa5
register_admin user9 pass9
sign_in a5 pa5
whoami
create_folder folder2
show_folders
add_item_property item4 key5=val10 key2=val2 key7=val9 key2=val2 
show_folders
cd folder2
register_user user4 pass4
sign_in user9 pass9
add_item item2 key4=val10 key4=val3 key6=val9 key2=val6 
sign_out
sign_in a5 pa5
show_items
pwd
rename_user user2 <function generate_user at 0x027087F0>
current_folder
add_item item1 key8=val2 key4=val4 key3=val2 key7=val7 
sign_in a2 pa2
add_item_property item2 key8=val3 key6=val2 key3=val2 key4=val1 
add_item item5 key9=val5 key6=val6 key9=val3 key2=val6 
show_folders
add_item_property item1 key3=val6 key10=val5 key9=val2 key5=val4 
which_group
buy
whoami
show_users
put item2
pwd
rename_user user6 <function generate_user at 0x027087F0>
register_admin user9 pass9
register_admin user8 pass8
show_item_properties item3
ls_folders
cd folder5
show_users
register_admin user1 pass1
buy
register_admin user7 pass7
whoami
sign_in user2 pass2
show_folders
put item1
add_item item1 key7=val5 key2=val6 key1=val9 key3=val1 
buy
add_item item2 key3=val8 key2=val5 key7=val9 key3=val3 
which_group
cd folder2
whoami
whoami
buy
ls_folders
add_item item3 key1=val3 key7=val3 key9=val10 key6=val2 
register_admin user5 pass5
put item1
add_item item4 key9=val1 key3=val4 key7=val3 key2=val10 
show_users
show_users
add_item_property item4 key1=val9 key2=val6 key1=val5 key8=val10 
show_users
show_items
sign_in a2 pa2
add_item item3 key2=val6 key10=val9 key1=val10 key5=val9 
create_folder folder1
register_admin user1 pass1
whoami
ls_folders
current_folder
put item2
ls_folders
current_folder
register_admin user6 pass6
help show_item_properties
sign_in user2 pass2
whoami
help register_admin
show_items
sign_in user5 pass5
which_group
ls_folders
ls
register_user user6 pass6
pwd
which_group
create_folder folder4
pwd
add_item_property item2 key8=val3 key6=val2 key3=val7 key2=val5 
whoami
sign_in a3 pa3
show_folders
cd folder3
buy
buy
show_item_properties item1
add_item_property item5 key10=val3 key4=val5 key8=val9 key3=val2 
put item5
add_item item2 key3=val9 key4=val10 key10=val4 key3=val6 
show_items
register_admin user7 pass7
sign_in user4 pass4
buy
show_item_properties item1
register_admin user3 pass3
which_group
pwd
sign_in a3 pa3
buy
cd folder2
add_item item5 key8=val7 key10=val6 key7=val6 key9=val9 
rename_user user5 <function generate_user at 0x027087F0>
put item3
create_folder folder2
show_folders
show_items
rename_user user6 <function generate_user at 0x027087F0>
cd folder5
pwd
add_item item3 key10=val9 key6=val9 key4=val3 key3=val5 
current_folder
add_item_property item3 key4=val7 key9=val7 key10=val4 key10=val3 
show_folders
add_item item4 key4=val5 key9=val3 key9=val4 key3=val2 
ls_folders
sign_in a1 pa1
sign_out
sign_in user8 pass8
add_item item4 key7=val1 key1=val2 key8=val8 key5=val3 
show_items
add_item_property item2 key7=val7 key8=val7 key3=val3 key5=val10 
which_group
pwd
rename_user user5 <function generate_user at 0x027087F0>
help ls
show_folders
create_folder folder2
current_folder
create_folder folder2
create_folder folder2
put item2
show_users
whoami
show_users
put item2
put item2
show_items
show_folders
buy
register_admin user3 pass3
sign_in a4 pa4
pwd
current_folder
current_folder
put item3
register_user user5 pass5
add_item_property item4 key8=val6 key6=val5 key5=val6 key4=val2 
whoami
rename_user user2 <function generate_user at 0x027087F0>
rename_user user1 <function generate_user at 0x027087F0>
which_group
show_item_properties item4
show_folders
add_item item4 key1=val5 key9=val5 key4=val1 key9=val9 
cd folder2
ls_folders
show_item_properties item3
show_folders
show_items
sign_in user6 pass6
buy
ls
add_item_property item1 key6=val9 key1=val2 key2=val6 key3=val3 
pwd
add_item_property item3 key2=val5 key3=val6 key4=val10 key6=val4 
ls_folders
show_users
sign_out
sign_out
sign_out
whoami
create_folder folder2
ls
rename_user user2 <function generate_user at 0x027087F0>
create_folder folder2
whoami
register_user user7 pass7
current_folder
sign_out
show_item_properties item5
sign_out
sign_out
register_user user8 pass8
help which_group
cd folder3
put item4
rename_user user6 <function generate_user at 0x027087F0>
sign_out
rename_user user1 <function generate_user at 0x027087F0>
put item3
add_item item3 key7=val10 key7=val8 key6=val5 key5=val4 
show_folders
put item1
register_user user8 pass8
cd folder3
buy
ls
show_items
whoami
sign_in user3 pass3
show_users
rename_user user0 <function generate_user at 0x027087F0>
sign_out
add_item item5 key3=val8 key9=val10 key7=val1 key8=val1 
show_items
register_user user6 pass6
help show_items
rename_user user6 <function generate_user at 0x027087F0>
show_items
sign_out
which_group
show_item_properties item5
show_folders
show_users
current_folder
show_users
add_item_property item1 key8=val1 key2=val4 key3=val8 key4=val7 
buy
add_item item3 key4=val2 key9=val2 key9=val4 key4=val7 
help history
buy
cd folder5
add_item_property item3 key1=val8 key2=val1 key9=val5 key1=val4 
sign_out
register_user user8 pass8
show_folders
add_item item1 key5=val6 key7=val1 key6=val1 key9=val9 
pwd
ls
rename_user user4 <function generate_user at 0x027087F0>
register_user user3 pass3
buy
sign_out
sign_in user4 pass4
register_user user2 pass2
buy
cd folder2
add_item item4 key5=val9 key7=val5 key10=val3 key10=val6 
put item5
show_items
show_items
put item3
register_user user6 pass6
register_user user2 pass2
ls
current_folder
add_item_property item1 key4=val6 key3=val3 key10=val10 key10=val6 
ls_folders
sign_out
help help
which_group
show_items
show_items
cd folder4
add_item_property item5 key9=val10 key10=val8 key9=val6 key8=val6 
current_folder
current_folder
pwd
ls
register_user admin admin
show_users
which_group
show_users
show_users
add_item item4 key4=val6 key10=val3 key8=val2 key3=val3 
put item3
show_items
rename_user user7 <function generate_user at 0x027087F0>
put item1
show_item_properties item3
cd folder4
add_item item2 key7=val7 key5=val10 key8=val1 key3=val4 
put item1
ls
pwd
sign_in a2 pa2
pwd
register_admin user9 pass9
register_admin admin admin
rename_user user7 <function generate_user at 0x027087F0>
rename_user user2 <function generate_user at 0x027087F0>
show_items
sign_out
show_users
show_items
register_user user6 pass6
add_item_property item3 key9=val7 key2=val1 key2=val8 key6=val2 
cd folder3
cd folder2
cd folder3
show_item_properties item2
add_item_property item2 key7=val3 key9=val5 key5=val10 key1=val10 
show_folders
help put
buy
show_folders
show_folders
which_group
buy
show_items
help show_item_properties
show_item_properties item2
sign_in a2 pa2
create_folder folder2
whoami
sign_in a3 pa3
add_item_property item3 key7=val4 key4=val4 key10=val5 key4=val5 
sign_in a2 pa2
show_users
pwd
register_admin user2 pass2
ls_folders
register_admin user8 pass8
add_item_property item3 key2=val4 key2=val4 key6=val9 key7=val3 
which_group
register_admin user7 pass7
sign_in user8 pass8
whoami
sign_in a5 pa5
help register_admin
sign_in user5 pass5
show_folders
which_group
help ls_folders
add_item_property item3 key3=val7 key2=val5 key4=val6 key3=val1 
register_user user1 pass1
add_item item5 key5=val5 key2=val8 key9=val9 key3=val8 
show_item_properties item2
register_admin user9 pass9
show_users
cd folder5
register_admin user6 pass6
add_item item4 key5=val5 key6=val3 key2=val5 key3=val8 
create_folder folder2
whoami
help history
pwd
show_folders
rename_user user5 <function generate_user at 0x027087F0>
show_item_properties item1
add_item_property item1 key6=val1 key7=val4 key6=val6 key10=val9 
ls_folders
show_item_properties item1
current_folder
show_items
create_folder folder1
ls_folders
ls_folders
sign_in user3 pass3
sign_out
pwd
help put
add_item_property item3 key8=val10 key5=val2 key10=val2 key2=val2 
show_items
register_user user5 pass5
whoami
sign_in a3 pa3
help rename_user
whoami
add_item_property item1 key7=val3 key10=val5 key2=val5 key1=val4 
current_folder
help put
show_users
show_users
cd folder4
sign_out
buy
rename_user user6 <function generate_user at 0x027087F0>
help register_admin
ls_folders
create_folder folder4
register_user user3 pass3
sign_out
show_item_properties item1
ls
which_group
show_folders
pwd
rename_user user9 <function generate_user at 0x027087F0>
sign_in a4 pa4
sign_in a5 pa5
sign_out
register_admin user9 pass9
pwd
show_item_properties item5
help add_item
show_item_properties item1
rename_user user2 <function generate_user at 0x027087F0>
buy
show_item_properties item2
add_item item2 key2=val9 key4=val3 key5=val7 key10=val6 
add_item item5 key10=val6 key3=val9 key10=val2 key8=val9 
put item5
show_item_properties item4
create_folder folder4
show_folders
show_folders
show_item_properties item4
rename_user user8 <function generate_user at 0x027087F0>
create_folder folder1
ls_folders
create_folder folder2
help delete_user
register_admin user6 pass6
which_group
rename_user user2 <function generate_user at 0x027087F0>
show_item_properties item2
help show_users
add_item item2 key1=val9 key5=val2 key8=val9 key10=val5 
cd folder2
sign_in a5 pa5
sign_in admin admin
current_folder
buy
show_item_properties item5
cd folder3
add_item_property item1 key2=val8 key9=val1 key8=val1 key6=val9 
help register_user
whoami
show_items
show_users
ls_folders
put item4
put item3
pwd
add_item item4 key10=val7 key7=val7 key8=val2 key2=val5 
sign_in user2 pass2
help show_folders
register_user user7 pass7
show_items
register_user user8 pass8
sign_in a3 pa3
put item1
cd folder1
add_item item1 key2=val10 key6=val6 key10=val10 key1=val10 
add_item_property item1 key1=val4 key6=val7 key7=val8 key9=val1 
buy
register_user user4 pass4
show_folders
current_folder
pwd
whoami
current_folder
put item4
ls
pwd
show_users
show_item_properties item5
show_users
help whoami
rename_user user1 <function generate_user at 0x027087F0>
cd folder3
show_folders
put item2
show_users
help register_admin
help current_folder
sign_in user6 pass6
whoami
show_item_properties item3
create_folder folder4
put item3
cd folder2
show_folders
which_group
cd folder4
show_item_properties item1
show_folders
help register_user
whoami
current_folder
sign_in a1 pa1
show_folders
show_items
current_folder
rename_user user5 <function generate_user at 0x027087F0>
whoami
sign_in a1 pa1
whoami
add_item item5 key5=val10 key7=val6 key9=val6 key2=val6 
pwd
create_folder folder3
pwd
sign_in a2 pa2
cd folder1
show_items
create_folder folder4
buy
show_users
show_item_properties item5
which_group
show_item_properties item5
sign_in user1 pass1
ls_folders
cd folder1
show_items
sign_out
sign_out
show_users
add_item item3 key5=val6 key10=val3 key7=val6 key2=val8 
ls_folders
register_user user4 pass4
show_folders
whoami
register_user user4 pass4
ls_folders
help register_user
show_item_properties item1
cd folder5
rename_user user7 <function generate_user at 0x027087F0>
register_admin user4 pass4
show_item_properties item2
show_items
sign_in user1 pass1
ls_folders
show_item_properties item5
show_item_properties item1
register_admin user8 pass8
cd folder4
register_admin user8 pass8
show_items
help show_folders
show_items
register_user user3 pass3
add_item_property item4 key9=val1 key6=val4 key3=val9 key5=val2 
show_item_properties item2
which_group
create_folder folder1
show_users
which_group
sign_in a4 pa4
add_item item3 key6=val9 key8=val8 key9=val4 key6=val9 
cd folder4
which_group
add_item item5 key7=val5 key4=val10 key5=val10 key9=val10 
help pwd
show_items
sign_in user1 pass1
ls
which_group
register_admin user6 pass6
sign_in a5 pa5
rename_user user4 <function generate_user at 0x027087F0>
ls_folders
show_items
sign_out
rename_user user8 <function generate_user at 0x027087F0>
register_admin user7 pass7
sign_out
buy
whoami
show_item_properties item5
ls
ls
register_admin user2 pass2
sign_out
add_item_property item3 key3=val4 key3=val7 key7=val2 key10=val5 
current_folder
pwd
show_folders
which_group
ls
add_item_property item1 key6=val4 key3=val1 key8=val5 key6=val10 
rename_user user0 <function generate_user at 0x027087F0>
show_item_properties item5
register_admin admin admin
pwd
show_items
add_item_property item4 key4=val7 key4=val9 key3=val9 key7=val9 
add_item item3 key2=val5 key7=val1 key10=val4 key1=val8 
ls
show_users
register_user user4 pass4
show_folders
put item1
sign_out
current_folder
add_item item2 key1=val7 key3=val4 key6=val5 key2=val5 
register_admin user2 pass2
ls
whoami
sign_in admin admin
sign_in a2 pa2
whoami
ls
buy
show_users
ls_folders
create_folder folder3
pwd
sign_in user7 pass7
whoami
which_group
rename_user user3 <function generate_user at 0x027087F0>
ls
add_item item3 key7=val1 key4=val10 key9=val6 key1=val6 
add_item item1 key1=val6 key4=val2 key6=val4 key2=val7 
current_folder
rename_user user5 <function generate_user at 0x027087F0>
ls
show_folders
cd folder3
put item4
show_users
register_admin user2 pass2
buy
register_user user7 pass7
put item1
create_folder folder5
cd folder5
show_items
cd folder5
show_users
cd folder2
rename_user user4 <function generate_user at 0x027087F0>
ls
register_user user9 pass9
ls
create_folder folder4
show_users
put item4
current_folder
buy
register_admin admin admin
show_items
register_user user8 pass8
show_items
sign_in user1 pass1
rename_user user2 <function generate_user at 0x027087F0>
which_group
register_user user1 pass1
show_users
pwd
create_folder folder4
show_items
add_item_property item3 key1=val1 key2=val9 key10=val7 key2=val10 
show_folders
rename_user user1 <function generate_user at 0x027087F0>
create_folder folder1
help help
sign_in a4 pa4
create_folder folder2
show_users
show_folders
create_folder folder4
pwd
cd folder5
help rename_user
sign_out
add_item item2 key6=val1 key9=val4 key7=val5 key9=val6 
register_user user8 pass8
show_item_properties item3
show_items
show_items
show_item_properties item3
ls
sign_in a1 pa1
current_folder
which_group
sign_out
cd folder1
cd folder4
sign_in a2 pa2
help ls_folders
register_user user4 pass4
show_item_properties item4
ls_folders
cd folder5
which_group
ls_folders
current_folder
help delete_user
add_item_property item2 key8=val1 key8=val10 key4=val5 key1=val9 
current_folder
show_item_properties item5
add_item item4 key9=val3 key3=val5 key10=val4 key9=val7 
show_items
register_admin user9 pass9
show_users
register_user user2 pass2
help register_user
sign_in user7 pass7
register_user user6 pass6
ls
buy
help ls
show_item_properties item5
create_folder folder2
ls
rename_user user3 <function generate_user at 0x027087F0>
ls
create_folder folder1
add_item_property item1 key8=val9 key4=val1 key3=val1 key2=val10 
current_folder
buy
sign_in a1 pa1
sign_in user1 pass1
which_group
register_admin user6 pass6
buy
rename_user user3 <function generate_user at 0x027087F0>
show_item_properties item1
show_users
sign_in a3 pa3
which_group
rename_user user6 <function generate_user at 0x027087F0>
show_item_properties item4
show_item_properties item3
pwd
cd folder2
show_items
register_admin user9 pass9
rename_user user9 <function generate_user at 0x027087F0>
ls_folders
add_item_property item5 key5=val8 key10=val1 key1=val2 key3=val7 
sign_in admin admin
show_item_properties item1
buy
register_admin user9 pass9
buy
which_group
show_item_properties item2
register_admin user6 pass6
sign_in user3 pass3
show_items
whoami
whoami
show_item_properties item4
register_user user4 pass4
put item4
help sign_out
cd folder5
register_admin user2 pass2
current_folder
cd folder3
buy
buy
which_group
which_group
add_item_property item4 key1=val1 key6=val3 key1=val7 key9=val6 
which_group
register_admin user8 pass8
rename_user user6 <function generate_user at 0x027087F0>
ls
show_items
whoami
show_items
help cd
buy
pwd
put item2
put item4
buy
which_group
add_item item5 key7=val10 key1=val5 key10=val3 key5=val10 
register_admin user4 pass4
ls
show_folders
create_folder folder1
rename_user user7 <function generate_user at 0x027087F0>
register_admin user4 pass4
rename_user user7 <function generate_user at 0x027087F0>
pwd
rename_user user9 <function generate_user at 0x027087F0>
sign_out
pwd
register_user user6 pass6
ls_folders
help which_group
add_item item2 key5=val10 key6=val9 key7=val7 key8=val7 
show_item_properties item4
show_users
show_folders
which_group
buy
show_item_properties item3
sign_in a5 pa5
cd folder4
whoami
create_folder folder1
show_folders
register_user user7 pass7
pwd
register_admin user4 pass4
show_folders
rename_user user2 <function generate_user at 0x027087F0>
help ls
sign_in user2 pass2
show_item_properties item4
add_item item1 key1=val7 key10=val7 key9=val2 key1=val4 
help history
sign_in a3 pa3
create_folder folder4
pwd
cd folder3
whoami
current_folder
register_admin user5 pass5
show_item_properties item3
show_folders
register_admin user7 pass7
whoami
sign_in user5 pass5
add_item_property item4 key1=val2 key9=val2 key4=val1 key5=val10 
ls_folders
register_admin user7 pass7
sign_out
show_folders
register_admin user2 pass2
show_items
which_group
ls_folders
show_items
help sign_in
show_items
sign_in a1 pa1
cd folder3
whoami
help current_folder
buy
rename_user user9 <function generate_user at 0x027087F0>
whoami
add_item item3 key1=val6 key5=val4 key3=val3 key2=val8 
pwd
show_item_properties item2
ls_folders
buy
pwd
help add_item
rename_user user3 <function generate_user at 0x027087F0>
add_item item2 key8=val10 key7=val7 key7=val10 key5=val4 
show_item_properties item3
ls
pwd
show_users
show_items
sign_in a3 pa3
buy
ls_folders
current_folder
pwd
current_folder
show_items
sign_out
show_folders
register_admin user2 pass2
create_folder folder2
register_user user4 pass4
ls_folders
sign_in a5 pa5
help ls_folders
buy
show_folders
ls_folders
register_admin user7 pass7
sign_in user7 pass7
current_folder
sign_in user8 pass8
pwd
show_item_properties item4
create_folder folder5
sign_out
pwd
ls_folders
cd folder1
sign_in a4 pa4
show_folders
add_item item4 key4=val2 key5=val7 key9=val9 key8=val6 
show_items
register_admin user9 pass9
whoami
buy
buy
ls_folders
cd folder4
sign_in user6 pass6
current_folder
cd folder2
buy
add_item item4 key9=val2 key9=val6 key8=val6 key9=val8 
help pwd
whoami
show_folders
cd folder1
cd folder1
help register_user
create_folder folder4
register_user admin admin
put item5
create_folder folder3
show_items
register_admin user8 pass8
whoami
show_users
cd folder1
which_group
add_item_property item3 key2=val9 key1=val8 key3=val5 key1=val4 
add_item item5 key8=val9 key1=val10 key5=val5 key4=val9 
pwd
current_folder
current_folder
add_item item1 key5=val3 key10=val9 key6=val10 key7=val10 
show_folders
show_item_properties item3
sign_in user2 pass2
which_group
whoami
which_group
help whoami
sign_in a2 pa2
add_item_property item3 key6=val7 key7=val9 key6=val4 key7=val10 
sign_in a1 pa1
ls_folders
create_folder folder5
ls
register_user admin admin
buy
register_admin admin admin
register_admin user4 pass4
current_folder
ls_folders
register_user user8 pass8
ls
buy
put item1
whoami
sign_in a1 pa1
whoami
put item2
sign_out
register_admin user5 pass5
pwd
show_items
sign_in user3 pass3
pwd
ls_folders
current_folder
put item3
show_folders
buy
buy
current_folder
put item4
put item5
show_folders
show_folders
show_folders
ls_folders
cd folder1
buy
pwd
current_folder
put item1
show_item_properties item1
ls_folders
which_group
show_item_properties item4
register_user user8 pass8
current_folder
create_folder folder1
cd folder3
sign_in user7 pass7
which_group
put item4
show_folders
sign_out
add_item_property item2 key8=val2 key7=val1 key3=val8 key7=val7 
current_folder
show_folders
register_user user5 pass5
pwd
show_users
buy
add_item item1 key4=val6 key7=val8 key9=val10 key6=val3 
sign_in user6 pass6
show_users
sign_out
create_folder folder3
show_users
show_users
create_folder folder5
register_user user6 pass6
register_admin admin admin
cd folder1
show_item_properties item1
whoami
show_folders
sign_out
buy
register_user user7 pass7
current_folder
ls
whoami
show_items
create_folder folder2
sign_in user5 pass5
show_item_properties item2
add_item_property item1 key2=val2 key7=val7 key7=val5 key9=val1 
create_folder folder1
sign_in admin admin
add_item_property item4 key3=val3 key4=val4 key2=val8 key10=val1 
whoami
put item2
pwd
register_admin user2 pass2
current_folder
show_folders
register_admin user5 pass5
add_item_property item5 key3=val5 key1=val3 key1=val6 key4=val7 
sign_out
create_folder folder5
show_item_properties item4
ls
help help
put item1
create_folder folder3
rename_user user7 <function generate_user at 0x027087F0>
sign_in a2 pa2
help rename_user
current_folder
show_item_properties item3
which_group
show_users
register_admin user5 pass5
create_folder folder4
create_folder folder2
put item3
cd folder5
sign_out
add_item_property item2 key5=val5 key6=val8 key3=val7 key4=val3 
create_folder folder3
pwd
show_items
pwd
whoami
show_users
ls_folders
help show_item_properties
show_item_properties item2
whoami
whoami
sign_in a4 pa4
cd folder1
pwd
register_admin user6 pass6
register_user user1 pass1
show_items
whoami
sign_in a3 pa3
whoami
show_item_properties item1
rename_user user9 <function generate_user at 0x027087F0>
sign_in a4 pa4
current_folder
current_folder
show_item_properties item3
cd folder4
ls_folders
sign_in user6 pass6
sign_out
sign_in a5 pa5
register_admin user4 pass4
sign_in user4 pass4
which_group
help rename_user
put item3
help create_folder
register_admin admin admin
buy
which_group
which_group
help delete_user
ls_folders
pwd
cd folder2
which_group
ls
create_folder folder3
rename_user user1 <function generate_user at 0x027087F0>
buy
sign_in user5 pass5
rename_user user7 <function generate_user at 0x027087F0>
sign_in a1 pa1
add_item_property item2 key4=val2 key1=val2 key5=val4 key7=val1 
help show_item_properties
cd folder4
show_item_properties item1
put item4
show_items
add_item_property item5 key10=val7 key9=val3 key3=val5 key1=val9 
register_user user5 pass5
show_folders
whoami
register_admin user4 pass4
rename_user user5 <function generate_user at 0x027087F0>
add_item_property item2 key3=val4 key4=val1 key8=val2 key4=val2 
register_admin user2 pass2
show_folders
register_user user3 pass3
show_folders
whoami
pwd
current_folder
show_folders
buy
show_folders
show_items
put item2
add_item item2 key8=val7 key2=val2 key9=val1 key5=val3 
register_admin user5 pass5
show_items
buy
cd folder4
whoami
rename_user user2 <function generate_user at 0x027087F0>
current_folder
current_folder
rename_user user6 <function generate_user at 0x027087F0>
add_item_property item4 key9=val8 key5=val5 key1=val4 key5=val6 
rename_user user6 <function generate_user at 0x027087F0>
show_item_properties item5
show_users
ls
create_folder folder5
add_item_property item3 key4=val7 key1=val8 key2=val4 key4=val9 
whoami
buy
register_user user1 pass1
add_item item1 key4=val3 key4=val7 key6=val3 key2=val3 
show_folders
add_item_property item3 key10=val7 key7=val6 key10=val7 key1=val2 
ls_folders
current_folder
sign_in a4 pa4
put item5
sign_out
sign_in a2 pa2
buy
sign_in admin admin
ls
put item4
pwd
ls
sign_in user3 pass3
buy
put item4
cd folder2
help sign_in
put item3
register_admin user8 pass8
register_admin user7 pass7
which_group
ls
sign_in a2 pa2
which_group
show_items
sign_in a4 pa4
show_item_properties item3
sign_out
rename_user user4 <function generate_user at 0x027087F0>
current_folder
register_admin user9 pass9
current_folder
ls
which_group
show_users
pwd
register_user admin admin
sign_out
create_folder folder3
pwd
sign_in user7 pass7
sign_in user1 pass1
sign_out
register_user user6 pass6
put item4
ls
show_items
which_group
sign_in a2 pa2
show_users
show_folders
sign_out
current_folder
whoami
sign_in a5 pa5
create_folder folder2
ls
rename_user user7 <function generate_user at 0x027087F0>
which_group
whoami
sign_out
sign_out
sign_in user8 pass8
show_users
current_folder
show_items
add_item item2 key1=val6 key2=val10 key9=val4 key4=val8 
cd folder1
current_folder
current_folder
rename_user user2 <function generate_user at 0x027087F0>
show_item_properties item5
show_item_properties item1
ls
register_user admin admin
rename_user user0 <function generate_user at 0x027087F0>
ls
help show_users
register_user user8 pass8
current_folder
whoami
whoami
sign_in user8 pass8
add_item_property item1 key6=val9 key6=val10 key5=val8 key2=val10 
put item5
put item1
which_group
whoami
put item5
buy
put item4
ls_folders
create_folder folder3
show_items
cd folder1
ls_folders
ls
sign_out
sign_out
sign_out
ls
which_group
which_group
add_item_property item5 key6=val6 key6=val10 key6=val6 key4=val10 
create_folder folder5
ls_folders
buy
add_item_property item3 key4=val1 key1=val7 key8=val1 key2=val5 
rename_user user5 <function generate_user at 0x027087F0>
whoami
buy
sign_in a5 pa5
create_folder folder4
sign_in user2 pass2
current_folder
add_item item1 key2=val10 key7=val2 key2=val9 key5=val8 
which_group
which_group
show_item_properties item1
sign_out
which_group
buy
put item5
register_admin user3 pass3
current_folder
sign_out
show_users
which_group
add_item_property item1 key7=val1 key3=val10 key6=val1 key4=val4 
register_admin admin admin
register_admin user5 pass5
sign_out
ls
help ls
whoami
show_item_properties item2
ls_folders
whoami
ls_folders
show_folders
register_user admin admin
current_folder
rename_user user9 <function generate_user at 0x027087F0>
pwd
rename_user user7 <function generate_user at 0x027087F0>
show_item_properties item3
pwd
buy
current_folder
ls_folders
help add_item_property
sign_in a3 pa3
register_user user4 pass4
show_items
show_items
current_folder
show_item_properties item1
help sign_in
current_folder
add_item item4 key3=val6 key9=val4 key4=val9 key3=val3 
sign_in user2 pass2
show_items
help register_admin
sign_out
current_folder
register_user user9 pass9
register_admin user9 pass9
show_folders
create_folder folder2
show_item_properties item3
ls
put item4
pwd
current_folder
add_item item2 key7=val3 key6=val8 key10=val8 key3=val9 
rename_user user5 <function generate_user at 0x027087F0>
whoami
put item1
add_item item3 key8=val7 key3=val7 key9=val8 key3=val7 
show_folders
show_users
register_user user8 pass8
current_folder
pwd
cd folder1
cd folder4
help pwd
pwd
cd folder4
whoami
ls_folders
buy
register_admin user8 pass8
show_item_properties item2
register_user user5 pass5
which_group
register_admin user8 pass8
ls_folders
show_users
which_group
register_admin user2 pass2
register_user user9 pass9
sign_in admin admin
show_item_properties item1
rename_user user8 <function generate_user at 0x027087F0>
ls
add_item item2 key2=val2 key4=val5 key6=val3 key4=val10 
ls_folders
add_item_property item2 key1=val2 key10=val2 key2=val6 key9=val3 
show_folders
ls
current_folder
register_user user5 pass5
register_admin user5 pass5
show_users
ls_folders
add_item item5 key4=val9 key10=val5 key8=val3 key2=val2 
cd folder5
buy
rename_user user5 <function generate_user at 0x027087F0>
ls_folders
show_users
show_item_properties item4
sign_in a2 pa2
ls_folders
current_folder
pwd
sign_in user9 pass9
sign_out
help sign_in
put item4
create_folder folder3
sign_out
show_item_properties item4
cd folder1
put item1
show_users
help help
register_user admin admin
sign_in user8 pass8
register_admin user8 pass8
add_item item1 key6=val10 key3=val4 key7=val1 key8=val5 
rename_user user0 <function generate_user at 0x027087F0>
sign_in user8 pass8
register_user user6 pass6
cd folder1
show_items
sign_in user1 pass1
add_item_property item2 key1=val8 key4=val2 key5=val8 key9=val5 
show_folders
show_folders
current_folder
whoami
current_folder
ls_folders
add_item_property item2 key3=val1 key9=val10 key9=val8 key7=val9 
show_users
register_admin user6 pass6
sign_in a4 pa4
whoami
create_folder folder1
sign_in a2 pa2
pwd
help sign_in
help history
ls_folders
buy
ls
ls_folders
register_admin user1 pass1
current_folder
show_item_properties item2
put item3
sign_in a5 pa5
add_item item1 key8=val10 key5=val8 key4=val2 key8=val4 
add_item item1 key4=val7 key9=val3 key4=val6 key6=val8 
register_user admin admin
whoami
show_items
ls_folders
rename_user user7 <function generate_user at 0x027087F0>
register_admin user3 pass3
create_folder folder5
show_items
whoami
current_folder
ls_folders
rename_user user6 <function generate_user at 0x027087F0>
help ls_folders
put item1
add_item_property item5 key10=val2 key5=val7 key1=val2 key9=val9 
cd folder4
show_users
sign_in a3 pa3
rename_user user2 <function generate_user at 0x027087F0>
which_group
add_item_property item5 key5=val1 key2=val3 key9=val2 key3=val8 
register_admin user4 pass4
rename_user user9 <function generate_user at 0x027087F0>
which_group
buy
show_folders
buy
current_folder
ls_folders
show_folders
current_folder
current_folder
sign_out
show_items
current_folder
whoami
whoami
ls_folders
show_item_properties item4
ls_folders
sign_out
add_item_property item1 key8=val6 key1=val9 key3=val5 key6=val7 
rename_user user7 <function generate_user at 0x027087F0>
sign_out
add_item item2 key3=val9 key7=val9 key7=val6 key9=val10 
put item1
ls
add_item_property item5 key3=val1 key4=val3 key10=val9 key7=val9 
buy
sign_out
which_group
rename_user user1 <function generate_user at 0x027087F0>
whoami
which_group
rename_user user6 <function generate_user at 0x027087F0>
register_admin user9 pass9
help which_group
help create_folder
cd folder1
create_folder folder1
show_folders
current_folder
sign_in a4 pa4
show_folders
register_admin user6 pass6
sign_in a3 pa3
create_folder folder3
help cd
ls
show_users
show_users
buy
show_item_properties item1
ls_folders
rename_user user8 <function generate_user at 0x027087F0>
whoami
current_folder
show_users
add_item item3 key9=val5 key7=val2 key4=val3 key8=val2 
current_folder
buy
sign_in a2 pa2
whoami
show_item_properties item1
current_folder
register_admin user9 pass9
show_users
cd folder3
ls
which_group
sign_out
whoami
rename_user user0 <function generate_user at 0x027087F0>
help sign_out
pwd
create_folder folder4
put item1
ls
put item4
current_folder
sign_out
add_item_property item5 key8=val4 key4=val2 key6=val3 key8=val6 
show_item_properties item4
add_item_property item4 key6=val2 key9=val7 key3=val1 key8=val6 
put item1
help add_item
show_folders
put item4
sign_in a1 pa1
add_item item4 key6=val7 key10=val9 key2=val5 key5=val9 
sign_out
which_group
register_admin user6 pass6
help register_admin
create_folder folder2
pwd
show_folders
add_item item1 key1=val5 key8=val8 key9=val4 key6=val8 
show_items
pwd
sign_in a3 pa3
whoami
sign_in a2 pa2
which_group
add_item item5 key5=val9 key7=val7 key6=val10 key7=val7 
which_group
pwd
put item2
sign_in a5 pa5
sign_in user6 pass6
sign_in user6 pass6
register_user user5 pass5
current_folder
register_user user7 pass7
show_folders
show_items
register_user user5 pass5
rename_user user0 <function generate_user at 0x027087F0>
show_folders
sign_in a2 pa2
which_group
whoami
sign_in a3 pa3
sign_in user3 pass3
show_item_properties item3
current_folder
ls_folders
rename_user user3 <function generate_user at 0x027087F0>
ls
cd folder2
show_item_properties item3
rename_user user4 <function generate_user at 0x027087F0>
add_item_property item2 key10=val8 key7=val10 key1=val3 key6=val10 
show_item_properties item3
create_folder folder5
add_item_property item1 key8=val8 key2=val5 key6=val6 key3=val2 
show_folders
create_folder folder4
whoami
buy
help add_item_property
sign_in a4 pa4
ls
sign_in a2 pa2
cd folder2
pwd
show_users
sign_out
register_user user4 pass4
show_users
cd folder2
current_folder
put item3
which_group
show_folders
help sign_in
add_item item5 key2=val1 key2=val3 key6=val5 key4=val7 
whoami
register_admin user1 pass1
register_admin user3 pass3
ls
ls
ls_folders
rename_user user8 <function generate_user at 0x027087F0>
show_folders
show_users
register_admin user6 pass6
help ls_folders
buy
register_user user2 pass2
buy
pwd
which_group
show_users
rename_user user1 <function generate_user at 0x027087F0>
show_users
whoami
sign_out
sign_in a3 pa3
show_items
cd folder1
put item3
rename_user user5 <function generate_user at 0x027087F0>
add_item item2 key5=val7 key5=val1 key1=val5 key8=val5 
cd folder3
put item3
create_folder folder2
register_user admin admin
sign_out
current_folder
sign_in a1 pa1
ls_folders
register_user user3 pass3
show_item_properties item1
ls
which_group
sign_in user2 pass2
which_group
rename_user user3 <function generate_user at 0x027087F0>
register_user user6 pass6
sign_in a2 pa2
put item5
which_group
ls_folders
show_folders
register_admin user9 pass9
rename_user user5 <function generate_user at 0x027087F0>
cd folder2
add_item item5 key5=val6 key8=val7 key6=val8 key4=val4 
rename_user user3 <function generate_user at 0x027087F0>
current_folder
add_item item2 key7=val5 key8=val7 key1=val3 key10=val5 
show_users
show_users
register_user user9 pass9
cd folder2
current_folder
buy
help help
register_admin user2 pass2
create_folder folder3
show_users
show_folders
help register_admin
rename_user user5 <function generate_user at 0x027087F0>
put item1
current_folder
show_items
register_user user8 pass8
pwd
whoami
add_item item5 key8=val2 key1=val2 key6=val6 key1=val7 
show_items
show_item_properties item1
show_item_properties item3
ls_folders
register_admin user4 pass4
help view_order
register_user user3 pass3
pwd
help pwd
current_folder
sign_in user3 pass3
put item4
cd folder3
register_admin user2 pass2
show_folders
rename_user user2 <function generate_user at 0x027087F0>
sign_out
register_user user8 pass8
ls_folders
show_users
rename_user user2 <function generate_user at 0x027087F0>
sign_out
ls_folders
help register_admin
sign_in user6 pass6
register_user user8 pass8
current_folder
show_item_properties item2
show_item_properties item1
sign_out
show_users
ls_folders
help which_group
current_folder
current_folder
put item5
add_item item1 key5=val2 key2=val4 key2=val2 key3=val3 
cd folder4
whoami
help cd
sign_in a1 pa1
register_user user9 pass9
put item3
current_folder
sign_in a2 pa2
sign_out
cd folder5
sign_in a3 pa3
register_user user3 pass3
cd folder3
show_folders
ls
ls_folders
current_folder
rename_user user3 <function generate_user at 0x027087F0>
add_item_property item5 key10=val5 key4=val8 key5=val8 key8=val6 
register_admin admin admin
help cd
which_group
add_item_property item1 key3=val4 key10=val7 key2=val1 key6=val4 
register_user user2 pass2
show_folders
sign_in a4 pa4
sign_in a5 pa5
put item2
register_admin admin admin
create_folder folder4
ls
sign_out
add_item item5 key5=val9 key6=val7 key3=val9 key9=val4 
register_admin user2 pass2
sign_in a4 pa4
register_admin user6 pass6
ls
rename_user user2 <function generate_user at 0x027087F0>
show_folders
which_group
whoami
ls
current_folder
show_item_properties item1
show_users
cd folder1
add_item_property item3 key4=val4 key10=val3 key7=val2 key2=val7 
ls
rename_user user2 <function generate_user at 0x027087F0>
create_folder folder2
which_group
rename_user user8 <function generate_user at 0x027087F0>
rename_user user6 <function generate_user at 0x027087F0>
buy
ls
put item3
show_items
cd folder4
ls_folders
register_user admin admin
show_folders
pwd
create_folder folder3
ls_folders
help rename_user
register_admin user2 pass2
sign_out
add_item item5 key10=val4 key5=val9 key3=val7 key8=val3 
help create_folder
show_users
pwd
which_group
which_group
help history
sign_out
sign_in a5 pa5
rename_user user9 <function generate_user at 0x027087F0>
ls
which_group
show_folders
ls
pwd
pwd
sign_out
show_items
register_user admin admin
whoami
which_group
cd folder1
register_admin user2 pass2
add_item_property item2 key10=val1 key7=val9 key3=val10 key8=val5 
help show_item_properties
buy
show_users
register_user user3 pass3
register_admin user1 pass1
help show_folders
show_users
rename_user user1 <function generate_user at 0x027087F0>
add_item item2 key10=val8 key7=val6 key5=val4 key7=val8 
register_admin user1 pass1
sign_out
buy
create_folder folder1
ls
add_item item2 key10=val9 key1=val3 key1=val6 key10=val6 
buy
rename_user user7 <function generate_user at 0x027087F0>
whoami
show_users
show_item_properties item3
cd folder1
show_items
add_item_property item5 key7=val6 key10=val9 key10=val10 key5=val4 
pwd
put item4
register_user user2 pass2
ls_folders
register_user user4 pass4
show_folders
sign_in user5 pass5
ls_folders
sign_out
pwd
rename_user user9 <function generate_user at 0x027087F0>
show_items
cd folder1
register_user user6 pass6
ls
register_user user9 pass9
register_user user3 pass3
put item2
put item4
add_item_property item5 key7=val5 key10=val5 key3=val4 key8=val2 
ls
cd folder2
current_folder
show_users
show_users
show_users
sign_in a2 pa2
register_admin user2 pass2
add_item_property item2 key10=val7 key4=val8 key3=val10 key4=val6 
show_users
which_group
create_folder folder5
ls
put item5
put item5
show_items
show_users
register_admin user1 pass1
ls_folders
rename_user user7 <function generate_user at 0x027087F0>
help sign_out
show_item_properties item2
sign_in a5 pa5
buy
add_item item1 key8=val3 key10=val6 key8=val7 key1=val8 
pwd
put item5
current_folder
show_item_properties item2
sign_in user8 pass8
show_item_properties item3
create_folder folder2
ls_folders
pwd
which_group
put item1
show_folders
pwd
current_folder
add_item_property item5 key6=val3 key10=val2 key7=val8 key8=val7 
add_item_property item3 key4=val8 key7=val9 key9=val4 key4=val6 
ls
whoami
create_folder folder5
sign_in a3 pa3
sign_in a3 pa3
show_item_properties item2
add_item item3 key3=val6 key9=val10 key8=val6 key5=val2 
buy
sign_out
pwd
help show_users
show_users
pwd
which_group
sign_in user9 pass9
add_item item4 key1=val7 key7=val4 key1=val2 key2=val2 
which_group
add_item item5 key1=val4 key8=val10 key2=val5 key10=val9 
create_folder folder4
show_item_properties item4
cd folder4
add_item_property item2 key4=val2 key3=val3 key4=val2 key5=val7 
buy
pwd
show_folders
show_users
put item1
help exit
help register_user
show_item_properties item3
add_item item4 key3=val8 key2=val6 key4=val5 key9=val6 
show_item_properties item3
pwd
register_user user8 pass8
add_item item4 key4=val10 key5=val3 key1=val5 key10=val4 
put item2
create_folder folder1
put item5
cd folder4
put item1
show_folders
pwd
whoami
put item4
whoami
show_item_properties item5
rename_user user2 <function generate_user at 0x027087F0>
add_item item5 key6=val3 key5=val2 key10=val10 key1=val2 
cd folder5
which_group
register_admin user7 pass7
buy
add_item item2 key10=val6 key2=val5 key3=val2 key7=val10 
show_item_properties item4
sign_in a1 pa1
help pwd
pwd
ls
register_admin user8 pass8
show_folders
pwd
sign_in a2 pa2
help history
buy
register_user user5 pass5
put item5
put item3
sign_in a4 pa4
sign_out
whoami
show_folders
buy
rename_user user7 <function generate_user at 0x027087F0>
rename_user user0 <function generate_user at 0x027087F0>
buy
current_folder
sign_in a4 pa4
sign_in a1 pa1
sign_out
show_folders
pwd
current_folder
whoami
ls
create_folder folder5
sign_out
create_folder folder4
show_users
buy
register_user user6 pass6
register_admin user6 pass6
show_users
add_item_property item2 key5=val3 key6=val10 key5=val10 key7=val7 
show_items
add_item_property item1 key3=val2 key5=val2 key1=val5 key3=val5 
sign_in a1 pa1
whoami
buy
show_items
whoami
show_folders
sign_in a5 pa5
register_user user9 pass9
sign_out
show_item_properties item2
add_item item2 key7=val2 key4=val1 key2=val3 key1=val9 
add_item_property item1 key1=val6 key6=val5 key1=val1 key3=val6 
add_item_property item4 key4=val2 key2=val3 key3=val10 key6=val6 
show_folders
add_item_property item3 key2=val8 key8=val7 key6=val10 key1=val4 
show_items
register_user user9 pass9
cd folder1
create_folder folder3
which_group
show_folders
register_admin user8 pass8
rename_user user3 <function generate_user at 0x027087F0>
register_user admin admin
put item3
sign_in a4 pa4
sign_in user8 pass8
show_item_properties item1
help which_group
current_folder
rename_user user0 <function generate_user at 0x027087F0>
rename_user user7 <function generate_user at 0x027087F0>
register_admin user3 pass3
which_group
register_admin user2 pass2
ls
register_admin user6 pass6
ls_folders
register_user user2 pass2
help show_items
which_group
put item4
create_folder folder5
add_item item3 key6=val2 key7=val6 key6=val5 key7=val10 
show_item_properties item2
register_admin user3 pass3
create_folder folder1
current_folder
cd folder3
show_items
add_item_property item4 key2=val9 key5=val1 key6=val6 key3=val2 
put item4
show_users
sign_out
help show_users
show_folders
sign_out
rename_user user6 <function generate_user at 0x027087F0>
register_user user4 pass4
add_item item4 key4=val9 key7=val9 key3=val7 key4=val8 
show_folders
sign_in a5 pa5
put item5
show_items
sign_out
sign_out
add_item_property item1 key2=val3 key5=val4 key3=val5 key8=val5 
sign_in a3 pa3
pwd
create_folder folder5
which_group
create_folder folder1
ls_folders
sign_out
which_group
current_folder
help show_folders
sign_out
rename_user user3 <function generate_user at 0x027087F0>
sign_out
sign_in admin admin
register_user user3 pass3
buy
rename_user user5 <function generate_user at 0x027087F0>
register_admin user6 pass6
put item5
whoami
show_folders
show_users
show_users
help view_order
show_users
rename_user user2 <function generate_user at 0x027087F0>
pwd
whoami
add_item item5 key7=val5 key1=val3 key10=val6 key8=val7 
create_folder folder2
create_folder folder3
show_folders
buy
rename_user user0 <function generate_user at 0x027087F0>
ls
sign_in user8 pass8
current_folder
put item3
sign_in a1 pa1
ls_folders
show_folders
show_folders
create_folder folder4
buy
add_item item4 key3=val2 key10=val4 key1=val4 key5=val1 
sign_in a2 pa2
pwd
show_item_properties item4
cd folder1
which_group
help create_folder
help add_item_property
pwd
pwd
add_item_property item1 key3=val4 key8=val2 key2=val8 key8=val8 
help pwd
cd folder2
cd folder3
ls_folders
create_folder folder3
cd folder4
register_admin user1 pass1
create_folder folder2
pwd
show_users
show_item_properties item2
sign_in user9 pass9
buy
cd folder2
sign_in a4 pa4
whoami
ls
whoami
cd folder3
add_item item1 key3=val7 key1=val9 key5=val2 key8=val3 
put item2
whoami
show_users
whoami
register_admin user6 pass6
show_items
which_group
sign_in a2 pa2
ls
add_item_property item5 key3=val5 key6=val1 key5=val8 key7=val6 
create_folder folder4
show_folders
ls
rename_user user9 <function generate_user at 0x027087F0>
show_users
sign_in user6 pass6
show_items
put item3
sign_out
rename_user user7 <function generate_user at 0x027087F0>
current_folder
current_folder
add_item item1 key7=val5 key1=val7 key4=val5 key7=val1 
sign_in user6 pass6
ls_folders
sign_in a1 pa1
sign_in user9 pass9
buy
put item1
show_item_properties item1
show_item_properties item2
sign_out
current_folder
buy
show_item_properties item5
ls
create_folder folder2
which_group
cd folder1
show_folders
pwd
register_admin user6 pass6
sign_in admin admin
put item4
show_items
sign_in a2 pa2
register_user user4 pass4
show_users
add_item item3 key1=val3 key5=val5 key4=val8 key9=val6 
ls_folders
sign_out
show_users
which_group
sign_in user9 pass9
buy
pwd
register_admin user6 pass6
register_user admin admin
show_items
ls
show_users
sign_out
show_folders
add_item_property item2 key6=val3 key6=val2 key10=val3 key1=val3 
show_folders
ls
show_item_properties item5
cd folder4
create_folder folder1
rename_user user3 <function generate_user at 0x027087F0>
add_item_property item1 key1=val3 key4=val4 key2=val4 key10=val8 
sign_in user1 pass1
sign_out
put item3
register_admin user3 pass3
show_users
sign_out
sign_in user5 pass5
create_folder folder4
show_item_properties item3
buy
pwd
current_folder
rename_user user4 <function generate_user at 0x027087F0>
help ls
create_folder folder2
add_item_property item2 key3=val7 key8=val8 key1=val7 key6=val10 
put item5
sign_out
show_item_properties item1
buy
ls
add_item item3 key5=val3 key4=val10 key9=val4 key4=val9 
show_item_properties item5
help exit
show_folders
put item5
ls
show_item_properties item3
which_group
ls
help add_item
buy
rename_user user1 <function generate_user at 0x027087F0>
pwd
ls_folders
show_item_properties item3
add_item item2 key3=val6 key10=val9 key4=val7 key3=val9 
ls
current_folder
rename_user user7 <function generate_user at 0x027087F0>
rename_user user6 <function generate_user at 0x027087F0>
which_group
whoami
whoami
register_user user6 pass6
show_users
pwd
sign_out
rename_user user5 <function generate_user at 0x027087F0>
ls
put item2
pwd
register_admin user2 pass2
sign_out
ls_folders
current_folder
show_items
add_item item1 key10=val5 key7=val10 key1=val6 key9=val10 
whoami
ls_folders
register_admin admin admin
sign_in user8 pass8
show_users
put item4
sign_out
cd folder3
buy
whoami
cd folder5
add_item_property item2 key3=val8 key4=val10 key9=val6 key9=val7 
cd folder2
register_admin user5 pass5
sign_out
sign_in a4 pa4
register_admin user2 pass2
show_folders
show_folders
show_users
create_folder folder1
add_item item3 key5=val4 key8=val1 key8=val9 key5=val1 
put item1
help sign_in
show_folders
show_items
show_folders
current_folder
rename_user user2 <function generate_user at 0x027087F0>
whoami
which_group
which_group
sign_in a4 pa4
ls
sign_out
show_users
ls_folders
current_folder
show_users
buy
create_folder folder5
ls_folders
sign_in user2 pass2
whoami
rename_user user0 <function generate_user at 0x027087F0>
add_item_property item4 key9=val8 key2=val5 key2=val5 key8=val9 
register_admin user3 pass3
show_items
put item3
ls_folders
register_admin admin admin
show_users
register_admin user2 pass2
which_group
which_group
put item2
register_user user3 pass3
create_folder folder5
pwd
show_users
show_item_properties item1
put item5
current_folder
sign_out
sign_in user7 pass7
rename_user user1 <function generate_user at 0x027087F0>
ls
rename_user user4 <function generate_user at 0x027087F0>
rename_user user9 <function generate_user at 0x027087F0>
show_item_properties item4
add_item item4 key6=val6 key2=val2 key2=val4 key7=val6 
current_folder
show_folders
which_group
create_folder folder2
sign_in a3 pa3
put item3
sign_in a1 pa1
sign_in a5 pa5
buy
show_item_properties item5
sign_in a5 pa5
register_user user8 pass8
ls
pwd
create_folder folder3
register_admin user7 pass7
register_user user4 pass4
help show_users
whoami
sign_in user8 pass8
show_items
put item2
buy
ls_folders
create_folder folder5
current_folder
create_folder folder1
which_group
sign_out
whoami
show_folders
show_items
add_item_property item4 key5=val7 key2=val3 key10=val5 key5=val10 
ls_folders
register_admin user9 pass9
show_item_properties item2
help put
register_user user2 pass2
show_items
register_admin user8 pass8
show_folders
ls
current_folder
ls
show_items
show_users
add_item_property item4 key10=val8 key7=val6 key3=val5 key10=val2 
add_item item2 key3=val8 key2=val5 key10=val10 key10=val1 
ls_folders
sign_in a4 pa4
create_folder folder4
create_folder folder3
register_admin user7 pass7
sign_in user1 pass1
add_item item3 key4=val3 key6=val8 key5=val9 key4=val1 
cd folder1
add_item_property item2 key3=val4 key8=val6 key8=val6 key2=val9 
sign_in user1 pass1
show_users
register_user user6 pass6
show_folders
which_group
register_user admin admin
ls
add_item_property item5 key3=val9 key1=val4 key2=val9 key4=val2 
add_item item4 key1=val10 key5=val5 key1=val3 key7=val7 
current_folder
add_item item4 key1=val1 key1=val5 key2=val6 key3=val3 
ls
show_users
ls
add_item item3 key4=val2 key1=val1 key9=val6 key8=val5 
rename_user user4 <function generate_user at 0x027087F0>
help show_item_properties
current_folder
create_folder folder2
cd folder1
ls
help ls
show_users
which_group
ls_folders
add_item_property item4 key2=val8 key8=val10 key2=val10 key2=val4 
show_item_properties item5
rename_user user0 <function generate_user at 0x027087F0>
show_folders
create_folder folder2
register_user user5 pass5
sign_in a4 pa4
cd folder1
show_users
sign_out
sign_out
rename_user user7 <function generate_user at 0x027087F0>
cd folder5
buy
current_folder
show_item_properties item4
sign_in user7 pass7
add_item item5 key3=val9 key2=val6 key10=val9 key1=val3 
show_item_properties item1
cd folder1
rename_user user1 <function generate_user at 0x027087F0>
ls
current_folder
rename_user user1 <function generate_user at 0x027087F0>
ls_folders
add_item item4 key6=val8 key2=val6 key3=val5 key2=val2 
add_item_property item3 key7=val10 key10=val1 key6=val8 key5=val4 
which_group
put item2
put item5
which_group
register_admin user4 pass4
show_items
sign_in a5 pa5
help pwd
ls_folders
register_user user3 pass3
register_admin user7 pass7
rename_user user0 <function generate_user at 0x027087F0>
register_user user1 pass1
ls
show_items
register_user user7 pass7
buy
show_items
ls
put item4
show_item_properties item5
cd folder4
rename_user user6 <function generate_user at 0x027087F0>
help delete_user
buy
whoami
sign_in a1 pa1
ls_folders
show_items
put item5
buy
buy
current_folder
pwd
ls
put item4
ls
create_folder folder5
register_admin user9 pass9
whoami
show_folders
show_item_properties item2
sign_in admin admin
show_items
show_item_properties item1
whoami
create_folder folder4
register_user admin admin
show_item_properties item2
buy
show_users
rename_user user2 <function generate_user at 0x027087F0>
cd folder2
show_folders
current_folder
sign_in a3 pa3
help current_folder
put item5
pwd
show_item_properties item2
sign_in a5 pa5
add_item item2 key8=val5 key9=val2 key6=val5 key1=val5 
sign_in a4 pa4
help exit
show_users
ls
sign_in user5 pass5
show_users
help cd
whoami
show_items
show_users
whoami
sign_in user2 pass2
show_users
sign_in user1 pass1
sign_in a2 pa2
create_folder folder2
show_folders
sign_out
whoami
whoami
sign_in a3 pa3
ls
ls
register_user user3 pass3
add_item item1 key4=val1 key9=val4 key5=val8 key7=val9 
whoami
help current_folder
show_items
help delete_user
register_user user6 pass6
register_admin user5 pass5
show_items
help current_folder
register_user user5 pass5
ls_folders
show_item_properties item2
show_folders
add_item item2 key5=val10 key1=val8 key1=val2 key2=val6 
ls
ls_folders
help register_user
sign_in user8 pass8
show_item_properties item1
rename_user user8 <function generate_user at 0x027087F0>
cd folder2
add_item_property item4 key3=val10 key9=val9 key3=val6 key2=val6 
current_folder
ls
add_item item4 key9=val4 key3=val8 key3=val4 key9=val9 
show_users
buy
add_item item3 key9=val9 key3=val3 key8=val8 key2=val6 
add_item_property item5 key5=val3 key3=val6 key5=val10 key8=val3 
sign_in a1 pa1
cd folder5
ls
show_item_properties item4
sign_in user3 pass3
which_group
show_items
which_group
register_user user3 pass3
sign_in user6 pass6
show_users
whoami
which_group
put item2
create_folder folder3
register_user user1 pass1
create_folder folder2
add_item item4 key3=val8 key3=val10 key5=val7 key1=val2 
add_item_property item5 key3=val1 key3=val3 key10=val3 key10=val3 
show_item_properties item5
whoami
create_folder folder1
add_item item2 key2=val9 key6=val1 key8=val7 key8=val5 
sign_in a5 pa5
show_users
show_items
show_folders
ls_folders
rename_user user2 <function generate_user at 0x027087F0>
ls_folders
which_group
ls
add_item item3 key10=val7 key5=val3 key8=val5 key10=val6 
buy
register_admin admin admin
register_admin user7 pass7
cd folder2
sign_out
show_users
sign_out
rename_user user6 <function generate_user at 0x027087F0>
current_folder
help pwd
buy
sign_in a2 pa2
show_users
buy
show_users
rename_user user4 <function generate_user at 0x027087F0>
rename_user user3 <function generate_user at 0x027087F0>
put item4
add_item_property item5 key5=val8 key10=val5 key9=val2 key3=val1 
create_folder folder4
register_user user7 pass7
register_user user5 pass5
create_folder folder1
sign_in a4 pa4
sign_in user1 pass1
buy
whoami
register_user user6 pass6
put item5
rename_user user6 <function generate_user at 0x027087F0>
buy
cd folder5
help sign_out
show_item_properties item1
register_user user6 pass6
ls_folders
put item5
sign_in a1 pa1
whoami
sign_in admin admin
show_users
register_user user4 pass4
register_admin user3 pass3
ls_folders
buy
show_folders
cd folder3
help exit
register_admin user2 pass2
create_folder folder4
sign_in a1 pa1
create_folder folder1
cd folder3
sign_in user8 pass8
show_items
add_item item2 key7=val4 key2=val6 key6=val1 key8=val7 
sign_out
cd folder2
whoami
ls_folders
put item4
sign_in a5 pa5
show_folders
create_folder folder2
help which_group
create_folder folder2
sign_in user9 pass9
show_item_properties item2
register_admin user5 pass5
show_folders
help sign_in
register_admin admin admin
add_item_property item4 key1=val1 key3=val7 key10=val1 key5=val4 
pwd
add_item_property item1 key2=val2 key5=val10 key7=val4 key9=val4 
rename_user user7 <function generate_user at 0x027087F0>
register_admin user7 pass7
which_group
register_admin user3 pass3
ls
add_item_property item5 key7=val10 key6=val3 key6=val9 key10=val6 
pwd
whoami
register_user user8 pass8
sign_out
put item1
create_folder folder4
which_group
show_folders
sign_in user7 pass7
sign_in user3 pass3
show_users
which_group
sign_in a2 pa2
show_item_properties item3
whoami
create_folder folder4
show_users
which_group
create_folder folder5
cd folder1
buy
show_items
ls_folders
pwd
whoami
help sign_in
show_folders
sign_out
show_folders
help add_item
cd folder1
cd folder3
which_group
show_item_properties item5
ls
register_admin user3 pass3
show_folders
whoami
sign_in a2 pa2
add_item_property item1 key3=val8 key7=val3 key2=val1 key3=val6 
show_users
whoami
add_item_property item1 key10=val6 key6=val5 key1=val5 key3=val5 
show_item_properties item3
show_item_properties item2
put item2
show_users
sign_out
cd folder2
create_folder folder3
show_users
cd folder4
show_folders
help register_user
help ls
current_folder
help buy
rename_user user7 <function generate_user at 0x027087F0>
show_folders
add_item item4 key10=val1 key2=val6 key1=val9 key9=val8 
whoami
create_folder folder4
add_item item4 key9=val10 key7=val6 key10=val9 key1=val5 
ls_folders
whoami
rename_user user7 <function generate_user at 0x027087F0>
which_group
whoami
sign_in a5 pa5
show_items
sign_in a4 pa4
rename_user user3 <function generate_user at 0x027087F0>
rename_user user8 <function generate_user at 0x027087F0>
add_item item2 key10=val4 key5=val10 key9=val1 key8=val8 
show_folders
show_users
sign_out
which_group
show_users
put item1
rename_user user3 <function generate_user at 0x027087F0>
sign_in user5 pass5
add_item item2 key8=val9 key3=val8 key2=val1 key9=val1 
sign_in a5 pa5
show_folders
buy
put item3
sign_in user8 pass8
register_user user6 pass6
register_user user5 pass5
create_folder folder4
show_users
create_folder folder3
ls_folders
show_users
pwd
ls_folders
whoami
register_admin user5 pass5
register_admin user8 pass8
show_users
register_user user5 pass5
add_item item1 key3=val3 key6=val8 key5=val5 key6=val6 
register_admin user4 pass4
add_item item5 key3=val3 key2=val2 key1=val5 key6=val4 
help sign_in
ls_folders
show_users
buy
sign_in a3 pa3
register_user user8 pass8
show_folders
sign_in user9 pass9
rename_user user0 <function generate_user at 0x027087F0>
register_admin admin admin
cd folder4
current_folder
which_group
show_users
rename_user user5 <function generate_user at 0x027087F0>
show_item_properties item3
add_item_property item4 key2=val9 key4=val3 key7=val9 key8=val2 
add_item_property item4 key6=val3 key6=val4 key3=val7 key10=val2 
show_item_properties item1
which_group
register_user user8 pass8
put item1
show_items
ls_folders
help exit
sign_in user5 pass5
ls_folders
show_users
create_folder folder2
help delete_user
register_admin user8 pass8
sign_in a5 pa5
create_folder folder1
sign_out
show_item_properties item5
add_item item2 key2=val2 key1=val3 key7=val5 key9=val8 
register_admin user1 pass1
cd folder5
cd folder2
show_users
rename_user user5 <function generate_user at 0x027087F0>
which_group
current_folder
sign_in a5 pa5
pwd
ls_folders
ls_folders
whoami
show_folders
rename_user user0 <function generate_user at 0x027087F0>
register_admin user4 pass4
show_item_properties item5
cd folder1
put item5
ls
sign_out
help put
create_folder folder4
show_folders
show_items
show_item_properties item3
pwd
sign_in a2 pa2
show_items
sign_out
show_item_properties item2
sign_in a1 pa1
sign_in a4 pa4
show_users
buy
help show_items
sign_in a5 pa5
show_items
register_admin user4 pass4
sign_in a2 pa2
create_folder folder2
current_folder
add_item_property item3 key7=val4 key5=val8 key10=val10 key1=val4 
ls
show_items
add_item item4 key5=val4 key6=val9 key7=val3 key7=val3 
register_admin user6 pass6
current_folder
cd folder5
register_user user2 pass2
add_item item4 key2=val7 key2=val2 key3=val8 key3=val10 
add_item item2 key10=val3 key7=val7 key7=val5 key2=val6 
put item4
show_folders
register_admin user7 pass7
show_item_properties item5
show_users
sign_out
current_folder
register_admin user5 pass5
register_admin user7 pass7
whoami
ls_folders
pwd
show_folders
show_users
which_group
cd folder5
add_item item5 key5=val5 key7=val9 key1=val9 key8=val10 
sign_in a4 pa4
add_item item1 key7=val9 key3=val9 key8=val4 key1=val8 
sign_in user3 pass3
whoami
which_group
add_item item3 key6=val6 key7=val4 key7=val5 key5=val1 
current_folder
buy
put item1
help whoami
current_folder
cd folder4
register_user user7 pass7
show_users
ls_folders
buy
whoami
rename_user user1 <function generate_user at 0x027087F0>
show_item_properties item5
help show_folders
rename_user user2 <function generate_user at 0x027087F0>
whoami
show_users
cd folder4
pwd
whoami
show_item_properties item1
add_item_property item5 key8=val4 key5=val10 key2=val4 key3=val1 
show_item_properties item3
show_folders
show_items
show_users
register_user admin admin
show_users
buy
show_item_properties item3
create_folder folder1
sign_out
add_item item3 key1=val10 key10=val10 key9=val6 key8=val5 
current_folder
buy
help ls_folders
sign_in a2 pa2
add_item item3 key3=val8 key10=val4 key9=val9 key9=val8 
show_users
add_item item4 key10=val6 key7=val5 key7=val1 key7=val2 
pwd
cd folder1
show_items
show_users
register_user user9 pass9
whoami
rename_user user1 <function generate_user at 0x027087F0>
ls
register_user user2 pass2
whoami
show_folders
ls_folders
register_admin user1 pass1
pwd
create_folder folder5
ls
add_item_property item4 key9=val7 key9=val8 key6=val5 key7=val4 
ls_folders
show_items
ls_folders
register_admin user4 pass4
ls
show_items
show_item_properties item4
pwd
which_group
show_folders
rename_user user8 <function generate_user at 0x027087F0>
buy
show_items
ls
pwd
sign_in a1 pa1
buy
sign_in user1 pass1
sign_in user9 pass9
pwd
create_folder folder4
cd folder5
register_admin user3 pass3
which_group
show_item_properties item5
current_folder
sign_out
ls_folders
add_item item1 key7=val5 key4=val1 key10=val2 key2=val4 
show_item_properties item2
ls_folders
register_user user3 pass3
cd folder1
ls_folders
whoami
sign_in a5 pa5
show_item_properties item5
help register_admin
sign_in a5 pa5
put item2
ls_folders
create_folder folder1
register_admin user3 pass3
which_group
which_group
pwd
put item4
show_items
register_admin user7 pass7
ls
cd folder4
show_item_properties item4
whoami
whoami
show_folders
current_folder
register_admin user9 pass9
show_items
ls
pwd
cd folder3
add_item item4 key7=val9 key9=val4 key2=val8 key10=val4 
sign_in a5 pa5
rename_user user4 <function generate_user at 0x027087F0>
which_group
add_item_property item5 key7=val4 key1=val6 key3=val3 key6=val7 
show_users
which_group
sign_out
put item5
put item3
whoami
create_folder folder5
buy
whoami
pwd
show_item_properties item3
buy
show_users
put item2
register_user admin admin
add_item_property item4 key1=val5 key5=val7 key9=val7 key4=val3 
sign_out
show_folders
add_item_property item2 key9=val2 key8=val3 key8=val2 key5=val3 
sign_out
pwd
show_items
sign_out
rename_user user6 <function generate_user at 0x027087F0>
sign_out
show_users
pwd
show_folders
rename_user user7 <function generate_user at 0x027087F0>
whoami
sign_in user5 pass5
create_folder folder3
ls
help which_group
show_item_properties item2
show_items
register_admin user2 pass2
sign_in user4 pass4
help pwd
ls_folders
create_folder folder4
register_admin user2 pass2
sign_in a1 pa1
whoami
current_folder
show_users
sign_in a1 pa1
sign_in user9 pass9
sign_in user7 pass7
show_item_properties item5
show_users
which_group
show_item_properties item5
register_user user4 pass4
rename_user user3 <function generate_user at 0x027087F0>
help history
ls
show_users
create_folder folder2
sign_in a2 pa2
whoami
put item3
sign_in user1 pass1
ls_folders
show_item_properties item5
sign_out
ls_folders
help create_folder
show_item_properties item5
add_item item5 key10=val9 key7=val7 key7=val5 key7=val2 
show_users
register_user user8 pass8
rename_user user8 <function generate_user at 0x027087F0>
add_item_property item1 key10=val8 key5=val5 key4=val10 key5=val9 
register_admin user4 pass4
pwd
which_group
buy
show_users
sign_in a3 pa3
show_item_properties item2
add_item item3 key2=val5 key6=val6 key4=val7 key1=val5 
sign_in user1 pass1
current_folder
create_folder folder1
sign_in a5 pa5
sign_in user4 pass4
cd folder4
create_folder folder2
pwd
add_item_property item1 key5=val6 key2=val10 key3=val9 key10=val6 
show_item_properties item3
create_folder folder2
buy
add_item item2 key5=val3 key9=val1 key1=val9 key2=val2 
which_group
create_folder folder2
whoami
add_item item1 key2=val8 key1=val3 key4=val10 key10=val10 
show_item_properties item3
show_item_properties item1
show_items
add_item item4 key7=val4 key3=val7 key10=val5 key1=val8 
sign_in a3 pa3
which_group
buy
create_folder folder1
register_admin user9 pass9
sign_out
pwd
sign_in a1 pa1
register_user user3 pass3
register_admin user9 pass9
sign_out
sign_out
sign_in a4 pa4
rename_user user1 <function generate_user at 0x027087F0>
show_users
buy
sign_in a3 pa3
sign_out
add_item_property item2 key9=val8 key8=val8 key5=val9 key7=val2 
sign_out
which_group
add_item_property item4 key8=val3 key3=val1 key4=val10 key8=val1 
ls_folders
rename_user user6 <function generate_user at 0x027087F0>
buy
rename_user user8 <function generate_user at 0x027087F0>
rename_user user7 <function generate_user at 0x027087F0>
current_folder
ls
ls
which_group
sign_out
ls_folders
show_users
cd folder4
current_folder
register_user admin admin
show_users
sign_out
help show_item_properties
buy
add_item item3 key7=val8 key9=val6 key2=val7 key10=val10 
show_item_properties item1
show_folders
buy
register_user user8 pass8
register_admin user9 pass9
register_user user2 pass2
add_item_property item2 key8=val3 key9=val2 key7=val8 key1=val2 
show_folders
add_item_property item4 key6=val7 key4=val3 key3=val6 key7=val8 
rename_user user5 <function generate_user at 0x027087F0>
register_admin user9 pass9
create_folder folder3
ls_folders
register_user user3 pass3
whoami
ls
add_item item3 key6=val10 key2=val8 key10=val1 key4=val3 
add_item_property item3 key2=val8 key9=val7 key1=val3 key1=val9 
show_items
which_group
whoami
sign_in a2 pa2
buy
show_folders
sign_in user8 pass8
pwd
ls
create_folder folder2
sign_in a3 pa3
sign_in admin admin
show_folders
buy
current_folder
show_item_properties item5
buy
show_items
show_folders
sign_in user2 pass2
show_item_properties item3
cd folder4
ls
buy
show_item_properties item3
add_item_property item3 key3=val9 key9=val5 key1=val2 key9=val4 
put item1
cd folder2
add_item item1 key5=val8 key9=val1 key5=val4 key4=val9 
whoami
create_folder folder2
show_items
ls
current_folder
put item5
rename_user user3 <function generate_user at 0x027087F0>
help history
put item4
current_folder
rename_user user4 <function generate_user at 0x027087F0>
sign_in a5 pa5
which_group
add_item item4 key1=val8 key3=val7 key5=val9 key4=val6 
buy
which_group
help rename_user
add_item_property item4 key8=val1 key8=val5 key9=val5 key1=val4 
whoami
add_item item4 key4=val10 key4=val10 key1=val9 key6=val8 
show_users
sign_out
show_folders
sign_out
show_items
whoami
cd folder5
sign_in a4 pa4
buy
add_item item2 key2=val2 key7=val3 key1=val1 key10=val10 
help show_items
which_group
cd folder1
sign_in user9 pass9
sign_in a1 pa1
show_item_properties item4
show_folders
cd folder4
pwd
ls
add_item_property item5 key2=val7 key3=val7 key3=val10 key7=val1 
show_folders
put item1
pwd
sign_out
ls
current_folder
show_item_properties item5
show_items
sign_in user4 pass4
show_users
ls_folders
whoami
buy
cd folder1
pwd
whoami
show_users
ls_folders
put item1
current_folder
buy
register_admin user5 pass5
help show_users
sign_out
sign_in a2 pa2
current_folder
register_admin user6 pass6
buy
pwd
ls
register_admin user4 pass4
show_items
register_admin user5 pass5
which_group
sign_in user1 pass1
add_item_property item4 key8=val2 key7=val8 key1=val9 key1=val10 
create_folder folder2
show_users
register_user user4 pass4
add_item_property item4 key10=val6 key4=val2 key1=val5 key4=val9 
help show_item_properties
sign_in user3 pass3
sign_in a4 pa4
register_user user2 pass2
pwd
ls
show_item_properties item1
show_items
whoami
add_item_property item3 key2=val4 key6=val2 key9=val7 key5=val7 
ls_folders
sign_in user4 pass4
ls_folders
show_users
help register_admin
ls
put item3
register_user user3 pass3
show_users
current_folder
show_users
ls_folders
show_item_properties item3
current_folder
sign_in a3 pa3
ls_folders
pwd
show_folders
whoami
pwd
buy
buy
show_users
show_items
sign_out
ls
show_items
sign_in user6 pass6
put item3
show_users
sign_out
which_group
buy
buy
show_users
current_folder
ls_folders
cd folder1
add_item_property item4 key6=val8 key3=val3 key3=val6 key3=val1 
show_item_properties item2
rename_user user8 <function generate_user at 0x027087F0>
current_folder
add_item_property item1 key7=val6 key10=val1 key6=val8 key9=val7 
sign_out
register_user user8 pass8
put item1
add_item item1 key7=val9 key8=val1 key10=val6 key4=val4 
put item1
cd folder2
register_user user3 pass3
cd folder4
rename_user user7 <function generate_user at 0x027087F0>
create_folder folder1
add_item item4 key7=val4 key3=val1 key5=val8 key10=val9 
put item5
show_item_properties item2
add_item item4 key2=val9 key4=val10 key3=val5 key4=val9 
show_users
ls_folders
sign_in user5 pass5
rename_user user9 <function generate_user at 0x027087F0>
register_user user2 pass2
show_users
rename_user user1 <function generate_user at 0x027087F0>
show_folders
create_folder folder4
sign_in a4 pa4
sign_in user4 pass4
ls_folders
which_group
which_group
ls_folders
pwd
create_folder folder5
sign_in admin admin
cd folder4
show_users
ls
show_item_properties item1
register_user user9 pass9
sign_in user3 pass3
register_admin user2 pass2
help add_item_property
add_item item5 key4=val7 key10=val2 key10=val7 key3=val3 
create_folder folder3
sign_in user1 pass1
register_admin user3 pass3
sign_in a1 pa1
register_user user5 pass5
cd folder3
sign_in a1 pa1
rename_user user8 <function generate_user at 0x027087F0>
show_item_properties item2
cd folder2
register_admin user6 pass6
buy
which_group
add_item item5 key10=val3 key10=val8 key10=val7 key8=val8 
ls_folders
sign_out
current_folder
rename_user user2 <function generate_user at 0x027087F0>
buy
register_admin user5 pass5
show_users
help cd
which_group
put item4
register_admin user7 pass7
ls_folders
ls_folders
buy
which_group
show_item_properties item2
show_folders
ls
sign_in a3 pa3
add_item item4 key10=val4 key10=val4 key10=val5 key1=val6 
show_folders
add_item_property item5 key2=val5 key5=val7 key10=val1 key5=val2 
which_group
which_group
sign_out
sign_in a4 pa4
ls_folders
buy
show_users
cd folder2
add_item item2 key4=val1 key6=val1 key2=val9 key6=val1 
ls
sign_out
show_folders
show_item_properties item1
add_item_property item1 key3=val4 key4=val6 key3=val4 key4=val5 
help pwd
which_group
help whoami
ls
buy
add_item item2 key2=val3 key1=val6 key9=val9 key9=val4 
put item2
ls_folders
show_folders
show_folders
ls
put item4
help delete_user
pwd
help show_item_properties
cd folder4
sign_in user5 pass5
ls
add_item item2 key5=val4 key2=val10 key2=val7 key7=val3 
create_folder folder5
show_item_properties item1
show_folders
rename_user user1 <function generate_user at 0x027087F0>
show_users
rename_user user7 <function generate_user at 0x027087F0>
add_item_property item4 key10=val5 key1=val10 key7=val7 key2=val4 
show_users
ls_folders
sign_in user3 pass3
add_item item3 key9=val3 key6=val10 key3=val7 key10=val9 
buy
put item5
add_item_property item2 key5=val4 key6=val5 key10=val2 key3=val6 
put item1
cd folder1
register_admin user3 pass3
register_user user9 pass9
sign_out
show_users
show_users
show_users
sign_out
sign_in user7 pass7
show_items
show_items
add_item item4 key5=val9 key6=val5 key8=val5 key8=val4 
show_items
show_folders
show_item_properties item4
cd folder5
buy
sign_out
help show_item_properties
put item2
cd folder3
current_folder
add_item item4 key6=val4 key7=val7 key6=val5 key10=val2 
sign_out
help add_item
put item2
sign_in user7 pass7
ls
help add_item
register_user user1 pass1
ls
show_item_properties item3
register_admin user1 pass1
ls
show_items
sign_out
sign_in a2 pa2
current_folder
sign_out
add_item item1 key7=val4 key2=val9 key7=val7 key3=val9 
show_items
add_item item4 key10=val9 key7=val5 key4=val9 key1=val5 
register_admin user2 pass2
register_user user5 pass5
buy
current_folder
whoami
sign_in a4 pa4
add_item_property item1 key4=val2 key6=val9 key10=val8 key3=val6 
which_group
ls
buy
help buy
create_folder folder5
current_folder
sign_out
ls_folders
create_folder folder1
buy
create_folder folder1
sign_in a4 pa4
pwd
create_folder folder3
cd folder2
add_item item3 key2=val5 key2=val4 key1=val8 key9=val9 
show_items
buy
whoami
sign_in a2 pa2
show_items
ls_folders
sign_in a3 pa3
show_folders
sign_in a4 pa4
show_users
which_group
current_folder
add_item item1 key9=val7 key1=val8 key7=val1 key2=val4 
add_item_property item4 key3=val1 key1=val7 key10=val3 key4=val5 
rename_user user3 <function generate_user at 0x027087F0>
ls_folders
sign_out
which_group
register_admin admin admin
current_folder
register_user user3 pass3
sign_out
pwd
rename_user user9 <function generate_user at 0x027087F0>
rename_user user1 <function generate_user at 0x027087F0>
sign_in user7 pass7
ls_folders
register_admin admin admin
sign_in user3 pass3
register_admin user2 pass2
current_folder
pwd
show_users
which_group
whoami
whoami
show_folders
add_item_property item2 key6=val2 key4=val5 key1=val3 key6=val4 
pwd
help add_item
rename_user user3 <function generate_user at 0x027087F0>
rename_user user9 <function generate_user at 0x027087F0>
sign_out
current_folder
ls_folders
register_user admin admin
help view_order
sign_in user8 pass8
show_items
register_admin user5 pass5
rename_user user1 <function generate_user at 0x027087F0>
pwd
ls_folders
rename_user user6 <function generate_user at 0x027087F0>
current_folder
create_folder folder5
rename_user user2 <function generate_user at 0x027087F0>
show_users
sign_in user5 pass5
buy
buy
register_user user8 pass8
create_folder folder5
cd folder5
help pwd
add_item item4 key7=val8 key7=val2 key2=val4 key8=val6 
which_group
current_folder
which_group
sign_in a2 pa2
whoami
current_folder
which_group
put item1
sign_in user9 pass9
whoami
show_items
ls
add_item_property item3 key4=val3 key1=val9 key9=val4 key9=val5 
ls_folders
add_item_property item4 key6=val5 key9=val9 key4=val1 key7=val5 
rename_user user1 <function generate_user at 0x027087F0>
show_folders
cd folder1
ls_folders
add_item_property item4 key1=val1 key3=val8 key1=val1 key9=val5 
pwd
which_group
cd folder2
put item4
add_item item3 key5=val10 key10=val9 key5=val5 key3=val8 
show_item_properties item2
create_folder folder2
register_admin user9 pass9
sign_in a5 pa5
show_item_properties item1
add_item_property item4 key7=val10 key7=val7 key6=val6 key8=val5 
cd folder1
help pwd
show_item_properties item5
cd folder3
show_users
show_items
ls_folders
whoami
buy
register_user user3 pass3
ls
show_users
show_users
sign_in user9 pass9
show_users
create_folder folder3
cd folder3
buy
show_items
which_group
show_folders
put item1
current_folder
show_folders
add_item_property item2 key6=val2 key3=val2 key10=val6 key1=val3 
put item1
which_group
create_folder folder3
sign_in user6 pass6
cd folder5
pwd
show_folders
rename_user user2 <function generate_user at 0x027087F0>
show_users
help show_item_properties
buy
ls_folders
which_group
buy
show_item_properties item5
pwd
add_item_property item4 key2=val4 key5=val10 key2=val10 key10=val3 
put item2
add_item_property item4 key8=val8 key4=val3 key9=val1 key10=val6 
sign_in a3 pa3
put item2
buy
which_group
ls_folders
cd folder5
whoami
add_item item3 key4=val1 key7=val2 key5=val5 key7=val9 
add_item_property item1 key6=val7 key1=val7 key7=val5 key6=val9 
whoami
show_users
show_users
show_users
register_admin user3 pass3
whoami
whoami
add_item_property item2 key2=val6 key9=val4 key5=val8 key7=val1 
current_folder
register_admin user7 pass7
which_group
which_group
help pwd
sign_in a3 pa3
create_folder folder1
sign_in a5 pa5
rename_user user0 <function generate_user at 0x027087F0>
current_folder
register_admin user7 pass7
sign_in a1 pa1
sign_out
show_folders
which_group
put item5
cd folder5
whoami
whoami
whoami
pwd
buy
which_group
add_item_property item5 key9=val4 key2=val7 key4=val4 key5=val8 
show_item_properties item2
help ls
show_items
show_folders
which_group
help whoami
create_folder folder1
add_item_property item3 key2=val3 key4=val8 key1=val4 key8=val4 
which_group
cd folder4
sign_in a2 pa2
ls_folders
create_folder folder1
create_folder folder4
sign_in user6 pass6
show_folders
register_admin user9 pass9
which_group
ls_folders
put item2
ls_folders
sign_out
show_items
register_user user6 pass6
show_folders
current_folder
add_item item2 key2=val10 key5=val1 key2=val9 key10=val6 
pwd
buy
sign_out
sign_in user7 pass7
ls_folders
current_folder
ls
ls
pwd
create_folder folder5
whoami
current_folder
add_item_property item2 key9=val5 key8=val2 key6=val4 key1=val3 
put item4
whoami
sign_in a2 pa2
sign_out
which_group
show_item_properties item3
add_item_property item3 key8=val4 key8=val2 key8=val10 key8=val1 
sign_out
register_user admin admin
sign_in a3 pa3
sign_out
current_folder
buy
show_item_properties item4
cd folder4
show_folders
register_admin user2 pass2
ls_folders
ls
ls
pwd
put item5
register_admin user2 pass2
pwd
whoami
ls_folders
register_admin user9 pass9
register_user user1 pass1
show_folders
show_folders
cd folder4
which_group
pwd
sign_in admin admin
pwd
sign_in a4 pa4
register_admin user5 pass5
add_item_property item1 key9=val2 key3=val7 key9=val9 key9=val6 
register_user user4 pass4
put item4
put item1
cd folder4
sign_in a5 pa5
create_folder folder2
help show_users
buy
register_admin user9 pass9
rename_user user9 <function generate_user at 0x027087F0>
show_folders
show_users
help sign_in
add_item_property item3 key3=val8 key10=val4 key5=val10 key2=val3 
whoami
show_folders
register_admin user5 pass5
whoami
add_item_property item3 key2=val2 key8=val5 key9=val1 key9=val1 
ls_folders
pwd
add_item_property item2 key7=val8 key6=val2 key2=val2 key7=val10 
which_group
sign_out
ls_folders
show_items
put item3
cd folder4
show_items
which_group
current_folder
current_folder
ls_folders
show_users
ls_folders
rename_user user0 <function generate_user at 0x027087F0>
rename_user user1 <function generate_user at 0x027087F0>
add_item item5 key6=val7 key7=val4 key10=val2 key10=val7 
current_folder
sign_out
put item1
show_folders
ls
current_folder
register_admin user8 pass8
sign_in user3 pass3
buy
sign_out
help exit
buy
pwd
show_folders
which_group
show_items
help pwd
show_folders
buy
which_group
register_user user4 pass4
buy
rename_user user4 <function generate_user at 0x027087F0>
ls_folders
help register_user
add_item_property item2 key2=val4 key1=val10 key6=val10 key1=val8 
ls
show_item_properties item4
create_folder folder1
put item2
help add_item_property
register_user user9 pass9
ls_folders
show_folders
whoami
whoami
ls_folders
sign_out
ls_folders
put item4
add_item_property item2 key2=val3 key2=val7 key6=val3 key3=val3 
register_user admin admin
sign_in a3 pa3
add_item item2 key10=val2 key10=val1 key5=val6 key7=val9 
pwd
ls
sign_in a1 pa1
create_folder folder4
show_folders
current_folder
register_admin user2 pass2
add_item item1 key4=val5 key9=val6 key3=val7 key3=val7 
ls
create_folder folder4
ls
show_folders
add_item item4 key1=val2 key2=val10 key2=val6 key5=val1 
buy
sign_out
sign_in a1 pa1
help show_users
sign_out
cd folder3
show_folders
put item1
show_users
buy
cd folder2
add_item_property item1 key2=val7 key7=val4 key9=val9 key4=val5 
add_item item2 key1=val10 key1=val7 key5=val8 key9=val10 
register_admin user4 pass4
add_item item5 key6=val6 key10=val6 key5=val6 key8=val7 
sign_in a3 pa3
show_users
sign_in user4 pass4
show_users
ls
ls
add_item item2 key10=val1 key7=val9 key5=val1 key2=val9 
create_folder folder1
sign_out
ls
sign_in user8 pass8
whoami
current_folder
sign_in user1 pass1
add_item item3 key1=val6 key8=val5 key5=val2 key4=val8 
create_folder folder1
rename_user user2 <function generate_user at 0x027087F0>
current_folder
help ls
show_users
sign_in user7 pass7
whoami
cd folder2
show_items
whoami
register_user user1 pass1
rename_user user0 <function generate_user at 0x027087F0>
pwd
rename_user user6 <function generate_user at 0x027087F0>
add_item item1 key7=val7 key1=val10 key10=val9 key2=val8 
whoami
help add_item_property
add_item_property item5 key5=val6 key9=val1 key8=val8 key10=val4 
show_folders
create_folder folder1
add_item item5 key7=val1 key10=val2 key2=val7 key5=val1 
cd folder3
register_user user2 pass2
rename_user user7 <function generate_user at 0x027087F0>
sign_in a4 pa4
register_admin user5 pass5
show_item_properties item4
register_user user9 pass9
show_items
rename_user user5 <function generate_user at 0x027087F0>
sign_in a1 pa1
show_users
which_group
add_item item2 key3=val10 key9=val5 key9=val9 key10=val9 
sign_in admin admin
ls
show_items
which_group
pwd
create_folder folder4
current_folder
current_folder
put item2
show_users
register_admin user9 pass9
show_items
put item4
ls_folders
register_admin user3 pass3
ls
show_items
create_folder folder1
help buy
show_items
current_folder
show_users
add_item item3 key5=val3 key10=val2 key4=val3 key1=val4 
show_item_properties item1
current_folder
show_item_properties item2
whoami
ls
which_group
rename_user user6 <function generate_user at 0x027087F0>
rename_user user4 <function generate_user at 0x027087F0>
create_folder folder3
show_item_properties item1
show_item_properties item5
show_item_properties item3
help view_order
which_group
show_item_properties item5
sign_in a5 pa5
which_group
sign_out
show_users
add_item_property item2 key8=val4 key3=val10 key3=val10 key4=val3 
current_folder
put item5
ls_folders
rename_user user3 <function generate_user at 0x027087F0>
rename_user user4 <function generate_user at 0x027087F0>
cd folder4
pwd
buy
whoami
sign_out
cd folder3
register_user user5 pass5
cd folder2
pwd
put item5
ls
create_folder folder4
show_item_properties item1
buy
ls_folders
put item4
help which_group
sign_out
whoami
sign_in a5 pa5
register_admin user3 pass3
which_group
sign_in admin admin
register_user user7 pass7
put item5
sign_in a3 pa3
show_items
show_users
show_users
rename_user user0 <function generate_user at 0x027087F0>
cd folder5
help history
pwd
help add_item
current_folder
whoami
add_item_property item2 key9=val5 key2=val5 key2=val8 key1=val10 
show_users
register_user user3 pass3
sign_in user5 pass5
sign_out
register_user user3 pass3
sign_in a3 pa3
sign_out
help show_items
sign_out
show_users
current_folder
ls
create_folder folder3
sign_out
pwd
sign_out
show_items
whoami
show_items
register_admin user3 pass3
cd folder3
add_item_property item3 key10=val3 key3=val8 key4=val5 key8=val6 
show_item_properties item1
show_folders
whoami
sign_out
sign_out
ls
help put
which_group
show_item_properties item1
sign_out
cd folder5
put item1
ls_folders
ls
cd folder4
sign_in a3 pa3
sign_out
rename_user user8 <function generate_user at 0x027087F0>
show_folders
sign_in user3 pass3
pwd
ls
help show_items
register_admin user5 pass5
help create_folder
whoami
sign_in a1 pa1
add_item_property item2 key2=val6 key4=val6 key7=val3 key2=val6 
sign_out
add_item item2 key7=val1 key1=val5 key1=val3 key7=val8 
whoami
show_folders
register_admin user5 pass5
add_item_property item4 key6=val6 key3=val4 key7=val4 key6=val5 
show_item_properties item1
register_user user2 pass2
show_users
put item2
sign_in a4 pa4
show_users
register_user user4 pass4
show_folders
show_items
show_item_properties item3
sign_in a5 pa5
cd folder5
which_group
ls_folders
show_item_properties item5
ls
cd folder1
ls_folders
show_users
help show_items
sign_in a3 pa3
current_folder
cd folder5
which_group
help cd
rename_user user5 <function generate_user at 0x027087F0>
rename_user user2 <function generate_user at 0x027087F0>
buy
ls
sign_in user4 pass4
help create_folder
show_users
create_folder folder2
sign_out
whoami
show_users
ls
show_item_properties item1
rename_user user3 <function generate_user at 0x027087F0>
pwd
register_user user6 pass6
rename_user user1 <function generate_user at 0x027087F0>
add_item_property item1 key3=val10 key8=val10 key9=val7 key9=val8 
create_folder folder3
add_item_property item4 key10=val5 key5=val4 key8=val8 key3=val3 
add_item_property item1 key5=val8 key10=val5 key4=val4 key6=val3 
rename_user user5 <function generate_user at 0x027087F0>
pwd
help add_item
ls
sign_out
rename_user user1 <function generate_user at 0x027087F0>
pwd
show_folders
whoami
pwd
sign_in a2 pa2
add_item_property item5 key10=val4 key7=val2 key10=val10 key10=val5 
put item5
pwd
show_item_properties item4
register_user user2 pass2
ls_folders
help help
register_user user1 pass1
current_folder
whoami
which_group
sign_in a5 pa5
sign_out
create_folder folder1
register_user user1 pass1
buy
sign_out
register_admin user2 pass2
current_folder
rename_user user4 <function generate_user at 0x027087F0>
buy
show_folders
whoami
current_folder
pwd
current_folder
buy
whoami
pwd
buy
buy
help show_item_properties
add_item item2 key5=val10 key10=val6 key4=val7 key1=val8 
show_users
sign_in admin admin
cd folder4
add_item_property item3 key9=val4 key1=val6 key10=val10 key2=val4 
buy
cd folder5
show_users
rename_user user8 <function generate_user at 0x027087F0>
register_admin user1 pass1
show_items
cd folder5
put item4
add_item_property item5 key9=val1 key3=val1 key1=val9 key8=val6 
add_item_property item5 key10=val8 key2=val2 key7=val4 key10=val9 
pwd
sign_in user3 pass3
ls_folders
which_group
sign_out
pwd
pwd
ls
show_item_properties item2
ls_folders
create_folder folder5
show_users
add_item item4 key4=val2 key1=val4 key2=val1 key1=val1 
ls_folders
current_folder
show_folders
put item5
current_folder
show_folders
add_item_property item4 key5=val5 key5=val1 key2=val9 key10=val10 
show_item_properties item4
add_item_property item1 key3=val3 key8=val7 key2=val1 key9=val1 
ls
register_user user1 pass1
create_folder folder3
sign_out
current_folder
current_folder
add_item item5 key5=val4 key1=val6 key10=val10 key2=val9 
put item4
put item1
sign_in user5 pass5
add_item_property item2 key10=val5 key7=val8 key7=val2 key2=val10 
create_folder folder1
put item4
pwd
cd folder4
current_folder
help rename_user
create_folder folder5
whoami
rename_user user0 <function generate_user at 0x027087F0>
buy
buy
show_items
add_item_property item5 key1=val10 key5=val4 key5=val9 key8=val10 
show_items
cd folder3
help pwd
ls_folders
sign_in user8 pass8
show_folders
whoami
cd folder1
rename_user user5 <function generate_user at 0x027087F0>
current_folder
current_folder
ls_folders
which_group
current_folder
sign_in user9 pass9
add_item item2 key10=val1 key1=val1 key1=val6 key6=val9 
pwd
whoami
add_item_property item5 key9=val10 key4=val3 key5=val2 key3=val5 
show_items
sign_in user3 pass3
which_group
add_item item5 key4=val3 key7=val3 key10=val3 key10=val5 
put item1
sign_out
show_items
sign_in a5 pa5
help help
register_user user8 pass8
whoami
ls
sign_in a3 pa3
show_folders
add_item_property item4 key7=val6 key9=val1 key8=val3 key1=val10 
ls
ls
add_item item1 key6=val1 key10=val9 key6=val1 key5=val5 
add_item_property item1 key3=val7 key8=val7 key3=val5 key4=val3 
add_item_property item1 key6=val1 key1=val2 key1=val9 key3=val9 
buy
sign_out
help view_order
show_item_properties item4
create_folder folder1
which_group
cd folder3
register_admin admin admin
sign_in user6 pass6
rename_user user4 <function generate_user at 0x027087F0>
pwd
show_users
add_item item1 key6=val7 key1=val9 key2=val3 key5=val7 
sign_in a3 pa3
show_items
show_item_properties item3
help buy
show_folders
sign_in a3 pa3
buy
ls
add_item_property item1 key1=val7 key1=val9 key6=val7 key1=val1 
register_admin user6 pass6
put item2
sign_in a4 pa4
show_item_properties item3
add_item item3 key1=val5 key3=val2 key10=val3 key9=val8 
show_folders
whoami
add_item_property item5 key2=val4 key9=val2 key1=val6 key2=val9 
add_item item2 key6=val9 key9=val3 key2=val3 key4=val2 
help history
put item3
add_item_property item4 key1=val3 key2=val5 key5=val3 key2=val5 
rename_user user3 <function generate_user at 0x027087F0>
ls_folders
whoami
register_user user1 pass1
add_item_property item5 key9=val4 key4=val7 key10=val4 key5=val3 
cd folder1
which_group
whoami
cd folder3
help current_folder
sign_out
register_user user3 pass3
show_users
show_users
register_user user6 pass6
buy
show_items
current_folder
buy
buy
add_item item1 key6=val1 key1=val2 key3=val8 key2=val5 
show_users
put item4
cd folder3
ls
sign_in a5 pa5
show_items
show_users
rename_user user4 <function generate_user at 0x027087F0>
ls
help add_item_property
which_group
show_items
buy
rename_user user2 <function generate_user at 0x027087F0>
ls_folders
show_users
current_folder
which_group
whoami
pwd
put item5
rename_user user1 <function generate_user at 0x027087F0>
ls_folders
sign_in user6 pass6
rename_user user5 <function generate_user at 0x027087F0>
help pwd
current_folder
put item5
register_admin admin admin
sign_in a2 pa2
pwd
sign_in user6 pass6
show_users
pwd
sign_in admin admin
show_users
sign_in a3 pa3
create_folder folder2
help delete_user
show_folders
register_admin user5 pass5
create_folder folder1
cd folder3
add_item item4 key9=val5 key1=val9 key1=val7 key6=val5 
rename_user user7 <function generate_user at 0x027087F0>
create_folder folder3
register_admin user7 pass7
pwd
register_user user9 pass9
ls_folders
show_users
register_admin user7 pass7
whoami
create_folder folder3
add_item_property item3 key7=val6 key9=val6 key2=val7 key9=val4 
rename_user user0 <function generate_user at 0x027087F0>
add_item_property item2 key10=val3 key10=val8 key9=val10 key3=val3 
pwd
ls
show_items
current_folder
sign_out
ls
sign_in a2 pa2
show_folders
buy
which_group
buy
create_folder folder4
show_items
sign_in user6 pass6
register_admin user3 pass3
add_item_property item3 key8=val1 key9=val4 key9=val1 key3=val7 
add_item_property item2 key3=val3 key8=val10 key5=val7 key8=val5 
sign_in a2 pa2
which_group
whoami
register_admin user1 pass1
show_items
add_item_property item4 key8=val9 key7=val5 key6=val4 key4=val3 
show_folders
pwd
cd folder2
add_item item1 key1=val3 key3=val10 key10=val10 key7=val3 
pwd
rename_user user9 <function generate_user at 0x027087F0>
put item1
cd folder3
register_user user7 pass7
show_users
show_users
add_item_property item3 key4=val1 key1=val9 key7=val5 key2=val3 
show_users
current_folder
help show_folders
show_item_properties item5
cd folder4
add_item item3 key7=val2 key6=val5 key3=val3 key2=val6 
whoami
current_folder
show_item_properties item3
ls
register_admin user6 pass6
sign_in user6 pass6
pwd
whoami
show_items
cd folder1
register_user user2 pass2
ls
rename_user user3 <function generate_user at 0x027087F0>
rename_user user9 <function generate_user at 0x027087F0>
sign_in a2 pa2
register_admin admin admin
ls
which_group
show_item_properties item1
show_item_properties item4
ls_folders
show_item_properties item5
show_users
add_item item2 key1=val1 key6=val8 key6=val2 key4=val4 
current_folder
show_folders
pwd
create_folder folder4
register_user user3 pass3
show_users
register_admin user5 pass5
which_group
show_item_properties item2
sign_out
show_folders
buy
create_folder folder3
add_item item4 key5=val8 key2=val7 key10=val1 key3=val4 
pwd
rename_user user0 <function generate_user at 0x027087F0>
pwd
sign_in user5 pass5
whoami
register_admin user9 pass9
show_items
show_item_properties item1
sign_in user4 pass4
register_user user3 pass3
add_item item5 key8=val9 key4=val8 key1=val5 key10=val3 
ls
cd folder5
sign_out
show_items
whoami
show_item_properties item5
pwd
show_item_properties item5
create_folder folder1
whoami
whoami
show_folders
put item3
register_admin user3 pass3
ls_folders
pwd
which_group
current_folder
add_item_property item4 key8=val4 key9=val7 key8=val1 key9=val6 
sign_in user1 pass1
register_admin admin admin
put item3
show_users
sign_out
whoami
show_items
whoami
ls_folders
help current_folder
cd folder2
sign_in a1 pa1
whoami
ls
sign_out
add_item_property item4 key3=val5 key2=val1 key4=val5 key5=val5 
add_item_property item4 key6=val10 key2=val1 key6=val4 key5=val6 
show_folders
ls_folders
show_items
sign_in user9 pass9
register_user user1 pass1
current_folder
cd folder4
show_item_properties item1
show_item_properties item5
whoami
sign_out
whoami
buy
register_admin user5 pass5
sign_in a2 pa2
create_folder folder5
current_folder
which_group
show_users
show_folders
show_items
rename_user user0 <function generate_user at 0x027087F0>
cd folder5
put item2
show_item_properties item2
buy
show_folders
which_group
whoami
whoami
whoami
ls_folders
sign_out
register_admin user4 pass4
pwd
add_item item5 key1=val10 key3=val2 key5=val5 key2=val5 
help exit
create_folder folder4
sign_in user6 pass6
sign_out
show_item_properties item5
show_items
show_items
ls
ls_folders
show_users
show_item_properties item3
buy
add_item item1 key8=val2 key1=val3 key4=val9 key2=val8 
whoami
cd folder2
current_folder
which_group
sign_out
pwd
help register_admin
show_folders
buy
which_group
current_folder
add_item_property item1 key8=val8 key2=val7 key4=val10 key10=val4 
sign_in admin admin
sign_out
show_item_properties item1
sign_out
sign_in admin admin
ls_folders
register_user user4 pass4
add_item_property item4 key9=val3 key5=val10 key4=val9 key10=val8 
show_folders
sign_out
put item5
rename_user user9 <function generate_user at 0x027087F0>
help pwd
put item3
which_group
sign_out
register_user user5 pass5
create_folder folder4
whoami
current_folder
ls
register_admin admin admin
pwd
show_item_properties item1
sign_in user5 pass5
ls_folders
add_item_property item1 key5=val1 key8=val8 key10=val3 key2=val8 
rename_user user2 <function generate_user at 0x027087F0>
pwd
which_group
register_admin user4 pass4
show_users
register_user user2 pass2
rename_user user8 <function generate_user at 0x027087F0>
add_item_property item4 key5=val4 key8=val1 key3=val7 key3=val5 
register_user user8 pass8
add_item_property item1 key2=val1 key4=val3 key4=val5 key2=val8 
show_users
register_user user3 pass3
sign_out
register_admin user4 pass4
show_folders
show_item_properties item4
register_admin user9 pass9
cd folder2
current_folder
show_folders
sign_in a4 pa4
show_folders
current_folder
sign_out
show_item_properties item3
current_folder
ls
show_item_properties item4
whoami
put item3
cd folder1
show_users
pwd
register_admin admin admin
sign_in user3 pass3
rename_user user1 <function generate_user at 0x027087F0>
show_items
buy
show_folders
sign_in user1 pass1
sign_in user3 pass3
whoami
whoami
add_item_property item5 key9=val9 key3=val2 key9=val5 key5=val5 
help view_order
show_users
sign_in a5 pa5
show_item_properties item5
sign_in user4 pass4
ls
put item5
sign_in user7 pass7
show_item_properties item4
sign_in a2 pa2
cd folder1
cd folder2
create_folder folder4
sign_in user7 pass7
sign_in a2 pa2
buy
put item1
cd folder3
whoami
pwd
show_items
sign_in user9 pass9
which_group
rename_user user4 <function generate_user at 0x027087F0>
ls_folders
cd folder5
pwd
sign_in a2 pa2
put item1
cd folder4
register_admin user7 pass7
create_folder folder2
ls
current_folder
put item4
sign_in a3 pa3
sign_in user3 pass3
buy
add_item_property item2 key3=val4 key8=val3 key5=val6 key10=val6 
ls
buy
ls
sign_out
rename_user user1 <function generate_user at 0x027087F0>
sign_out
ls
put item2
show_items
sign_in a1 pa1
add_item_property item1 key2=val6 key4=val2 key3=val8 key10=val5 
show_items
sign_out
add_item item1 key2=val3 key7=val4 key4=val9 key2=val3 
put item4
show_item_properties item3
help sign_in
show_folders
sign_in a4 pa4
sign_in a5 pa5
register_admin user8 pass8
cd folder4
show_users
show_item_properties item4
show_folders
buy
show_items
show_folders
create_folder folder2
sign_in a1 pa1
register_admin user6 pass6
add_item_property item2 key1=val10 key1=val5 key2=val1 key5=val5 
register_user user2 pass2
rename_user user2 <function generate_user at 0x027087F0>
pwd
register_admin user3 pass3
add_item item1 key9=val4 key8=val10 key5=val8 key1=val5 
put item3
current_folder
which_group
current_folder
show_items
sign_in user6 pass6
help exit
current_folder
add_item_property item1 key8=val1 key7=val9 key3=val5 key7=val4 
ls_folders
create_folder folder3
ls
rename_user user0 <function generate_user at 0x027087F0>
sign_out
pwd
sign_in user4 pass4
cd folder3
ls_folders
current_folder
put item1
sign_in user3 pass3
ls
current_folder
ls_folders
ls_folders
show_item_properties item3
cd folder1
register_admin user8 pass8
create_folder folder1
add_item_property item1 key8=val9 key6=val1 key7=val8 key3=val2 
put item2
register_user user6 pass6
pwd
show_items
pwd
show_folders
current_folder
sign_in user9 pass9
help show_folders
which_group
buy
add_item item5 key1=val6 key4=val8 key3=val4 key2=val9 
show_folders
whoami
register_user user9 pass9
buy
current_folder
help view_order
show_folders
help history
rename_user user4 <function generate_user at 0x027087F0>
cd folder2
show_folders
show_folders
show_items
cd folder4
whoami
rename_user user6 <function generate_user at 0x027087F0>
register_user user3 pass3
rename_user user4 <function generate_user at 0x027087F0>
ls
sign_in a1 pa1
add_item_property item2 key8=val2 key3=val2 key8=val4 key8=val4 
current_folder
current_folder
rename_user user0 <function generate_user at 0x027087F0>
pwd
ls
which_group
show_users
sign_out
sign_in user9 pass9
which_group
register_user user4 pass4
add_item_property item1 key10=val3 key9=val4 key10=val8 key1=val5 
ls
sign_out
register_admin user4 pass4
show_users
which_group
sign_out
add_item_property item3 key8=val5 key5=val5 key6=val2 key8=val7 
whoami
add_item_property item2 key10=val10 key2=val1 key9=val8 key6=val7 
sign_in a5 pa5
pwd
current_folder
whoami
put item5
show_items
add_item_property item1 key4=val1 key4=val6 key6=val4 key7=val4 
pwd
help sign_out
show_users
current_folder
cd folder1
rename_user user0 <function generate_user at 0x027087F0>
cd folder4
ls_folders
show_folders
create_folder folder4
ls_folders
sign_in user8 pass8
add_item item1 key9=val5 key2=val9 key7=val7 key1=val6 
register_admin user4 pass4
whoami
ls_folders
which_group
show_folders
ls
sign_in a1 pa1
rename_user user8 <function generate_user at 0x027087F0>
add_item_property item2 key10=val5 key6=val10 key6=val5 key6=val6 
add_item item1 key10=val10 key2=val8 key9=val5 key7=val7 
whoami
add_item_property item3 key2=val9 key4=val8 key10=val7 key7=val3 
pwd
put item2
help sign_in
add_item_property item1 key4=val9 key5=val3 key9=val7 key8=val2 
add_item_property item2 key9=val10 key2=val6 key2=val1 key1=val3 
rename_user user4 <function generate_user at 0x027087F0>
add_item item4 key8=val3 key5=val6 key3=val2 key6=val8 
sign_out
ls_folders
whoami
create_folder folder5
help show_items
show_item_properties item1
create_folder folder4
ls
register_user user8 pass8
cd folder4
put item4
show_folders
put item3
put item5
ls
show_items
sign_in user8 pass8
sign_in a4 pa4
add_item_property item5 key10=val4 key8=val3 key3=val5 key8=val5 
rename_user user8 <function generate_user at 0x027087F0>
ls
ls_folders
cd folder2
show_folders
show_item_properties item2
rename_user user1 <function generate_user at 0x027087F0>
register_user admin admin
pwd
create_folder folder5
rename_user user1 <function generate_user at 0x027087F0>
put item5
cd folder1
show_item_properties item3
sign_in user4 pass4
whoami
sign_out
create_folder folder4
ls
help history
register_user user6 pass6
which_group
show_items
show_folders
create_folder folder1
register_user user9 pass9
add_item item4 key7=val6 key2=val9 key1=val7 key2=val1 
rename_user user7 <function generate_user at 0x027087F0>
help ls
rename_user user3 <function generate_user at 0x027087F0>
put item2
which_group
buy
whoami
create_folder folder2
which_group
ls_folders
add_item item2 key3=val3 key3=val6 key2=val6 key5=val5 
add_item_property item3 key9=val7 key10=val2 key4=val6 key3=val7 
create_folder folder3
add_item_property item5 key8=val3 key2=val8 key5=val10 key1=val6 
add_item_property item2 key4=val9 key9=val5 key9=val7 key6=val3 
sign_in a5 pa5
create_folder folder5
ls_folders
which_group
help exit
help ls_folders
ls_folders
which_group
register_user user9 pass9
add_item item1 key7=val8 key9=val1 key5=val1 key8=val10 
register_user user7 pass7
put item3
create_folder folder1
add_item item2 key6=val10 key10=val10 key3=val5 key2=val10 
sign_in a2 pa2
pwd
buy
sign_out
help cd
register_user user5 pass5
which_group
pwd
show_users
sign_in a1 pa1
show_folders
ls_folders
ls
show_item_properties item5
whoami
show_folders
sign_in a2 pa2
whoami
ls
cd folder1
register_admin user6 pass6
show_users
sign_in a4 pa4
pwd
register_admin user3 pass3
sign_in a1 pa1
register_user user5 pass5
register_admin user8 pass8
add_item_property item2 key10=val2 key5=val9 key1=val9 key9=val8 
ls_folders
which_group
register_admin admin admin
show_users
add_item item5 key10=val3 key8=val4 key2=val8 key9=val6 
help whoami
which_group
sign_in user7 pass7
whoami
current_folder
whoami
register_admin user2 pass2
whoami
show_item_properties item4
add_item item2 key7=val2 key9=val2 key1=val1 key1=val10 
register_user admin admin
sign_out
put item1
which_group
create_folder folder1
cd folder2
help rename_user
buy
current_folder
show_users
current_folder
create_folder folder3
help register_admin
show_folders
rename_user user9 <function generate_user at 0x027087F0>
ls_folders
show_folders
whoami
register_user user8 pass8
put item3
pwd
put item3
register_user user5 pass5
show_items
sign_out
register_user user3 pass3
help add_item_property
register_admin user5 pass5
create_folder folder1
show_items
show_item_properties item2
sign_out
rename_user user6 <function generate_user at 0x027087F0>
ls_folders
add_item item5 key2=val3 key9=val3 key8=val7 key4=val2 
ls_folders
help current_folder
add_item_property item1 key10=val10 key6=val8 key3=val1 key8=val4 
register_user admin admin
add_item_property item3 key2=val7 key10=val8 key10=val5 key1=val7 
create_folder folder1
whoami
create_folder folder1
show_folders
sign_out
show_users
buy
show_item_properties item2
ls_folders
cd folder2
show_users
ls
ls
which_group
rename_user user7 <function generate_user at 0x027087F0>
cd folder1
show_item_properties item5
show_users
show_folders
register_user user7 pass7
sign_in user9 pass9
ls
add_item_property item3 key6=val9 key10=val6 key8=val5 key4=val9 
show_items
sign_out
sign_in a1 pa1
buy
register_admin user2 pass2
register_user user7 pass7
ls
show_users
current_folder
add_item_property item3 key8=val10 key3=val2 key2=val4 key2=val10 
show_item_properties item1
add_item_property item4 key1=val10 key5=val7 key6=val8 key10=val5 
show_users
show_folders
sign_out
rename_user user1 <function generate_user at 0x027087F0>
current_folder
add_item item1 key2=val6 key1=val7 key1=val6 key4=val9 
which_group
sign_in a3 pa3
which_group
put item2
add_item item5 key9=val1 key10=val3 key6=val8 key6=val8 
whoami
whoami
show_users
pwd
ls
current_folder
which_group
ls
show_folders
buy
add_item_property item5 key10=val7 key7=val3 key5=val4 key5=val8 
sign_in a2 pa2
sign_in a3 pa3
current_folder
show_users
ls_folders
show_users
add_item item5 key8=val8 key6=val2 key6=val6 key3=val7 
add_item_property item2 key8=val3 key2=val9 key4=val7 key3=val3 
show_item_properties item2
which_group
show_folders
put item3
sign_out
show_items
which_group
pwd
show_users
show_items
current_folder
show_items
add_item_property item1 key4=val7 key8=val1 key10=val10 key9=val2 
ls_folders
rename_user user2 <function generate_user at 0x027087F0>
put item3
pwd
current_folder
add_item item5 key7=val5 key6=val9 key10=val8 key1=val2 
which_group
register_admin user1 pass1
register_admin user6 pass6
ls
pwd
ls_folders
show_items
sign_in admin admin
sign_in a5 pa5
show_users
pwd
sign_in user4 pass4
register_user user9 pass9
sign_in user3 pass3
current_folder
cd folder1
sign_in a2 pa2
create_folder folder4
register_user user6 pass6
ls_folders
current_folder
add_item item3 key6=val4 key5=val5 key7=val4 key4=val8 
show_folders
current_folder
ls
show_items
show_users
add_item_property item3 key10=val7 key8=val7 key6=val8 key3=val3 
create_folder folder1
add_item_property item5 key3=val3 key5=val6 key6=val2 key4=val4 
add_item_property item4 key9=val1 key9=val2 key4=val9 key7=val1 
rename_user user4 <function generate_user at 0x027087F0>
cd folder5
show_folders
show_folders
buy
register_admin user6 pass6
current_folder
add_item item5 key4=val2 key7=val4 key6=val10 key2=val3 
whoami
whoami
sign_out
register_admin user7 pass7
ls
cd folder3
register_admin user4 pass4
sign_in user4 pass4
pwd
whoami
sign_out
show_items
add_item item1 key3=val10 key2=val2 key3=val7 key2=val8 
ls_folders
add_item_property item4 key5=val9 key4=val7 key5=val10 key6=val1 
put item2
add_item_property item1 key10=val2 key9=val6 key7=val8 key6=val6 
show_items
show_items
buy
whoami
show_folders
sign_in user7 pass7
add_item_property item5 key8=val4 key9=val5 key8=val2 key9=val6 
show_folders
ls_folders
create_folder folder1
sign_out
show_items
show_users
sign_out
sign_in a2 pa2
sign_in user8 pass8
cd folder5
which_group
show_users
create_folder folder3
show_folders
add_item item5 key4=val5 key1=val7 key10=val3 key6=val1 
rename_user user7 <function generate_user at 0x027087F0>
put item1
buy
show_items
register_user user5 pass5
pwd
buy
create_folder folder4
create_folder folder1
sign_in a4 pa4
cd folder3
sign_in a3 pa3
ls_folders
pwd
buy
cd folder1
rename_user user7 <function generate_user at 0x027087F0>
show_users
add_item item3 key4=val4 key4=val6 key3=val9 key10=val1 
sign_in a1 pa1
ls_folders
show_items
show_users
help put
whoami
sign_out
show_users
register_admin admin admin
register_admin user9 pass9
register_user user3 pass3
which_group
help sign_out
pwd
rename_user user7 <function generate_user at 0x027087F0>
show_folders
add_item item3 key2=val7 key9=val3 key5=val3 key4=val6 
rename_user user7 <function generate_user at 0x027087F0>
sign_in a1 pa1
sign_out
sign_out
register_user user4 pass4
show_item_properties item5
register_admin user5 pass5
put item2
create_folder folder3
add_item item5 key1=val3 key1=val6 key3=val4 key8=val10 
buy
help cd
whoami
register_admin user8 pass8
add_item_property item3 key9=val3 key2=val6 key5=val8 key7=val5 
show_folders
show_item_properties item3
buy
which_group
buy
add_item_property item2 key3=val10 key10=val8 key10=val2 key10=val4 
help whoami
sign_in a3 pa3
current_folder
cd folder1
ls_folders
help sign_in
whoami
sign_in a2 pa2
add_item item2 key7=val8 key8=val5 key7=val6 key9=val7 
show_users
show_items
sign_out
put item2
buy
rename_user user4 <function generate_user at 0x027087F0>
ls_folders
cd folder3
register_user user9 pass9
cd folder1
show_items
show_users
sign_in a4 pa4
ls
help add_item
sign_out
sign_in a2 pa2
add_item item1 key1=val6 key10=val6 key5=val10 key10=val5 
cd folder1
show_items
sign_in user8 pass8
sign_out
show_items
whoami
register_user user2 pass2
help add_item
show_items
ls
rename_user user1 <function generate_user at 0x027087F0>
show_users
register_user user8 pass8
whoami
show_folders
register_admin user7 pass7
register_user user9 pass9
sign_out
put item4
show_item_properties item2
ls_folders
show_items
put item3
create_folder folder1
add_item item5 key1=val2 key2=val2 key9=val2 key2=val8 
sign_out
current_folder
create_folder folder3
sign_in a1 pa1
help buy
help register_user
register_user user7 pass7
rename_user user5 <function generate_user at 0x027087F0>
cd folder3
create_folder folder2
register_admin user9 pass9
show_folders
current_folder
ls
rename_user user3 <function generate_user at 0x027087F0>
put item4
ls_folders
show_item_properties item2
buy
show_folders
sign_in a4 pa4
register_user user5 pass5
show_folders
cd folder5
buy
show_users
rename_user user5 <function generate_user at 0x027087F0>
sign_out
show_items
help cd
show_folders
current_folder
put item3
ls
sign_in a2 pa2
whoami
add_item item1 key10=val8 key8=val4 key6=val1 key6=val5 
ls_folders
register_admin user9 pass9
help cd
register_admin user3 pass3
ls
sign_in admin admin
sign_out
help show_users
register_admin user7 pass7
show_item_properties item2
pwd
rename_user user5 <function generate_user at 0x027087F0>
ls_folders
add_item_property item5 key9=val9 key9=val4 key8=val8 key3=val7 
put item3
sign_in user4 pass4
show_items
register_user user1 pass1
current_folder
sign_out
add_item_property item2 key2=val7 key6=val5 key9=val4 key10=val9 
ls_folders
sign_in user6 pass6
cd folder2
ls
rename_user user2 <function generate_user at 0x027087F0>
whoami
show_users
create_folder folder2
ls_folders
show_item_properties item3
ls_folders
buy
add_item item3 key3=val3 key10=val5 key8=val1 key5=val4 
current_folder
register_admin user5 pass5
show_item_properties item2
buy
whoami
put item2
add_item item2 key8=val6 key8=val9 key7=val3 key9=val4 
register_admin user2 pass2
register_admin user5 pass5
rename_user user4 <function generate_user at 0x027087F0>
add_item_property item1 key2=val9 key8=val1 key10=val3 key9=val5 
sign_in user1 pass1
register_admin user6 pass6
sign_in a5 pa5
rename_user user9 <function generate_user at 0x027087F0>
buy
pwd
ls_folders
pwd
help show_users
whoami
help create_folder
which_group
add_item item5 key4=val6 key9=val3 key1=val8 key3=val1 
ls_folders
cd folder4
sign_in a1 pa1
show_items
cd folder3
ls
ls
which_group
ls
rename_user user1 <function generate_user at 0x027087F0>
ls_folders
rename_user user5 <function generate_user at 0x027087F0>
put item3
whoami
sign_in user2 pass2
register_user admin admin
register_admin user6 pass6
create_folder folder4
ls_folders
put item1
sign_in user1 pass1
add_item_property item4 key9=val3 key6=val7 key4=val2 key7=val5 
add_item_property item1 key6=val8 key4=val10 key6=val9 key1=val4 
cd folder2
show_item_properties item1
sign_in a1 pa1
register_admin user9 pass9
ls
buy
pwd
show_items
sign_in user3 pass3
ls_folders
add_item item5 key8=val7 key7=val7 key2=val7 key5=val10 
register_user user8 pass8
sign_out
register_admin user5 pass5
sign_out
register_user user9 pass9
register_admin user2 pass2
show_users
whoami
pwd
put item1
cd folder2
sign_in a1 pa1
register_user user3 pass3
create_folder folder4
sign_out
register_user user2 pass2
rename_user user3 <function generate_user at 0x027087F0>
put item3
register_admin admin admin
show_items
ls_folders
sign_in user8 pass8
show_folders
which_group
sign_in a2 pa2
rename_user user1 <function generate_user at 0x027087F0>
register_user user8 pass8
add_item_property item4 key10=val2 key9=val2 key10=val5 key9=val2 
cd folder3
cd folder4
buy
whoami
register_admin user9 pass9
show_item_properties item4
pwd
sign_out
ls_folders
sign_in a2 pa2
rename_user user2 <function generate_user at 0x027087F0>
create_folder folder1
pwd
add_item item2 key2=val2 key1=val4 key6=val5 key6=val8 
show_users
ls_folders
show_items
add_item item1 key2=val2 key10=val7 key9=val2 key10=val4 
show_users
add_item item4 key4=val5 key1=val3 key10=val2 key6=val9 
put item2
show_users
show_users
current_folder
register_user user3 pass3
add_item item5 key7=val1 key2=val6 key5=val9 key6=val6 
create_folder folder1
current_folder
register_admin user3 pass3
cd folder3
whoami
register_admin user5 pass5
ls_folders
sign_in a1 pa1
show_items
sign_in a3 pa3
pwd
sign_in user3 pass3
create_folder folder5
register_user user1 pass1
help add_item
show_users
sign_out
whoami
add_item item5 key8=val10 key3=val3 key8=val8 key7=val2 
whoami
sign_out
add_item_property item4 key5=val9 key5=val4 key3=val5 key6=val2 
cd folder4
which_group
add_item item1 key3=val2 key5=val1 key7=val6 key1=val10 
ls_folders
current_folder
rename_user user9 <function generate_user at 0x027087F0>
sign_out
cd folder4
add_item item5 key8=val8 key10=val3 key9=val10 key1=val1 
add_item item2 key2=val3 key2=val6 key9=val2 key6=val1 
register_user user7 pass7
show_folders
add_item_property item4 key7=val7 key9=val5 key9=val4 key4=val8 
buy
whoami
pwd
add_item item4 key3=val7 key8=val5 key2=val4 key8=val1 
help show_users
add_item_property item1 key1=val7 key9=val1 key7=val6 key3=val10 
buy
which_group
ls_folders
pwd
which_group
whoami
create_folder folder3
put item2
which_group
which_group
show_users
register_user user1 pass1
buy
whoami
current_folder
whoami
show_item_properties item1
show_users
ls_folders
put item2
register_admin user9 pass9
put item3
ls_folders
sign_in a3 pa3
put item3
show_folders
show_folders
which_group
buy
whoami
ls_folders
buy
sign_in a1 pa1
show_users
show_users
ls
register_admin user4 pass4
add_item item5 key6=val1 key10=val2 key1=val4 key8=val2 
register_admin user2 pass2
add_item_property item5 key5=val3 key4=val10 key8=val1 key9=val4 
show_item_properties item5
current_folder
current_folder
register_admin user5 pass5
register_admin user1 pass1
cd folder4
rename_user user7 <function generate_user at 0x027087F0>
add_item item2 key5=val3 key9=val5 key8=val1 key9=val10 
sign_in a1 pa1
show_folders
show_items
show_users
add_item_property item1 key2=val6 key10=val3 key10=val3 key6=val2 
ls
put item4
put item5
cd folder4
pwd
sign_out
show_users
pwd
rename_user user2 <function generate_user at 0x027087F0>
rename_user user8 <function generate_user at 0x027087F0>
put item1
show_item_properties item5
show_item_properties item5
sign_out
show_items
ls
help pwd
sign_out
which_group
show_items
ls_folders
show_item_properties item5
register_user user9 pass9
buy
create_folder folder3
show_folders
pwd
add_item_property item4 key5=val2 key5=val9 key8=val5 key9=val8 
create_folder folder4
rename_user user9 <function generate_user at 0x027087F0>
sign_out
add_item_property item4 key6=val3 key3=val2 key7=val10 key2=val5 
which_group
buy
ls_folders
which_group
ls_folders
buy
register_user user2 pass2
ls
sign_in user9 pass9
ls
show_item_properties item4
register_admin user3 pass3
create_folder folder2
rename_user user3 <function generate_user at 0x027087F0>
cd folder4
sign_in user2 pass2
whoami
create_folder folder3
sign_out
pwd
add_item item2 key7=val9 key7=val9 key1=val7 key5=val4 
whoami
rename_user user0 <function generate_user at 0x027087F0>
show_users
which_group
pwd
which_group
add_item_property item3 key3=val3 key3=val7 key6=val8 key10=val9 
register_user user8 pass8
sign_in admin admin
sign_out
show_items
sign_in admin admin
current_folder
help delete_user
register_admin user6 pass6
pwd
sign_in user8 pass8
register_user user4 pass4
register_user user8 pass8
ls_folders
help view_order
sign_in a3 pa3
sign_in user5 pass5
sign_out
which_group
whoami
show_folders
show_folders
sign_in a1 pa1
rename_user user1 <function generate_user at 0x027087F0>
register_user user3 pass3
create_folder folder3
current_folder
current_folder
current_folder
which_group
show_items
create_folder folder3
add_item_property item2 key6=val8 key2=val7 key10=val4 key4=val8 
register_user user8 pass8
sign_in user8 pass8
whoami
sign_in admin admin
whoami
sign_out
sign_out
sign_in user1 pass1
sign_in a2 pa2
put item3
pwd
ls_folders
show_users
show_users
ls_folders
show_items
register_user admin admin
register_user user6 pass6
create_folder folder3
cd folder1
show_folders
put item3
add_item_property item4 key9=val1 key5=val10 key1=val2 key2=val7 
rename_user user2 <function generate_user at 0x027087F0>
rename_user user5 <function generate_user at 0x027087F0>
help pwd
help history
which_group
show_users
show_users
ls_folders
rename_user user2 <function generate_user at 0x027087F0>
sign_in a3 pa3
cd folder3
put item3
ls_folders
put item2
buy
create_folder folder5
pwd
rename_user user7 <function generate_user at 0x027087F0>
buy
sign_in a3 pa3
rename_user user7 <function generate_user at 0x027087F0>
ls
ls
put item1
show_users
ls
add_item_property item3 key4=val9 key2=val1 key2=val6 key2=val2 
ls_folders
register_user user4 pass4
show_users
cd folder2
buy
put item1
ls_folders
register_user user5 pass5
sign_in user7 pass7
show_item_properties item1
register_admin user4 pass4
whoami
help show_items
which_group
pwd
show_users
sign_in user9 pass9
put item3
ls_folders
whoami
sign_out
buy
create_folder folder5
current_folder
which_group
create_folder folder2
which_group
pwd
add_item item3 key5=val6 key3=val3 key9=val3 key2=val8 
whoami
sign_in a2 pa2
rename_user user0 <function generate_user at 0x027087F0>
show_users
sign_in user9 pass9
ls
pwd
rename_user user3 <function generate_user at 0x027087F0>
create_folder folder2
add_item item2 key4=val4 key9=val1 key3=val10 key2=val3 
ls
current_folder
help which_group
show_folders
show_item_properties item3
register_admin user2 pass2
which_group
whoami
register_user user6 pass6
create_folder folder5
put item4
register_admin user3 pass3
put item3
create_folder folder3
whoami
ls_folders
current_folder
whoami
sign_out
current_folder
add_item_property item4 key10=val2 key8=val8 key6=val2 key7=val2 
show_item_properties item2
rename_user user4 <function generate_user at 0x027087F0>
sign_in user2 pass2
whoami
sign_in a1 pa1
add_item_property item3 key3=val3 key2=val10 key10=val10 key4=val5 
cd folder3
pwd
ls_folders
register_admin user2 pass2
create_folder folder2
ls_folders
ls_folders
sign_in a4 pa4
current_folder
show_item_properties item4
show_items
buy
sign_out
add_item_property item5 key7=val9 key7=val5 key5=val5 key4=val2 
cd folder1
which_group
show_folders
show_item_properties item4
sign_out
sign_in user8 pass8
show_folders
show_items
show_folders
whoami
whoami
put item2
which_group
show_item_properties item1
ls
ls_folders
ls
sign_out
sign_out
sign_out
create_folder folder3
show_item_properties item4
sign_in a3 pa3
show_users
put item4
show_item_properties item5
sign_in user5 pass5
sign_in a2 pa2
which_group
show_users
sign_out
ls
buy
register_admin user4 pass4
show_folders
whoami
sign_out
whoami
sign_in user9 pass9
cd folder2
which_group
register_user user6 pass6
show_folders
current_folder
pwd
register_user user9 pass9
buy
sign_in user7 pass7
sign_out
show_users
add_item_property item5 key1=val3 key2=val1 key2=val7 key10=val1 
sign_in a4 pa4
add_item_property item3 key7=val5 key8=val5 key8=val5 key4=val1 
add_item_property item4 key3=val10 key4=val2 key9=val1 key5=val1 
ls
add_item_property item4 key1=val7 key2=val9 key8=val5 key5=val8 
ls_folders
put item5
pwd
create_folder folder2
sign_in a1 pa1
cd folder3
put item2
register_user user2 pass2
sign_out
create_folder folder5
ls
sign_in user7 pass7
sign_out
ls_folders
show_item_properties item2
sign_in admin admin
register_user user6 pass6
register_admin user2 pass2
add_item item4 key6=val8 key3=val7 key4=val10 key4=val8 
put item2
sign_out
show_folders
pwd
whoami
cd folder5
register_admin user5 pass5
sign_in a5 pa5
show_item_properties item5
add_item_property item2 key10=val3 key1=val2 key2=val4 key5=val10 
show_items
show_users
show_items
ls
add_item_property item1 key1=val7 key6=val2 key1=val7 key2=val8 
current_folder
register_user user6 pass6
buy
add_item_property item1 key1=val6 key10=val3 key1=val4 key3=val4 
register_admin user6 pass6
register_admin user9 pass9
add_item_property item3 key1=val3 key10=val5 key2=val6 key8=val1 
show_item_properties item3
whoami
sign_out
put item1
create_folder folder4
sign_out
whoami
cd folder2
create_folder folder1
ls_folders
help buy
whoami
buy
show_folders
sign_in a3 pa3
ls
sign_in a1 pa1
show_folders
register_user user8 pass8
sign_in a2 pa2
buy
cd folder1
ls_folders
sign_in a3 pa3
register_admin user4 pass4
ls_folders
show_items
rename_user user4 <function generate_user at 0x027087F0>
show_items
rename_user user3 <function generate_user at 0x027087F0>
put item4
which_group
help exit
buy
show_folders
current_folder
add_item item1 key10=val9 key2=val9 key10=val5 key8=val1 
show_folders
register_user user8 pass8
which_group
sign_in user2 pass2
sign_out
sign_in a1 pa1
show_item_properties item3
register_admin user1 pass1
sign_in a1 pa1
rename_user user8 <function generate_user at 0x027087F0>
sign_in user3 pass3
show_folders
buy
show_items
show_items
show_users
current_folder
current_folder
create_folder folder2
pwd
show_item_properties item4
ls
add_item_property item2 key7=val5 key1=val9 key1=val6 key6=val5 
help register_user
show_folders
cd folder1
help which_group
show_folders
rename_user user0 <function generate_user at 0x027087F0>
sign_out
register_admin user5 pass5
add_item item2 key2=val6 key3=val9 key3=val1 key7=val3 
add_item item4 key3=val6 key9=val9 key5=val7 key5=val1 
show_users
ls_folders
put item5
show_folders
show_items
buy
put item1
show_item_properties item5
create_folder folder1
whoami
rename_user user4 <function generate_user at 0x027087F0>
ls
register_admin user4 pass4
ls
which_group
sign_in a5 pa5
register_user user6 pass6
current_folder
sign_in user1 pass1
help ls
ls_folders
show_item_properties item3
whoami
show_items
show_item_properties item5
sign_in user7 pass7
show_folders
put item1
sign_out
create_folder folder4
sign_in a1 pa1
current_folder
help show_item_properties
which_group
put item1
ls_folders
sign_out
sign_out
show_users
cd folder2
ls_folders
cd folder5
create_folder folder2
pwd
create_folder folder2
show_items
register_admin user5 pass5
create_folder folder5
sign_in a2 pa2
whoami
sign_out
sign_out
add_item_property item4 key3=val5 key2=val7 key5=val9 key10=val4 
register_user user7 pass7
ls_folders
help create_folder
create_folder folder1
put item1
ls_folders
rename_user user4 <function generate_user at 0x027087F0>
add_item_property item2 key9=val10 key1=val5 key6=val7 key1=val7 
which_group
show_users
pwd
whoami
show_folders
buy
show_items
create_folder folder4
ls
whoami
buy
whoami
rename_user user4 <function generate_user at 0x027087F0>
sign_out
create_folder folder3
whoami
register_admin user1 pass1
sign_in admin admin
current_folder
help current_folder
show_items
pwd
show_items
ls
pwd
current_folder
sign_in user4 pass4
cd folder2
ls
register_admin user1 pass1
put item2
show_users
cd folder1
add_item item4 key8=val10 key5=val7 key9=val1 key8=val5 
show_items
help which_group
ls
create_folder folder2
rename_user user8 <function generate_user at 0x027087F0>
create_folder folder5
show_item_properties item2
show_folders
whoami
help view_order
show_folders
current_folder
whoami
whoami
pwd
cd folder1
ls
sign_in user1 pass1
show_users
register_admin user1 pass1
whoami
current_folder
ls_folders
add_item_property item4 key2=val8 key10=val4 key1=val9 key4=val3 
sign_in user4 pass4
pwd
put item3
ls_folders
add_item_property item4 key5=val7 key5=val10 key10=val8 key7=val2 
create_folder folder4
add_item_property item2 key4=val9 key3=val8 key5=val5 key4=val9 
whoami
rename_user user6 <function generate_user at 0x027087F0>
put item1
register_admin user4 pass4
register_user user9 pass9
create_folder folder3
add_item item4 key3=val8 key7=val5 key10=val9 key8=val5 
show_items
register_admin user2 pass2
ls
ls_folders
create_folder folder4
sign_out
ls
sign_in a3 pa3
show_items
show_items
add_item item1 key5=val6 key3=val7 key1=val3 key5=val6 
add_item_property item5 key5=val8 key3=val4 key6=val1 key5=val3 
show_users
sign_in user1 pass1
sign_in a2 pa2
buy
create_folder folder2
sign_in user7 pass7
show_folders
add_item item1 key2=val6 key3=val10 key4=val2 key5=val9 
register_user user5 pass5
show_item_properties item5
ls
ls_folders
current_folder
ls_folders
add_item item1 key1=val7 key3=val1 key5=val2 key4=val8 
which_group
ls
rename_user user8 <function generate_user at 0x027087F0>
put item1
pwd
register_user user1 pass1
help show_users
add_item_property item3 key9=val7 key9=val7 key6=val5 key9=val1 
which_group
ls
show_folders
sign_out
buy
cd folder2
rename_user user3 <function generate_user at 0x027087F0>
which_group
sign_out
ls
ls_folders
cd folder2
put item5
ls_folders
show_folders
add_item item1 key4=val2 key7=val2 key1=val9 key6=val10 
sign_in a5 pa5
buy
help create_folder
show_items
current_folder
sign_in user5 pass5
show_users
cd folder1
put item4
which_group
cd folder1
rename_user user2 <function generate_user at 0x027087F0>
cd folder2
sign_out
add_item_property item3 key1=val7 key9=val10 key3=val10 key10=val3 
show_item_properties item1
show_items
buy
sign_out
sign_in user2 pass2
which_group
which_group
ls_folders
sign_in a1 pa1
show_item_properties item4
put item2
create_folder folder1
add_item item2 key3=val4 key10=val3 key1=val9 key1=val8 
ls
put item3
show_folders
add_item item2 key9=val9 key6=val4 key3=val2 key4=val8 
add_item_property item3 key3=val5 key4=val9 key1=val9 key5=val1 
show_item_properties item4
show_users
ls_folders
add_item_property item1 key10=val6 key7=val8 key4=val3 key1=val8 
sign_in user3 pass3
current_folder
sign_in user1 pass1
add_item_property item2 key8=val3 key7=val3 key3=val2 key7=val8 
register_user user4 pass4
pwd
add_item_property item1 key5=val1 key5=val3 key3=val7 key4=val7 
which_group
which_group
which_group
which_group
sign_in a4 pa4
add_item_property item2 key1=val9 key9=val6 key6=val5 key2=val8 
rename_user user4 <function generate_user at 0x027087F0>
show_items
sign_in a1 pa1
buy
register_admin user3 pass3
sign_in a2 pa2
help sign_out
current_folder
register_admin user1 pass1
sign_in user7 pass7
add_item_property item5 key2=val8 key2=val9 key6=val1 key3=val3 
ls_folders
current_folder
help sign_in
cd folder5
show_items
put item5
rename_user user2 <function generate_user at 0x027087F0>
put item2
cd folder1
add_item_property item4 key8=val4 key3=val5 key8=val6 key6=val5 
ls_folders
ls
ls_folders
show_item_properties item5
show_items
whoami
register_admin user6 pass6
help register_admin
ls_folders
sign_in a5 pa5
add_item item5 key2=val7 key8=val9 key1=val2 key3=val7 
current_folder
rename_user user1 <function generate_user at 0x027087F0>
cd folder4
sign_in user9 pass9
put item5
add_item item3 key2=val10 key3=val7 key7=val4 key1=val9 
show_items
buy
current_folder
create_folder folder3
sign_in user6 pass6
put item5
show_users
ls_folders
rename_user user5 <function generate_user at 0x027087F0>
pwd
sign_in user4 pass4
show_items
ls
current_folder
sign_in a1 pa1
show_users
show_item_properties item3
show_items
sign_out
pwd
help register_user
register_admin user7 pass7
whoami
show_items
pwd
sign_in a1 pa1
show_users
ls_folders
sign_in user2 pass2
sign_in user5 pass5
sign_in user6 pass6
add_item item2 key2=val2 key1=val8 key5=val6 key9=val4 
put item4
ls
cd folder5
sign_out
show_items
register_user user9 pass9
cd folder1
sign_in user8 pass8
ls
pwd
show_users
help put
create_folder folder1
ls_folders
show_folders
sign_in user4 pass4
create_folder folder1
current_folder
rename_user user1 <function generate_user at 0x027087F0>
show_users
rename_user user9 <function generate_user at 0x027087F0>
show_users
whoami
buy
ls_folders
register_user admin admin
sign_in user1 pass1
show_users
sign_out
show_users
register_user admin admin
add_item item2 key4=val3 key2=val2 key1=val3 key8=val8 
help sign_out
ls_folders
put item1
add_item item3 key7=val7 key2=val7 key9=val9 key2=val5 
put item3
register_admin user6 pass6
cd folder3
help register_user
show_item_properties item4
show_items
ls_folders
show_items
cd folder5
show_items
show_item_properties item3
show_items
show_folders
register_user user6 pass6
pwd
sign_in a2 pa2
ls
rename_user user4 <function generate_user at 0x027087F0>
sign_in a4 pa4
buy
ls_folders
pwd
current_folder
show_folders
pwd
sign_out
register_user admin admin
add_item item2 key6=val5 key1=val5 key5=val3 key7=val8 
show_items
which_group
add_item item2 key1=val8 key3=val3 key7=val5 key10=val5 
which_group
sign_in a1 pa1
add_item item2 key10=val5 key3=val3 key2=val9 key4=val6 
sign_out
buy
whoami
ls
sign_out
current_folder
put item1
which_group
current_folder
sign_in user6 pass6
ls
help ls_folders
register_user user6 pass6
buy
whoami
put item4
register_admin admin admin
sign_in admin admin
add_item item5 key10=val6 key3=val3 key8=val5 key7=val8 
ls
create_folder folder5
show_folders
sign_out
sign_out
whoami
create_folder folder3
help buy
sign_in a1 pa1
sign_in user9 pass9
sign_in a1 pa1
ls_folders
register_user user6 pass6
register_admin user2 pass2
whoami
show_users
create_folder folder3
pwd
whoami
which_group
show_item_properties item3
whoami
sign_in a3 pa3
add_item_property item1 key4=val9 key3=val9 key7=val7 key5=val9 
rename_user user5 <function generate_user at 0x027087F0>
cd folder2
buy
show_folders
buy
sign_in user7 pass7
pwd
sign_out
help view_order
show_users
show_items
show_folders
ls_folders
buy
sign_out
create_folder folder4
show_folders
sign_in a4 pa4
rename_user user1 <function generate_user at 0x027087F0>
rename_user user2 <function generate_user at 0x027087F0>
register_user user4 pass4
sign_in user7 pass7
which_group
show_item_properties item4
cd folder5
create_folder folder1
show_users
help exit
add_item item3 key7=val10 key7=val2 key2=val9 key4=val10 
rename_user user5 <function generate_user at 0x027087F0>
add_item_property item5 key10=val6 key2=val10 key10=val6 key1=val3 
show_folders
ls
sign_in a2 pa2
create_folder folder1
ls
help view_order
show_users
sign_in a3 pa3
sign_out
add_item item3 key9=val6 key9=val3 key9=val1 key10=val3 
rename_user user1 <function generate_user at 0x027087F0>
sign_out
sign_out
register_user admin admin
current_folder
create_folder folder3
whoami
cd folder1
show_users
cd folder5
show_users
sign_out
show_users
pwd
add_item item5 key3=val4 key7=val10 key8=val5 key5=val6 
sign_in user1 pass1
show_items
show_users
help show_items
sign_out
pwd
add_item item3 key10=val5 key7=val4 key1=val9 key3=val5 
ls
show_users
which_group
which_group
which_group
current_folder
help add_item_property
current_folder
ls
show_folders
whoami
show_item_properties item5
buy
register_user user2 pass2
which_group
ls_folders
sign_in a2 pa2
add_item_property item1 key5=val6 key4=val9 key1=val8 key7=val8 
show_item_properties item4
show_users
cd folder3
put item4
show_users
sign_out
sign_in a1 pa1
show_items
whoami
rename_user user5 <function generate_user at 0x027087F0>
current_folder
which_group
help register_user
show_items
show_users
register_user user5 pass5
pwd
which_group
show_item_properties item1
help buy
add_item_property item2 key1=val10 key10=val9 key9=val2 key4=val7 
add_item_property item4 key1=val7 key8=val1 key8=val5 key4=val8 
pwd
sign_out
show_folders
show_item_properties item5
sign_in user3 pass3
put item1
sign_in user4 pass4
add_item_property item1 key4=val8 key5=val1 key5=val9 key10=val8 
cd folder4
sign_in a1 pa1
register_admin user5 pass5
current_folder
ls
sign_out
create_folder folder5
register_user user7 pass7
ls_folders
whoami
current_folder
create_folder folder4
show_items
current_folder
ls_folders
buy
create_folder folder5
rename_user user1 <function generate_user at 0x027087F0>
register_admin user2 pass2
show_users
show_item_properties item5
put item1
ls
sign_in user6 pass6
put item5
whoami
current_folder
create_folder folder1
show_items
whoami
show_folders
register_admin user4 pass4
show_items
register_user user1 pass1
create_folder folder2
buy
register_user user9 pass9
add_item item2 key3=val6 key2=val4 key1=val4 key2=val8 
show_users
add_item_property item4 key1=val6 key1=val4 key2=val7 key7=val9 
ls
pwd
put item2
show_users
register_admin user4 pass4
register_admin user7 pass7
whoami
register_admin user4 pass4
show_items
help pwd
create_folder folder3
show_items
current_folder
sign_out
help put
register_admin user1 pass1
which_group
add_item_property item3 key4=val8 key10=val1 key1=val4 key6=val4 
put item1
rename_user user2 <function generate_user at 0x027087F0>
buy
whoami
ls
whoami
rename_user user1 <function generate_user at 0x027087F0>
rename_user user2 <function generate_user at 0x027087F0>
pwd
which_group
ls_folders
register_user user8 pass8
which_group
add_item item5 key10=val7 key8=val7 key3=val1 key8=val6 
rename_user user9 <function generate_user at 0x027087F0>
buy
show_item_properties item5
ls_folders
sign_out
buy
register_admin user6 pass6
current_folder
cd folder4
whoami
pwd
register_admin user5 pass5
pwd
which_group
show_users
show_items
put item2
put item5
pwd
sign_out
show_users
sign_in admin admin
current_folder
register_user admin admin
create_folder folder2
show_items
cd folder3
register_admin admin admin
put item2
which_group
current_folder
sign_in user7 pass7
help current_folder
ls
register_user user9 pass9
sign_in user4 pass4
help show_items
sign_out
whoami
sign_in a4 pa4
sign_in a1 pa1
register_user user8 pass8
create_folder folder5
add_item_property item3 key3=val6 key6=val1 key6=val1 key5=val9 
sign_in a5 pa5
show_items
sign_in user5 pass5
pwd
register_user user7 pass7
register_admin user6 pass6
create_folder folder2
rename_user user2 <function generate_user at 0x027087F0>
show_items
add_item_property item4 key2=val8 key8=val1 key10=val7 key8=val1 
show_item_properties item3
sign_out
put item4
buy
buy
show_items
create_folder folder5
show_items
show_items
rename_user user1 <function generate_user at 0x027087F0>
add_item_property item4 key5=val6 key4=val2 key10=val1 key6=val3 
which_group
put item2
rename_user user2 <function generate_user at 0x027087F0>
create_folder folder4
create_folder folder3
create_folder folder5
register_user user9 pass9
which_group
current_folder
buy
put item4
add_item item3 key1=val1 key3=val6 key9=val8 key2=val3 
rename_user user2 <function generate_user at 0x027087F0>
ls
add_item_property item4 key7=val4 key8=val9 key4=val1 key8=val10 
sign_in user2 pass2
ls
register_user user7 pass7
add_item_property item3 key4=val10 key10=val4 key6=val2 key10=val5 
sign_in user5 pass5
rename_user user3 <function generate_user at 0x027087F0>
sign_out
add_item_property item3 key3=val2 key8=val6 key10=val5 key10=val8 
pwd
add_item_property item1 key7=val4 key7=val5 key6=val6 key4=val5 
show_folders
current_folder
help exit
show_items
buy
show_users
cd folder1
create_folder folder1
show_users
pwd
which_group
show_folders
put item1
rename_user user6 <function generate_user at 0x027087F0>
register_admin user5 pass5
which_group
sign_in user8 pass8
sign_out
register_user user9 pass9
whoami
pwd
show_items
sign_in a1 pa1
ls
cd folder3
current_folder
pwd
create_folder folder5
create_folder folder4
buy
add_item_property item5 key7=val5 key4=val4 key8=val5 key8=val2 
ls
sign_in user5 pass5
sign_out
cd folder4
add_item_property item2 key5=val2 key3=val5 key3=val1 key8=val7 
help add_item
ls
cd folder5
pwd
ls_folders
pwd
show_folders
create_folder folder5
put item5
show_folders
create_folder folder4
which_group
put item2
sign_out
rename_user user0 <function generate_user at 0x027087F0>
register_user user2 pass2
show_folders
which_group
cd folder3
ls
show_item_properties item1
ls_folders
register_admin user1 pass1
current_folder
current_folder
which_group
register_user user6 pass6
show_users
sign_in user9 pass9
whoami
register_user user3 pass3
add_item item2 key2=val4 key8=val4 key5=val6 key2=val6 
sign_in user4 pass4
add_item item2 key7=val8 key2=val7 key6=val2 key4=val2 
which_group
add_item_property item1 key1=val5 key2=val4 key5=val9 key10=val3 
show_items
sign_in user8 pass8
show_folders
current_folder
ls
show_items
register_user user8 pass8
show_users
whoami
put item4
help show_item_properties
show_items
sign_in a1 pa1
current_folder
rename_user user9 <function generate_user at 0x027087F0>
pwd
cd folder2
add_item_property item3 key5=val3 key4=val9 key3=val2 key9=val2 
show_users
sign_in user4 pass4
sign_in a3 pa3
sign_in user4 pass4
show_users
buy
register_user user3 pass3
show_folders
rename_user user6 <function generate_user at 0x027087F0>
sign_in a1 pa1
buy
show_folders
current_folder
show_folders
current_folder
ls_folders
buy
register_admin admin admin
which_group
help cd
which_group
buy
which_group
show_items
sign_in a3 pa3
ls_folders
help create_folder
current_folder
register_user user4 pass4
pwd
put item2
cd folder1
register_admin user3 pass3
show_folders
help help
show_item_properties item2
sign_out
sign_in user9 pass9
register_user admin admin
sign_in user2 pass2
sign_in user9 pass9
create_folder folder1
register_admin user7 pass7
register_user user2 pass2
which_group
current_folder
ls_folders
show_folders
which_group
register_admin user9 pass9
register_user user2 pass2
whoami
show_item_properties item5
show_item_properties item3
add_item item1 key4=val2 key4=val1 key1=val6 key7=val4 
create_folder folder1
sign_out
add_item_property item2 key6=val10 key1=val3 key1=val4 key8=val2 
sign_out
ls_folders
show_item_properties item5
put item4
add_item_property item5 key3=val4 key1=val5 key9=val2 key5=val4 
buy
add_item_property item4 key1=val1 key3=val7 key9=val2 key8=val1 
add_item_property item2 key5=val2 key10=val10 key10=val4 key1=val10 
add_item_property item5 key1=val10 key10=val6 key7=val8 key8=val7 
put item1
help show_items
which_group
which_group
show_item_properties item1
register_admin user5 pass5
show_folders
current_folder
ls_folders
show_item_properties item1
sign_in admin admin
register_admin user7 pass7
show_folders
current_folder
register_user user7 pass7
sign_in admin admin
buy
put item5
show_item_properties item5
register_admin user6 pass6
rename_user user3 <function generate_user at 0x027087F0>
show_users
register_admin user1 pass1
ls
add_item item1 key6=val8 key1=val3 key10=val2 key10=val7 
ls
sign_in user2 pass2
current_folder
register_user user5 pass5
sign_out
create_folder folder2
sign_out
cd folder3
show_users
put item1
whoami
register_user user9 pass9
register_user user9 pass9
help put
rename_user user7 <function generate_user at 0x027087F0>
pwd
show_users
whoami
rename_user user1 <function generate_user at 0x027087F0>
put item3
which_group
help show_item_properties
add_item item2 key2=val5 key3=val3 key7=val10 key5=val2 
rename_user user8 <function generate_user at 0x027087F0>
ls
whoami
buy
sign_in user9 pass9
add_item_property item4 key2=val3 key2=val4 key7=val8 key7=val3 
buy
show_folders
rename_user user8 <function generate_user at 0x027087F0>
rename_user user9 <function generate_user at 0x027087F0>
which_group
sign_in a4 pa4
show_users
help buy
register_admin user7 pass7
add_item_property item3 key4=val10 key4=val8 key1=val7 key2=val4 
sign_in a1 pa1
pwd
create_folder folder5
sign_in a2 pa2
show_users
ls_folders
buy
register_user user3 pass3
sign_in a3 pa3
sign_in user1 pass1
buy
sign_in user8 pass8
which_group
ls
add_item item2 key9=val5 key6=val2 key5=val10 key9=val1 
sign_out
register_user admin admin
add_item item3 key1=val8 key10=val3 key10=val2 key9=val2 
whoami
add_item_property item4 key1=val3 key6=val9 key1=val4 key1=val2 
put item5
ls_folders
pwd
show_folders
show_folders
cd folder5
ls_folders
rename_user user8 <function generate_user at 0x027087F0>
sign_in a5 pa5
add_item item2 key8=val6 key3=val1 key10=val1 key2=val7 
ls
sign_in a2 pa2
show_item_properties item5
buy
cd folder5
sign_in a2 pa2
add_item item3 key2=val3 key6=val3 key2=val2 key4=val9 
sign_in a3 pa3
cd folder5
ls_folders
show_users
current_folder
sign_in user4 pass4
sign_in a3 pa3
current_folder
show_folders
buy
sign_in user9 pass9
add_item_property item4 key3=val9 key6=val3 key2=val1 key1=val7 
register_user user6 pass6
sign_in a2 pa2
ls_folders
which_group
register_user admin admin
show_item_properties item2
help ls_folders
buy
add_item item3 key5=val5 key9=val9 key4=val5 key10=val5 
cd folder2
pwd
show_folders
add_item_property item3 key9=val7 key3=val7 key2=val5 key2=val1 
register_user user3 pass3
whoami
buy
sign_in a5 pa5
sign_in a2 pa2
sign_out
register_admin user3 pass3
help show_items
sign_out
whoami
sign_out
add_item item3 key4=val3 key9=val3 key1=val3 key2=val1 
put item5
add_item_property item4 key7=val3 key6=val10 key3=val6 key8=val10 
cd folder1
add_item item1 key4=val5 key4=val9 key7=val3 key1=val5 
ls_folders
sign_in user8 pass8
help help
register_admin user9 pass9
help show_item_properties
create_folder folder1
add_item item3 key10=val6 key6=val2 key4=val4 key1=val7 
put item2
help whoami
help sign_out
ls_folders
add_item_property item4 key9=val8 key2=val3 key8=val9 key2=val2 
sign_in user6 pass6
add_item item3 key3=val8 key9=val5 key3=val3 key9=val7 
pwd
current_folder
sign_in user2 pass2
register_admin user5 pass5
current_folder
cd folder5
register_admin user9 pass9
register_admin admin admin
ls_folders
sign_in a3 pa3
current_folder
show_folders
show_folders
register_user user6 pass6
pwd
show_items
sign_in a5 pa5
rename_user user6 <function generate_user at 0x027087F0>
show_item_properties item4
rename_user user6 <function generate_user at 0x027087F0>
put item4
add_item item1 key7=val2 key9=val8 key1=val8 key8=val3 
whoami
show_folders
sign_in a2 pa2
show_users
create_folder folder5
put item5
buy
create_folder folder3
buy
sign_in user6 pass6
rename_user user7 <function generate_user at 0x027087F0>
ls_folders
add_item_property item4 key5=val1 key1=val7 key2=val5 key8=val6 
show_items
sign_in a5 pa5
put item3
current_folder
show_folders
register_user user5 pass5
show_items
create_folder folder1
show_folders
ls_folders
add_item item4 key1=val3 key10=val1 key7=val4 key7=val10 
show_users
show_folders
which_group
add_item_property item3 key3=val4 key8=val10 key9=val4 key10=val5 
show_folders
register_user user8 pass8
sign_out
sign_in user8 pass8
current_folder
whoami
show_users
whoami
buy
buy
help ls_folders
show_users
help current_folder
help create_folder
sign_in a4 pa4
create_folder folder4
help ls_folders
show_folders
buy
rename_user user5 <function generate_user at 0x027087F0>
current_folder
pwd
add_item_property item1 key8=val6 key8=val1 key8=val6 key6=val8 
current_folder
buy
show_folders
pwd
whoami
show_item_properties item1
rename_user user8 <function generate_user at 0x027087F0>
show_users
cd folder1
sign_out
ls_folders
whoami
sign_in a1 pa1
show_items
show_item_properties item2
pwd
sign_in user8 pass8
which_group
rename_user user0 <function generate_user at 0x027087F0>
add_item item1 key2=val7 key8=val4 key5=val3 key2=val2 
help register_admin
ls
add_item item4 key4=val3 key10=val1 key9=val8 key5=val10 
whoami
cd folder2
show_item_properties item4
put item2
whoami
sign_in a2 pa2
ls
put item4
show_item_properties item3
register_admin user7 pass7
ls_folders
buy
put item4
ls
sign_in a2 pa2
ls
put item5
put item1
show_users
whoami
whoami
cd folder3
show_items
whoami
help whoami
current_folder
current_folder
show_users
show_item_properties item1
show_item_properties item2
whoami
which_group
buy
sign_in user6 pass6
ls
which_group
show_items
sign_in a2 pa2
sign_in a3 pa3
whoami
show_item_properties item2
show_items
add_item_property item1 key9=val5 key7=val1 key10=val1 key1=val8 
ls_folders
create_folder folder1
register_user admin admin
pwd
show_users
register_user user2 pass2
sign_out
register_admin user3 pass3
add_item item5 key10=val6 key8=val1 key9=val10 key9=val9 
help add_item
cd folder3
buy
which_group
help which_group
show_folders
help pwd
ls
buy
add_item_property item1 key9=val10 key3=val4 key9=val8 key4=val7 
whoami
show_items
rename_user user3 <function generate_user at 0x027087F0>
register_user user5 pass5
which_group
sign_out
create_folder folder4
register_user admin admin
rename_user user5 <function generate_user at 0x027087F0>
add_item_property item2 key8=val3 key8=val9 key5=val7 key2=val8 
show_items
register_user user5 pass5
create_folder folder1
show_users
add_item_property item3 key8=val2 key1=val3 key8=val9 key1=val5 
sign_in a3 pa3
buy
show_users
register_admin user1 pass1
pwd
which_group
create_folder folder4
show_folders
sign_out
which_group
cd folder4
which_group
whoami
show_item_properties item1
ls_folders
show_item_properties item3
put item5
which_group
rename_user user1 <function generate_user at 0x027087F0>
create_folder folder2
add_item_property item4 key9=val8 key1=val9 key2=val5 key5=val2 
create_folder folder4
which_group
cd folder3
help cd
register_user user7 pass7
sign_in user1 pass1
help cd
sign_in user3 pass3
put item3
put item5
add_item_property item3 key4=val5 key4=val7 key5=val6 key1=val8 
help rename_user
whoami
show_folders
cd folder4
current_folder
whoami
register_user user3 pass3
put item5
put item1
current_folder
create_folder folder3
which_group
register_user user8 pass8
sign_out
ls
rename_user user9 <function generate_user at 0x027087F0>
add_item_property item5 key7=val2 key10=val10 key1=val3 key2=val7 
sign_out
sign_in a2 pa2
sign_in a5 pa5
current_folder
put item3
sign_in user4 pass4
current_folder
ls_folders
buy
rename_user user6 <function generate_user at 0x027087F0>
show_items
sign_in a3 pa3
sign_in user8 pass8
show_users
register_admin user7 pass7
ls
add_item item4 key3=val3 key10=val2 key4=val3 key10=val8 
sign_in a2 pa2
show_folders
add_item_property item4 key1=val8 key6=val8 key2=val4 key4=val3 
cd folder2
create_folder folder4
add_item item5 key4=val9 key9=val2 key5=val8 key7=val5 
help show_items
show_users
ls
add_item item2 key8=val2 key10=val7 key4=val2 key3=val2 
put item2
add_item item5 key7=val10 key5=val4 key4=val2 key2=val5 
show_users
ls
show_folders
add_item_property item2 key10=val7 key10=val8 key7=val4 key2=val10 
pwd
show_items
ls
current_folder
add_item item3 key5=val2 key10=val6 key4=val2 key6=val1 
sign_in user7 pass7
rename_user user3 <function generate_user at 0x027087F0>
whoami
add_item item4 key3=val8 key5=val1 key2=val6 key4=val10 
which_group
add_item_property item3 key6=val6 key3=val7 key10=val2 key2=val6 
show_users
add_item_property item1 key10=val4 key2=val8 key2=val4 key1=val4 
show_item_properties item2
show_users
rename_user user0 <function generate_user at 0x027087F0>
register_user admin admin
rename_user user1 <function generate_user at 0x027087F0>
whoami
ls
show_folders
sign_in admin admin
which_group
ls
put item1
sign_in user4 pass4
which_group
create_folder folder1
add_item_property item2 key6=val3 key8=val9 key8=val5 key1=val7 
sign_in a3 pa3
put item5
create_folder folder1
pwd
cd folder4
pwd
add_item_property item4 key1=val4 key10=val1 key10=val5 key2=val8 
ls
current_folder
show_users
show_items
buy
sign_in user3 pass3
sign_in a2 pa2
add_item_property item5 key4=val1 key4=val9 key3=val6 key2=val9 
put item3
cd folder2
show_users
cd folder2
show_users
sign_in user8 pass8
sign_out
help rename_user
pwd
put item4
sign_in user6 pass6
current_folder
show_users
sign_in a5 pa5
show_item_properties item4
add_item item4 key7=val5 key2=val1 key6=val5 key10=val4 
buy
ls_folders
put item1
ls
show_users
create_folder folder1
rename_user user9 <function generate_user at 0x027087F0>
show_items
add_item_property item5 key1=val10 key9=val10 key2=val1 key1=val1 
register_admin user5 pass5
help add_item_property
cd folder1
help register_user
sign_out
register_admin user8 pass8
help sign_out
sign_in a2 pa2
ls_folders
register_admin user4 pass4
put item4
which_group
rename_user user4 <function generate_user at 0x027087F0>
which_group
put item3
sign_out
register_admin user2 pass2
show_users
register_user user2 pass2
whoami
show_folders
show_item_properties item2
show_item_properties item4
which_group
register_user user8 pass8
ls
show_folders
pwd
sign_in user9 pass9
ls
register_admin user6 pass6
sign_in a2 pa2
ls_folders
buy
show_items
register_user user4 pass4
help show_folders
ls_folders
ls
buy
put item5
add_item_property item3 key5=val7 key1=val3 key7=val7 key5=val6 
create_folder folder2
create_folder folder4
rename_user user7 <function generate_user at 0x027087F0>
rename_user user1 <function generate_user at 0x027087F0>
sign_in a5 pa5
add_item_property item1 key5=val5 key2=val1 key5=val8 key7=val7 
register_user user3 pass3
register_user user4 pass4
sign_in a2 pa2
put item1
sign_out
ls
ls_folders
sign_in user9 pass9
which_group
register_admin admin admin
show_users
put item4
which_group
sign_in a4 pa4
show_users
create_folder folder5
help pwd
ls_folders
ls
show_folders
rename_user user9 <function generate_user at 0x027087F0>
sign_out
buy
current_folder
cd folder2
ls_folders
whoami
show_users
sign_out
ls
put item2
which_group
sign_in a4 pa4
sign_in user2 pass2
which_group
sign_in user9 pass9
current_folder
put item4
ls_folders
sign_out
show_item_properties item5
put item5
sign_in a2 pa2
register_user admin admin
show_users
register_user admin admin
sign_in a1 pa1
register_user user6 pass6
sign_in a1 pa1
register_user user2 pass2
rename_user user5 <function generate_user at 0x027087F0>
cd folder3
sign_out
show_item_properties item4
rename_user user1 <function generate_user at 0x027087F0>
register_user user9 pass9
buy
buy
show_folders
create_folder folder1
show_items
show_users
pwd
sign_in a5 pa5
show_items
show_users
register_admin user4 pass4
sign_in user8 pass8
help history
add_item item5 key1=val7 key7=val5 key9=val5 key1=val3 
help sign_out
show_items
show_users
show_users
show_items
help show_items
sign_in user4 pass4
whoami
show_folders
ls_folders
sign_out
put item4
current_folder
sign_in user8 pass8
buy
ls
show_item_properties item2
register_admin user5 pass5
show_users
put item1
add_item item4 key7=val5 key9=val10 key5=val10 key7=val4 
show_users
sign_in user4 pass4
cd folder5
ls
help history
help ls_folders
show_item_properties item2
sign_in user8 pass8
register_user user7 pass7
create_folder folder3
rename_user user5 <function generate_user at 0x027087F0>
whoami
which_group
put item5
show_users
register_admin user2 pass2
sign_out
create_folder folder1
register_user user5 pass5
cd folder5
register_user user1 pass1
ls
sign_in user1 pass1
help show_users
cd folder2
show_items
create_folder folder3
sign_out
add_item_property item2 key8=val1 key6=val3 key1=val6 key2=val1 
add_item item5 key6=val3 key5=val5 key10=val2 key6=val10 
sign_in user1 pass1
register_admin user9 pass9
register_admin user6 pass6
register_admin user8 pass8
ls_folders
sign_out
sign_out
current_folder
put item4
add_item_property item1 key6=val4 key4=val8 key9=val7 key3=val1 
add_item item5 key8=val4 key2=val5 key1=val9 key4=val5 
show_item_properties item3
buy
add_item_property item2 key2=val5 key2=val5 key6=val8 key1=val3 
show_users
sign_in user4 pass4
show_item_properties item4
register_user admin admin
ls
pwd
sign_in a3 pa3
sign_in a1 pa1
ls
sign_in a1 pa1
pwd
register_user admin admin
cd folder5
