sign_out
add_item_property item3 key1=val4 key5=val7 key1=val3 key3=val6 
register_user user4 pass4
cd folder5
buy
ls_folders
buy
rename_user user4 <function generate_user at 0x027087F0>
show_items
show_item_properties item3
current_folder
register_admin user3 pass3
show_items
sign_in user7 pass7
show_items
rename_user user5 <function generate_user at 0x027087F0>
sign_out
which_group
ls
put item4
pwd
help register_admin
ls_folders
show_users
add_item_property item4 key9=val4 key5=val6 key7=val7 key7=val4 
show_users
sign_in a3 pa3
create_folder folder3
buy
ls_folders
put item4
create_folder folder3
pwd
whoami
buy
show_item_properties item1
which_group
add_item item4 key1=val7 key2=val4 key7=val2 key4=val6 
create_folder folder2
ls_folders
buy
whoami
help ls
ls_folders
cd folder1
cd folder4
show_folders
put item2
add_item_property item5 key2=val5 key7=val5 key3=val7 key5=val7 
put item5
pwd
register_user user5 pass5
whoami
cd folder2
register_admin user7 pass7
create_folder folder3
show_item_properties item4
rename_user user5 <function generate_user at 0x027087F0>
show_users
sign_in user8 pass8
current_folder
register_user user2 pass2
ls
create_folder folder2
show_item_properties item5
whoami
ls_folders
show_item_properties item5
show_users
rename_user user7 <function generate_user at 0x027087F0>
which_group
put item1
sign_in user5 pass5
ls
sign_in a4 pa4
show_item_properties item2
help register_admin
cd folder2
sign_in user6 pass6
create_folder folder4
ls
show_folders
add_item_property item3 key1=val7 key6=val1 key6=val5 key4=val1 
add_item_property item3 key3=val5 key10=val7 key10=val10 key5=val4 
sign_in a4 pa4
which_group
show_items
register_admin admin admin
current_folder
add_item_property item4 key4=val3 key8=val5 key10=val5 key7=val1 
rename_user user2 <function generate_user at 0x027087F0>
ls
ls
register_user user3 pass3
add_item item5 key9=val4 key7=val9 key4=val5 key8=val5 
ls_folders
show_items
add_item_property item4 key9=val10 key4=val3 key1=val6 key5=val4 
create_folder folder3
ls
show_item_properties item1
create_folder folder4
sign_in user3 pass3
rename_user user8 <function generate_user at 0x027087F0>
add_item item3 key4=val1 key6=val8 key2=val9 key6=val1 
current_folder
pwd
help ls
which_group
pwd
register_admin user8 pass8
sign_in admin admin
buy
register_user user3 pass3
add_item_property item4 key2=val3 key5=val9 key6=val1 key7=val8 
register_user user8 pass8
add_item_property item2 key7=val7 key5=val5 key10=val3 key6=val10 
whoami
create_folder folder3
buy
current_folder
sign_in user4 pass4
sign_in a4 pa4
put item1
show_folders
buy
buy
show_users
whoami
rename_user user1 <function generate_user at 0x027087F0>
current_folder
cd folder3
which_group
sign_out
sign_in user3 pass3
sign_out
pwd
show_folders
sign_in a3 pa3
ls_folders
sign_in a2 pa2
show_users
add_item_property item2 key5=val2 key6=val2 key6=val1 key6=val1 
register_user user2 pass2
add_item item3 key9=val3 key7=val6 key1=val8 key4=val4 
rename_user user9 <function generate_user at 0x027087F0>
add_item_property item1 key10=val1 key7=val4 key8=val1 key6=val3 
show_folders
rename_user user5 <function generate_user at 0x027087F0>
which_group
ls
sign_out
show_items
register_admin user2 pass2
sign_in user5 pass5
pwd
register_user user6 pass6
ls_folders
put item1
sign_out
add_item item2 key5=val7 key10=val1 key10=val4 key3=val9 
show_folders
show_users
ls_folders
show_users
add_item_property item5 key2=val4 key2=val5 key5=val2 key8=val10 
ls
sign_in a1 pa1
add_item_property item5 key9=val5 key4=val2 key1=val5 key1=val10 
ls
put item1
show_folders
create_folder folder3
which_group
sign_in user1 pass1
add_item_property item2 key6=val5 key6=val6 key4=val9 key9=val1 
which_group
whoami
register_user user8 pass8
show_users
sign_out
cd folder4
ls
show_folders
register_admin user9 pass9
help sign_out
pwd
add_item_property item3 key5=val10 key2=val3 key1=val9 key8=val10 
add_item item5 key4=val8 key8=val5 key5=val7 key2=val1 
add_item item5 key6=val7 key5=val2 key10=val1 key9=val10 
sign_out
rename_user user5 <function generate_user at 0x027087F0>
ls
sign_in a2 pa2
sign_out
register_admin user4 pass4
show_items
create_folder folder3
help current_folder
register_admin user4 pass4
register_user user7 pass7
create_folder folder2
cd folder5
show_items
whoami
show_users
ls
show_items
register_user user2 pass2
sign_in user4 pass4
which_group
show_item_properties item3
sign_out
ls_folders
put item2
register_admin admin admin
which_group
buy
show_item_properties item4
ls
pwd
show_items
show_users
ls_folders
sign_in user6 pass6
put item5
register_admin user3 pass3
sign_out
show_item_properties item3
add_item_property item4 key10=val2 key1=val5 key4=val3 key3=val1 
register_admin user9 pass9
show_folders
ls
ls
sign_in admin admin
rename_user user4 <function generate_user at 0x027087F0>
register_admin admin admin
sign_in a1 pa1
add_item_property item3 key10=val6 key10=val1 key5=val7 key10=val7 
show_item_properties item4
show_folders
show_users
current_folder
show_item_properties item4
put item1
whoami
sign_in user1 pass1
which_group
current_folder
show_item_properties item5
add_item item5 key10=val3 key8=val10 key9=val2 key8=val1 
sign_in user5 pass5
rename_user user9 <function generate_user at 0x027087F0>
pwd
show_items
add_item item1 key9=val9 key3=val7 key10=val3 key5=val10 
current_folder
current_folder
show_users
show_users
show_folders
help buy
buy
current_folder
cd folder5
add_item item4 key10=val5 key8=val2 key10=val8 key5=val7 
pwd
add_item_property item5 key9=val10 key5=val8 key4=val1 key10=val2 
ls
put item5
pwd
create_folder folder5
create_folder folder3
register_user user6 pass6
register_user user6 pass6
sign_in user6 pass6
current_folder
put item3
ls
buy
whoami
ls_folders
which_group
create_folder folder3
sign_out
sign_in user6 pass6
put item5
whoami
add_item_property item1 key6=val8 key8=val6 key2=val1 key7=val7 
rename_user user8 <function generate_user at 0x027087F0>
register_user user4 pass4
put item2
register_admin user6 pass6
cd folder5
pwd
show_items
add_item item3 key8=val10 key1=val6 key9=val2 key10=val3 
show_folders
show_items
register_admin user3 pass3
buy
create_folder folder4
ls
show_item_properties item4
add_item item4 key7=val4 key6=val8 key7=val7 key1=val6 
create_folder folder5
buy
add_item_property item1 key3=val6 key4=val7 key1=val10 key6=val1 
buy
which_group
create_folder folder2
ls_folders
whoami
pwd
rename_user user8 <function generate_user at 0x027087F0>
pwd
which_group
create_folder folder5
cd folder2
ls
show_item_properties item4
current_folder
ls
register_admin user2 pass2
sign_out
sign_out
put item2
add_item_property item5 key9=val3 key1=val4 key6=val6 key7=val6 
put item2
help help
register_admin user7 pass7
help whoami
current_folder
cd folder2
add_item_property item2 key1=val7 key1=val2 key8=val8 key1=val9 
put item1
register_admin user3 pass3
create_folder folder3
register_user user1 pass1
current_folder
rename_user user8 <function generate_user at 0x027087F0>
show_items
register_user user9 pass9
register_admin user9 pass9
rename_user user4 <function generate_user at 0x027087F0>
register_user user6 pass6
ls
rename_user user0 <function generate_user at 0x027087F0>
whoami
sign_out
register_user user5 pass5
show_users
buy
register_admin user2 pass2
sign_in user2 pass2
rename_user user0 <function generate_user at 0x027087F0>
sign_in a5 pa5
add_item_property item2 key3=val9 key5=val6 key9=val7 key2=val5 
ls
ls
sign_out
which_group
add_item_property item3 key8=val3 key4=val1 key1=val7 key4=val9 
ls
register_user user7 pass7
register_user user8 pass8
create_folder folder5
ls
register_user user2 pass2
pwd
whoami
register_admin user3 pass3
ls
sign_in admin admin
show_items
which_group
whoami
show_folders
show_item_properties item2
add_item_property item2 key6=val7 key4=val5 key8=val1 key4=val9 
which_group
add_item_property item2 key2=val2 key7=val2 key4=val6 key1=val3 
whoami
register_user admin admin
show_users
show_users
register_admin user8 pass8
ls_folders
show_folders
sign_in user9 pass9
which_group
register_user user7 pass7
show_item_properties item5
cd folder4
help register_user
add_item item3 key1=val7 key1=val5 key3=val10 key3=val1 
register_admin admin admin
register_user user4 pass4
pwd
create_folder folder5
put item5
show_item_properties item5
ls
sign_in a4 pa4
sign_in user9 pass9
register_admin user9 pass9
which_group
ls_folders
sign_in a3 pa3
create_folder folder4
sign_in user3 pass3
sign_out
cd folder5
sign_out
add_item_property item1 key8=val8 key7=val3 key8=val3 key8=val2 
create_folder folder1
help delete_user
pwd
sign_in user4 pass4
current_folder
register_user user6 pass6
show_item_properties item1
put item2
current_folder
help which_group
put item3
register_admin user7 pass7
show_item_properties item3
buy
rename_user user2 <function generate_user at 0x027087F0>
add_item item4 key6=val4 key6=val6 key9=val8 key7=val2 
current_folder
whoami
add_item_property item5 key2=val2 key4=val8 key7=val5 key4=val8 
buy
buy
add_item item4 key6=val10 key2=val7 key5=val9 key9=val10 
buy
show_items
sign_in a4 pa4
add_item_property item3 key7=val3 key10=val7 key2=val10 key5=val4 
ls
whoami
sign_in a2 pa2
sign_out
sign_in admin admin
sign_in a4 pa4
rename_user user6 <function generate_user at 0x027087F0>
add_item_property item5 key6=val5 key8=val10 key9=val6 key7=val9 
sign_in user4 pass4
buy
add_item item5 key7=val7 key5=val10 key3=val1 key5=val9 
add_item item3 key8=val5 key6=val9 key3=val1 key1=val6 
rename_user user1 <function generate_user at 0x027087F0>
show_items
buy
show_items
add_item_property item3 key3=val9 key2=val6 key10=val8 key5=val9 
add_item_property item4 key1=val9 key2=val3 key3=val9 key8=val9 
show_item_properties item2
ls_folders
create_folder folder5
pwd
sign_in user7 pass7
add_item item2 key5=val1 key7=val10 key5=val1 key9=val10 
cd folder1
ls_folders
show_users
ls_folders
sign_out
cd folder5
sign_in admin admin
which_group
ls
add_item_property item3 key1=val3 key7=val1 key1=val1 key4=val1 
rename_user user3 <function generate_user at 0x027087F0>
pwd
ls
sign_in user1 pass1
show_folders
buy
add_item item4 key9=val4 key9=val5 key4=val8 key6=val7 
sign_out
add_item_property item1 key5=val1 key9=val4 key9=val7 key5=val9 
sign_in a3 pa3
show_item_properties item4
pwd
show_item_properties item4
pwd
which_group
put item1
show_folders
which_group
add_item_property item3 key7=val4 key2=val6 key3=val3 key10=val2 
whoami
sign_in user4 pass4
show_item_properties item1
cd folder2
pwd
sign_in admin admin
help ls
sign_in user6 pass6
add_item_property item3 key10=val7 key6=val8 key1=val10 key5=val6 
sign_out
show_folders
ls_folders
which_group
add_item_property item5 key6=val1 key7=val8 key2=val10 key5=val4 
cd folder3
show_folders
show_users
which_group
whoami
register_admin admin admin
sign_in a5 pa5
current_folder
rename_user user3 <function generate_user at 0x027087F0>
pwd
show_folders
help which_group
rename_user user4 <function generate_user at 0x027087F0>
whoami
show_users
ls_folders
current_folder
show_items
register_admin user3 pass3
ls_folders
current_folder
cd folder1
show_users
pwd
help sign_in
sign_in a2 pa2
show_users
cd folder2
buy
add_item item4 key2=val3 key3=val9 key8=val1 key5=val8 
current_folder
buy
sign_out
cd folder5
add_item_property item1 key6=val5 key2=val8 key5=val6 key7=val2 
rename_user user1 <function generate_user at 0x027087F0>
pwd
register_user user2 pass2
pwd
register_admin user3 pass3
sign_in admin admin
help show_item_properties
show_folders
create_folder folder4
help history
show_folders
help create_folder
ls_folders
create_folder folder3
sign_out
put item2
current_folder
pwd
register_user user6 pass6
show_items
show_items
show_users
put item4
ls_folders
create_folder folder5
whoami
show_item_properties item1
which_group
register_admin admin admin
show_items
register_user user2 pass2
cd folder5
create_folder folder5
rename_user user7 <function generate_user at 0x027087F0>
sign_in user2 pass2
rename_user user7 <function generate_user at 0x027087F0>
show_item_properties item3
buy
show_folders
create_folder folder4
sign_in a4 pa4
put item2
buy
buy
show_item_properties item5
show_items
put item2
ls_folders
buy
create_folder folder1
register_user user5 pass5
show_item_properties item3
add_item_property item3 key3=val9 key7=val7 key6=val7 key4=val8 
current_folder
register_user user3 pass3
which_group
register_admin user1 pass1
add_item item5 key5=val4 key5=val7 key4=val9 key6=val4 
whoami
buy
cd folder4
register_user user6 pass6
show_items
show_folders
pwd
show_item_properties item3
sign_in user3 pass3
put item5
sign_in user9 pass9
show_users
show_item_properties item5
put item1
sign_out
buy
cd folder3
ls
cd folder5
current_folder
whoami
ls
sign_in a2 pa2
add_item_property item3 key9=val5 key7=val10 key8=val10 key4=val5 
put item1
show_folders
buy
sign_in user3 pass3
sign_in user4 pass4
help ls
show_folders
put item3
help history
cd folder2
ls
buy
sign_out
current_folder
help sign_out
sign_in user4 pass4
create_folder folder4
sign_in user7 pass7
register_user user5 pass5
which_group
help rename_user
current_folder
which_group
register_admin user1 pass1
add_item item1 key2=val4 key2=val3 key8=val4 key3=val10 
buy
put item5
create_folder folder4
put item4
show_folders
register_user user7 pass7
register_admin user2 pass2
create_folder folder2
sign_in a2 pa2
show_folders
show_users
whoami
pwd
cd folder4
ls
pwd
create_folder folder3
whoami
register_admin user8 pass8
whoami
put item2
add_item_property item4 key5=val10 key5=val5 key1=val8 key10=val8 
show_items
sign_in user1 pass1
show_users
help add_item_property
show_items
show_item_properties item4
pwd
register_user user3 pass3
register_admin user8 pass8
show_folders
sign_in a4 pa4
register_user user3 pass3
sign_in a1 pa1
sign_in user7 pass7
create_folder folder3
create_folder folder2
sign_out
sign_in a2 pa2
register_user user5 pass5
show_item_properties item3
pwd
add_item_property item5 key3=val2 key2=val5 key4=val4 key9=val4 
whoami
sign_in a3 pa3
pwd
current_folder
show_item_properties item2
show_users
ls
which_group
buy
pwd
show_users
current_folder
put item4
register_admin user2 pass2
register_user user8 pass8
whoami
sign_in user2 pass2
show_folders
show_folders
which_group
add_item_property item2 key1=val1 key6=val3 key2=val6 key9=val5 
sign_in a5 pa5
add_item_property item5 key4=val1 key10=val4 key3=val10 key9=val2 
show_folders
add_item_property item2 key8=val10 key5=val3 key2=val9 key2=val7 
register_admin user4 pass4
show_item_properties item2
whoami
ls
ls
put item5
sign_out
buy
show_item_properties item5
buy
rename_user user0 <function generate_user at 0x027087F0>
current_folder
create_folder folder4
pwd
create_folder folder5
cd folder5
ls
whoami
register_user user7 pass7
sign_in user3 pass3
help show_users
pwd
which_group
ls
buy
create_folder folder2
which_group
current_folder
add_item_property item3 key4=val2 key2=val8 key1=val4 key10=val7 
put item1
pwd
show_users
show_items
show_folders
pwd
ls
show_folders
put item1
show_folders
put item5
buy
create_folder folder3
ls
sign_in user8 pass8
sign_in user2 pass2
current_folder
sign_in user4 pass4
add_item_property item3 key6=val2 key9=val9 key6=val5 key2=val5 
current_folder
put item4
show_folders
whoami
register_user user8 pass8
show_item_properties item2
ls_folders
register_user user6 pass6
show_items
cd folder3
register_user user9 pass9
sign_in user9 pass9
show_item_properties item3
whoami
help sign_out
rename_user user5 <function generate_user at 0x027087F0>
add_item_property item2 key10=val8 key6=val10 key8=val4 key10=val8 
sign_in a3 pa3
whoami
rename_user user5 <function generate_user at 0x027087F0>
which_group
whoami
sign_in user5 pass5
whoami
show_items
buy
ls_folders
cd folder3
whoami
create_folder folder1
put item1
whoami
add_item item2 key10=val2 key6=val2 key7=val7 key1=val6 
pwd
show_item_properties item3
register_admin user9 pass9
help show_item_properties
sign_in a5 pa5
ls
which_group
pwd
show_folders
sign_in a4 pa4
rename_user user7 <function generate_user at 0x027087F0>
sign_out
show_folders
which_group
add_item_property item3 key10=val4 key2=val7 key10=val5 key9=val10 
buy
cd folder2
show_item_properties item1
show_items
sign_in a4 pa4
rename_user user3 <function generate_user at 0x027087F0>
whoami
put item1
show_users
whoami
sign_in a2 pa2
add_item_property item5 key4=val1 key4=val10 key8=val5 key6=val1 
add_item item4 key1=val6 key1=val4 key7=val8 key9=val6 
show_folders
put item3
ls
help pwd
buy
help pwd
help cd
which_group
ls_folders
add_item_property item5 key7=val7 key8=val3 key6=val1 key8=val3 
whoami
create_folder folder1
show_folders
show_folders
register_user user5 pass5
rename_user user2 <function generate_user at 0x027087F0>
which_group
put item2
add_item_property item4 key3=val5 key9=val6 key1=val3 key8=val3 
pwd
create_folder folder4
show_folders
show_items
rename_user user7 <function generate_user at 0x027087F0>
cd folder3
ls
add_item item5 key5=val6 key2=val8 key1=val2 key5=val2 
pwd
create_folder folder4
ls
buy
show_items
register_user user2 pass2
show_folders
ls_folders
pwd
show_item_properties item2
whoami
show_folders
which_group
show_folders
sign_out
current_folder
show_users
cd folder3
help show_item_properties
rename_user user3 <function generate_user at 0x027087F0>
add_item_property item1 key4=val2 key10=val5 key9=val7 key8=val9 
show_item_properties item1
show_users
add_item_property item4 key3=val9 key2=val6 key4=val3 key9=val3 
put item5
sign_in user5 pass5
sign_out
put item5
add_item_property item4 key9=val2 key4=val9 key10=val10 key7=val3 
show_folders
sign_out
show_item_properties item3
rename_user user2 <function generate_user at 0x027087F0>
sign_in a3 pa3
rename_user user3 <function generate_user at 0x027087F0>
sign_out
sign_out
show_users
show_folders
help rename_user
sign_out
ls_folders
pwd
buy
ls_folders
put item3
show_items
whoami
sign_in user6 pass6
sign_in user8 pass8
create_folder folder3
current_folder
register_admin admin admin
register_admin user7 pass7
show_items
show_folders
add_item item4 key3=val3 key6=val4 key6=val9 key4=val3 
sign_in a4 pa4
whoami
show_folders
rename_user user5 <function generate_user at 0x027087F0>
buy
show_items
show_items
show_items
register_user user2 pass2
sign_in user8 pass8
ls
show_item_properties item1
help show_items
ls_folders
register_user user4 pass4
show_users
register_admin user3 pass3
ls_folders
show_users
put item3
help cd
show_item_properties item2
register_user user5 pass5
cd folder3
help exit
sign_out
add_item_property item3 key9=val7 key8=val8 key6=val3 key7=val4 
show_item_properties item2
register_admin user7 pass7
ls
current_folder
create_folder folder3
register_admin admin admin
show_users
show_folders
which_group
ls
register_admin user5 pass5
show_users
create_folder folder1
pwd
show_items
add_item item5 key2=val4 key7=val4 key1=val9 key3=val8 
ls
register_user user1 pass1
show_users
rename_user user3 <function generate_user at 0x027087F0>
current_folder
create_folder folder5
add_item_property item5 key4=val10 key10=val5 key7=val6 key4=val4 
sign_in user5 pass5
ls_folders
rename_user user9 <function generate_user at 0x027087F0>
buy
which_group
current_folder
which_group
ls
current_folder
show_item_properties item4
add_item item3 key5=val3 key3=val8 key9=val10 key2=val2 
show_items
sign_out
add_item_property item2 key7=val6 key9=val9 key9=val4 key9=val8 
rename_user user2 <function generate_user at 0x027087F0>
sign_in a1 pa1
register_admin user5 pass5
register_admin user1 pass1
show_users
create_folder folder3
register_user user2 pass2
add_item item5 key2=val8 key9=val1 key8=val6 key3=val4 
sign_in user1 pass1
ls_folders
put item2
whoami
ls
sign_in a1 pa1
help history
put item1
ls
which_group
sign_in user8 pass8
buy
sign_out
which_group
add_item item3 key9=val1 key2=val8 key8=val9 key7=val8 
show_users
ls
help add_item
rename_user user4 <function generate_user at 0x027087F0>
show_folders
show_users
which_group
sign_in user3 pass3
create_folder folder5
ls_folders
rename_user user0 <function generate_user at 0x027087F0>
ls_folders
sign_out
which_group
show_items
register_admin user7 pass7
show_item_properties item1
which_group
sign_out
put item5
cd folder3
register_user user7 pass7
pwd
sign_out
show_users
sign_in a3 pa3
register_admin user5 pass5
add_item item1 key2=val5 key2=val2 key3=val4 key10=val8 
put item4
buy
put item5
add_item item4 key1=val3 key10=val7 key5=val1 key3=val3 
buy
show_item_properties item3
register_admin user9 pass9
create_folder folder4
show_item_properties item2
put item1
whoami
add_item_property item3 key7=val5 key5=val6 key1=val7 key3=val10 
whoami
show_item_properties item1
sign_in user7 pass7
put item4
buy
register_admin user7 pass7
ls
pwd
sign_in a4 pa4
show_folders
sign_out
buy
show_users
sign_in user5 pass5
add_item item3 key5=val5 key5=val3 key8=val10 key7=val2 
whoami
show_items
pwd
show_items
add_item_property item2 key9=val3 key1=val1 key1=val6 key5=val10 
whoami
show_item_properties item3
sign_in a3 pa3
help show_items
cd folder4
pwd
add_item item2 key8=val5 key3=val5 key3=val8 key7=val8 
put item3
register_user user1 pass1
pwd
current_folder
ls
which_group
sign_in user1 pass1
create_folder folder3
show_users
ls
ls_folders
show_items
register_admin user7 pass7
rename_user user6 <function generate_user at 0x027087F0>
register_admin admin admin
pwd
ls
ls
current_folder
register_user user5 pass5
sign_in user5 pass5
register_user user8 pass8
register_admin user3 pass3
show_items
current_folder
ls_folders
show_folders
add_item item2 key8=val8 key7=val10 key3=val10 key8=val4 
register_admin admin admin
cd folder1
show_items
register_user user9 pass9
sign_in user9 pass9
register_admin admin admin
add_item item1 key10=val6 key1=val9 key7=val9 key2=val6 
sign_in a5 pa5
register_user user9 pass9
current_folder
ls
sign_out
sign_in user2 pass2
cd folder4
show_item_properties item3
sign_out
current_folder
which_group
rename_user user2 <function generate_user at 0x027087F0>
show_items
sign_in user5 pass5
buy
sign_in user1 pass1
whoami
add_item_property item3 key6=val10 key7=val3 key1=val8 key10=val7 
add_item_property item5 key6=val4 key4=val1 key1=val5 key6=val3 
ls
add_item item2 key9=val6 key6=val8 key7=val3 key6=val3 
show_users
register_admin user9 pass9
cd folder3
register_user user4 pass4
sign_in user1 pass1
ls_folders
which_group
ls_folders
register_user user5 pass5
add_item item4 key7=val2 key5=val8 key1=val2 key2=val1 
whoami
rename_user user6 <function generate_user at 0x027087F0>
show_items
sign_in a1 pa1
ls
current_folder
put item1
sign_in user1 pass1
buy
show_item_properties item5
create_folder folder2
add_item item2 key6=val5 key9=val9 key3=val9 key5=val9 
ls_folders
ls
cd folder1
sign_out
sign_in a1 pa1
help whoami
ls_folders
create_folder folder1
put item3
add_item item2 key6=val10 key1=val4 key9=val2 key7=val9 
sign_out
ls_folders
show_item_properties item4
show_users
ls
sign_out
add_item item5 key10=val9 key4=val4 key7=val7 key6=val9 
sign_out
ls_folders
help put
add_item item2 key3=val10 key9=val5 key2=val8 key1=val1 
which_group
help delete_user
pwd
sign_in admin admin
rename_user user8 <function generate_user at 0x027087F0>
ls_folders
register_admin admin admin
show_users
sign_in a5 pa5
which_group
add_item_property item1 key3=val7 key6=val5 key3=val9 key10=val9 
show_items
current_folder
current_folder
register_user user6 pass6
register_admin user7 pass7
sign_out
add_item_property item3 key3=val2 key1=val8 key8=val10 key5=val10 
whoami
sign_in a1 pa1
buy
sign_in a3 pa3
sign_out
put item2
register_user user2 pass2
show_items
pwd
ls
register_user user6 pass6
show_users
help whoami
current_folder
ls
register_user user3 pass3
rename_user user9 <function generate_user at 0x027087F0>
sign_in a4 pa4
add_item item2 key5=val9 key8=val7 key9=val6 key5=val4 
sign_in user8 pass8
show_items
create_folder folder5
buy
ls_folders
create_folder folder5
add_item_property item1 key6=val7 key6=val5 key4=val3 key7=val5 
put item5
sign_in user4 pass4
current_folder
register_user user9 pass9
sign_out
sign_out
add_item item5 key8=val10 key4=val5 key5=val2 key1=val7 
buy
ls
show_folders
register_user user5 pass5
put item3
sign_out
buy
ls
register_user user3 pass3
rename_user user6 <function generate_user at 0x027087F0>
which_group
show_users
help sign_out
help view_order
add_item item1 key7=val1 key7=val10 key1=val2 key10=val1 
pwd
buy
rename_user user5 <function generate_user at 0x027087F0>
put item5
add_item item5 key5=val2 key4=val9 key3=val7 key4=val5 
add_item item3 key1=val4 key1=val8 key4=val10 key9=val3 
current_folder
show_items
add_item item1 key8=val2 key1=val1 key10=val2 key6=val6 
ls_folders
ls
current_folder
show_items
ls_folders
add_item_property item5 key1=val9 key4=val7 key2=val5 key8=val2 
create_folder folder4
show_item_properties item4
buy
show_item_properties item5
buy
add_item_property item4 key3=val7 key3=val9 key6=val9 key1=val6 
rename_user user5 <function generate_user at 0x027087F0>
show_folders
rename_user user7 <function generate_user at 0x027087F0>
whoami
help pwd
register_admin user4 pass4
register_admin user1 pass1
show_item_properties item2
show_item_properties item3
add_item item3 key2=val5 key4=val7 key7=val3 key4=val1 
current_folder
show_users
rename_user user6 <function generate_user at 0x027087F0>
show_item_properties item2
ls
add_item_property item4 key4=val4 key5=val1 key9=val4 key3=val5 
sign_out
whoami
rename_user user2 <function generate_user at 0x027087F0>
sign_in a3 pa3
create_folder folder4
cd folder4
show_item_properties item5
help delete_user
add_item_property item3 key10=val8 key8=val6 key2=val9 key8=val10 
add_item_property item5 key3=val5 key9=val10 key6=val4 key8=val4 
ls_folders
cd folder3
buy
show_users
show_item_properties item1
which_group
sign_in user3 pass3
whoami
register_admin user7 pass7
buy
show_item_properties item4
add_item_property item4 key10=val9 key10=val10 key10=val3 key2=val1 
sign_in a2 pa2
sign_out
show_folders
which_group
pwd
sign_in a1 pa1
rename_user user7 <function generate_user at 0x027087F0>
pwd
sign_in a5 pa5
add_item item2 key5=val3 key3=val9 key7=val5 key5=val1 
add_item item5 key5=val9 key3=val7 key8=val7 key4=val2 
show_users
add_item_property item5 key8=val9 key10=val6 key6=val7 key3=val10 
create_folder folder1
add_item_property item5 key5=val10 key3=val3 key1=val4 key8=val3 
add_item item3 key10=val10 key5=val7 key5=val9 key3=val2 
rename_user user0 <function generate_user at 0x027087F0>
buy
register_admin user4 pass4
rename_user user3 <function generate_user at 0x027087F0>
register_user user6 pass6
create_folder folder4
show_folders
buy
cd folder4
rename_user user3 <function generate_user at 0x027087F0>
register_user admin admin
show_item_properties item2
show_item_properties item2
current_folder
ls_folders
pwd
put item5
show_users
help whoami
ls
help sign_in
show_folders
create_folder folder1
show_users
ls_folders
show_users
cd folder3
put item4
current_folder
rename_user user6 <function generate_user at 0x027087F0>
sign_in user5 pass5
current_folder
create_folder folder3
rename_user user0 <function generate_user at 0x027087F0>
put item4
show_users
help pwd
create_folder folder5
show_items
pwd
ls_folders
register_admin admin admin
create_folder folder3
buy
buy
buy
add_item_property item1 key5=val10 key10=val6 key1=val4 key10=val5 
rename_user user3 <function generate_user at 0x027087F0>
put item4
register_user user2 pass2
pwd
add_item_property item5 key4=val1 key10=val6 key7=val4 key1=val8 
register_user user6 pass6
which_group
sign_in a4 pa4
help current_folder
show_items
sign_in user8 pass8
buy
help show_items
current_folder
ls
sign_out
register_admin user3 pass3
register_admin user6 pass6
create_folder folder5
rename_user user4 <function generate_user at 0x027087F0>
show_items
rename_user user4 <function generate_user at 0x027087F0>
help view_order
sign_out
show_folders
add_item item1 key2=val3 key5=val10 key7=val9 key8=val10 
ls
buy
add_item_property item5 key5=val10 key9=val1 key6=val1 key1=val2 
show_items
ls_folders
rename_user user6 <function generate_user at 0x027087F0>
ls
which_group
rename_user user0 <function generate_user at 0x027087F0>
put item1
put item2
create_folder folder2
sign_out
sign_out
rename_user user8 <function generate_user at 0x027087F0>
which_group
show_users
help history
sign_in a4 pa4
sign_out
register_admin user8 pass8
sign_in a1 pa1
register_user user1 pass1
pwd
buy
buy
sign_out
add_item item4 key9=val5 key5=val7 key6=val2 key2=val2 
rename_user user8 <function generate_user at 0x027087F0>
put item5
show_users
ls_folders
buy
create_folder folder4
current_folder
which_group
which_group
help buy
whoami
sign_out
show_item_properties item5
sign_in a1 pa1
which_group
create_folder folder5
show_item_properties item2
sign_in a5 pa5
register_user user1 pass1
sign_in a5 pa5
whoami
rename_user user2 <function generate_user at 0x027087F0>
show_users
show_folders
help create_folder
add_item item4 key7=val1 key6=val6 key8=val8 key4=val9 
sign_in a1 pa1
help show_folders
which_group
add_item item1 key4=val1 key6=val5 key5=val9 key1=val5 
cd folder1
put item5
show_items
whoami
cd folder1
show_folders
create_folder folder2
create_folder folder2
show_folders
show_items
register_user user2 pass2
put item4
current_folder
register_user user6 pass6
pwd
pwd
register_user user7 pass7
create_folder folder2
show_users
ls_folders
create_folder folder5
put item3
put item2
register_user user5 pass5
register_admin user4 pass4
help put
ls_folders
rename_user user0 <function generate_user at 0x027087F0>
register_admin user2 pass2
help pwd
buy
whoami
show_folders
add_item_property item2 key1=val6 key7=val7 key7=val5 key10=val4 
sign_in a5 pa5
add_item_property item3 key2=val5 key1=val5 key1=val8 key8=val8 
put item5
add_item_property item4 key3=val2 key2=val10 key10=val5 key8=val2 
show_item_properties item3
buy
cd folder1
rename_user user8 <function generate_user at 0x027087F0>
whoami
register_user user2 pass2
put item5
whoami
whoami
create_folder folder1
pwd
whoami
register_admin admin admin
ls_folders
show_folders
add_item_property item3 key2=val3 key3=val7 key9=val7 key6=val8 
register_admin admin admin
pwd
put item4
show_items
rename_user user0 <function generate_user at 0x027087F0>
put item3
register_admin user7 pass7
pwd
whoami
show_items
which_group
show_users
register_admin user8 pass8
show_folders
register_user user2 pass2
create_folder folder2
add_item_property item2 key2=val5 key7=val5 key10=val2 key1=val3 
show_item_properties item1
show_users
add_item item5 key6=val2 key2=val5 key4=val8 key3=val9 
sign_out
sign_in user7 pass7
which_group
cd folder3
create_folder folder4
show_folders
register_user user1 pass1
add_item item4 key3=val1 key4=val1 key6=val8 key9=val10 
pwd
show_item_properties item4
show_folders
show_folders
which_group
create_folder folder3
sign_out
current_folder
sign_in user4 pass4
sign_out
ls
show_users
cd folder5
cd folder3
whoami
cd folder2
which_group
current_folder
whoami
sign_in user5 pass5
show_items
sign_in a3 pa3
add_item item2 key7=val2 key6=val3 key5=val1 key5=val3 
whoami
sign_in a2 pa2
add_item_property item5 key8=val4 key3=val2 key9=val9 key8=val2 
rename_user user7 <function generate_user at 0x027087F0>
add_item item4 key8=val2 key7=val2 key1=val8 key7=val1 
show_folders
show_users
add_item_property item3 key2=val10 key9=val3 key2=val9 key2=val8 
add_item_property item4 key5=val1 key1=val10 key6=val7 key4=val2 
add_item item5 key8=val9 key10=val5 key5=val10 key7=val3 
sign_in user7 pass7
register_user user8 pass8
add_item_property item4 key9=val2 key2=val7 key10=val9 key6=val2 
create_folder folder2
help register_admin
sign_in a2 pa2
which_group
sign_in user7 pass7
put item3
ls_folders
rename_user user8 <function generate_user at 0x027087F0>
buy
current_folder
create_folder folder4
show_folders
buy
pwd
cd folder4
ls_folders
ls
sign_in user4 pass4
ls
current_folder
rename_user user1 <function generate_user at 0x027087F0>
ls
ls
sign_in a4 pa4
rename_user user7 <function generate_user at 0x027087F0>
rename_user user2 <function generate_user at 0x027087F0>
add_item item3 key1=val4 key9=val10 key4=val3 key9=val4 
sign_out
show_users
help add_item_property
show_items
buy
current_folder
show_items
current_folder
show_items
show_items
show_items
register_user user7 pass7
show_items
rename_user user4 <function generate_user at 0x027087F0>
which_group
buy
current_folder
add_item_property item3 key2=val7 key3=val3 key2=val4 key5=val5 
current_folder
buy
buy
sign_in user1 pass1
sign_in a1 pa1
buy
sign_in user8 pass8
show_folders
which_group
sign_in user3 pass3
sign_out
create_folder folder2
which_group
sign_in user1 pass1
show_folders
sign_in a3 pa3
help exit
sign_in user5 pass5
put item2
rename_user user7 <function generate_user at 0x027087F0>
show_folders
show_item_properties item2
show_folders
sign_out
current_folder
cd folder5
show_folders
show_folders
put item4
current_folder
which_group
register_user user8 pass8
pwd
help delete_user
register_user user6 pass6
register_user user5 pass5
show_users
sign_out
show_folders
add_item item4 key9=val6 key4=val8 key8=val10 key9=val7 
add_item item5 key10=val2 key2=val1 key10=val7 key5=val4 
create_folder folder5
show_items
show_items
ls_folders
create_folder folder3
show_users
current_folder
cd folder2
add_item item1 key5=val2 key8=val7 key6=val8 key7=val7 
ls
add_item_property item3 key10=val1 key8=val7 key5=val10 key9=val1 
show_users
add_item item4 key4=val9 key1=val1 key9=val10 key6=val2 
show_items
show_items
ls_folders
show_item_properties item1
show_item_properties item4
sign_in user2 pass2
buy
show_folders
buy
put item4
register_user user5 pass5
whoami
help view_order
show_users
help help
sign_in user7 pass7
show_users
sign_in user3 pass3
buy
cd folder1
register_admin user5 pass5
sign_in user3 pass3
whoami
cd folder2
ls
show_folders
whoami
buy
show_item_properties item5
show_items
register_user user9 pass9
show_users
put item4
create_folder folder4
put item1
current_folder
register_admin user8 pass8
show_items
ls_folders
add_item item2 key3=val6 key7=val7 key4=val7 key7=val7 
which_group
sign_out
cd folder5
create_folder folder4
help add_item_property
ls_folders
current_folder
register_admin admin admin
buy
show_folders
create_folder folder3
cd folder2
add_item item5 key7=val10 key9=val2 key2=val5 key2=val7 
sign_in a1 pa1
cd folder2
register_user user5 pass5
add_item_property item5 key10=val9 key4=val6 key7=val2 key4=val2 
sign_out
show_item_properties item1
pwd
show_folders
current_folder
rename_user user3 <function generate_user at 0x027087F0>
whoami
help put
add_item item4 key8=val1 key8=val6 key3=val8 key5=val1 
register_user user8 pass8
put item3
pwd
sign_in user1 pass1
sign_in a3 pa3
put item5
current_folder
which_group
show_folders
help create_folder
register_user user9 pass9
show_users
ls_folders
sign_in user7 pass7
current_folder
buy
whoami
register_admin user2 pass2
which_group
register_user user9 pass9
ls
which_group
show_item_properties item4
show_folders
sign_out
current_folder
which_group
help show_item_properties
add_item_property item1 key8=val8 key8=val9 key9=val5 key3=val7 
ls_folders
sign_out
sign_in user7 pass7
which_group
cd folder3
put item4
buy
register_admin admin admin
current_folder
show_items
cd folder2
add_item item1 key9=val4 key8=val4 key7=val9 key1=val10 
show_items
ls_folders
ls
put item5
add_item_property item2 key5=val2 key5=val3 key4=val5 key5=val1 
register_admin user7 pass7
show_items
rename_user user2 <function generate_user at 0x027087F0>
sign_in user2 pass2
sign_in a5 pa5
rename_user user0 <function generate_user at 0x027087F0>
ls
whoami
sign_out
register_user user8 pass8
add_item_property item3 key3=val2 key3=val9 key5=val1 key7=val6 
sign_in a1 pa1
register_admin admin admin
which_group
create_folder folder1
sign_out
add_item_property item2 key1=val5 key6=val4 key1=val10 key6=val5 
sign_in user2 pass2
show_users
add_item_property item4 key9=val5 key10=val3 key8=val4 key3=val7 
add_item_property item1 key10=val1 key2=val10 key3=val6 key2=val2 
whoami
create_folder folder1
sign_in user9 pass9
register_user user6 pass6
put item1
put item2
ls
which_group
show_items
create_folder folder4
create_folder folder2
whoami
buy
show_item_properties item3
whoami
show_item_properties item3
put item1
show_folders
help exit
ls_folders
put item2
create_folder folder2
show_item_properties item2
ls
put item3
sign_in user5 pass5
register_admin user4 pass4
cd folder3
show_item_properties item5
add_item item1 key2=val5 key7=val9 key8=val10 key2=val2 
show_item_properties item4
sign_out
show_users
register_user user5 pass5
cd folder5
sign_in user6 pass6
register_admin user3 pass3
cd folder4
register_admin user9 pass9
ls
add_item_property item5 key8=val6 key8=val2 key8=val4 key7=val3 
sign_in admin admin
sign_out
rename_user user3 <function generate_user at 0x027087F0>
pwd
current_folder
show_users
create_folder folder5
help delete_user
register_admin user6 pass6
cd folder2
cd folder4
help sign_in
buy
current_folder
ls
ls_folders
cd folder2
show_items
sign_in a1 pa1
current_folder
register_user user1 pass1
show_users
register_admin user3 pass3
current_folder
which_group
rename_user user1 <function generate_user at 0x027087F0>
current_folder
sign_in a4 pa4
whoami
help register_user
show_items
ls
put item5
add_item_property item5 key1=val10 key4=val2 key1=val9 key6=val10 
sign_in a1 pa1
cd folder5
put item2
put item3
show_users
show_items
sign_out
register_admin user1 pass1
pwd
whoami
cd folder5
create_folder folder5
cd folder4
show_folders
ls
whoami
add_item_property item1 key3=val4 key4=val8 key9=val7 key2=val3 
ls
show_users
register_user user2 pass2
current_folder
register_admin user4 pass4
current_folder
sign_in a5 pa5
ls
create_folder folder4
pwd
sign_in user1 pass1
show_users
ls_folders
rename_user user7 <function generate_user at 0x027087F0>
add_item_property item2 key6=val6 key9=val4 key1=val8 key9=val1 
create_folder folder1
cd folder3
cd folder5
which_group
whoami
pwd
sign_in user6 pass6
buy
add_item item3 key3=val1 key10=val3 key2=val9 key6=val8 
register_user user9 pass9
show_folders
register_admin user9 pass9
register_admin user2 pass2
show_item_properties item3
sign_in user2 pass2
sign_in a5 pa5
show_items
rename_user user4 <function generate_user at 0x027087F0>
sign_in a3 pa3
register_admin user1 pass1
add_item_property item2 key2=val3 key4=val5 key6=val7 key2=val5 
create_folder folder3
add_item item4 key10=val9 key1=val6 key4=val9 key9=val3 
sign_out
cd folder1
help current_folder
sign_in a4 pa4
sign_in user7 pass7
whoami
current_folder
put item1
help add_item_property
register_user user9 pass9
show_item_properties item2
create_folder folder5
put item4
current_folder
sign_out
current_folder
whoami
current_folder
sign_in a3 pa3
help show_folders
which_group
register_user user2 pass2
help create_folder
put item3
cd folder1
rename_user user2 <function generate_user at 0x027087F0>
ls
which_group
add_item_property item1 key3=val10 key7=val4 key7=val3 key8=val2 
create_folder folder4
sign_in user6 pass6
register_user user1 pass1
ls
show_item_properties item3
add_item item2 key4=val9 key10=val6 key10=val6 key3=val8 
put item2
sign_in a2 pa2
register_admin user2 pass2
cd folder3
ls_folders
pwd
show_items
add_item_property item5 key8=val6 key7=val2 key7=val5 key9=val9 
which_group
rename_user user9 <function generate_user at 0x027087F0>
put item4
show_users
show_items
cd folder2
create_folder folder1
sign_in user7 pass7
sign_in user6 pass6
register_user user4 pass4
cd folder4
cd folder2
show_item_properties item5
sign_in a2 pa2
add_item_property item1 key5=val9 key2=val3 key5=val4 key8=val4 
pwd
rename_user user9 <function generate_user at 0x027087F0>
add_item_property item2 key9=val10 key4=val8 key2=val6 key5=val5 
ls_folders
sign_in user8 pass8
show_folders
show_users
create_folder folder1
pwd
show_item_properties item5
rename_user user7 <function generate_user at 0x027087F0>
add_item item1 key5=val6 key5=val1 key3=val9 key8=val7 
register_user user2 pass2
cd folder3
pwd
current_folder
register_user admin admin
add_item_property item2 key7=val2 key10=val1 key9=val8 key1=val3 
current_folder
register_admin user7 pass7
show_item_properties item2
create_folder folder5
help cd
which_group
whoami
which_group
add_item item5 key6=val10 key6=val1 key2=val8 key1=val7 
register_user user5 pass5
ls
sign_in user8 pass8
buy
show_users
pwd
ls
buy
register_user user8 pass8
show_folders
buy
cd folder4
current_folder
add_item_property item5 key6=val4 key10=val6 key8=val3 key3=val9 
add_item item5 key1=val8 key4=val6 key5=val6 key9=val5 
add_item_property item4 key9=val3 key2=val3 key9=val3 key7=val1 
buy
show_items
show_users
buy
ls_folders
register_user user5 pass5
add_item_property item1 key2=val10 key3=val3 key2=val10 key1=val3 
show_folders
show_users
help buy
pwd
ls
ls_folders
which_group
show_items
create_folder folder3
put item5
pwd
help show_items
cd folder3
ls
sign_in a5 pa5
help add_item
buy
sign_in user3 pass3
cd folder5
show_folders
current_folder
whoami
whoami
show_item_properties item3
sign_in a1 pa1
sign_in user7 pass7
add_item_property item4 key7=val8 key5=val10 key3=val7 key1=val4 
register_user user9 pass9
show_folders
show_items
ls_folders
help view_order
add_item item3 key4=val3 key3=val4 key1=val5 key8=val4 
show_item_properties item2
whoami
buy
cd folder4
put item5
show_folders
cd folder2
current_folder
show_folders
put item1
create_folder folder2
ls_folders
help view_order
rename_user user0 <function generate_user at 0x027087F0>
show_users
show_folders
pwd
ls_folders
sign_in user8 pass8
buy
pwd
register_admin user5 pass5
which_group
pwd
show_item_properties item2
register_admin user6 pass6
sign_in user3 pass3
show_item_properties item1
current_folder
sign_in user9 pass9
sign_in a1 pa1
rename_user user0 <function generate_user at 0x027087F0>
add_item item4 key2=val7 key7=val1 key4=val9 key7=val3 
put item1
create_folder folder1
register_admin user7 pass7
sign_in a2 pa2
buy
rename_user user3 <function generate_user at 0x027087F0>
pwd
show_items
ls_folders
add_item item5 key4=val6 key3=val8 key1=val10 key2=val1 
register_admin user9 pass9
ls
create_folder folder4
create_folder folder4
ls
show_folders
create_folder folder3
show_items
pwd
add_item_property item4 key9=val9 key5=val7 key3=val3 key8=val1 
show_folders
add_item item1 key1=val8 key4=val10 key8=val4 key10=val1 
show_users
sign_in a4 pa4
sign_in a4 pa4
cd folder1
show_folders
ls_folders
ls
which_group
current_folder
add_item item5 key2=val10 key2=val6 key1=val8 key3=val9 
ls_folders
register_admin user3 pass3
sign_out
sign_in user2 pass2
sign_out
add_item item4 key8=val6 key6=val7 key6=val4 key10=val3 
register_user user2 pass2
help add_item
register_admin user6 pass6
put item4
sign_in a1 pa1
register_user user9 pass9
register_admin user2 pass2
whoami
add_item item3 key10=val6 key6=val2 key7=val8 key2=val6 
sign_out
buy
buy
show_items
current_folder
show_folders
show_users
sign_in user2 pass2
ls
sign_out
show_item_properties item3
ls_folders
show_users
help view_order
show_items
sign_out
register_admin user9 pass9
register_admin user5 pass5
sign_out
rename_user user8 <function generate_user at 0x027087F0>
ls_folders
put item4
add_item item5 key6=val6 key4=val1 key4=val1 key1=val6 
buy
rename_user user2 <function generate_user at 0x027087F0>
add_item_property item2 key6=val2 key2=val9 key9=val2 key2=val9 
buy
which_group
register_admin user2 pass2
sign_in a5 pa5
sign_out
whoami
cd folder2
help current_folder
cd folder2
show_folders
create_folder folder5
rename_user user6 <function generate_user at 0x027087F0>
which_group
register_user user8 pass8
pwd
show_item_properties item4
put item1
rename_user user2 <function generate_user at 0x027087F0>
add_item item1 key8=val9 key4=val6 key4=val1 key3=val7 
sign_out
show_folders
add_item_property item3 key5=val8 key9=val4 key3=val8 key6=val8 
register_admin user3 pass3
put item4
pwd
show_items
show_folders
cd folder5
sign_in a4 pa4
add_item_property item2 key10=val1 key4=val1 key3=val10 key1=val4 
cd folder3
show_users
show_item_properties item2
cd folder5
create_folder folder3
pwd
sign_out
which_group
which_group
cd folder4
show_folders
register_admin user9 pass9
sign_out
rename_user user6 <function generate_user at 0x027087F0>
rename_user user1 <function generate_user at 0x027087F0>
whoami
show_users
add_item item5 key3=val2 key4=val2 key4=val6 key1=val2 
help current_folder
show_item_properties item4
which_group
sign_in a5 pa5
pwd
register_admin user3 pass3
sign_in a4 pa4
sign_in a3 pa3
show_item_properties item1
show_items
show_folders
add_item item2 key6=val7 key3=val1 key5=val6 key6=val1 
add_item item3 key3=val4 key9=val1 key6=val9 key1=val7 
show_items
help whoami
show_folders
create_folder folder3
show_folders
create_folder folder4
ls
current_folder
sign_in admin admin
whoami
sign_out
put item4
help which_group
show_folders
ls_folders
cd folder4
current_folder
put item2
buy
which_group
cd folder2
register_admin user7 pass7
show_items
add_item_property item1 key5=val10 key10=val3 key7=val7 key3=val5 
show_folders
create_folder folder2
create_folder folder5
help rename_user
create_folder folder1
show_folders
add_item_property item1 key5=val4 key3=val2 key5=val6 key8=val4 
show_item_properties item2
show_item_properties item2
ls
help put
current_folder
sign_in user8 pass8
buy
show_item_properties item1
sign_in user8 pass8
sign_in admin admin
which_group
which_group
show_users
current_folder
cd folder4
pwd
sign_out
register_user user7 pass7
ls
pwd
sign_out
add_item item2 key8=val1 key7=val5 key6=val5 key4=val8 
sign_in user9 pass9
sign_in user3 pass3
rename_user user2 <function generate_user at 0x027087F0>
sign_out
register_admin user1 pass1
register_admin user2 pass2
ls_folders
register_user user2 pass2
help sign_out
show_items
current_folder
sign_in a1 pa1
show_folders
cd folder4
add_item item1 key3=val2 key8=val7 key8=val2 key9=val6 
current_folder
put item5
ls
add_item_property item1 key3=val3 key8=val5 key5=val9 key9=val2 
add_item_property item2 key7=val4 key3=val4 key2=val10 key4=val5 
show_users
pwd
current_folder
help put
help exit
register_user user3 pass3
show_items
create_folder folder1
put item4
register_user user8 pass8
which_group
pwd
pwd
current_folder
pwd
whoami
sign_out
pwd
register_admin user3 pass3
buy
current_folder
help show_item_properties
register_admin user3 pass3
show_users
show_users
add_item item5 key8=val8 key4=val9 key2=val3 key8=val1 
show_folders
rename_user user9 <function generate_user at 0x027087F0>
show_items
buy
sign_in user2 pass2
add_item item1 key5=val3 key3=val7 key3=val8 key2=val3 
ls
which_group
buy
register_admin user1 pass1
whoami
add_item item2 key7=val7 key8=val5 key7=val2 key9=val4 
register_user user3 pass3
which_group
put item4
sign_out
create_folder folder1
sign_out
whoami
cd folder2
whoami
add_item_property item3 key2=val10 key1=val8 key5=val10 key7=val3 
add_item_property item5 key3=val7 key8=val4 key6=val2 key3=val9 
show_users
sign_in a4 pa4
pwd
rename_user user2 <function generate_user at 0x027087F0>
add_item item5 key8=val5 key4=val4 key10=val8 key6=val5 
add_item item2 key7=val3 key9=val7 key7=val6 key3=val5 
sign_in user7 pass7
register_admin user5 pass5
show_item_properties item2
register_admin user7 pass7
whoami
help sign_in
show_item_properties item2
which_group
buy
ls_folders
ls_folders
register_admin user3 pass3
show_item_properties item1
put item5
sign_out
help create_folder
register_admin user1 pass1
sign_out
ls_folders
show_folders
show_folders
register_user user2 pass2
show_users
ls_folders
which_group
put item5
cd folder3
put item3
show_item_properties item3
show_users
buy
add_item_property item1 key8=val5 key8=val10 key8=val6 key3=val9 
ls
add_item_property item4 key9=val9 key4=val5 key6=val5 key3=val6 
help show_items
help pwd
rename_user user0 <function generate_user at 0x027087F0>
create_folder folder4
sign_in user9 pass9
create_folder folder3
ls_folders
whoami
sign_in admin admin
register_user user9 pass9
buy
add_item_property item5 key5=val10 key6=val4 key7=val7 key2=val7 
register_user user6 pass6
sign_in user8 pass8
buy
put item1
cd folder3
show_users
buy
rename_user user4 <function generate_user at 0x027087F0>
add_item item3 key6=val5 key8=val6 key8=val10 key8=val8 
create_folder folder4
buy
help rename_user
register_user user2 pass2
show_users
help whoami
sign_in a4 pa4
pwd
which_group
create_folder folder5
show_folders
add_item item1 key8=val10 key9=val1 key1=val4 key5=val10 
current_folder
help sign_in
put item2
sign_in user9 pass9
current_folder
rename_user user8 <function generate_user at 0x027087F0>
put item2
pwd
sign_in a5 pa5
current_folder
show_items
rename_user user1 <function generate_user at 0x027087F0>
current_folder
ls
add_item item3 key10=val2 key6=val3 key10=val1 key4=val1 
sign_in user4 pass4
rename_user user2 <function generate_user at 0x027087F0>
help register_admin
ls_folders
which_group
help exit
sign_in user6 pass6
help show_items
sign_out
ls_folders
pwd
sign_in a1 pa1
rename_user user8 <function generate_user at 0x027087F0>
current_folder
show_item_properties item2
buy
show_folders
rename_user user2 <function generate_user at 0x027087F0>
sign_out
show_users
put item1
create_folder folder4
sign_out
ls
register_admin user7 pass7
sign_in a5 pa5
whoami
sign_in admin admin
show_items
ls_folders
register_user user7 pass7
ls
show_item_properties item2
create_folder folder1
put item4
create_folder folder1
help history
add_item item4 key2=val9 key9=val3 key4=val8 key9=val8 
help sign_in
add_item item1 key5=val8 key6=val4 key7=val9 key3=val3 
show_users
add_item_property item1 key2=val8 key6=val2 key6=val3 key5=val7 
ls
current_folder
put item2
cd folder5
ls_folders
current_folder
show_folders
put item3
sign_in user9 pass9
register_admin user4 pass4
show_items
ls
sign_in a2 pa2
sign_in a3 pa3
register_admin user8 pass8
ls
show_users
sign_out
register_user user4 pass4
ls_folders
show_users
put item2
put item5
whoami
sign_out
put item1
help exit
cd folder2
pwd
show_items
buy
which_group
show_item_properties item2
sign_out
which_group
sign_in user2 pass2
current_folder
pwd
which_group
ls
current_folder
ls_folders
cd folder3
current_folder
show_items
show_item_properties item2
sign_out
put item2
add_item_property item3 key9=val3 key2=val3 key1=val1 key5=val6 
ls_folders
pwd
help show_users
pwd
create_folder folder2
show_users
current_folder
register_user user1 pass1
show_users
current_folder
buy
ls_folders
register_user user6 pass6
add_item item1 key10=val2 key9=val6 key5=val1 key10=val2 
show_item_properties item1
ls
current_folder
pwd
rename_user user1 <function generate_user at 0x027087F0>
cd folder3
buy
which_group
show_users
sign_in a4 pa4
ls
register_user user6 pass6
current_folder
sign_out
add_item_property item3 key10=val1 key6=val3 key6=val8 key5=val10 
sign_in a5 pa5
ls
buy
ls_folders
help rename_user
help sign_out
pwd
buy
add_item_property item1 key7=val7 key5=val5 key2=val3 key7=val7 
current_folder
create_folder folder3
cd folder5
cd folder4
create_folder folder2
show_items
show_item_properties item3
ls_folders
whoami
which_group
show_users
put item5
show_folders
add_item_property item3 key6=val3 key9=val1 key9=val10 key7=val3 
cd folder3
which_group
rename_user user7 <function generate_user at 0x027087F0>
pwd
add_item item5 key7=val1 key3=val7 key9=val9 key1=val5 
pwd
which_group
whoami
show_users
ls_folders
whoami
show_users
help put
register_admin user4 pass4
register_user user8 pass8
add_item item1 key7=val2 key1=val1 key3=val2 key6=val3 
cd folder2
which_group
help delete_user
which_group
show_items
current_folder
create_folder folder4
show_items
add_item item2 key3=val3 key4=val7 key9=val1 key10=val1 
show_items
show_users
sign_out
cd folder1
current_folder
rename_user user8 <function generate_user at 0x027087F0>
cd folder3
add_item item5 key4=val10 key8=val10 key6=val10 key2=val4 
sign_in user6 pass6
sign_out
pwd
help show_items
put item3
which_group
put item4
register_user user1 pass1
sign_in user9 pass9
show_folders
put item3
which_group
current_folder
ls
ls_folders
pwd
buy
register_user user6 pass6
register_admin user3 pass3
show_folders
rename_user user4 <function generate_user at 0x027087F0>
sign_in user6 pass6
sign_in a3 pa3
whoami
sign_in a5 pa5
ls_folders
register_admin user2 pass2
show_items
rename_user user8 <function generate_user at 0x027087F0>
buy
pwd
show_items
register_admin admin admin
ls
which_group
ls_folders
show_folders
add_item_property item4 key9=val9 key1=val4 key3=val1 key2=val5 
ls_folders
current_folder
buy
create_folder folder1
show_users
help show_users
sign_out
sign_out
register_user admin admin
pwd
register_user user7 pass7
register_user user5 pass5
show_users
sign_in user9 pass9
ls_folders
cd folder5
ls
ls_folders
add_item item2 key4=val6 key9=val8 key8=val1 key10=val1 
show_users
sign_in user2 pass2
buy
show_folders
put item5
create_folder folder3
sign_in user8 pass8
sign_in a4 pa4
sign_in a5 pa5
sign_in a5 pa5
show_items
create_folder folder5
put item2
sign_in a5 pa5
help view_order
ls_folders
put item5
sign_in user6 pass6
register_admin user2 pass2
buy
buy
show_folders
show_item_properties item2
pwd
show_items
ls
which_group
rename_user user4 <function generate_user at 0x027087F0>
create_folder folder2
sign_out
show_folders
pwd
add_item item5 key3=val4 key6=val10 key2=val5 key4=val4 
register_admin user1 pass1
add_item_property item5 key5=val1 key1=val6 key6=val2 key9=val10 
ls_folders
register_admin user6 pass6
register_user user2 pass2
rename_user user0 <function generate_user at 0x027087F0>
buy
current_folder
sign_out
help cd
rename_user user3 <function generate_user at 0x027087F0>
add_item_property item3 key3=val8 key7=val2 key5=val6 key9=val2 
ls_folders
sign_in a3 pa3
pwd
cd folder3
register_user user4 pass4
current_folder
sign_in a5 pa5
show_folders
register_admin user9 pass9
add_item item1 key4=val4 key2=val6 key7=val5 key5=val2 
buy
show_users
current_folder
ls
help help
pwd
cd folder3
which_group
ls_folders
sign_in a5 pa5
cd folder3
current_folder
register_user user1 pass1
help show_users
ls_folders
sign_in user4 pass4
show_folders
add_item_property item2 key7=val3 key5=val4 key7=val5 key10=val3 
sign_in user5 pass5
show_folders
current_folder
ls
cd folder4
sign_in a5 pa5
cd folder4
show_users
which_group
whoami
add_item item4 key7=val10 key6=val2 key3=val2 key2=val5 
put item4
rename_user user7 <function generate_user at 0x027087F0>
current_folder
help pwd
pwd
register_user user2 pass2
sign_in user8 pass8
current_folder
buy
cd folder2
add_item item3 key4=val8 key4=val5 key10=val5 key9=val7 
sign_in a5 pa5
add_item_property item5 key4=val5 key9=val10 key9=val9 key6=val10 
show_items
add_item_property item5 key8=val9 key5=val2 key1=val8 key2=val9 
register_admin user3 pass3
show_folders
help show_users
add_item item3 key5=val9 key3=val7 key10=val4 key2=val9 
show_items
ls
register_user admin admin
cd folder4
sign_out
rename_user user1 <function generate_user at 0x027087F0>
which_group
put item4
ls_folders
cd folder5
show_item_properties item2
create_folder folder3
rename_user user5 <function generate_user at 0x027087F0>
put item1
which_group
ls_folders
rename_user user5 <function generate_user at 0x027087F0>
show_users
register_user user9 pass9
sign_out
show_folders
rename_user user9 <function generate_user at 0x027087F0>
pwd
add_item item4 key10=val5 key4=val3 key7=val6 key8=val4 
show_folders
put item2
pwd
whoami
ls_folders
rename_user user9 <function generate_user at 0x027087F0>
rename_user user5 <function generate_user at 0x027087F0>
register_admin user5 pass5
whoami
cd folder3
register_admin user7 pass7
current_folder
rename_user user9 <function generate_user at 0x027087F0>
create_folder folder3
sign_in a1 pa1
rename_user user1 <function generate_user at 0x027087F0>
whoami
buy
add_item_property item3 key6=val3 key9=val10 key3=val9 key2=val8 
pwd
put item3
sign_in a4 pa4
ls_folders
rename_user user4 <function generate_user at 0x027087F0>
sign_out
whoami
register_admin user2 pass2
register_admin user3 pass3
put item4
create_folder folder4
ls
show_users
sign_out
show_items
cd folder1
show_folders
add_item_property item3 key3=val6 key7=val5 key2=val10 key7=val9 
sign_in admin admin
create_folder folder4
buy
help history
cd folder3
ls
pwd
help create_folder
whoami
register_admin user7 pass7
sign_in a2 pa2
show_item_properties item4
sign_in user7 pass7
buy
show_items
show_item_properties item3
ls_folders
create_folder folder3
which_group
ls_folders
add_item_property item3 key8=val2 key9=val5 key6=val2 key6=val7 
register_user user1 pass1
cd folder4
show_users
sign_in user4 pass4
add_item_property item2 key10=val5 key4=val4 key10=val9 key8=val3 
show_folders
sign_out
create_folder folder1
show_users
rename_user user8 <function generate_user at 0x027087F0>
pwd
ls
add_item item1 key8=val2 key1=val10 key1=val3 key5=val1 
sign_in user9 pass9
show_folders
show_users
rename_user user4 <function generate_user at 0x027087F0>
show_items
buy
which_group
show_item_properties item2
show_item_properties item4
ls_folders
sign_in a4 pa4
put item2
show_users
ls_folders
show_item_properties item1
put item3
pwd
rename_user user1 <function generate_user at 0x027087F0>
show_folders
show_users
add_item_property item2 key1=val5 key9=val6 key8=val9 key4=val10 
put item2
help sign_out
show_folders
show_item_properties item3
add_item item2 key1=val1 key7=val1 key7=val8 key8=val9 
current_folder
buy
add_item_property item2 key3=val7 key4=val4 key6=val2 key8=val10 
show_items
register_user user8 pass8
put item5
sign_out
show_items
add_item item5 key2=val1 key5=val7 key2=val5 key4=val8 
pwd
sign_in a2 pa2
sign_in user5 pass5
add_item_property item3 key8=val10 key6=val5 key6=val7 key6=val5 
show_users
pwd
sign_in user1 pass1
which_group
current_folder
buy
add_item item3 key9=val10 key2=val2 key9=val5 key7=val1 
ls_folders
show_items
show_item_properties item5
ls
ls
show_users
show_item_properties item2
current_folder
sign_in user2 pass2
sign_out
which_group
show_users
whoami
sign_out
show_folders
pwd
cd folder5
register_admin user6 pass6
which_group
whoami
add_item item2 key4=val4 key6=val9 key5=val8 key6=val6 
create_folder folder3
ls_folders
create_folder folder3
current_folder
create_folder folder4
put item3
show_item_properties item3
show_items
sign_out
ls
register_admin user7 pass7
add_item item5 key3=val1 key3=val4 key2=val1 key1=val4 
sign_out
cd folder1
pwd
show_folders
whoami
sign_in a5 pa5
put item2
ls_folders
add_item_property item5 key5=val5 key3=val4 key7=val1 key1=val10 
whoami
show_item_properties item2
show_item_properties item1
rename_user user2 <function generate_user at 0x027087F0>
show_folders
register_admin admin admin
show_users
register_admin user6 pass6
current_folder
create_folder folder4
ls
sign_in a3 pa3
rename_user user1 <function generate_user at 0x027087F0>
pwd
buy
create_folder folder3
buy
help add_item_property
help delete_user
current_folder
buy
pwd
put item4
ls
buy
which_group
ls
cd folder1
which_group
whoami
sign_in user1 pass1
create_folder folder5
add_item item1 key10=val2 key3=val1 key6=val8 key8=val8 
show_item_properties item3
show_item_properties item1
register_admin user9 pass9
show_folders
ls
ls_folders
cd folder2
current_folder
cd folder3
ls_folders
register_admin user2 pass2
show_items
show_folders
show_folders
register_user user7 pass7
add_item_property item5 key6=val10 key4=val2 key5=val3 key7=val8 
current_folder
cd folder2
add_item_property item3 key8=val2 key10=val9 key5=val1 key5=val1 
create_folder folder5
show_item_properties item2
sign_in a3 pa3
sign_in user8 pass8
sign_in user9 pass9
ls_folders
buy
whoami
buy
cd folder5
ls_folders
show_users
show_folders
current_folder
show_items
show_folders
sign_out
show_users
cd folder3
rename_user user2 <function generate_user at 0x027087F0>
ls_folders
register_user user9 pass9
buy
buy
whoami
add_item item1 key7=val4 key5=val10 key5=val6 key3=val6 
sign_in a1 pa1
ls
register_user user5 pass5
current_folder
show_users
sign_in user1 pass1
create_folder folder2
sign_in user9 pass9
ls_folders
show_item_properties item2
show_users
ls_folders
ls_folders
cd folder3
ls
show_items
current_folder
show_users
show_items
register_user admin admin
put item2
help sign_in
add_item_property item1 key6=val6 key3=val1 key9=val8 key1=val2 
rename_user user7 <function generate_user at 0x027087F0>
register_user user2 pass2
ls_folders
cd folder2
rename_user user2 <function generate_user at 0x027087F0>
ls
sign_in admin admin
add_item item3 key5=val1 key9=val5 key4=val5 key1=val3 
register_admin user9 pass9
ls
show_item_properties item2
add_item_property item4 key8=val7 key1=val3 key7=val9 key1=val3 
whoami
show_folders
sign_out
add_item_property item1 key5=val4 key2=val4 key5=val10 key7=val7 
help buy
register_user user9 pass9
help register_user
current_folder
create_folder folder3
current_folder
show_folders
whoami
which_group
ls_folders
sign_in a3 pa3
whoami
show_users
show_item_properties item4
buy
add_item_property item1 key6=val6 key6=val6 key9=val10 key6=val4 
register_admin user6 pass6
register_user user3 pass3
put item5
cd folder3
show_item_properties item5
create_folder folder3
show_folders
sign_in user1 pass1
ls
register_admin user6 pass6
add_item item2 key10=val9 key1=val7 key7=val10 key9=val2 
pwd
rename_user user0 <function generate_user at 0x027087F0>
show_item_properties item5
buy
register_admin user7 pass7
cd folder5
add_item item3 key10=val6 key3=val5 key7=val6 key2=val7 
show_folders
sign_out
current_folder
put item1
ls
register_admin user9 pass9
pwd
buy
show_item_properties item3
which_group
help create_folder
sign_in user8 pass8
show_folders
sign_out
create_folder folder2
show_item_properties item5
help pwd
show_users
add_item item2 key6=val7 key5=val5 key7=val7 key6=val10 
add_item item2 key1=val7 key4=val9 key4=val2 key8=val7 
add_item item5 key1=val8 key8=val5 key1=val8 key8=val1 
whoami
ls_folders
ls_folders
rename_user user5 <function generate_user at 0x027087F0>
which_group
show_folders
rename_user user6 <function generate_user at 0x027087F0>
pwd
sign_out
pwd
cd folder4
rename_user user9 <function generate_user at 0x027087F0>
show_item_properties item4
put item1
show_items
register_admin user7 pass7
register_admin user8 pass8
show_item_properties item4
add_item_property item3 key8=val3 key1=val3 key1=val10 key8=val4 
ls
sign_in a5 pa5
ls_folders
buy
add_item item5 key1=val9 key8=val10 key4=val2 key8=val7 
register_admin user8 pass8
help rename_user
show_folders
whoami
register_user user8 pass8
show_items
register_user user9 pass9
sign_in user2 pass2
show_items
cd folder4
add_item item2 key9=val3 key4=val7 key5=val4 key5=val6 
current_folder
buy
register_admin admin admin
sign_in a1 pa1
ls
show_folders
sign_in a2 pa2
register_user user4 pass4
register_user user1 pass1
sign_in user4 pass4
which_group
ls_folders
whoami
register_user user4 pass4
which_group
ls_folders
put item5
cd folder5
put item1
ls
sign_in a5 pa5
show_folders
cd folder5
add_item item3 key2=val10 key8=val8 key7=val3 key3=val1 
whoami
buy
help show_folders
put item2
buy
buy
register_admin user4 pass4
help help
cd folder2
show_folders
show_item_properties item1
put item3
show_users
sign_in user3 pass3
sign_out
show_items
buy
sign_out
show_folders
which_group
ls
sign_in a2 pa2
show_users
show_folders
show_items
buy
buy
whoami
ls
add_item_property item2 key8=val3 key8=val3 key3=val4 key6=val7 
ls_folders
register_user user6 pass6
show_item_properties item3
which_group
show_item_properties item4
cd folder4
put item2
which_group
put item5
pwd
whoami
buy
sign_in a3 pa3
pwd
ls
ls_folders
create_folder folder2
whoami
current_folder
sign_out
pwd
whoami
show_users
help show_folders
sign_in user7 pass7
rename_user user8 <function generate_user at 0x027087F0>
sign_out
create_folder folder4
sign_out
pwd
add_item item3 key9=val5 key4=val1 key4=val8 key6=val10 
pwd
add_item item2 key5=val3 key4=val6 key3=val10 key2=val3 
help delete_user
add_item_property item4 key4=val4 key5=val2 key9=val2 key10=val7 
show_users
ls_folders
pwd
sign_in user7 pass7
which_group
sign_in user5 pass5
show_folders
put item1
rename_user user9 <function generate_user at 0x027087F0>
add_item item1 key9=val10 key10=val1 key5=val3 key3=val8 
show_folders
ls
sign_out
current_folder
sign_in user3 pass3
show_users
add_item item3 key9=val2 key3=val4 key1=val10 key3=val5 
show_folders
sign_in a3 pa3
add_item item4 key10=val9 key4=val1 key2=val4 key4=val3 
sign_out
current_folder
cd folder3
sign_out
which_group
add_item item1 key7=val8 key7=val5 key1=val1 key2=val6 
current_folder
help buy
whoami
show_folders
which_group
pwd
sign_in user5 pass5
ls_folders
help show_users
sign_in a4 pa4
which_group
add_item item2 key2=val7 key5=val10 key8=val7 key1=val10 
sign_out
register_admin user1 pass1
pwd
pwd
register_user user5 pass5
pwd
put item5
sign_out
ls_folders
ls_folders
show_items
register_user user6 pass6
buy
which_group
put item4
show_folders
sign_out
put item3
show_items
ls
show_folders
add_item item2 key6=val8 key10=val3 key9=val5 key8=val8 
ls
show_users
show_item_properties item4
rename_user user0 <function generate_user at 0x027087F0>
add_item item4 key1=val9 key3=val9 key4=val7 key3=val5 
current_folder
whoami
sign_out
show_item_properties item4
show_users
show_item_properties item5
add_item_property item2 key1=val5 key2=val6 key4=val9 key10=val2 
register_user user2 pass2
sign_out
pwd
show_items
show_item_properties item1
current_folder
current_folder
show_folders
add_item item2 key1=val5 key8=val6 key7=val8 key1=val2 
add_item item1 key8=val3 key7=val7 key8=val3 key5=val7 
which_group
pwd
register_admin user2 pass2
show_item_properties item2
create_folder folder2
whoami
add_item_property item3 key2=val5 key7=val2 key8=val5 key7=val7 
sign_in a2 pa2
show_folders
show_folders
show_items
sign_out
which_group
which_group
sign_out
sign_in a4 pa4
create_folder folder3
put item5
sign_in a5 pa5
buy
register_user user3 pass3
show_item_properties item1
put item3
sign_in user4 pass4
sign_in a5 pa5
sign_in admin admin
show_users
show_items
ls
pwd
ls_folders
help delete_user
sign_out
rename_user user5 <function generate_user at 0x027087F0>
sign_in a4 pa4
ls_folders
show_items
put item1
rename_user user7 <function generate_user at 0x027087F0>
show_folders
show_item_properties item5
add_item item5 key2=val3 key1=val8 key9=val9 key3=val10 
sign_in user9 pass9
sign_in user9 pass9
ls_folders
ls_folders
sign_out
current_folder
cd folder1
which_group
current_folder
ls
ls
ls_folders
show_users
current_folder
whoami
show_users
cd folder4
register_user user5 pass5
register_user user7 pass7
put item1
help ls
add_item_property item5 key9=val6 key4=val10 key5=val10 key4=val6 
sign_in a2 pa2
rename_user user3 <function generate_user at 0x027087F0>
which_group
help add_item_property
cd folder4
register_user user7 pass7
sign_in user1 pass1
show_users
which_group
sign_out
add_item_property item2 key5=val10 key4=val3 key10=val6 key8=val9 
pwd
put item1
help exit
whoami
whoami
show_items
show_item_properties item4
current_folder
add_item_property item4 key9=val9 key5=val9 key4=val1 key4=val10 
register_user user9 pass9
ls
add_item_property item2 key5=val5 key10=val7 key9=val10 key3=val1 
buy
put item1
show_users
pwd
show_users
create_folder folder1
sign_in admin admin
register_admin user2 pass2
show_users
help help
help show_users
register_admin user4 pass4
rename_user user6 <function generate_user at 0x027087F0>
add_item_property item3 key2=val1 key1=val8 key4=val9 key10=val6 
register_user user7 pass7
put item3
add_item_property item4 key3=val9 key8=val6 key2=val6 key6=val10 
help add_item_property
put item1
create_folder folder4
ls
current_folder
sign_in user8 pass8
sign_in a5 pa5
sign_in admin admin
ls
put item5
pwd
register_admin user6 pass6
sign_in a4 pa4
sign_in user8 pass8
register_admin user5 pass5
show_items
show_item_properties item1
add_item item2 key9=val6 key6=val10 key4=val1 key8=val9 
add_item_property item2 key10=val7 key2=val9 key3=val2 key8=val4 
sign_in user5 pass5
sign_in a4 pa4
buy
buy
sign_out
sign_out
current_folder
create_folder folder5
create_folder folder1
register_user user7 pass7
buy
add_item item5 key6=val7 key7=val7 key5=val10 key4=val10 
put item4
register_user user4 pass4
rename_user user9 <function generate_user at 0x027087F0>
whoami
sign_in user6 pass6
show_item_properties item4
sign_in user4 pass4
put item5
add_item item2 key7=val2 key1=val2 key9=val3 key10=val9 
cd folder4
whoami
ls
whoami
add_item_property item5 key4=val6 key4=val8 key3=val1 key9=val7 
whoami
which_group
create_folder folder5
cd folder2
sign_out
show_folders
ls
sign_in a1 pa1
ls
show_item_properties item5
show_folders
show_users
show_users
which_group
register_user user4 pass4
register_user user2 pass2
show_item_properties item1
buy
current_folder
ls
show_items
help show_item_properties
register_user user8 pass8
whoami
show_items
register_user user7 pass7
ls
register_admin user7 pass7
put item5
show_items
pwd
cd folder4
sign_out
which_group
add_item_property item4 key8=val8 key3=val10 key7=val8 key2=val10 
show_item_properties item2
which_group
which_group
show_folders
whoami
buy
register_admin user6 pass6
which_group
whoami
pwd
pwd
buy
register_admin user5 pass5
current_folder
sign_in a1 pa1
show_users
pwd
sign_in user9 pass9
which_group
show_folders
pwd
whoami
ls_folders
ls_folders
current_folder
sign_in a2 pa2
show_folders
buy
ls_folders
ls
show_folders
show_users
cd folder3
which_group
cd folder3
show_item_properties item3
show_users
buy
show_item_properties item2
current_folder
pwd
show_item_properties item5
sign_in user8 pass8
pwd
whoami
show_folders
show_item_properties item4
create_folder folder3
show_item_properties item1
add_item_property item5 key5=val3 key7=val3 key4=val4 key3=val4 
ls
sign_out
add_item_property item4 key3=val6 key2=val1 key5=val8 key8=val9 
sign_in user4 pass4
register_admin user7 pass7
create_folder folder2
show_folders
show_users
cd folder1
current_folder
show_folders
pwd
ls
show_item_properties item2
sign_in a3 pa3
sign_in admin admin
buy
whoami
show_users
cd folder5
show_folders
which_group
add_item_property item3 key1=val3 key9=val2 key10=val7 key4=val2 
buy
cd folder5
register_admin user2 pass2
show_folders
help pwd
add_item_property item1 key8=val3 key7=val7 key3=val1 key4=val2 
sign_in user5 pass5
ls_folders
ls_folders
sign_out
show_folders
sign_in a4 pa4
sign_in user1 pass1
register_admin admin admin
cd folder4
show_folders
rename_user user1 <function generate_user at 0x027087F0>
sign_out
register_admin user9 pass9
register_admin user7 pass7
register_admin user2 pass2
put item4
sign_out
ls_folders
register_admin user8 pass8
sign_out
register_admin user9 pass9
help cd
which_group
show_item_properties item2
ls
help current_folder
sign_out
current_folder
buy
show_users
show_folders
register_admin user6 pass6
register_user user4 pass4
sign_in user2 pass2
help buy
show_folders
ls
show_users
put item5
current_folder
show_folders
sign_in user1 pass1
current_folder
show_users
show_items
rename_user user2 <function generate_user at 0x027087F0>
show_item_properties item2
register_user user2 pass2
cd folder1
show_items
register_admin admin admin
put item3
register_user user9 pass9
buy
show_item_properties item1
sign_in a1 pa1
which_group
ls
register_user user5 pass5
pwd
create_folder folder4
show_item_properties item2
ls_folders
add_item_property item5 key4=val3 key3=val5 key5=val4 key6=val8 
ls
sign_in a5 pa5
show_item_properties item3
show_users
ls
register_admin user5 pass5
whoami
show_item_properties item2
register_user user5 pass5
show_items
sign_in a2 pa2
add_item item4 key8=val2 key5=val4 key1=val2 key8=val1 
put item4
pwd
add_item item1 key5=val10 key7=val7 key4=val5 key4=val6 
ls_folders
create_folder folder3
show_users
cd folder4
register_user user4 pass4
current_folder
put item5
ls_folders
register_user user2 pass2
whoami
buy
show_users
cd folder1
ls
buy
rename_user user3 <function generate_user at 0x027087F0>
help history
sign_in a2 pa2
pwd
ls
buy
show_items
show_item_properties item4
show_item_properties item4
ls
register_admin user7 pass7
which_group
show_users
rename_user user3 <function generate_user at 0x027087F0>
show_items
sign_in a2 pa2
show_item_properties item2
show_item_properties item1
show_users
show_item_properties item1
register_user user4 pass4
sign_in a3 pa3
register_user user9 pass9
ls
show_users
ls_folders
add_item_property item5 key2=val3 key5=val9 key6=val1 key1=val7 
sign_in a3 pa3
create_folder folder5
pwd
cd folder2
register_admin user9 pass9
which_group
sign_in user5 pass5
pwd
ls
add_item item5 key2=val4 key7=val2 key7=val5 key4=val2 
pwd
pwd
put item2
show_item_properties item2
show_items
add_item item1 key9=val4 key5=val9 key10=val9 key7=val9 
rename_user user7 <function generate_user at 0x027087F0>
show_users
sign_out
show_folders
rename_user user5 <function generate_user at 0x027087F0>
put item2
show_items
sign_in a2 pa2
help cd
cd folder2
show_items
cd folder4
put item4
register_admin user3 pass3
sign_in user1 pass1
show_folders
create_folder folder1
create_folder folder4
show_users
show_folders
buy
sign_in a3 pa3
register_admin user6 pass6
add_item_property item4 key5=val1 key8=val2 key5=val5 key3=val8 
show_item_properties item2
rename_user user5 <function generate_user at 0x027087F0>
add_item_property item5 key6=val10 key1=val6 key1=val4 key2=val1 
create_folder folder2
show_users
whoami
current_folder
buy
cd folder5
ls_folders
register_admin user5 pass5
rename_user user2 <function generate_user at 0x027087F0>
show_item_properties item4
ls
whoami
ls_folders
register_user user7 pass7
sign_in a2 pa2
register_user user2 pass2
add_item item2 key5=val7 key8=val5 key6=val3 key3=val3 
show_users
register_admin user8 pass8
buy
help which_group
register_user user8 pass8
register_admin user6 pass6
sign_in a3 pa3
help show_users
create_folder folder4
create_folder folder3
register_user user6 pass6
sign_out
sign_in user4 pass4
pwd
cd folder4
register_user user9 pass9
register_admin user6 pass6
rename_user user6 <function generate_user at 0x027087F0>
rename_user user2 <function generate_user at 0x027087F0>
ls
add_item_property item5 key7=val5 key6=val7 key10=val7 key1=val10 
show_items
show_items
cd folder3
current_folder
sign_out
pwd
rename_user user7 <function generate_user at 0x027087F0>
register_user user2 pass2
pwd
sign_out
create_folder folder2
sign_out
whoami
which_group
current_folder
show_folders
rename_user user1 <function generate_user at 0x027087F0>
register_user user6 pass6
ls
show_items
rename_user user7 <function generate_user at 0x027087F0>
create_folder folder1
show_items
whoami
show_users
cd folder3
ls_folders
register_user user4 pass4
sign_in a4 pa4
register_user user5 pass5
sign_in user3 pass3
register_admin user4 pass4
show_users
register_admin admin admin
add_item item1 key7=val4 key9=val4 key5=val5 key4=val6 
pwd
ls
show_items
show_folders
ls_folders
register_admin user9 pass9
cd folder4
sign_in a3 pa3
cd folder3
show_users
help sign_out
which_group
sign_out
show_items
add_item item2 key4=val9 key7=val7 key6=val6 key10=val8 
show_item_properties item1
ls_folders
show_folders
cd folder3
sign_in user2 pass2
which_group
register_admin user4 pass4
register_admin user4 pass4
buy
sign_out
show_item_properties item1
show_users
help exit
add_item_property item2 key1=val4 key5=val9 key7=val2 key6=val6 
ls_folders
cd folder1
whoami
whoami
add_item item2 key5=val2 key9=val2 key1=val1 key8=val1 
show_items
help delete_user
pwd
current_folder
create_folder folder5
sign_in a2 pa2
register_user user5 pass5
cd folder5
rename_user user4 <function generate_user at 0x027087F0>
show_folders
create_folder folder2
sign_in a3 pa3
show_items
cd folder1
show_folders
current_folder
create_folder folder2
rename_user user3 <function generate_user at 0x027087F0>
current_folder
help add_item_property
ls
create_folder folder3
whoami
show_folders
sign_in user8 pass8
which_group
register_user admin admin
create_folder folder5
show_folders
which_group
ls
create_folder folder4
show_users
add_item item1 key5=val1 key9=val5 key3=val2 key6=val6 
put item1
add_item_property item2 key3=val2 key9=val3 key10=val7 key1=val3 
show_item_properties item5
sign_in a5 pa5
sign_in a3 pa3
show_folders
sign_in a3 pa3
register_user admin admin
register_admin user6 pass6
help sign_out
sign_out
which_group
pwd
current_folder
put item1
show_users
register_user admin admin
sign_in a1 pa1
pwd
show_folders
pwd
sign_in a5 pa5
pwd
pwd
sign_in user6 pass6
show_folders
which_group
show_users
buy
sign_in a1 pa1
buy
show_item_properties item2
create_folder folder5
register_user admin admin
add_item item4 key6=val3 key2=val5 key8=val7 key9=val9 
current_folder
register_user user9 pass9
register_user user6 pass6
register_admin user1 pass1
which_group
put item1
sign_in a5 pa5
cd folder1
rename_user user7 <function generate_user at 0x027087F0>
show_item_properties item5
ls
show_items
sign_out
sign_in user8 pass8
register_user user1 pass1
sign_in user1 pass1
put item2
pwd
sign_in a3 pa3
pwd
help history
sign_out
sign_in a2 pa2
pwd
add_item_property item5 key6=val4 key7=val7 key6=val10 key10=val2 
pwd
ls
sign_in user8 pass8
create_folder folder3
show_folders
put item2
show_item_properties item4
show_item_properties item3
which_group
ls
sign_in a3 pa3
cd folder4
help help
show_item_properties item4
which_group
register_admin user2 pass2
ls_folders
show_folders
show_users
add_item item4 key6=val4 key5=val2 key2=val5 key3=val10 
show_items
add_item_property item4 key9=val6 key8=val6 key2=val6 key5=val7 
whoami
which_group
sign_in user2 pass2
add_item_property item4 key2=val6 key1=val5 key10=val4 key4=val7 
sign_in user6 pass6
show_folders
register_user user1 pass1
show_item_properties item3
show_users
show_items
register_user user8 pass8
register_user user1 pass1
ls
which_group
show_users
register_user user9 pass9
sign_in user8 pass8
help add_item_property
register_user user2 pass2
buy
show_folders
ls
buy
cd folder4
ls
rename_user user9 <function generate_user at 0x027087F0>
sign_in user3 pass3
pwd
sign_in a5 pa5
put item3
ls
show_items
show_item_properties item3
add_item_property item2 key6=val1 key7=val2 key10=val6 key2=val10 
register_admin user6 pass6
add_item_property item1 key8=val8 key2=val7 key7=val6 key10=val6 
pwd
pwd
create_folder folder4
register_admin user7 pass7
help pwd
cd folder5
sign_in a5 pa5
add_item item4 key4=val10 key5=val4 key6=val6 key7=val1 
which_group
current_folder
add_item item3 key4=val8 key10=val5 key8=val4 key5=val7 
create_folder folder1
show_users
show_users
pwd
ls_folders
sign_in a4 pa4
whoami
register_user user6 pass6
buy
help rename_user
ls
show_users
sign_in a2 pa2
put item2
put item3
which_group
whoami
cd folder3
pwd
ls_folders
rename_user user1 <function generate_user at 0x027087F0>
ls
whoami
show_users
add_item_property item1 key3=val9 key9=val4 key9=val1 key9=val9 
register_admin user3 pass3
sign_in a3 pa3
help rename_user
add_item_property item3 key9=val2 key10=val8 key2=val8 key4=val4 
show_users
sign_in a5 pa5
add_item_property item3 key8=val7 key3=val5 key1=val8 key2=val1 
put item1
sign_out
sign_in user8 pass8
ls_folders
which_group
show_item_properties item2
sign_in a1 pa1
rename_user user5 <function generate_user at 0x027087F0>
show_users
sign_in user3 pass3
whoami
whoami
show_item_properties item4
add_item_property item2 key2=val4 key7=val1 key3=val7 key5=val9 
which_group
show_users
which_group
register_admin user3 pass3
whoami
add_item item3 key2=val5 key3=val2 key5=val10 key7=val3 
buy
help add_item
show_folders
register_admin admin admin
ls
rename_user user5 <function generate_user at 0x027087F0>
help show_folders
help show_item_properties
sign_in a4 pa4
help register_admin
ls
cd folder4
ls
pwd
show_users
pwd
create_folder folder2
add_item item3 key6=val3 key2=val4 key9=val6 key2=val8 
show_item_properties item5
add_item_property item1 key1=val6 key8=val2 key7=val9 key9=val3 
show_item_properties item4
which_group
register_admin user5 pass5
current_folder
add_item_property item3 key3=val6 key2=val6 key8=val3 key5=val2 
sign_in a5 pa5
pwd
show_folders
pwd
whoami
cd folder5
help rename_user
show_items
pwd
pwd
rename_user user4 <function generate_user at 0x027087F0>
ls
ls
show_users
register_admin user2 pass2
show_folders
pwd
buy
register_admin user4 pass4
current_folder
help add_item
help sign_out
ls
sign_in user8 pass8
cd folder1
show_items
ls_folders
register_user user8 pass8
add_item item5 key9=val10 key7=val1 key7=val4 key10=val3 
register_admin user8 pass8
register_user user8 pass8
sign_in user8 pass8
sign_out
show_folders
pwd
buy
buy
put item1
put item3
ls_folders
show_folders
show_users
which_group
which_group
sign_in a5 pa5
show_items
rename_user user1 <function generate_user at 0x027087F0>
put item1
help whoami
cd folder5
create_folder folder2
sign_out
sign_out
ls_folders
register_admin user7 pass7
create_folder folder4
register_user user4 pass4
add_item item1 key5=val1 key8=val7 key10=val7 key3=val8 
pwd
show_folders
sign_out
which_group
show_item_properties item3
rename_user user8 <function generate_user at 0x027087F0>
show_users
show_folders
show_folders
ls_folders
put item4
help help
show_users
ls_folders
current_folder
put item1
current_folder
show_users
show_items
cd folder2
show_item_properties item3
show_users
ls_folders
sign_in a5 pa5
show_item_properties item1
which_group
cd folder5
add_item item1 key9=val2 key1=val5 key4=val7 key5=val10 
register_admin user4 pass4
ls_folders
register_user user3 pass3
create_folder folder5
buy
add_item item2 key2=val7 key1=val6 key3=val2 key7=val7 
ls
ls
show_folders
help create_folder
current_folder
whoami
cd folder1
ls
whoami
sign_in user9 pass9
register_user user8 pass8
sign_in user7 pass7
show_folders
pwd
show_folders
create_folder folder1
create_folder folder1
ls
buy
ls_folders
ls_folders
show_folders
add_item item5 key4=val2 key5=val6 key8=val6 key3=val5 
add_item item2 key8=val6 key10=val9 key10=val9 key4=val8 
show_items
register_admin user5 pass5
buy
put item2
rename_user user8 <function generate_user at 0x027087F0>
rename_user user7 <function generate_user at 0x027087F0>
cd folder5
show_item_properties item5
which_group
create_folder folder3
create_folder folder3
sign_in admin admin
add_item_property item1 key2=val8 key4=val3 key9=val3 key9=val9 
register_user user1 pass1
register_admin user7 pass7
sign_in admin admin
current_folder
create_folder folder3
pwd
current_folder
show_items
ls
add_item_property item3 key4=val3 key6=val5 key3=val9 key5=val6 
create_folder folder3
register_admin user2 pass2
sign_out
ls_folders
pwd
put item1
create_folder folder4
show_users
whoami
add_item_property item3 key1=val3 key10=val3 key7=val1 key7=val3 
show_folders
ls_folders
show_items
put item1
current_folder
buy
help put
register_user user5 pass5
show_item_properties item2
add_item_property item1 key1=val9 key8=val5 key8=val4 key4=val6 
sign_in a5 pa5
show_item_properties item3
register_user user4 pass4
sign_in a1 pa1
current_folder
ls_folders
register_user user9 pass9
show_items
create_folder folder1
which_group
show_item_properties item4
show_users
buy
sign_in user6 pass6
ls
put item1
sign_in a4 pa4
buy
show_folders
sign_in a4 pa4
ls_folders
cd folder2
put item4
whoami
sign_in user7 pass7
put item5
sign_in a2 pa2
register_user user5 pass5
which_group
pwd
register_user user4 pass4
whoami
add_item_property item1 key7=val8 key10=val7 key2=val1 key3=val7 
pwd
show_users
add_item item1 key2=val4 key9=val2 key2=val1 key9=val3 
add_item_property item2 key1=val10 key1=val3 key2=val9 key2=val10 
add_item item5 key9=val9 key1=val5 key2=val5 key2=val6 
which_group
pwd
whoami
which_group
which_group
help sign_out
pwd
show_item_properties item2
pwd
add_item_property item2 key7=val7 key4=val7 key9=val5 key1=val4 
show_items
help whoami
show_items
create_folder folder3
whoami
ls_folders
register_user user1 pass1
ls
sign_in a2 pa2
sign_out
sign_in user1 pass1
show_items
sign_in user8 pass8
add_item item4 key10=val9 key7=val3 key8=val2 key10=val6 
show_items
sign_in user7 pass7
add_item_property item4 key2=val2 key2=val10 key1=val5 key5=val10 
show_folders
cd folder2
add_item_property item1 key2=val2 key7=val8 key4=val2 key8=val1 
show_users
register_user user8 pass8
sign_in user9 pass9
whoami
show_folders
add_item_property item3 key8=val8 key5=val4 key2=val7 key7=val5 
show_items
buy
which_group
show_item_properties item2
show_users
show_items
help help
sign_in user8 pass8
show_item_properties item1
rename_user user4 <function generate_user at 0x027087F0>
put item4
which_group
add_item_property item4 key7=val8 key7=val10 key8=val1 key1=val4 
sign_in a2 pa2
create_folder folder5
current_folder
show_item_properties item1
put item4
cd folder1
show_items
sign_out
pwd
current_folder
which_group
rename_user user4 <function generate_user at 0x027087F0>
help show_users
rename_user user7 <function generate_user at 0x027087F0>
buy
sign_out
current_folder
sign_in a1 pa1
sign_out
current_folder
show_item_properties item5
buy
ls
create_folder folder3
register_user user6 pass6
pwd
which_group
rename_user user9 <function generate_user at 0x027087F0>
buy
sign_in user8 pass8
add_item item5 key4=val2 key4=val8 key6=val8 key5=val3 
help ls
add_item item3 key1=val10 key1=val8 key8=val8 key9=val10 
sign_out
ls_folders
sign_out
sign_in user1 pass1
sign_out
register_user user3 pass3
which_group
add_item_property item2 key1=val8 key10=val2 key8=val8 key4=val5 
which_group
ls_folders
buy
put item3
put item1
sign_in user5 pass5
cd folder2
add_item_property item3 key9=val7 key8=val1 key5=val3 key6=val5 
current_folder
add_item item5 key9=val7 key2=val5 key4=val1 key9=val4 
current_folder
add_item_property item5 key2=val1 key8=val6 key2=val8 key10=val10 
cd folder1
create_folder folder2
rename_user user2 <function generate_user at 0x027087F0>
help cd
register_admin user9 pass9
current_folder
cd folder3
register_user user7 pass7
register_admin user8 pass8
show_users
register_admin user3 pass3
put item2
sign_out
put item2
pwd
sign_in a2 pa2
cd folder2
sign_in user7 pass7
which_group
add_item_property item2 key6=val7 key8=val4 key3=val8 key8=val4 
put item3
show_items
ls
buy
put item1
sign_out
sign_out
show_folders
create_folder folder3
put item3
register_user user2 pass2
add_item_property item1 key10=val2 key2=val9 key5=val6 key9=val8 
sign_in user8 pass8
ls_folders
sign_out
pwd
current_folder
register_admin admin admin
sign_out
which_group
buy
help view_order
sign_out
register_user user6 pass6
buy
create_folder folder5
pwd
show_items
buy
show_users
sign_out
cd folder5
ls_folders
sign_in user2 pass2
show_item_properties item2
current_folder
show_items
show_users
sign_in a4 pa4
pwd
which_group
add_item_property item1 key5=val1 key3=val10 key10=val10 key9=val2 
buy
register_admin user1 pass1
register_admin user9 pass9
rename_user user0 <function generate_user at 0x027087F0>
show_item_properties item5
sign_in a4 pa4
which_group
which_group
show_users
create_folder folder5
show_item_properties item3
put item4
sign_in user9 pass9
show_users
add_item item1 key10=val4 key3=val9 key1=val6 key6=val3 
cd folder3
register_admin user7 pass7
whoami
rename_user user0 <function generate_user at 0x027087F0>
register_admin user9 pass9
cd folder3
sign_in user4 pass4
current_folder
show_users
ls
put item4
register_admin user9 pass9
register_admin user9 pass9
pwd
which_group
sign_out
sign_in user5 pass5
current_folder
buy
show_folders
ls_folders
create_folder folder5
sign_out
cd folder4
current_folder
whoami
add_item item3 key10=val1 key7=val8 key8=val3 key1=val5 
register_admin user6 pass6
buy
ls
put item3
ls_folders
sign_in admin admin
pwd
help sign_out
cd folder1
buy
add_item_property item4 key10=val7 key8=val2 key5=val3 key6=val6 
sign_out
rename_user user5 <function generate_user at 0x027087F0>
put item4
show_items
which_group
ls
put item5
which_group
rename_user user7 <function generate_user at 0x027087F0>
ls_folders
which_group
add_item_property item4 key4=val7 key9=val2 key1=val7 key4=val10 
show_items
ls_folders
show_folders
ls_folders
register_user admin admin
sign_out
sign_in a1 pa1
rename_user user1 <function generate_user at 0x027087F0>
create_folder folder4
show_users
show_items
show_items
add_item_property item1 key10=val3 key10=val2 key4=val4 key4=val10 
sign_out
add_item item3 key2=val6 key8=val8 key2=val10 key2=val7 
sign_out
help view_order
show_folders
put item1
register_user user2 pass2
buy
put item5
rename_user user5 <function generate_user at 0x027087F0>
current_folder
register_admin user6 pass6
which_group
sign_in user3 pass3
sign_out
add_item_property item2 key10=val7 key7=val4 key4=val10 key10=val5 
show_users
ls
register_user user4 pass4
buy
help exit
which_group
create_folder folder4
cd folder3
sign_in user8 pass8
buy
ls
register_admin user4 pass4
ls_folders
put item1
help ls_folders
ls
show_item_properties item1
buy
cd folder3
register_user user2 pass2
sign_in user8 pass8
sign_in user7 pass7
whoami
put item4
ls
create_folder folder4
cd folder4
which_group
put item2
register_user user3 pass3
which_group
register_user user1 pass1
sign_out
add_item item2 key8=val3 key1=val1 key6=val4 key9=val1 
add_item item1 key7=val5 key3=val9 key5=val9 key9=val1 
sign_in user1 pass1
put item5
show_folders
show_folders
show_users
sign_out
show_users
cd folder5
help show_users
help current_folder
sign_out
show_items
sign_in user9 pass9
sign_in a3 pa3
add_item item2 key4=val9 key2=val3 key7=val6 key7=val2 
ls_folders
rename_user user7 <function generate_user at 0x027087F0>
put item5
whoami
show_item_properties item3
help show_item_properties
show_items
show_items
show_item_properties item1
sign_in a1 pa1
help ls
which_group
cd folder2
ls
create_folder folder2
register_admin user5 pass5
show_users
cd folder2
show_users
rename_user user6 <function generate_user at 0x027087F0>
sign_in a5 pa5
sign_out
put item1
whoami
which_group
sign_out
put item5
show_users
add_item_property item2 key6=val5 key5=val10 key4=val2 key2=val4 
help pwd
show_folders
put item5
buy
current_folder
buy
help delete_user
create_folder folder1
sign_in user7 pass7
register_user user6 pass6
help view_order
current_folder
put item1
whoami
ls_folders
pwd
cd folder4
create_folder folder1
help register_admin
sign_out
show_folders
show_folders
ls
ls
register_admin user6 pass6
buy
add_item_property item5 key3=val1 key2=val8 key6=val5 key2=val10 
add_item_property item4 key4=val3 key9=val7 key5=val10 key8=val8 
sign_out
sign_in user9 pass9
cd folder3
put item4
register_user user8 pass8
cd folder5
cd folder3
sign_in user5 pass5
register_admin user4 pass4
add_item item1 key7=val2 key5=val6 key7=val3 key3=val6 
rename_user user8 <function generate_user at 0x027087F0>
ls
sign_in a1 pa1
create_folder folder1
put item1
register_admin user7 pass7
show_items
register_admin user9 pass9
sign_in user3 pass3
register_user user8 pass8
which_group
add_item item1 key9=val10 key9=val1 key5=val3 key10=val10 
add_item_property item1 key10=val5 key2=val10 key1=val10 key10=val7 
ls
register_admin user3 pass3
add_item item4 key1=val8 key9=val9 key1=val1 key7=val10 
help ls_folders
cd folder4
register_user user9 pass9
show_users
which_group
show_folders
ls_folders
ls
current_folder
current_folder
pwd
sign_out
ls
add_item item2 key1=val4 key10=val1 key4=val2 key2=val2 
add_item_property item5 key6=val4 key4=val10 key7=val2 key5=val9 
show_items
put item5
whoami
show_users
whoami
show_users
current_folder
help add_item_property
sign_in a5 pa5
cd folder3
create_folder folder1
create_folder folder1
buy
show_items
pwd
register_admin user7 pass7
cd folder5
sign_in a5 pa5
pwd
create_folder folder1
whoami
current_folder
create_folder folder5
sign_out
register_admin user9 pass9
sign_in a3 pa3
help which_group
register_admin user9 pass9
ls_folders
register_user user1 pass1
which_group
show_items
show_item_properties item1
add_item item5 key3=val5 key4=val8 key5=val5 key3=val5 
ls
sign_out
help create_folder
pwd
current_folder
sign_in a5 pa5
show_users
ls_folders
create_folder folder4
current_folder
pwd
put item1
show_items
ls_folders
current_folder
whoami
sign_in user1 pass1
which_group
add_item_property item2 key2=val2 key7=val9 key1=val4 key2=val5 
rename_user user3 <function generate_user at 0x027087F0>
register_admin user5 pass5
put item1
current_folder
register_user user2 pass2
ls_folders
ls
current_folder
show_item_properties item3
buy
sign_out
register_user user5 pass5
create_folder folder5
rename_user user9 <function generate_user at 0x027087F0>
help put
create_folder folder5
ls_folders
pwd
add_item_property item1 key9=val8 key5=val9 key9=val2 key8=val5 
add_item item4 key6=val9 key10=val8 key7=val5 key3=val10 
pwd
cd folder4
buy
ls_folders
ls_folders
ls_folders
whoami
buy
show_users
sign_in user1 pass1
current_folder
show_items
sign_out
show_users
sign_in user3 pass3
help current_folder
sign_out
help ls_folders
pwd
show_item_properties item4
which_group
create_folder folder1
sign_out
which_group
buy
sign_in user5 pass5
add_item_property item3 key6=val7 key4=val1 key1=val2 key10=val5 
add_item item1 key1=val4 key4=val2 key2=val10 key5=val10 
show_items
help ls
add_item_property item2 key9=val9 key6=val6 key6=val7 key6=val8 
which_group
cd folder3
pwd
show_folders
register_user user4 pass4
rename_user user7 <function generate_user at 0x027087F0>
whoami
whoami
current_folder
create_folder folder3
add_item_property item1 key10=val7 key5=val1 key9=val3 key1=val8 
show_folders
sign_in a2 pa2
sign_out
show_items
show_item_properties item5
sign_in user6 pass6
which_group
ls
pwd
show_users
sign_in user5 pass5
current_folder
sign_in user1 pass1
ls_folders
sign_out
current_folder
whoami
show_folders
whoami
cd folder3
which_group
buy
help history
register_user user3 pass3
show_items
which_group
add_item_property item4 key6=val3 key6=val4 key6=val6 key1=val2 
sign_in a5 pa5
put item4
current_folder
add_item item5 key10=val7 key2=val10 key8=val4 key3=val5 
show_folders
show_folders
add_item item1 key6=val1 key1=val4 key5=val6 key2=val2 
add_item item5 key8=val10 key3=val10 key8=val3 key5=val6 
create_folder folder3
buy
put item4
help sign_in
show_folders
add_item_property item3 key8=val10 key6=val6 key1=val10 key9=val7 
create_folder folder4
pwd
sign_out
help which_group
rename_user user1 <function generate_user at 0x027087F0>
pwd
add_item_property item5 key9=val4 key9=val7 key6=val3 key1=val2 
whoami
register_admin user4 pass4
show_users
register_user user8 pass8
show_folders
register_user user4 pass4
show_folders
add_item item4 key7=val5 key3=val3 key8=val10 key4=val9 
register_user user1 pass1
current_folder
sign_in a2 pa2
show_items
show_folders
show_items
show_users
show_items
buy
pwd
add_item item4 key9=val9 key10=val3 key1=val8 key9=val8 
sign_in a4 pa4
current_folder
ls_folders
buy
rename_user user0 <function generate_user at 0x027087F0>
ls_folders
pwd
which_group
whoami
sign_in a3 pa3
whoami
buy
which_group
show_item_properties item4
add_item_property item3 key4=val9 key4=val8 key6=val10 key9=val7 
show_items
sign_out
which_group
pwd
buy
help ls
show_folders
ls_folders
ls
show_folders
pwd
register_user user4 pass4
show_users
show_folders
sign_in a1 pa1
show_item_properties item4
pwd
show_item_properties item4
cd folder1
ls_folders
pwd
help cd
show_item_properties item1
show_items
register_admin user8 pass8
create_folder folder2
whoami
rename_user user8 <function generate_user at 0x027087F0>
sign_in a2 pa2
add_item_property item5 key7=val6 key7=val3 key8=val2 key3=val4 
cd folder4
current_folder
rename_user user8 <function generate_user at 0x027087F0>
show_users
help sign_in
ls
sign_out
create_folder folder2
show_users
add_item_property item4 key6=val5 key4=val6 key9=val10 key2=val6 
put item2
current_folder
cd folder4
add_item_property item5 key7=val2 key8=val2 key7=val1 key4=val3 
rename_user user7 <function generate_user at 0x027087F0>
add_item item3 key9=val2 key2=val2 key9=val2 key6=val8 
show_folders
show_users
cd folder2
ls_folders
current_folder
pwd
add_item item4 key6=val8 key7=val7 key4=val2 key7=val7 
sign_out
show_item_properties item2
help register_user
ls
sign_in a4 pa4
ls_folders
register_user user1 pass1
sign_in a5 pa5
whoami
show_folders
buy
pwd
sign_in user9 pass9
sign_out
pwd
show_item_properties item4
put item1
buy
show_items
create_folder folder2
pwd
whoami
show_folders
ls
sign_in user8 pass8
which_group
whoami
show_item_properties item4
show_item_properties item3
show_items
pwd
pwd
register_admin user2 pass2
put item1
which_group
current_folder
add_item item3 key1=val1 key10=val4 key10=val4 key1=val5 
help show_items
which_group
which_group
show_users
add_item item4 key7=val6 key5=val5 key5=val2 key5=val6 
add_item item4 key8=val9 key5=val5 key5=val4 key1=val1 
sign_out
ls_folders
ls
show_folders
show_folders
which_group
sign_in a1 pa1
sign_in a3 pa3
show_folders
current_folder
show_folders
show_items
current_folder
add_item_property item5 key10=val9 key7=val9 key5=val9 key3=val8 
buy
add_item item4 key2=val3 key9=val3 key3=val7 key10=val7 
register_user user8 pass8
show_users
create_folder folder4
sign_in a4 pa4
which_group
whoami
create_folder folder1
which_group
add_item item4 key4=val1 key2=val4 key2=val7 key5=val8 
sign_out
register_admin user8 pass8
add_item item5 key3=val4 key5=val6 key1=val6 key6=val4 
help add_item_property
show_items
ls
rename_user user9 <function generate_user at 0x027087F0>
show_item_properties item5
put item5
show_users
put item2
show_item_properties item5
show_users
sign_in a5 pa5
rename_user user8 <function generate_user at 0x027087F0>
create_folder folder5
pwd
cd folder4
show_folders
show_users
show_folders
show_users
show_items
sign_in user6 pass6
cd folder3
ls_folders
add_item_property item5 key3=val1 key2=val1 key2=val9 key1=val9 
register_user user9 pass9
help sign_out
ls_folders
sign_in user4 pass4
ls
show_users
ls_folders
show_items
show_folders
register_admin user8 pass8
which_group
add_item item1 key7=val1 key3=val8 key6=val7 key10=val5 
create_folder folder5
cd folder5
pwd
show_item_properties item5
sign_out
show_item_properties item5
add_item_property item3 key10=val5 key1=val2 key9=val8 key5=val7 
create_folder folder1
rename_user user2 <function generate_user at 0x027087F0>
add_item_property item4 key8=val8 key7=val6 key5=val8 key10=val7 
register_admin user4 pass4
sign_out
current_folder
ls
pwd
ls
cd folder1
show_folders
sign_in a5 pa5
rename_user user3 <function generate_user at 0x027087F0>
add_item item5 key10=val7 key5=val2 key3=val10 key1=val7 
show_items
which_group
register_admin user1 pass1
put item4
ls
ls_folders
sign_in user6 pass6
put item4
current_folder
whoami
rename_user user8 <function generate_user at 0x027087F0>
put item1
register_admin user3 pass3
sign_out
register_user user9 pass9
pwd
current_folder
show_users
put item4
show_items
whoami
show_item_properties item5
sign_in a4 pa4
which_group
register_admin user5 pass5
add_item item3 key7=val9 key2=val6 key9=val5 key6=val7 
sign_in a4 pa4
cd folder2
show_folders
register_user user6 pass6
ls
show_users
cd folder5
create_folder folder1
show_folders
show_folders
sign_in a4 pa4
ls_folders
show_folders
rename_user user4 <function generate_user at 0x027087F0>
create_folder folder2
add_item_property item1 key9=val4 key5=val2 key9=val6 key2=val2 
sign_in admin admin
pwd
sign_out
which_group
sign_in user9 pass9
show_items
rename_user user7 <function generate_user at 0x027087F0>
sign_in user9 pass9
rename_user user8 <function generate_user at 0x027087F0>
pwd
register_admin user6 pass6
register_admin user1 pass1
show_folders
show_users
buy
add_item item3 key3=val4 key8=val2 key4=val7 key1=val1 
sign_in a4 pa4
ls_folders
show_item_properties item4
ls
help register_user
add_item_property item4 key3=val1 key8=val4 key8=val7 key2=val4 
show_users
buy
show_item_properties item2
sign_out
pwd
add_item item5 key8=val7 key5=val7 key10=val8 key7=val1 
sign_in a2 pa2
register_user user6 pass6
ls_folders
pwd
buy
show_users
sign_in a1 pa1
register_user admin admin
add_item item4 key9=val6 key9=val2 key5=val4 key7=val2 
help create_folder
sign_in a2 pa2
register_admin user2 pass2
buy
cd folder2
which_group
register_admin user9 pass9
show_item_properties item2
whoami
show_item_properties item2
which_group
show_item_properties item3
put item2
sign_out
sign_in a5 pa5
sign_in a3 pa3
whoami
register_admin user7 pass7
register_admin admin admin
register_admin user2 pass2
ls
cd folder3
show_users
register_user user8 pass8
create_folder folder4
show_items
rename_user user2 <function generate_user at 0x027087F0>
ls
register_user user8 pass8
help show_items
cd folder5
pwd
cd folder1
show_item_properties item5
show_items
show_item_properties item1
whoami
cd folder4
add_item_property item5 key4=val7 key7=val10 key9=val8 key3=val6 
ls_folders
create_folder folder2
register_admin user6 pass6
sign_in a1 pa1
help register_admin
add_item item1 key3=val4 key7=val5 key3=val8 key8=val1 
cd folder4
show_folders
ls_folders
create_folder folder1
show_folders
show_items
rename_user user7 <function generate_user at 0x027087F0>
register_user admin admin
cd folder3
register_user user2 pass2
put item2
current_folder
rename_user user4 <function generate_user at 0x027087F0>
ls_folders
show_users
ls_folders
rename_user user1 <function generate_user at 0x027087F0>
cd folder1
pwd
rename_user user5 <function generate_user at 0x027087F0>
put item2
buy
ls
pwd
add_item_property item1 key1=val7 key2=val1 key5=val2 key1=val8 
add_item item4 key4=val2 key5=val4 key10=val8 key5=val1 
whoami
add_item_property item2 key5=val2 key4=val2 key4=val10 key10=val4 
register_user user1 pass1
put item5
which_group
ls
add_item_property item2 key1=val7 key10=val8 key6=val1 key5=val2 
pwd
buy
show_items
whoami
help sign_out
create_folder folder1
create_folder folder3
add_item item3 key5=val6 key2=val8 key5=val8 key5=val3 
register_admin admin admin
current_folder
add_item_property item5 key3=val9 key8=val6 key8=val2 key3=val4 
cd folder4
whoami
whoami
register_user user2 pass2
whoami
sign_out
show_users
whoami
show_items
sign_out
sign_out
ls_folders
buy
show_folders
sign_in user2 pass2
sign_out
sign_in user1 pass1
which_group
create_folder folder3
show_folders
pwd
put item3
ls
ls_folders
show_users
pwd
buy
ls_folders
ls
buy
sign_out
current_folder
add_item item2 key6=val6 key2=val8 key9=val3 key2=val10 
show_item_properties item1
buy
add_item item4 key10=val8 key6=val3 key5=val5 key10=val4 
add_item_property item1 key1=val1 key3=val6 key3=val7 key5=val3 
rename_user user4 <function generate_user at 0x027087F0>
sign_in a3 pa3
show_item_properties item2
buy
current_folder
add_item item1 key5=val3 key8=val5 key5=val2 key9=val1 
cd folder4
rename_user user0 <function generate_user at 0x027087F0>
buy
put item4
which_group
show_item_properties item4
buy
buy
cd folder5
rename_user user9 <function generate_user at 0x027087F0>
buy
add_item_property item2 key2=val1 key5=val7 key10=val4 key7=val9 
current_folder
sign_out
ls
put item2
rename_user user7 <function generate_user at 0x027087F0>
which_group
pwd
show_items
register_admin user4 pass4
show_items
help which_group
current_folder
whoami
add_item_property item1 key1=val5 key10=val10 key1=val9 key5=val9 
show_users
put item3
rename_user user8 <function generate_user at 0x027087F0>
create_folder folder2
sign_in user5 pass5
sign_out
current_folder
add_item item2 key3=val6 key7=val2 key8=val9 key10=val3 
add_item item1 key1=val1 key4=val4 key5=val9 key6=val1 
show_folders
whoami
current_folder
ls
sign_out
buy
sign_in a2 pa2
cd folder2
rename_user user7 <function generate_user at 0x027087F0>
show_users
add_item_property item1 key6=val10 key2=val4 key2=val5 key3=val10 
cd folder5
show_items
sign_out
ls
whoami
register_user user9 pass9
show_items
show_folders
add_item item2 key2=val7 key9=val9 key5=val1 key4=val2 
rename_user user4 <function generate_user at 0x027087F0>
add_item item4 key4=val8 key4=val2 key5=val3 key4=val7 
put item3
register_admin admin admin
add_item_property item1 key2=val7 key10=val2 key3=val2 key8=val5 
rename_user user3 <function generate_user at 0x027087F0>
ls
register_user user5 pass5
register_user user8 pass8
cd folder5
show_item_properties item3
ls
whoami
whoami
register_admin user7 pass7
current_folder
whoami
sign_in user8 pass8
sign_out
cd folder3
which_group
buy
ls_folders
put item2
help register_user
show_item_properties item2
sign_in a1 pa1
show_users
show_users
show_items
which_group
show_item_properties item4
show_items
pwd
pwd
put item5
register_user user6 pass6
whoami
pwd
add_item_property item4 key3=val1 key4=val10 key1=val9 key1=val8 
register_user user3 pass3
which_group
ls_folders
current_folder
sign_in admin admin
create_folder folder4
show_users
pwd
register_user user5 pass5
register_user user4 pass4
register_admin user1 pass1
create_folder folder3
add_item item5 key8=val10 key10=val10 key7=val5 key9=val5 
show_item_properties item5
sign_out
pwd
show_folders
help help
show_users
sign_in admin admin
sign_in user4 pass4
show_items
rename_user user3 <function generate_user at 0x027087F0>
ls_folders
add_item item4 key6=val3 key3=val10 key8=val8 key1=val9 
pwd
show_item_properties item2
show_folders
ls
sign_in user3 pass3
cd folder4
register_admin user8 pass8
ls_folders
show_item_properties item2
cd folder2
sign_in a5 pa5
put item3
register_user user9 pass9
create_folder folder4
pwd
help register_admin
put item3
ls_folders
show_users
pwd
which_group
show_item_properties item1
ls
buy
sign_out
ls
sign_in user5 pass5
show_items
add_item item3 key8=val1 key8=val3 key10=val10 key3=val3 
rename_user user6 <function generate_user at 0x027087F0>
register_user user8 pass8
whoami
put item4
ls_folders
cd folder5
show_items
register_admin user5 pass5
ls_folders
show_items
sign_in a3 pa3
cd folder2
ls
sign_in a2 pa2
whoami
current_folder
current_folder
show_folders
ls
pwd
put item1
create_folder folder2
show_users
show_items
show_users
put item2
rename_user user0 <function generate_user at 0x027087F0>
help current_folder
pwd
sign_out
rename_user user0 <function generate_user at 0x027087F0>
cd folder1
cd folder5
show_item_properties item5
put item4
show_items
cd folder5
which_group
whoami
add_item item3 key10=val7 key6=val5 key5=val4 key1=val8 
register_user user1 pass1
rename_user user6 <function generate_user at 0x027087F0>
ls
show_item_properties item2
sign_in a3 pa3
ls
ls_folders
help delete_user
put item3
ls
register_user user2 pass2
whoami
sign_out
whoami
rename_user user5 <function generate_user at 0x027087F0>
cd folder1
whoami
add_item item4 key8=val9 key1=val10 key7=val10 key7=val5 
show_folders
ls
ls
add_item item4 key10=val7 key4=val2 key7=val4 key2=val5 
buy
add_item item4 key2=val8 key3=val6 key7=val5 key8=val2 
pwd
which_group
sign_in a3 pa3
whoami
sign_out
sign_in a3 pa3
cd folder4
create_folder folder1
add_item_property item2 key6=val5 key5=val6 key3=val5 key3=val2 
register_admin user1 pass1
add_item_property item3 key3=val6 key6=val7 key2=val6 key7=val8 
current_folder
sign_in a5 pa5
rename_user user5 <function generate_user at 0x027087F0>
show_folders
cd folder2
show_folders
buy
show_items
buy
whoami
sign_in user1 pass1
show_users
whoami
sign_in user6 pass6
add_item_property item3 key8=val5 key10=val2 key6=val10 key6=val3 
ls_folders
show_users
ls_folders
sign_in user3 pass3
add_item item4 key2=val7 key1=val7 key10=val5 key10=val6 
show_users
show_items
register_admin user1 pass1
show_item_properties item1
cd folder5
buy
add_item_property item1 key10=val8 key9=val3 key6=val2 key1=val5 
register_admin user9 pass9
create_folder folder5
create_folder folder1
whoami
show_users
show_folders
current_folder
register_admin user7 pass7
show_users
add_item_property item2 key3=val8 key4=val9 key5=val4 key6=val1 
ls
help add_item_property
put item1
sign_out
register_admin user6 pass6
show_item_properties item3
register_user user3 pass3
show_folders
ls
show_items
sign_out
sign_in a1 pa1
register_user user6 pass6
rename_user user3 <function generate_user at 0x027087F0>
current_folder
show_item_properties item3
ls
sign_out
register_admin user6 pass6
create_folder folder4
show_item_properties item4
add_item item1 key5=val5 key3=val8 key4=val8 key9=val7 
show_folders
register_admin user6 pass6
sign_out
show_items
register_admin admin admin
help show_items
current_folder
show_folders
put item4
register_admin admin admin
sign_out
ls_folders
sign_in user9 pass9
current_folder
ls_folders
show_items
help register_admin
show_folders
ls_folders
buy
show_folders
pwd
add_item_property item5 key8=val9 key3=val7 key3=val5 key10=val7 
show_items
pwd
show_items
sign_in user6 pass6
show_item_properties item2
add_item_property item1 key3=val9 key5=val9 key3=val7 key7=val4 
show_item_properties item5
which_group
buy
put item3
pwd
cd folder2
register_user admin admin
rename_user user7 <function generate_user at 0x027087F0>
pwd
ls_folders
current_folder
ls
buy
show_item_properties item5
ls
current_folder
sign_in user2 pass2
buy
show_folders
show_item_properties item1
pwd
create_folder folder3
register_admin user8 pass8
add_item item3 key9=val9 key4=val7 key6=val2 key10=val8 
create_folder folder3
ls
current_folder
add_item item1 key8=val9 key10=val4 key8=val1 key9=val7 
add_item_property item4 key9=val2 key4=val1 key2=val1 key1=val8 
put item5
add_item item2 key1=val10 key7=val10 key7=val1 key3=val6 
help help
cd folder4
show_items
add_item_property item3 key6=val4 key8=val1 key3=val5 key8=val2 
ls_folders
cd folder1
put item5
register_admin user8 pass8
current_folder
register_user user4 pass4
current_folder
put item3
which_group
sign_out
which_group
rename_user user2 <function generate_user at 0x027087F0>
pwd
rename_user user2 <function generate_user at 0x027087F0>
put item3
sign_in a5 pa5
show_items
ls
sign_in a5 pa5
show_users
which_group
show_item_properties item3
help sign_in
whoami
rename_user user9 <function generate_user at 0x027087F0>
ls
pwd
ls
add_item item2 key10=val8 key9=val1 key7=val1 key6=val1 
pwd
current_folder
add_item item4 key1=val3 key3=val4 key9=val6 key9=val9 
ls
ls_folders
whoami
cd folder1
register_user user9 pass9
add_item item3 key9=val1 key6=val5 key10=val2 key10=val2 
put item3
whoami
sign_in a5 pa5
register_admin user9 pass9
whoami
show_item_properties item5
which_group
register_user admin admin
sign_in a4 pa4
add_item item3 key7=val10 key1=val10 key3=val2 key3=val3 
rename_user user0 <function generate_user at 0x027087F0>
ls_folders
show_item_properties item5
show_users
ls
buy
whoami
rename_user user5 <function generate_user at 0x027087F0>
rename_user user8 <function generate_user at 0x027087F0>
buy
ls
buy
which_group
register_admin user7 pass7
ls_folders
pwd
ls
which_group
register_user user7 pass7
show_items
current_folder
show_item_properties item1
buy
pwd
ls_folders
pwd
help rename_user
current_folder
create_folder folder1
create_folder folder1
register_user user1 pass1
create_folder folder2
help current_folder
cd folder2
add_item item2 key4=val9 key10=val5 key2=val9 key2=val10 
which_group
put item5
buy
help which_group
ls_folders
register_admin user1 pass1
pwd
sign_in user3 pass3
ls
put item2
show_folders
add_item item1 key10=val8 key5=val7 key10=val2 key1=val4 
add_item item1 key5=val4 key9=val5 key10=val9 key7=val1 
which_group
add_item item3 key4=val2 key3=val1 key2=val1 key3=val7 
show_item_properties item4
register_admin user8 pass8
show_folders
put item3
current_folder
add_item_property item1 key3=val1 key1=val3 key7=val3 key6=val9 
ls_folders
register_user user5 pass5
cd folder1
rename_user user6 <function generate_user at 0x027087F0>
sign_in a2 pa2
pwd
put item5
sign_in a4 pa4
put item4
sign_in a3 pa3
add_item_property item3 key9=val4 key2=val7 key2=val7 key10=val3 
rename_user user8 <function generate_user at 0x027087F0>
rename_user user8 <function generate_user at 0x027087F0>
add_item_property item4 key5=val5 key7=val5 key3=val5 key1=val7 
cd folder1
current_folder
show_items
ls
create_folder folder1
sign_out
buy
ls
which_group
cd folder4
ls
show_users
ls
add_item_property item3 key9=val10 key6=val10 key2=val6 key6=val10 
show_items
register_admin user6 pass6
ls_folders
show_users
pwd
show_users
create_folder folder4
ls
show_users
rename_user user3 <function generate_user at 0x027087F0>
show_items
whoami
sign_in user9 pass9
whoami
register_user user7 pass7
show_item_properties item3
sign_out
show_items
add_item item1 key2=val2 key9=val8 key10=val7 key1=val9 
sign_out
sign_in user4 pass4
pwd
show_items
sign_in a4 pa4
sign_in a5 pa5
ls_folders
register_admin user6 pass6
help buy
whoami
create_folder folder1
sign_out
sign_out
which_group
show_items
show_users
buy
cd folder2
rename_user user2 <function generate_user at 0x027087F0>
help rename_user
which_group
show_users
show_users
add_item item2 key10=val5 key3=val9 key5=val5 key5=val2 
sign_out
sign_in user1 pass1
register_user admin admin
show_folders
whoami
sign_in a1 pa1
sign_in a3 pa3
buy
which_group
sign_out
sign_in user9 pass9
show_item_properties item5
create_folder folder4
buy
sign_in a2 pa2
sign_out
ls_folders
show_folders
create_folder folder2
add_item_property item2 key9=val3 key5=val4 key10=val10 key2=val9 
show_folders
help create_folder
sign_in admin admin
buy
rename_user user4 <function generate_user at 0x027087F0>
cd folder1
sign_in user1 pass1
create_folder folder5
help sign_out
show_folders
sign_in a2 pa2
rename_user user0 <function generate_user at 0x027087F0>
add_item_property item1 key8=val1 key10=val4 key8=val9 key6=val7 
register_user user4 pass4
whoami
cd folder1
pwd
rename_user user9 <function generate_user at 0x027087F0>
which_group
cd folder5
sign_in admin admin
add_item item1 key7=val3 key6=val9 key2=val4 key8=val8 
add_item item3 key8=val1 key8=val2 key10=val2 key7=val3 
sign_in a1 pa1
show_item_properties item5
current_folder
ls_folders
add_item item4 key4=val8 key3=val3 key2=val6 key5=val7 
pwd
show_folders
show_users
cd folder3
sign_in a5 pa5
which_group
register_admin user3 pass3
show_folders
register_user user9 pass9
which_group
show_users
create_folder folder3
register_admin user4 pass4
sign_in user5 pass5
buy
add_item_property item3 key9=val1 key9=val1 key3=val1 key4=val1 
cd folder5
which_group
rename_user user7 <function generate_user at 0x027087F0>
whoami
whoami
show_item_properties item2
create_folder folder4
sign_out
rename_user user5 <function generate_user at 0x027087F0>
rename_user user4 <function generate_user at 0x027087F0>
register_user user9 pass9
put item2
ls
create_folder folder1
show_items
ls
register_admin user4 pass4
register_admin user2 pass2
whoami
help pwd
sign_out
buy
show_items
help rename_user
pwd
ls
show_folders
help show_item_properties
whoami
show_folders
pwd
whoami
create_folder folder1
add_item_property item3 key4=val3 key7=val1 key6=val5 key2=val1 
show_item_properties item3
put item2
create_folder folder3
create_folder folder3
put item3
current_folder
help rename_user
current_folder
pwd
show_items
show_folders
buy
whoami
current_folder
add_item_property item5 key7=val10 key3=val1 key4=val8 key8=val3 
current_folder
ls
ls
add_item item5 key7=val2 key2=val10 key5=val9 key8=val6 
which_group
add_item item3 key3=val10 key3=val3 key10=val4 key10=val3 
sign_in a3 pa3
register_admin user3 pass3
rename_user user7 <function generate_user at 0x027087F0>
show_item_properties item5
add_item_property item1 key6=val10 key8=val9 key9=val9 key2=val5 
whoami
sign_in user8 pass8
register_admin user3 pass3
show_folders
ls_folders
show_items
show_item_properties item4
sign_in a1 pa1
add_item_property item2 key8=val6 key6=val1 key8=val9 key4=val5 
whoami
put item2
show_users
current_folder
ls_folders
register_admin admin admin
sign_out
current_folder
show_users
cd folder5
which_group
create_folder folder4
ls_folders
sign_in a5 pa5
sign_in user1 pass1
register_admin user8 pass8
show_item_properties item3
cd folder3
put item4
register_user user4 pass4
rename_user user5 <function generate_user at 0x027087F0>
show_items
ls_folders
register_user user7 pass7
help create_folder
show_item_properties item4
register_user user4 pass4
show_folders
show_users
show_users
current_folder
put item4
show_item_properties item2
rename_user user3 <function generate_user at 0x027087F0>
add_item item5 key9=val3 key10=val9 key3=val10 key7=val2 
put item4
buy
create_folder folder5
buy
sign_out
sign_out
put item3
show_folders
current_folder
show_items
show_users
sign_out
show_item_properties item4
show_folders
cd folder2
sign_out
which_group
show_item_properties item2
show_item_properties item3
show_folders
register_user user2 pass2
add_item_property item2 key1=val5 key10=val6 key3=val2 key7=val1 
put item5
register_user user9 pass9
rename_user user4 <function generate_user at 0x027087F0>
buy
sign_in user1 pass1
buy
cd folder1
sign_in user5 pass5
create_folder folder1
rename_user user6 <function generate_user at 0x027087F0>
help ls_folders
sign_out
show_folders
ls_folders
cd folder3
sign_out
show_item_properties item5
whoami
show_items
put item1
ls
rename_user user3 <function generate_user at 0x027087F0>
register_user user4 pass4
whoami
create_folder folder1
register_admin user1 pass1
help pwd
help register_admin
show_items
show_item_properties item5
ls
show_item_properties item3
ls_folders
register_admin user1 pass1
which_group
current_folder
ls
ls
buy
current_folder
register_user user2 pass2
whoami
show_folders
add_item_property item3 key4=val5 key2=val2 key5=val6 key9=val4 
show_users
show_items
sign_in a4 pa4
register_admin admin admin
ls_folders
show_users
register_admin user4 pass4
show_folders
add_item_property item3 key7=val10 key8=val8 key4=val4 key6=val3 
show_users
whoami
show_folders
rename_user user5 <function generate_user at 0x027087F0>
add_item_property item2 key7=val2 key5=val5 key4=val8 key5=val8 
help show_users
rename_user user1 <function generate_user at 0x027087F0>
help cd
rename_user user3 <function generate_user at 0x027087F0>
show_folders
put item1
show_folders
show_folders
which_group
sign_in user3 pass3
add_item item3 key1=val4 key9=val2 key5=val9 key10=val10 
show_items
show_folders
help add_item
pwd
help help
ls
whoami
add_item_property item1 key5=val2 key10=val8 key4=val7 key7=val2 
ls
create_folder folder5
add_item item1 key6=val8 key6=val2 key5=val3 key2=val6 
whoami
register_admin admin admin
sign_in a2 pa2
whoami
current_folder
current_folder
show_item_properties item2
pwd
rename_user user3 <function generate_user at 0x027087F0>
add_item item5 key5=val4 key8=val1 key2=val10 key9=val5 
pwd
show_item_properties item4
show_users
show_items
pwd
register_admin user9 pass9
show_item_properties item5
show_item_properties item3
add_item item2 key6=val9 key7=val6 key4=val3 key8=val6 
show_items
sign_out
show_users
add_item_property item5 key10=val1 key9=val9 key8=val2 key5=val3 
add_item_property item2 key8=val3 key7=val6 key4=val6 key4=val6 
register_user user5 pass5
put item2
add_item item2 key9=val4 key1=val7 key1=val7 key2=val8 
show_folders
show_items
which_group
ls
sign_in admin admin
sign_in user2 pass2
rename_user user8 <function generate_user at 0x027087F0>
register_user user2 pass2
whoami
show_item_properties item5
ls
ls_folders
show_users
show_folders
register_admin user4 pass4
help put
add_item item3 key10=val2 key3=val8 key4=val9 key5=val6 
pwd
rename_user user2 <function generate_user at 0x027087F0>
buy
register_admin user7 pass7
sign_out
pwd
whoami
which_group
show_users
register_admin user4 pass4
add_item item1 key4=val5 key3=val1 key1=val1 key3=val6 
show_users
current_folder
rename_user user3 <function generate_user at 0x027087F0>
which_group
sign_in admin admin
buy
sign_out
register_user user8 pass8
rename_user user7 <function generate_user at 0x027087F0>
cd folder4
ls
ls_folders
rename_user user6 <function generate_user at 0x027087F0>
show_items
cd folder5
sign_out
current_folder
show_item_properties item4
pwd
show_item_properties item1
show_users
register_admin admin admin
show_users
whoami
which_group
show_folders
add_item_property item3 key1=val3 key7=val5 key10=val2 key5=val6 
add_item item4 key6=val4 key9=val9 key2=val1 key10=val3 
show_folders
register_admin user3 pass3
ls_folders
cd folder2
sign_out
put item1
cd folder5
help add_item_property
show_folders
show_users
which_group
ls
create_folder folder2
sign_out
buy
show_item_properties item2
ls_folders
rename_user user5 <function generate_user at 0x027087F0>
help current_folder
add_item item5 key3=val4 key9=val6 key2=val7 key10=val10 
pwd
ls_folders
sign_in user9 pass9
pwd
ls
sign_out
rename_user user0 <function generate_user at 0x027087F0>
sign_in user6 pass6
whoami
show_users
which_group
pwd
help delete_user
add_item item1 key8=val6 key4=val6 key8=val5 key1=val7 
whoami
sign_in user7 pass7
buy
put item4
show_item_properties item4
cd folder2
buy
add_item_property item2 key2=val1 key10=val7 key5=val1 key6=val4 
sign_in a5 pa5
register_user user8 pass8
sign_in a5 pa5
cd folder1
create_folder folder4
show_item_properties item1
register_admin user3 pass3
sign_in user8 pass8
sign_out
register_admin admin admin
rename_user user4 <function generate_user at 0x027087F0>
rename_user user2 <function generate_user at 0x027087F0>
show_item_properties item1
ls_folders
sign_in user9 pass9
cd folder4
buy
sign_in a2 pa2
help show_items
show_item_properties item2
buy
show_users
show_items
sign_in user4 pass4
help add_item
add_item_property item3 key3=val3 key6=val4 key9=val2 key9=val2 
show_folders
sign_in a5 pa5
create_folder folder4
rename_user user0 <function generate_user at 0x027087F0>
register_admin user9 pass9
help exit
pwd
help ls_folders
pwd
rename_user user0 <function generate_user at 0x027087F0>
sign_out
pwd
show_users
register_user user5 pass5
add_item item5 key4=val4 key2=val2 key6=val2 key7=val10 
buy
add_item item5 key10=val3 key1=val9 key9=val6 key10=val5 
help show_folders
ls_folders
show_items
ls
pwd
register_admin user9 pass9
pwd
put item2
show_item_properties item4
put item3
show_folders
sign_in user5 pass5
whoami
cd folder1
ls
help register_user
put item4
sign_out
add_item_property item3 key5=val7 key4=val8 key7=val4 key4=val10 
create_folder folder2
current_folder
current_folder
current_folder
show_folders
put item1
buy
show_folders
register_user user8 pass8
register_user user2 pass2
cd folder3
add_item item4 key2=val4 key1=val10 key6=val5 key3=val1 
put item1
show_users
show_users
help pwd
show_items
rename_user user0 <function generate_user at 0x027087F0>
create_folder folder2
ls
pwd
show_folders
show_folders
show_folders
show_item_properties item1
register_admin user5 pass5
rename_user user4 <function generate_user at 0x027087F0>
buy
rename_user user6 <function generate_user at 0x027087F0>
which_group
sign_in a4 pa4
help view_order
sign_in admin admin
put item1
ls
show_items
sign_in a4 pa4
show_item_properties item2
show_users
create_folder folder5
add_item_property item3 key3=val6 key9=val8 key6=val1 key9=val9 
current_folder
ls
show_item_properties item4
buy
register_admin user8 pass8
whoami
buy
which_group
cd folder3
put item5
create_folder folder4
register_user user7 pass7
buy
current_folder
cd folder4
register_user user5 pass5
put item4
help create_folder
register_user admin admin
cd folder4
create_folder folder2
show_item_properties item3
which_group
sign_out
which_group
which_group
sign_in a1 pa1
show_folders
cd folder2
cd folder4
sign_in user3 pass3
help delete_user
add_item item2 key7=val8 key1=val5 key8=val10 key5=val9 
rename_user user8 <function generate_user at 0x027087F0>
register_user user7 pass7
whoami
help cd
show_users
which_group
show_folders
put item2
create_folder folder4
rename_user user3 <function generate_user at 0x027087F0>
sign_in admin admin
put item4
which_group
sign_in a1 pa1
add_item item2 key2=val5 key2=val1 key3=val5 key10=val1 
register_user user8 pass8
ls_folders
ls_folders
show_item_properties item2
show_users
which_group
sign_in a5 pa5
buy
put item5
add_item_property item4 key2=val2 key10=val5 key7=val8 key6=val1 
create_folder folder1
show_folders
current_folder
create_folder folder3
register_user user5 pass5
which_group
rename_user user7 <function generate_user at 0x027087F0>
current_folder
add_item item1 key3=val5 key9=val10 key4=val6 key1=val9 
show_folders
register_admin user1 pass1
current_folder
buy
sign_in user1 pass1
sign_out
show_folders
current_folder
rename_user user2 <function generate_user at 0x027087F0>
register_user user5 pass5
cd folder5
sign_out
which_group
ls
register_admin user2 pass2
add_item_property item5 key5=val8 key5=val5 key6=val3 key3=val10 
ls
ls_folders
sign_in a3 pa3
put item4
which_group
create_folder folder5
buy
sign_out
ls
buy
help put
help register_user
cd folder3
buy
pwd
register_user user8 pass8
rename_user user8 <function generate_user at 0x027087F0>
show_item_properties item5
current_folder
pwd
sign_in a2 pa2
show_item_properties item4
show_folders
register_admin user5 pass5
show_items
current_folder
sign_in a3 pa3
pwd
buy
add_item item3 key5=val9 key7=val5 key8=val6 key8=val6 
show_folders
sign_in user6 pass6
show_users
buy
register_admin user9 pass9
ls
add_item item3 key8=val8 key9=val9 key3=val7 key9=val10 
pwd
show_users
sign_out
show_folders
register_admin user1 pass1
pwd
show_users
help buy
show_users
pwd
sign_in user7 pass7
show_folders
register_user user9 pass9
current_folder
show_items
create_folder folder2
rename_user user0 <function generate_user at 0x027087F0>
current_folder
create_folder folder3
sign_out
cd folder1
cd folder5
help buy
whoami
add_item_property item2 key2=val4 key7=val6 key1=val2 key2=val6 
pwd
register_user user2 pass2
buy
put item3
sign_in a3 pa3
current_folder
whoami
sign_in user6 pass6
sign_in user8 pass8
sign_in a5 pa5
rename_user user0 <function generate_user at 0x027087F0>
put item4
current_folder
show_items
buy
cd folder5
current_folder
show_items
pwd
pwd
which_group
ls_folders
ls_folders
show_users
whoami
add_item item4 key2=val10 key2=val4 key10=val3 key5=val6 
which_group
sign_in a5 pa5
ls
help register_admin
rename_user user8 <function generate_user at 0x027087F0>
show_items
create_folder folder2
sign_in a5 pa5
which_group
ls_folders
buy
current_folder
pwd
current_folder
show_items
add_item_property item5 key5=val3 key2=val6 key7=val5 key5=val4 
sign_in user4 pass4
pwd
put item5
current_folder
add_item_property item4 key3=val10 key10=val6 key5=val8 key3=val9 
show_item_properties item1
ls_folders
create_folder folder1
which_group
rename_user user2 <function generate_user at 0x027087F0>
show_items
pwd
show_users
show_folders
sign_in user5 pass5
show_folders
sign_out
ls_folders
register_admin admin admin
sign_in user9 pass9
sign_in user3 pass3
show_users
ls
show_users
create_folder folder1
ls
show_items
cd folder5
rename_user user6 <function generate_user at 0x027087F0>
show_item_properties item4
sign_in a1 pa1
rename_user user4 <function generate_user at 0x027087F0>
register_user user8 pass8
current_folder
buy
ls
create_folder folder1
sign_in user4 pass4
pwd
add_item_property item3 key8=val1 key10=val5 key2=val3 key9=val4 
add_item item1 key6=val4 key3=val8 key9=val8 key4=val9 
add_item_property item1 key8=val3 key8=val5 key9=val5 key3=val10 
show_item_properties item5
help help
ls
register_admin user4 pass4
show_item_properties item1
add_item item4 key9=val6 key3=val4 key10=val1 key2=val1 
help history
buy
sign_in admin admin
pwd
add_item_property item3 key1=val8 key5=val4 key8=val4 key4=val7 
current_folder
sign_in user9 pass9
sign_out
sign_out
whoami
sign_in user7 pass7
sign_out
sign_in user1 pass1
put item1
show_folders
help show_folders
whoami
show_items
current_folder
sign_out
show_items
add_item item4 key6=val3 key2=val7 key2=val5 key3=val2 
help show_users
ls
show_users
sign_out
rename_user user5 <function generate_user at 0x027087F0>
sign_in a3 pa3
ls_folders
show_folders
buy
whoami
show_items
buy
show_item_properties item2
cd folder5
add_item item1 key10=val3 key6=val9 key6=val3 key10=val8 
add_item_property item3 key3=val10 key10=val2 key3=val7 key5=val1 
register_admin user1 pass1
pwd
show_users
sign_in a4 pa4
put item2
buy
help show_items
put item1
register_user user3 pass3
put item3
ls_folders
show_item_properties item2
pwd
sign_out
rename_user user5 <function generate_user at 0x027087F0>
show_items
ls_folders
current_folder
show_folders
whoami
sign_in user6 pass6
cd folder2
register_admin user9 pass9
sign_in a4 pa4
sign_in a5 pa5
show_users
ls_folders
sign_in user8 pass8
sign_out
add_item item2 key6=val7 key2=val4 key9=val7 key7=val1 
sign_in admin admin
pwd
buy
current_folder
sign_in user1 pass1
buy
show_users
ls_folders
add_item item3 key4=val9 key2=val4 key10=val5 key6=val10 
create_folder folder2
buy
ls_folders
rename_user user3 <function generate_user at 0x027087F0>
ls
show_users
register_user user7 pass7
cd folder4
show_items
buy
add_item item2 key7=val6 key4=val2 key10=val8 key8=val4 
sign_in a1 pa1
ls_folders
ls
show_item_properties item3
whoami
show_folders
show_item_properties item3
put item1
buy
buy
add_item_property item5 key9=val9 key8=val5 key8=val9 key4=val9 
ls
sign_in a3 pa3
register_user user8 pass8
put item2
register_user user4 pass4
ls
put item5
show_users
register_admin user5 pass5
which_group
add_item_property item4 key10=val3 key5=val5 key1=val2 key4=val1 
show_item_properties item4
sign_in a4 pa4
sign_in a2 pa2
put item1
show_folders
show_item_properties item3
cd folder3
show_item_properties item3
ls
ls_folders
sign_in a5 pa5
show_folders
show_users
create_folder folder4
buy
add_item_property item1 key6=val8 key5=val5 key3=val8 key4=val5 
show_item_properties item1
help buy
current_folder
add_item item2 key1=val7 key1=val2 key6=val6 key9=val8 
ls
show_items
cd folder5
create_folder folder1
pwd
ls_folders
pwd
sign_in a3 pa3
cd folder5
put item1
rename_user user8 <function generate_user at 0x027087F0>
show_folders
cd folder2
cd folder5
buy
create_folder folder3
pwd
sign_in a2 pa2
add_item item2 key9=val2 key8=val3 key4=val8 key2=val3 
ls_folders
which_group
register_admin user4 pass4
put item2
pwd
which_group
whoami
sign_in a3 pa3
help help
register_admin user8 pass8
register_admin user4 pass4
sign_in a4 pa4
sign_in user2 pass2
rename_user user7 <function generate_user at 0x027087F0>
whoami
current_folder
rename_user user0 <function generate_user at 0x027087F0>
add_item_property item2 key7=val3 key4=val7 key3=val10 key3=val2 
put item1
show_folders
which_group
put item5
ls_folders
register_admin user4 pass4
create_folder folder2
create_folder folder3
which_group
buy
which_group
sign_in user1 pass1
show_items
add_item_property item1 key8=val3 key7=val6 key3=val7 key4=val5 
show_items
sign_in user4 pass4
sign_in user4 pass4
cd folder3
current_folder
ls
show_users
cd folder5
help show_items
show_item_properties item5
ls_folders
show_item_properties item2
sign_in a1 pa1
register_user user9 pass9
ls_folders
which_group
current_folder
ls
pwd
show_folders
ls_folders
show_users
register_user user8 pass8
current_folder
help cd
create_folder folder2
show_users
sign_in a4 pa4
sign_out
show_folders
help create_folder
sign_in a5 pa5
show_item_properties item2
rename_user user0 <function generate_user at 0x027087F0>
register_admin user5 pass5
current_folder
register_user admin admin
show_item_properties item2
sign_in admin admin
ls
add_item item4 key9=val7 key10=val7 key3=val7 key4=val3 
create_folder folder4
register_user user1 pass1
register_admin user2 pass2
ls_folders
register_admin user6 pass6
current_folder
current_folder
pwd
register_user user6 pass6
put item3
add_item item4 key9=val2 key8=val9 key4=val8 key8=val1 
pwd
rename_user user9 <function generate_user at 0x027087F0>
whoami
whoami
whoami
add_item item2 key1=val1 key1=val10 key7=val6 key9=val5 
sign_out
create_folder folder4
register_admin user6 pass6
add_item_property item4 key7=val8 key8=val8 key1=val10 key8=val2 
show_items
ls
register_user admin admin
show_folders
sign_out
buy
ls_folders
whoami
sign_in admin admin
buy
which_group
show_items
help ls_folders
which_group
add_item_property item3 key7=val9 key10=val9 key1=val5 key4=val1 
sign_out
register_user admin admin
put item2
ls
register_user user3 pass3
buy
pwd
add_item item3 key2=val4 key10=val1 key4=val10 key2=val10 
sign_in a2 pa2
sign_in a5 pa5
put item2
cd folder3
sign_out
cd folder4
put item4
show_items
cd folder2
add_item item4 key4=val2 key1=val2 key8=val8 key1=val4 
register_user user7 pass7
add_item_property item1 key8=val3 key1=val5 key5=val2 key2=val8 
add_item_property item5 key6=val5 key8=val8 key8=val1 key3=val6 
current_folder
whoami
ls_folders
register_user user3 pass3
show_item_properties item3
show_item_properties item5
register_admin user7 pass7
put item4
add_item_property item5 key3=val4 key3=val4 key5=val5 key1=val7 
show_users
sign_out
cd folder4
ls_folders
sign_in a4 pa4
sign_out
ls_folders
register_admin admin admin
show_item_properties item4
add_item_property item3 key6=val2 key8=val10 key10=val7 key1=val4 
current_folder
put item5
create_folder folder3
cd folder4
show_folders
show_users
show_items
add_item_property item2 key10=val6 key5=val7 key6=val10 key7=val3 
add_item_property item4 key7=val3 key3=val3 key1=val1 key5=val7 
ls_folders
show_users
pwd
ls_folders
help register_user
register_admin user6 pass6
register_admin user3 pass3
help add_item
buy
show_folders
current_folder
sign_in a2 pa2
show_folders
add_item_property item5 key8=val6 key10=val7 key8=val2 key9=val2 
current_folder
show_folders
buy
add_item item2 key8=val6 key7=val4 key1=val8 key8=val2 
register_user user7 pass7
help delete_user
show_users
show_folders
ls
register_user user8 pass8
whoami
add_item item4 key9=val9 key6=val2 key9=val4 key9=val2 
whoami
buy
ls
add_item item5 key3=val4 key10=val8 key3=val4 key2=val10 
put item2
show_folders
put item5
register_admin user8 pass8
which_group
add_item item5 key1=val9 key9=val7 key1=val4 key1=val9 
register_admin user5 pass5
show_items
sign_in a2 pa2
show_item_properties item5
show_users
pwd
ls_folders
pwd
register_admin user1 pass1
register_user user7 pass7
pwd
ls_folders
show_folders
ls
current_folder
ls
buy
sign_in a4 pa4
current_folder
ls
create_folder folder2
show_users
put item4
show_item_properties item3
add_item_property item5 key4=val9 key9=val3 key2=val2 key6=val4 
show_item_properties item2
sign_out
create_folder folder3
show_items
show_folders
ls
help add_item_property
add_item item4 key2=val2 key3=val9 key4=val2 key7=val1 
whoami
show_folders
show_folders
sign_in user7 pass7
add_item item3 key3=val1 key1=val1 key7=val3 key9=val5 
cd folder2
cd folder5
help register_admin
current_folder
current_folder
help cd
buy
create_folder folder1
ls
sign_in a2 pa2
ls
sign_in user9 pass9
buy
rename_user user7 <function generate_user at 0x027087F0>
pwd
sign_in a5 pa5
which_group
pwd
sign_in user8 pass8
ls_folders
put item3
buy
current_folder
show_items
rename_user user6 <function generate_user at 0x027087F0>
put item5
show_users
add_item_property item2 key5=val1 key4=val9 key10=val10 key7=val1 
ls
sign_in a5 pa5
show_items
create_folder folder3
sign_in user8 pass8
show_items
show_folders
sign_out
rename_user user7 <function generate_user at 0x027087F0>
sign_in a1 pa1
register_admin user4 pass4
rename_user user2 <function generate_user at 0x027087F0>
which_group
add_item_property item4 key10=val9 key4=val1 key10=val4 key2=val9 
rename_user user1 <function generate_user at 0x027087F0>
cd folder5
show_item_properties item1
pwd
create_folder folder5
register_admin user9 pass9
current_folder
sign_out
ls_folders
create_folder folder1
create_folder folder1
sign_out
put item1
show_item_properties item4
put item4
buy
ls
add_item item1 key4=val10 key3=val10 key7=val6 key5=val3 
sign_in user1 pass1
current_folder
show_folders
which_group
help add_item_property
register_user user9 pass9
ls_folders
create_folder folder1
show_items
help delete_user
show_users
which_group
rename_user user7 <function generate_user at 0x027087F0>
register_user user9 pass9
whoami
show_item_properties item2
add_item_property item2 key10=val10 key1=val4 key4=val8 key4=val4 
pwd
register_admin user1 pass1
show_users
create_folder folder1
sign_in user2 pass2
whoami
which_group
show_item_properties item5
show_items
help sign_out
sign_out
cd folder3
add_item item4 key6=val6 key4=val5 key5=val6 key6=val7 
buy
register_user admin admin
ls
buy
add_item_property item4 key3=val5 key1=val10 key10=val5 key4=val2 
register_admin admin admin
register_user user4 pass4
add_item item3 key6=val6 key10=val8 key3=val2 key6=val10 
register_admin user7 pass7
register_user user1 pass1
ls_folders
show_folders
add_item item4 key2=val3 key3=val9 key8=val8 key6=val9 
buy
show_item_properties item5
put item3
show_users
sign_out
sign_out
show_folders
sign_in admin admin
show_users
current_folder
put item3
rename_user user2 <function generate_user at 0x027087F0>
register_admin user7 pass7
buy
sign_out
current_folder
register_admin user8 pass8
sign_out
add_item_property item3 key5=val10 key3=val7 key7=val8 key5=val10 
show_items
show_folders
which_group
show_folders
ls
register_user user9 pass9
register_user user1 pass1
ls_folders
register_user user4 pass4
register_admin user3 pass3
show_items
show_items
ls_folders
sign_out
show_item_properties item3
ls
sign_out
show_item_properties item3
cd folder3
help ls
rename_user user0 <function generate_user at 0x027087F0>
register_admin user6 pass6
current_folder
whoami
show_item_properties item3
sign_in user9 pass9
sign_out
register_user user3 pass3
add_item_property item4 key3=val7 key7=val3 key4=val1 key9=val8 
help show_users
cd folder1
add_item item3 key6=val5 key5=val6 key6=val10 key3=val5 
show_items
cd folder4
whoami
sign_in a3 pa3
show_folders
whoami
rename_user user7 <function generate_user at 0x027087F0>
current_folder
register_admin user6 pass6
create_folder folder3
create_folder folder4
register_admin user1 pass1
register_admin user8 pass8
add_item_property item3 key3=val5 key9=val2 key10=val5 key1=val6 
add_item_property item2 key9=val7 key9=val8 key7=val2 key9=val4 
register_admin user9 pass9
buy
cd folder3
help pwd
which_group
which_group
register_user user5 pass5
put item3
which_group
register_admin user3 pass3
pwd
pwd
buy
show_users
sign_in a5 pa5
which_group
add_item item5 key1=val4 key3=val1 key5=val9 key6=val6 
show_users
ls_folders
rename_user user5 <function generate_user at 0x027087F0>
ls
register_user user7 pass7
ls
pwd
pwd
which_group
whoami
put item4
register_user user4 pass4
cd folder1
current_folder
sign_in user9 pass9
show_items
rename_user user1 <function generate_user at 0x027087F0>
help pwd
pwd
whoami
sign_in a4 pa4
put item2
whoami
ls
sign_in a1 pa1
put item1
buy
show_users
add_item item2 key6=val5 key4=val4 key4=val1 key1=val8 
help cd
help add_item_property
create_folder folder2
show_users
sign_in a5 pa5
which_group
ls_folders
register_user user2 pass2
ls
register_user user2 pass2
sign_out
whoami
rename_user user0 <function generate_user at 0x027087F0>
register_user user7 pass7
show_items
sign_out
sign_in a5 pa5
add_item_property item2 key9=val8 key4=val10 key9=val7 key5=val10 
show_items
pwd
put item3
cd folder1
ls
rename_user user0 <function generate_user at 0x027087F0>
show_folders
register_admin user9 pass9
cd folder2
pwd
add_item_property item1 key8=val7 key2=val8 key6=val10 key2=val10 
whoami
show_items
show_item_properties item5
put item1
cd folder1
put item4
show_item_properties item4
add_item item3 key1=val2 key5=val6 key10=val3 key5=val10 
register_admin user5 pass5
current_folder
create_folder folder4
ls
sign_in user7 pass7
help whoami
sign_out
rename_user user5 <function generate_user at 0x027087F0>
register_user admin admin
cd folder1
current_folder
ls
which_group
buy
show_item_properties item1
create_folder folder5
buy
sign_in a1 pa1
which_group
register_admin user2 pass2
help add_item
current_folder
show_users
register_user user9 pass9
current_folder
put item4
show_items
register_admin user5 pass5
show_folders
current_folder
help show_users
add_item_property item5 key7=val6 key6=val7 key1=val8 key5=val8 
cd folder4
show_items
show_item_properties item2
register_user user1 pass1
sign_in a1 pa1
register_user user9 pass9
current_folder
show_folders
create_folder folder4
sign_in a1 pa1
pwd
whoami
rename_user user5 <function generate_user at 0x027087F0>
pwd
put item4
ls
add_item item3 key6=val6 key6=val6 key5=val8 key9=val10 
add_item_property item2 key5=val8 key8=val7 key10=val3 key3=val7 
buy
show_folders
pwd
pwd
show_folders
show_item_properties item2
put item5
whoami
help register_admin
rename_user user8 <function generate_user at 0x027087F0>
add_item item3 key6=val8 key10=val2 key9=val6 key4=val8 
sign_in user9 pass9
ls_folders
current_folder
rename_user user7 <function generate_user at 0x027087F0>
add_item_property item3 key7=val3 key2=val3 key8=val8 key1=val8 
show_folders
register_admin user9 pass9
register_user user5 pass5
which_group
create_folder folder4
create_folder folder5
register_admin user5 pass5
show_users
register_user admin admin
buy
ls
whoami
show_users
create_folder folder1
which_group
create_folder folder3
register_user user9 pass9
buy
show_item_properties item1
buy
show_items
buy
which_group
help add_item
pwd
whoami
register_user user2 pass2
sign_in user1 pass1
put item4
cd folder2
ls
ls
cd folder5
create_folder folder5
create_folder folder5
show_item_properties item3
show_item_properties item4
cd folder4
show_folders
show_users
sign_in a3 pa3
show_item_properties item2
help add_item_property
register_user user2 pass2
ls
buy
whoami
sign_in a4 pa4
buy
show_item_properties item2
show_item_properties item5
show_users
register_user user5 pass5
show_item_properties item4
which_group
which_group
show_items
show_item_properties item1
cd folder3
show_folders
create_folder folder1
put item5
show_items
register_user user5 pass5
put item3
sign_out
sign_out
sign_in user4 pass4
pwd
ls
ls
which_group
rename_user user8 <function generate_user at 0x027087F0>
register_user user8 pass8
register_admin admin admin
ls_folders
add_item item5 key6=val2 key4=val7 key10=val7 key1=val4 
register_user user1 pass1
buy
register_user user6 pass6
help pwd
ls
help buy
add_item_property item5 key6=val7 key8=val4 key5=val7 key9=val8 
ls_folders
buy
buy
show_folders
create_folder folder1
current_folder
show_item_properties item5
current_folder
buy
whoami
add_item item5 key1=val10 key9=val3 key7=val6 key9=val4 
show_items
sign_in a5 pa5
sign_in user8 pass8
help show_users
sign_out
sign_out
whoami
which_group
register_user user7 pass7
register_user user4 pass4
show_users
sign_in user2 pass2
current_folder
sign_in user1 pass1
add_item item5 key2=val6 key5=val9 key5=val3 key10=val6 
whoami
register_admin user9 pass9
help sign_in
create_folder folder4
show_item_properties item2
rename_user user6 <function generate_user at 0x027087F0>
register_admin user8 pass8
show_item_properties item1
ls
create_folder folder5
sign_out
register_admin admin admin
sign_in a3 pa3
show_users
add_item_property item2 key2=val10 key3=val4 key7=val1 key3=val8 
ls
show_users
which_group
add_item_property item2 key9=val1 key10=val1 key7=val9 key9=val9 
put item2
create_folder folder1
create_folder folder1
register_user admin admin
cd folder1
pwd
show_users
rename_user user2 <function generate_user at 0x027087F0>
sign_in user4 pass4
current_folder
show_item_properties item3
ls_folders
ls
sign_in a2 pa2
add_item item5 key6=val3 key6=val2 key8=val9 key3=val1 
ls
rename_user user1 <function generate_user at 0x027087F0>
pwd
pwd
current_folder
sign_in a1 pa1
rename_user user7 <function generate_user at 0x027087F0>
add_item item5 key3=val8 key4=val9 key9=val2 key5=val1 
which_group
create_folder folder4
sign_out
which_group
sign_in user3 pass3
rename_user user8 <function generate_user at 0x027087F0>
help help
show_item_properties item2
show_users
add_item item5 key5=val8 key6=val2 key2=val5 key10=val6 
sign_in admin admin
sign_in a5 pa5
register_user user9 pass9
put item3
sign_in a5 pa5
show_item_properties item5
sign_out
sign_in admin admin
current_folder
register_admin user6 pass6
rename_user user7 <function generate_user at 0x027087F0>
sign_out
show_folders
show_users
add_item_property item5 key2=val3 key6=val2 key10=val5 key5=val4 
ls_folders
show_items
register_admin user8 pass8
current_folder
create_folder folder4
register_user user1 pass1
sign_in a5 pa5
cd folder5
rename_user user0 <function generate_user at 0x027087F0>
buy
add_item item5 key5=val1 key10=val1 key7=val10 key9=val7 
current_folder
help delete_user
add_item item2 key3=val6 key9=val10 key1=val10 key9=val5 
current_folder
cd folder1
create_folder folder5
whoami
rename_user user0 <function generate_user at 0x027087F0>
help register_admin
pwd
whoami
help sign_in
sign_in user2 pass2
register_user user5 pass5
add_item item1 key6=val5 key5=val10 key10=val6 key1=val1 
show_folders
show_items
pwd
help create_folder
show_folders
create_folder folder4
create_folder folder1
buy
show_users
whoami
register_user user5 pass5
whoami
rename_user user7 <function generate_user at 0x027087F0>
add_item item2 key5=val4 key8=val2 key8=val4 key4=val3 
show_item_properties item2
sign_in user6 pass6
register_admin user4 pass4
whoami
pwd
help show_folders
sign_in user2 pass2
show_items
sign_in a5 pa5
current_folder
create_folder folder2
help ls
sign_out
show_users
buy
pwd
add_item item2 key6=val10 key2=val9 key5=val5 key10=val3 
show_users
current_folder
current_folder
register_user user8 pass8
create_folder folder2
sign_in user5 pass5
show_items
rename_user user7 <function generate_user at 0x027087F0>
which_group
which_group
put item1
show_items
add_item_property item5 key3=val1 key8=val10 key10=val1 key9=val1 
create_folder folder1
show_users
show_item_properties item5
put item4
show_items
create_folder folder4
put item4
sign_in a4 pa4
help put
buy
add_item_property item5 key5=val9 key2=val7 key3=val10 key5=val10 
ls
which_group
add_item_property item5 key8=val10 key3=val3 key7=val2 key1=val8 
sign_in user9 pass9
pwd
add_item item1 key9=val7 key5=val8 key7=val9 key6=val8 
rename_user user0 <function generate_user at 0x027087F0>
ls_folders
ls
help rename_user
sign_in user8 pass8
pwd
register_admin user9 pass9
show_folders
add_item_property item3 key1=val4 key9=val5 key8=val9 key7=val10 
add_item item4 key3=val10 key4=val6 key6=val6 key3=val9 
show_item_properties item4
rename_user user1 <function generate_user at 0x027087F0>
show_items
cd folder3
register_admin user1 pass1
add_item_property item5 key6=val8 key1=val9 key6=val4 key1=val9 
create_folder folder2
register_admin user9 pass9
cd folder5
whoami
which_group
buy
show_item_properties item2
buy
show_items
sign_in a4 pa4
add_item item4 key1=val3 key8=val1 key5=val4 key3=val9 
sign_in a2 pa2
put item2
buy
show_items
pwd
ls_folders
create_folder folder4
rename_user user1 <function generate_user at 0x027087F0>
create_folder folder4
sign_out
show_item_properties item4
sign_in a2 pa2
cd folder2
show_users
current_folder
register_admin user6 pass6
ls
register_admin user6 pass6
register_user user5 pass5
sign_in a3 pa3
ls
rename_user user7 <function generate_user at 0x027087F0>
pwd
ls_folders
whoami
ls_folders
which_group
add_item item1 key10=val9 key7=val1 key6=val1 key2=val8 
pwd
register_admin user7 pass7
create_folder folder1
register_admin user1 pass1
buy
ls
register_user user3 pass3
add_item item1 key7=val1 key6=val2 key4=val10 key7=val5 
ls
pwd
show_users
show_users
sign_out
register_admin user3 pass3
show_folders
show_folders
sign_in a2 pa2
register_admin user8 pass8
show_users
register_admin user5 pass5
ls
show_items
put item3
sign_in a4 pa4
register_user user1 pass1
show_folders
help add_item_property
ls
cd folder1
put item1
register_user user7 pass7
ls_folders
whoami
show_users
which_group
help show_item_properties
ls
buy
help register_user
which_group
whoami
put item4
sign_in a4 pa4
register_user user2 pass2
add_item item3 key6=val9 key7=val5 key7=val7 key3=val3 
show_item_properties item1
help sign_out
cd folder3
rename_user user8 <function generate_user at 0x027087F0>
put item1
current_folder
sign_in user8 pass8
add_item_property item3 key4=val3 key1=val5 key7=val3 key7=val10 
register_admin user2 pass2
register_user user9 pass9
sign_in a5 pa5
add_item item4 key10=val1 key2=val8 key10=val6 key9=val5 
show_item_properties item1
create_folder folder3
put item2
ls
put item3
which_group
add_item_property item1 key8=val1 key6=val3 key1=val2 key7=val1 
show_item_properties item2
register_user user6 pass6
rename_user user8 <function generate_user at 0x027087F0>
ls
ls
add_item item3 key9=val2 key8=val3 key8=val5 key8=val6 
add_item_property item5 key2=val8 key3=val2 key10=val10 key2=val9 
rename_user user7 <function generate_user at 0x027087F0>
help current_folder
add_item item2 key1=val9 key6=val6 key6=val1 key7=val3 
buy
current_folder
add_item item4 key7=val2 key10=val8 key7=val8 key10=val9 
pwd
rename_user user0 <function generate_user at 0x027087F0>
whoami
pwd
add_item_property item2 key5=val6 key8=val5 key10=val1 key3=val5 
create_folder folder3
add_item_property item3 key5=val7 key10=val5 key7=val9 key8=val5 
sign_out
add_item item2 key4=val3 key5=val7 key6=val1 key4=val9 
show_item_properties item4
ls
buy
sign_in a4 pa4
show_items
sign_in admin admin
buy
cd folder5
add_item_property item2 key3=val4 key6=val10 key8=val5 key10=val4 
pwd
rename_user user9 <function generate_user at 0x027087F0>
register_admin user8 pass8
ls_folders
whoami
current_folder
sign_in a4 pa4
which_group
current_folder
register_user user6 pass6
add_item_property item5 key8=val4 key1=val4 key3=val5 key3=val8 
put item1
rename_user user1 <function generate_user at 0x027087F0>
add_item_property item2 key9=val10 key2=val6 key2=val3 key1=val7 
ls
show_item_properties item3
which_group
register_admin user5 pass5
whoami
put item5
sign_in a3 pa3
sign_in a4 pa4
rename_user user8 <function generate_user at 0x027087F0>
sign_out
show_users
register_user user2 pass2
add_item_property item5 key1=val7 key4=val8 key10=val1 key8=val7 
sign_in admin admin
add_item item3 key9=val5 key4=val2 key6=val4 key7=val6 
register_user user9 pass9
rename_user user6 <function generate_user at 0x027087F0>
ls
show_item_properties item1
help put
help rename_user
show_folders
which_group
rename_user user3 <function generate_user at 0x027087F0>
ls
add_item item1 key6=val3 key9=val5 key9=val7 key6=val10 
sign_in user3 pass3
register_user user2 pass2
create_folder folder2
show_item_properties item5
show_folders
add_item item2 key5=val3 key4=val1 key5=val8 key9=val10 
sign_in a5 pa5
show_item_properties item3
show_items
cd folder4
whoami
rename_user user8 <function generate_user at 0x027087F0>
ls
which_group
register_user user9 pass9
register_user user1 pass1
cd folder3
buy
whoami
register_admin user4 pass4
register_user user3 pass3
which_group
create_folder folder5
show_folders
show_item_properties item3
create_folder folder2
sign_out
show_folders
cd folder4
current_folder
pwd
show_items
show_item_properties item5
show_items
sign_out
show_users
cd folder3
whoami
help cd
show_users
buy
show_users
show_items
buy
add_item_property item2 key7=val5 key7=val2 key5=val10 key9=val3 
show_items
register_user user6 pass6
buy
cd folder1
ls
sign_in a5 pa5
show_items
add_item item4 key4=val9 key3=val1 key6=val1 key1=val5 
register_admin user7 pass7
sign_out
help delete_user
rename_user user4 <function generate_user at 0x027087F0>
ls
pwd
sign_in user9 pass9
add_item_property item5 key2=val9 key10=val2 key8=val2 key3=val10 
sign_in user3 pass3
which_group
rename_user user1 <function generate_user at 0x027087F0>
ls_folders
show_items
sign_in user2 pass2
which_group
sign_in user2 pass2
add_item_property item3 key2=val9 key10=val2 key9=val3 key10=val2 
sign_in user9 pass9
create_folder folder4
add_item_property item1 key10=val8 key2=val2 key2=val3 key8=val9 
register_admin user8 pass8
current_folder
register_user admin admin
create_folder folder5
cd folder5
sign_in a4 pa4
sign_in a2 pa2
current_folder
show_item_properties item1
ls
add_item_property item2 key7=val5 key1=val2 key5=val7 key4=val3 
register_user admin admin
add_item_property item4 key3=val9 key2=val1 key8=val1 key2=val9 
show_items
register_user user2 pass2
ls_folders
pwd
register_admin user6 pass6
buy
ls
rename_user user0 <function generate_user at 0x027087F0>
show_items
create_folder folder4
add_item_property item5 key9=val9 key2=val4 key1=val7 key6=val10 
ls_folders
pwd
show_items
add_item_property item1 key7=val1 key9=val6 key10=val10 key9=val3 
ls_folders
current_folder
sign_in a4 pa4
register_user user6 pass6
which_group
sign_in a1 pa1
current_folder
rename_user user5 <function generate_user at 0x027087F0>
show_item_properties item1
add_item item1 key5=val6 key1=val4 key9=val6 key9=val5 
cd folder2
whoami
whoami
create_folder folder4
ls_folders
show_item_properties item2
current_folder
sign_in user2 pass2
sign_out
put item4
pwd
sign_out
add_item item1 key6=val2 key4=val4 key7=val6 key7=val10 
ls
put item4
which_group
put item5
register_user user8 pass8
register_user user3 pass3
current_folder
add_item_property item3 key3=val7 key3=val10 key10=val2 key7=val8 
rename_user user8 <function generate_user at 0x027087F0>
whoami
ls_folders
whoami
show_users
which_group
which_group
show_items
rename_user user0 <function generate_user at 0x027087F0>
help show_folders
sign_in user3 pass3
add_item item2 key4=val8 key10=val7 key3=val10 key9=val4 
sign_in user4 pass4
sign_in a4 pa4
which_group
cd folder2
register_user user7 pass7
ls_folders
show_item_properties item5
sign_in a3 pa3
put item2
show_users
show_users
show_item_properties item2
create_folder folder4
sign_in user9 pass9
sign_in admin admin
register_admin user9 pass9
register_admin user5 pass5
show_items
put item4
ls
sign_in user3 pass3
sign_out
sign_out
sign_in user2 pass2
sign_in user4 pass4
add_item item2 key3=val8 key3=val7 key3=val3 key1=val8 
sign_in a2 pa2
show_items
put item1
whoami
register_user user4 pass4
create_folder folder2
current_folder
put item1
show_items
register_admin user7 pass7
buy
add_item item2 key10=val3 key2=val9 key8=val2 key3=val8 
help exit
ls_folders
sign_out
buy
register_admin user9 pass9
sign_out
show_users
cd folder5
sign_in user7 pass7
add_item_property item5 key9=val4 key4=val1 key2=val8 key3=val7 
show_folders
sign_out
ls
register_user admin admin
rename_user user9 <function generate_user at 0x027087F0>
sign_in user6 pass6
show_folders
whoami
buy
show_folders
whoami
whoami
cd folder1
add_item item3 key6=val5 key6=val7 key1=val4 key6=val4 
add_item_property item3 key6=val4 key7=val6 key8=val1 key7=val7 
sign_out
buy
register_user user6 pass6
current_folder
ls_folders
current_folder
register_user user7 pass7
pwd
register_admin user4 pass4
register_user user8 pass8
which_group
ls_folders
pwd
show_item_properties item5
cd folder5
add_item item5 key9=val3 key6=val1 key1=val9 key6=val4 
add_item item2 key6=val8 key3=val10 key7=val6 key8=val1 
ls
show_folders
pwd
pwd
show_users
sign_in user2 pass2
register_user user2 pass2
help ls_folders
buy
show_item_properties item4
sign_out
create_folder folder5
add_item item2 key7=val4 key10=val7 key1=val2 key3=val1 
help create_folder
add_item item2 key6=val5 key10=val5 key5=val9 key8=val10 
sign_out
help put
sign_out
pwd
show_users
help pwd
sign_out
show_users
sign_in a5 pa5
create_folder folder3
add_item item2 key8=val8 key5=val7 key8=val8 key8=val7 
show_folders
add_item item5 key1=val7 key1=val8 key6=val7 key10=val9 
ls_folders
which_group
register_admin user2 pass2
rename_user user9 <function generate_user at 0x027087F0>
ls
pwd
register_user user6 pass6
create_folder folder2
show_users
ls
sign_in user7 pass7
show_item_properties item2
current_folder
help sign_out
show_item_properties item3
ls
put item2
add_item item3 key8=val8 key2=val1 key6=val10 key7=val10 
add_item_property item4 key1=val3 key2=val8 key7=val9 key8=val3 
rename_user user0 <function generate_user at 0x027087F0>
current_folder
show_users
add_item item4 key7=val4 key6=val9 key10=val2 key9=val10 
register_user user2 pass2
register_user user6 pass6
put item1
create_folder folder3
sign_out
show_users
pwd
sign_in user9 pass9
register_user user5 pass5
show_users
add_item item2 key5=val3 key3=val9 key1=val2 key2=val10 
help register_user
which_group
buy
add_item item5 key5=val4 key10=val6 key7=val4 key5=val1 
rename_user user8 <function generate_user at 0x027087F0>
sign_out
whoami
ls_folders
rename_user user8 <function generate_user at 0x027087F0>
cd folder5
sign_in a2 pa2
whoami
which_group
sign_in user4 pass4
cd folder4
whoami
rename_user user0 <function generate_user at 0x027087F0>
register_admin user3 pass3
show_folders
sign_in admin admin
sign_out
sign_in user8 pass8
add_item item3 key1=val10 key8=val6 key3=val2 key4=val10 
show_folders
cd folder5
show_users
sign_in a2 pa2
sign_out
which_group
put item3
create_folder folder2
sign_in user6 pass6
sign_in user1 pass1
show_item_properties item3
buy
buy
ls_folders
whoami
put item4
put item4
sign_out
sign_in admin admin
sign_in a3 pa3
ls_folders
put item2
cd folder5
show_users
whoami
show_items
which_group
which_group
show_folders
register_user user5 pass5
ls
cd folder3
sign_out
show_items
whoami
put item5
sign_out
sign_in user9 pass9
ls_folders
sign_out
whoami
rename_user user1 <function generate_user at 0x027087F0>
register_admin user9 pass9
show_items
show_folders
ls_folders
current_folder
buy
current_folder
show_item_properties item4
current_folder
sign_out
put item4
buy
register_user user5 pass5
ls_folders
pwd
whoami
show_items
create_folder folder2
ls
put item1
create_folder folder1
which_group
cd folder5
whoami
pwd
pwd
buy
sign_out
sign_in admin admin
put item5
show_folders
sign_in a5 pa5
sign_in a4 pa4
ls
add_item item1 key5=val9 key1=val8 key5=val9 key4=val6 
pwd
whoami
show_folders
show_items
show_item_properties item4
put item1
sign_in a3 pa3
show_users
ls_folders
cd folder4
add_item_property item3 key2=val2 key3=val5 key4=val2 key7=val2 
ls_folders
add_item item5 key8=val1 key9=val4 key6=val10 key4=val5 
pwd
which_group
cd folder5
show_items
register_admin user4 pass4
whoami
show_items
pwd
add_item_property item2 key2=val5 key10=val3 key5=val5 key3=val9 
show_item_properties item3
show_items
show_folders
put item3
show_items
show_item_properties item1
which_group
show_users
show_users
show_folders
add_item item2 key3=val4 key5=val1 key4=val10 key3=val10 
buy
add_item_property item1 key3=val7 key8=val7 key1=val1 key9=val6 
ls_folders
sign_in a1 pa1
sign_in a3 pa3
ls_folders
show_folders
register_admin user3 pass3
show_folders
whoami
sign_in a3 pa3
show_folders
create_folder folder3
ls
add_item item3 key2=val3 key10=val10 key1=val3 key6=val10 
show_item_properties item5
show_users
show_items
show_folders
show_users
pwd
create_folder folder4
ls_folders
show_items
whoami
show_item_properties item4
show_items
which_group
rename_user user7 <function generate_user at 0x027087F0>
whoami
cd folder3
cd folder3
current_folder
add_item item5 key5=val2 key4=val5 key8=val9 key9=val3 
which_group
show_folders
add_item_property item3 key3=val10 key6=val7 key1=val2 key10=val10 
ls
rename_user user3 <function generate_user at 0x027087F0>
cd folder4
create_folder folder2
ls
put item3
ls_folders
show_folders
buy
cd folder2
whoami
pwd
pwd
sign_out
sign_in user1 pass1
register_admin user3 pass3
create_folder folder1
ls
cd folder5
rename_user user7 <function generate_user at 0x027087F0>
show_users
cd folder1
put item2
register_user user1 pass1
sign_in a2 pa2
sign_out
create_folder folder5
ls_folders
show_items
create_folder folder4
show_item_properties item4
add_item item5 key1=val1 key8=val6 key2=val3 key8=val6 
show_items
add_item_property item3 key4=val4 key1=val3 key8=val7 key2=val2 
sign_in admin admin
whoami
show_item_properties item5
rename_user user3 <function generate_user at 0x027087F0>
show_item_properties item5
add_item_property item1 key10=val2 key2=val1 key1=val4 key4=val7 
add_item_property item5 key1=val10 key8=val4 key6=val8 key6=val8 
ls_folders
add_item_property item1 key6=val10 key6=val7 key7=val3 key1=val4 
sign_in admin admin
cd folder2
put item3
sign_out
show_users
sign_in user8 pass8
sign_in a5 pa5
sign_in user1 pass1
which_group
put item1
whoami
pwd
pwd
register_admin admin admin
cd folder2
help which_group
cd folder3
buy
show_items
show_users
put item5
rename_user user6 <function generate_user at 0x027087F0>
buy
show_users
rename_user user3 <function generate_user at 0x027087F0>
add_item_property item3 key7=val7 key2=val2 key1=val7 key6=val6 
add_item_property item2 key7=val8 key8=val9 key1=val9 key2=val5 
current_folder
help whoami
whoami
which_group
buy
sign_out
show_items
add_item_property item3 key1=val4 key3=val2 key2=val10 key6=val4 
rename_user user1 <function generate_user at 0x027087F0>
help put
cd folder3
current_folder
show_users
whoami
whoami
current_folder
register_user user5 pass5
sign_in a3 pa3
show_folders
current_folder
show_folders
sign_in a5 pa5
show_users
show_items
sign_in user2 pass2
pwd
ls
add_item item3 key3=val7 key2=val5 key1=val1 key6=val9 
register_user admin admin
show_folders
add_item_property item3 key5=val8 key7=val2 key4=val9 key4=val9 
show_folders
add_item_property item1 key4=val6 key8=val8 key3=val2 key9=val4 
register_user user6 pass6
put item1
register_user user6 pass6
register_user user5 pass5
sign_in a4 pa4
which_group
whoami
ls_folders
sign_out
ls
register_user user1 pass1
sign_in a1 pa1
show_users
add_item item2 key2=val9 key3=val5 key5=val10 key5=val8 
pwd
put item2
show_users
show_items
register_admin admin admin
buy
create_folder folder3
add_item item3 key4=val6 key9=val3 key8=val10 key3=val2 
add_item item1 key7=val5 key10=val4 key1=val10 key6=val4 
current_folder
add_item item3 key2=val6 key1=val3 key5=val9 key9=val3 
buy
show_folders
which_group
cd folder4
pwd
cd folder4
put item2
register_user user5 pass5
show_users
buy
sign_in user6 pass6
add_item item1 key10=val9 key2=val4 key2=val10 key4=val3 
add_item_property item1 key4=val7 key6=val5 key7=val7 key1=val9 
help current_folder
current_folder
whoami
rename_user user9 <function generate_user at 0x027087F0>
which_group
show_items
buy
current_folder
show_items
show_folders
create_folder folder5
whoami
sign_in user9 pass9
cd folder3
cd folder1
show_folders
show_item_properties item3
register_admin user8 pass8
add_item item5 key7=val2 key2=val7 key4=val10 key4=val4 
current_folder
sign_in user3 pass3
put item2
ls
sign_in user2 pass2
which_group
rename_user user4 <function generate_user at 0x027087F0>
put item3
ls
ls
ls
show_users
buy
show_folders
ls_folders
current_folder
ls_folders
sign_in a5 pa5
show_item_properties item5
current_folder
register_user user8 pass8
pwd
show_users
add_item_property item4 key6=val4 key2=val1 key9=val10 key10=val8 
show_users
which_group
show_items
add_item_property item3 key10=val3 key6=val3 key7=val1 key6=val3 
show_items
buy
add_item item5 key4=val1 key3=val6 key8=val5 key10=val6 
register_user user4 pass4
which_group
sign_out
show_item_properties item5
whoami
pwd
register_user user2 pass2
add_item_property item5 key7=val8 key7=val9 key10=val3 key5=val3 
show_folders
add_item item5 key3=val5 key4=val10 key4=val5 key6=val4 
register_user admin admin
pwd
sign_in user6 pass6
register_user user1 pass1
add_item_property item5 key6=val2 key9=val8 key10=val5 key1=val3 
whoami
add_item item5 key3=val4 key7=val6 key5=val8 key3=val2 
add_item item1 key3=val6 key5=val8 key10=val5 key9=val8 
help ls_folders
sign_in user6 pass6
whoami
add_item item4 key5=val3 key3=val5 key6=val5 key6=val8 
sign_out
pwd
sign_out
help view_order
show_item_properties item3
sign_in user8 pass8
create_folder folder4
add_item_property item1 key7=val4 key2=val2 key6=val8 key5=val8 
ls
ls_folders
show_item_properties item5
show_users
register_user user6 pass6
buy
which_group
create_folder folder2
show_folders
create_folder folder4
pwd
sign_in a2 pa2
register_admin user1 pass1
create_folder folder2
show_folders
sign_out
show_users
add_item item1 key8=val8 key7=val10 key5=val3 key1=val6 
whoami
sign_in user3 pass3
sign_in user2 pass2
cd folder2
current_folder
pwd
add_item_property item1 key7=val8 key3=val5 key6=val1 key2=val6 
add_item_property item1 key6=val8 key5=val7 key1=val5 key6=val3 
cd folder3
pwd
cd folder3
add_item item5 key10=val7 key3=val6 key5=val10 key2=val2 
current_folder
which_group
ls
sign_out
show_item_properties item5
whoami
show_item_properties item3
cd folder5
sign_out
create_folder folder4
show_folders
put item2
cd folder2
rename_user user4 <function generate_user at 0x027087F0>
register_admin user5 pass5
create_folder folder4
whoami
sign_in user9 pass9
create_folder folder1
pwd
add_item_property item2 key9=val5 key2=val3 key1=val10 key1=val2 
pwd
whoami
sign_out
register_user admin admin
whoami
add_item item2 key8=val9 key1=val10 key4=val8 key10=val7 
which_group
show_item_properties item3
show_users
whoami
ls
show_item_properties item2
sign_out
cd folder4
ls
buy
pwd
help current_folder
show_item_properties item2
rename_user user5 <function generate_user at 0x027087F0>
sign_in a1 pa1
show_users
sign_in user1 pass1
cd folder3
put item3
show_item_properties item5
whoami
show_item_properties item1
register_admin user9 pass9
buy
cd folder1
add_item_property item4 key3=val2 key3=val4 key6=val7 key5=val7 
register_admin user6 pass6
pwd
buy
sign_in a5 pa5
add_item item3 key9=val1 key6=val8 key5=val5 key8=val8 
register_user user1 pass1
create_folder folder2
create_folder folder1
sign_in user5 pass5
which_group
help history
create_folder folder5
cd folder4
register_admin user3 pass3
sign_in a5 pa5
current_folder
register_user user2 pass2
sign_in a4 pa4
add_item_property item3 key8=val9 key1=val3 key8=val3 key8=val10 
sign_in a3 pa3
add_item item4 key5=val4 key10=val6 key10=val8 key1=val5 
create_folder folder2
whoami
show_items
show_folders
create_folder folder3
pwd
register_user user5 pass5
show_item_properties item2
show_item_properties item2
sign_out
register_admin user8 pass8
create_folder folder2
register_user user9 pass9
ls
register_admin user3 pass3
register_admin user6 pass6
ls
whoami
sign_out
current_folder
sign_in a4 pa4
help buy
pwd
create_folder folder1
add_item item5 key3=val7 key5=val5 key10=val2 key10=val2 
ls
put item3
whoami
rename_user user4 <function generate_user at 0x027087F0>
register_user user8 pass8
show_items
rename_user user5 <function generate_user at 0x027087F0>
sign_out
create_folder folder4
register_user admin admin
sign_out
put item5
whoami
register_admin user5 pass5
create_folder folder4
ls
cd folder1
show_items
show_folders
pwd
sign_in a5 pa5
sign_in user2 pass2
buy
show_folders
show_items
show_users
sign_in user9 pass9
add_item item5 key2=val5 key9=val9 key2=val6 key7=val5 
show_folders
register_user user2 pass2
show_items
show_items
put item4
buy
current_folder
show_items
cd folder5
show_items
create_folder folder1
register_user user9 pass9
ls
put item1
sign_in user9 pass9
whoami
help sign_out
help history
show_items
sign_out
add_item_property item1 key1=val2 key8=val5 key7=val7 key5=val5 
sign_out
which_group
cd folder4
register_admin user5 pass5
whoami
show_users
add_item_property item2 key2=val6 key6=val4 key4=val3 key10=val3 
rename_user user1 <function generate_user at 0x027087F0>
cd folder2
put item4
sign_in user2 pass2
help cd
rename_user user7 <function generate_user at 0x027087F0>
cd folder1
whoami
show_folders
whoami
add_item_property item5 key10=val8 key8=val9 key4=val7 key7=val5 
pwd
show_folders
current_folder
register_user user7 pass7
show_item_properties item4
register_user user6 pass6
add_item_property item3 key4=val6 key8=val1 key9=val2 key4=val10 
put item4
show_folders
put item4
cd folder2
show_users
pwd
current_folder
add_item item3 key6=val8 key7=val7 key10=val1 key10=val5 
help add_item
add_item_property item2 key1=val6 key2=val5 key1=val1 key1=val6 
add_item_property item5 key3=val5 key7=val9 key3=val5 key2=val3 
pwd
show_item_properties item3
ls_folders
register_user user3 pass3
sign_in a2 pa2
show_folders
sign_in a4 pa4
sign_in a5 pa5
add_item item1 key6=val10 key1=val9 key10=val10 key5=val4 
add_item_property item2 key3=val4 key2=val8 key4=val6 key3=val10 
add_item item5 key6=val2 key1=val1 key9=val9 key10=val9 
show_items
rename_user user0 <function generate_user at 0x027087F0>
put item2
pwd
show_folders
cd folder4
ls
sign_in a5 pa5
show_users
sign_in user3 pass3
show_users
show_item_properties item1
which_group
ls
put item5
show_users
show_users
buy
ls
buy
show_folders
show_item_properties item3
add_item item3 key1=val8 key5=val8 key9=val2 key1=val8 
ls
sign_in user7 pass7
cd folder1
register_user user7 pass7
pwd
sign_in a2 pa2
sign_in user7 pass7
put item4
show_folders
which_group
show_item_properties item5
show_folders
create_folder folder2
sign_out
current_folder
add_item item5 key6=val4 key8=val3 key10=val2 key4=val1 
pwd
register_user user7 pass7
current_folder
whoami
current_folder
ls_folders
add_item item4 key1=val5 key8=val10 key5=val5 key4=val8 
show_users
put item5
rename_user user9 <function generate_user at 0x027087F0>
show_items
sign_in user4 pass4
add_item_property item1 key9=val6 key1=val8 key10=val4 key6=val5 
show_folders
sign_out
sign_in user2 pass2
cd folder3
pwd
help show_item_properties
create_folder folder2
create_folder folder2
ls_folders
which_group
sign_in a1 pa1
whoami
put item5
help ls_folders
rename_user user2 <function generate_user at 0x027087F0>
which_group
add_item item1 key9=val6 key3=val7 key2=val9 key10=val8 
whoami
register_admin user5 pass5
sign_out
register_admin user4 pass4
add_item_property item1 key6=val4 key7=val10 key3=val9 key5=val10 
current_folder
show_folders
show_folders
register_admin user5 pass5
create_folder folder3
show_users
add_item_property item4 key8=val10 key5=val6 key2=val9 key5=val3 
help buy
show_users
show_item_properties item3
show_items
add_item_property item5 key1=val8 key5=val10 key1=val1 key10=val4 
ls_folders
current_folder
whoami
current_folder
which_group
buy
rename_user user5 <function generate_user at 0x027087F0>
current_folder
sign_in a4 pa4
help which_group
which_group
show_folders
pwd
show_item_properties item5
sign_out
sign_out
show_users
pwd
show_item_properties item3
show_item_properties item3
buy
show_folders
buy
current_folder
whoami
buy
register_user user4 pass4
pwd
sign_in a1 pa1
sign_out
put item5
rename_user user7 <function generate_user at 0x027087F0>
add_item item5 key6=val4 key4=val10 key2=val8 key10=val4 
ls
ls_folders
ls
show_items
whoami
pwd
show_items
register_admin user5 pass5
ls_folders
show_users
show_folders
show_users
register_admin admin admin
show_folders
show_users
whoami
put item1
sign_in user2 pass2
pwd
sign_in a3 pa3
sign_in a5 pa5
buy
add_item item3 key9=val7 key6=val10 key5=val4 key9=val1 
current_folder
cd folder5
register_admin user5 pass5
ls_folders
current_folder
help add_item_property
ls_folders
sign_out
current_folder
register_user user2 pass2
rename_user user2 <function generate_user at 0x027087F0>
rename_user user6 <function generate_user at 0x027087F0>
create_folder folder1
pwd
help view_order
ls
sign_in a3 pa3
ls
add_item item1 key6=val9 key3=val4 key8=val8 key10=val8 
ls_folders
create_folder folder5
show_items
sign_in user8 pass8
sign_in user7 pass7
show_users
sign_in user7 pass7
rename_user user3 <function generate_user at 0x027087F0>
cd folder1
show_item_properties item3
whoami
which_group
whoami
help create_folder
pwd
ls
show_items
register_user user4 pass4
rename_user user9 <function generate_user at 0x027087F0>
help whoami
current_folder
sign_in user4 pass4
sign_in user7 pass7
rename_user user6 <function generate_user at 0x027087F0>
sign_in user5 pass5
sign_out
which_group
register_admin user1 pass1
sign_in user8 pass8
register_user user5 pass5
which_group
sign_in user6 pass6
show_folders
buy
ls
add_item item1 key4=val8 key10=val2 key5=val4 key2=val1 
whoami
pwd
show_item_properties item3
show_items
cd folder1
show_item_properties item3
sign_in a4 pa4
put item1
buy
ls_folders
rename_user user9 <function generate_user at 0x027087F0>
show_items
current_folder
pwd
show_users
show_users
ls
add_item_property item4 key5=val3 key8=val5 key3=val1 key4=val7 
put item3
help put
pwd
add_item item3 key5=val8 key1=val8 key2=val6 key8=val8 
create_folder folder5
sign_in a1 pa1
ls_folders
register_admin user2 pass2
add_item_property item5 key8=val5 key3=val9 key8=val2 key6=val2 
sign_in a1 pa1
create_folder folder2
ls_folders
show_item_properties item3
ls_folders
sign_in user3 pass3
show_users
put item5
help ls
register_user user4 pass4
show_users
sign_in user8 pass8
pwd
show_items
show_items
which_group
rename_user user2 <function generate_user at 0x027087F0>
show_item_properties item4
create_folder folder5
cd folder1
ls
create_folder folder2
show_users
whoami
help exit
sign_in user3 pass3
sign_in user6 pass6
add_item item2 key10=val3 key4=val6 key8=val1 key2=val5 
put item4
current_folder
register_user user7 pass7
sign_in a4 pa4
register_user admin admin
ls_folders
