sign_in user7 pass7
current_folder
sign_in user7 pass7
add_item_property item3 key4=val4 key7=val7 key6=val8 key4=val4 
help exit
which_group
show_items
show_users
which_group
current_folder
show_folders
buy
rename_user user8 <function generate_user at 0x027087F0>
register_admin user4 pass4
show_items
current_folder
create_folder folder1
rename_user user0 <function generate_user at 0x027087F0>
show_folders
show_users
rename_user user6 <function generate_user at 0x027087F0>
show_users
help which_group
create_folder folder3
sign_in admin admin
show_item_properties item3
pwd
which_group
register_user user3 pass3
rename_user user7 <function generate_user at 0x027087F0>
create_folder folder5
show_folders
sign_out
show_item_properties item5
help show_users
sign_in user8 pass8
register_admin user8 pass8
rename_user user0 <function generate_user at 0x027087F0>
pwd
register_admin user2 pass2
create_folder folder2
whoami
sign_in a4 pa4
show_item_properties item1
ls
buy
rename_user user3 <function generate_user at 0x027087F0>
show_item_properties item5
create_folder folder5
whoami
ls
show_folders
whoami
sign_out
pwd
help current_folder
which_group
create_folder folder1
show_users
ls
show_users
show_item_properties item4
register_admin user8 pass8
create_folder folder3
sign_in a4 pa4
sign_in admin admin
show_item_properties item3
put item4
rename_user user5 <function generate_user at 0x027087F0>
help ls_folders
show_folders
add_item item1 key9=val3 key10=val5 key8=val9 key6=val3 
whoami
which_group
cd folder5
show_folders
show_item_properties item4
help buy
add_item item4 key8=val5 key2=val9 key9=val8 key3=val10 
show_folders
which_group
sign_out
add_item_property item1 key7=val8 key1=val10 key7=val4 key9=val10 
whoami
register_admin user7 pass7
buy
sign_in a3 pa3
rename_user user6 <function generate_user at 0x027087F0>
show_users
help help
cd folder2
sign_in a5 pa5
show_users
sign_in a4 pa4
show_folders
sign_out
show_users
ls_folders
sign_in user9 pass9
show_folders
register_user user4 pass4
show_item_properties item5
add_item item5 key10=val4 key8=val9 key3=val3 key9=val3 
show_item_properties item1
cd folder1
ls
sign_in a2 pa2
cd folder1
sign_in a4 pa4
sign_out
help history
rename_user user7 <function generate_user at 0x027087F0>
buy
sign_out
add_item item1 key2=val3 key2=val4 key2=val7 key9=val2 
show_item_properties item2
buy
whoami
help view_order
rename_user user4 <function generate_user at 0x027087F0>
which_group
show_item_properties item4
show_users
create_folder folder2
ls_folders
create_folder folder1
help rename_user
show_users
register_user user9 pass9
help cd
put item1
current_folder
register_admin user7 pass7
create_folder folder5
add_item_property item3 key9=val7 key6=val8 key2=val8 key3=val8 
sign_in a4 pa4
sign_out
register_user user2 pass2
ls
ls_folders
sign_out
put item1
ls_folders
rename_user user2 <function generate_user at 0x027087F0>
whoami
pwd
ls
sign_in a5 pa5
ls
put item1
current_folder
show_users
rename_user user7 <function generate_user at 0x027087F0>
show_folders
sign_in user6 pass6
help add_item
whoami
add_item_property item4 key3=val5 key7=val8 key7=val1 key3=val6 
add_item_property item5 key7=val1 key6=val6 key4=val2 key10=val3 
sign_in a4 pa4
show_items
show_folders
show_item_properties item2
ls_folders
register_admin user7 pass7
show_users
sign_in a4 pa4
sign_in user7 pass7
show_item_properties item5
register_admin user3 pass3
show_folders
show_users
register_user user3 pass3
pwd
show_folders
add_item item1 key4=val8 key9=val9 key5=val2 key1=val7 
whoami
which_group
sign_out
rename_user user6 <function generate_user at 0x027087F0>
sign_in user6 pass6
which_group
rename_user user4 <function generate_user at 0x027087F0>
register_admin user9 pass9
show_items
add_item item1 key4=val2 key2=val5 key9=val2 key1=val4 
add_item item4 key5=val5 key10=val4 key3=val7 key9=val1 
rename_user user3 <function generate_user at 0x027087F0>
register_user user2 pass2
cd folder3
sign_in a3 pa3
which_group
rename_user user3 <function generate_user at 0x027087F0>
rename_user user0 <function generate_user at 0x027087F0>
rename_user user6 <function generate_user at 0x027087F0>
current_folder
help show_items
register_user user2 pass2
sign_out
rename_user user6 <function generate_user at 0x027087F0>
register_admin user2 pass2
ls_folders
cd folder1
add_item_property item2 key4=val8 key8=val6 key2=val9 key3=val1 
register_user user5 pass5
current_folder
rename_user user5 <function generate_user at 0x027087F0>
show_users
whoami
sign_in user1 pass1
current_folder
help show_items
which_group
show_folders
show_folders
create_folder folder5
register_user user8 pass8
sign_in a4 pa4
register_admin user6 pass6
add_item_property item3 key8=val2 key6=val6 key6=val8 key6=val2 
sign_out
rename_user user1 <function generate_user at 0x027087F0>
put item3
current_folder
rename_user user8 <function generate_user at 0x027087F0>
ls_folders
show_item_properties item2
add_item_property item4 key4=val1 key4=val2 key4=val2 key10=val1 
cd folder5
help rename_user
show_users
register_admin user7 pass7
ls
add_item_property item1 key7=val8 key4=val1 key1=val2 key8=val1 
show_item_properties item4
sign_in user4 pass4
create_folder folder2
put item4
rename_user user7 <function generate_user at 0x027087F0>
ls_folders
show_folders
help show_items
ls_folders
current_folder
show_folders
sign_out
current_folder
whoami
cd folder3
add_item item4 key3=val4 key1=val10 key10=val3 key9=val5 
sign_in user7 pass7
show_folders
sign_out
add_item_property item5 key7=val1 key10=val2 key7=val4 key4=val8 
which_group
sign_out
add_item item3 key8=val6 key4=val6 key5=val8 key8=val3 
add_item item4 key7=val10 key8=val6 key3=val2 key2=val5 
sign_in a2 pa2
put item1
create_folder folder4
register_admin user6 pass6
register_admin user4 pass4
ls_folders
ls
ls
show_users
create_folder folder5
show_users
add_item item3 key6=val5 key9=val5 key9=val10 key3=val4 
which_group
put item3
add_item_property item1 key7=val5 key6=val4 key1=val3 key10=val8 
buy
which_group
current_folder
register_admin user1 pass1
whoami
show_folders
which_group
show_users
show_folders
show_items
sign_in a3 pa3
register_admin admin admin
show_items
buy
help view_order
help ls
rename_user user3 <function generate_user at 0x027087F0>
ls_folders
ls
register_admin user2 pass2
current_folder
current_folder
ls
register_admin user8 pass8
pwd
ls
show_users
ls_folders
pwd
add_item item1 key5=val6 key2=val5 key1=val7 key5=val1 
register_admin user9 pass9
rename_user user9 <function generate_user at 0x027087F0>
add_item_property item4 key5=val8 key10=val3 key8=val3 key1=val4 
show_folders
cd folder3
help sign_in
pwd
register_user user2 pass2
show_items
register_user user2 pass2
show_users
ls
rename_user user5 <function generate_user at 0x027087F0>
which_group
ls_folders
show_folders
ls_folders
help history
show_users
which_group
put item1
register_admin user7 pass7
help pwd
help add_item_property
create_folder folder2
register_admin admin admin
cd folder1
show_users
register_user user6 pass6
sign_in a3 pa3
sign_in user9 pass9
sign_in user9 pass9
ls_folders
help ls
create_folder folder1
sign_in a2 pa2
sign_in a1 pa1
rename_user user9 <function generate_user at 0x027087F0>
show_items
put item4
ls
sign_out
register_admin user2 pass2
buy
show_users
register_user user1 pass1
show_item_properties item4
which_group
add_item_property item1 key1=val6 key1=val4 key7=val8 key7=val9 
show_items
show_item_properties item2
register_user user8 pass8
show_items
add_item item5 key7=val3 key7=val1 key5=val9 key9=val4 
show_items
create_folder folder5
cd folder4
whoami
current_folder
create_folder folder4
show_item_properties item1
whoami
add_item_property item3 key6=val1 key8=val7 key7=val3 key2=val3 
sign_out
show_item_properties item5
show_item_properties item4
add_item item3 key4=val2 key6=val8 key9=val4 key4=val5 
show_item_properties item2
rename_user user2 <function generate_user at 0x027087F0>
cd folder5
add_item item3 key6=val1 key1=val3 key5=val2 key6=val8 
whoami
ls
sign_in a3 pa3
show_users
help exit
show_item_properties item2
help ls_folders
sign_out
add_item item4 key8=val4 key9=val9 key2=val10 key4=val4 
help add_item_property
show_users
current_folder
which_group
show_item_properties item3
current_folder
sign_out
show_item_properties item4
buy
cd folder2
which_group
show_items
add_item item1 key8=val6 key5=val7 key4=val6 key2=val10 
whoami
register_user user6 pass6
sign_in user5 pass5
register_admin user6 pass6
which_group
buy
pwd
create_folder folder2
show_items
ls
show_folders
rename_user user0 <function generate_user at 0x027087F0>
add_item_property item2 key1=val6 key10=val9 key3=val4 key7=val6 
show_items
rename_user user6 <function generate_user at 0x027087F0>
which_group
register_admin user4 pass4
sign_in user6 pass6
buy
put item5
show_users
register_admin user9 pass9
pwd
sign_out
sign_in a3 pa3
add_item item4 key1=val9 key8=val4 key7=val4 key8=val7 
show_items
ls_folders
show_folders
current_folder
sign_out
rename_user user7 <function generate_user at 0x027087F0>
show_folders
whoami
whoami
current_folder
create_folder folder5
sign_out
rename_user user2 <function generate_user at 0x027087F0>
register_admin user8 pass8
sign_out
current_folder
register_admin user6 pass6
pwd
show_users
ls_folders
put item5
add_item_property item5 key10=val7 key2=val4 key8=val4 key6=val10 
show_items
show_folders
ls
put item2
cd folder3
create_folder folder1
add_item_property item3 key7=val3 key9=val10 key9=val10 key8=val10 
ls_folders
sign_in admin admin
ls_folders
show_users
pwd
sign_in a4 pa4
rename_user user3 <function generate_user at 0x027087F0>
sign_out
show_item_properties item1
add_item item1 key1=val2 key3=val6 key9=val3 key2=val7 
ls
ls_folders
ls
register_user admin admin
which_group
create_folder folder1
put item1
put item4
rename_user user8 <function generate_user at 0x027087F0>
cd folder3
sign_in admin admin
show_item_properties item4
sign_in a3 pa3
which_group
create_folder folder1
sign_out
show_folders
show_item_properties item3
add_item_property item2 key1=val2 key3=val6 key5=val9 key10=val8 
ls
register_user user9 pass9
register_user user4 pass4
buy
sign_in user9 pass9
pwd
whoami
ls
show_folders
put item3
add_item_property item1 key4=val1 key1=val6 key1=val2 key6=val10 
add_item_property item3 key7=val10 key7=val7 key1=val8 key10=val2 
register_user user8 pass8
rename_user user1 <function generate_user at 0x027087F0>
show_item_properties item1
register_user user4 pass4
add_item item5 key5=val3 key9=val3 key5=val8 key4=val9 
buy
current_folder
register_user user5 pass5
show_users
ls
show_items
whoami
add_item_property item1 key6=val8 key6=val1 key4=val9 key1=val1 
current_folder
show_item_properties item2
show_item_properties item2
add_item item5 key6=val2 key10=val1 key5=val9 key1=val7 
current_folder
pwd
create_folder folder2
sign_in user2 pass2
sign_in a4 pa4
show_users
ls_folders
ls_folders
create_folder folder4
add_item item2 key4=val1 key1=val8 key5=val2 key2=val9 
create_folder folder3
ls_folders
create_folder folder4
register_admin user5 pass5
add_item_property item2 key10=val8 key10=val6 key1=val3 key10=val2 
help delete_user
ls_folders
show_items
show_folders
create_folder folder3
add_item item4 key3=val2 key2=val7 key8=val2 key8=val3 
sign_out
sign_in user4 pass4
pwd
ls_folders
put item1
which_group
show_items
ls
ls
current_folder
put item5
pwd
sign_out
rename_user user3 <function generate_user at 0x027087F0>
pwd
rename_user user5 <function generate_user at 0x027087F0>
put item2
ls_folders
sign_in user9 pass9
current_folder
ls
buy
register_admin admin admin
ls
register_admin user4 pass4
add_item_property item4 key6=val7 key3=val7 key1=val8 key3=val4 
cd folder5
show_users
sign_in user5 pass5
pwd
whoami
register_user user7 pass7
show_folders
whoami
register_user user7 pass7
pwd
rename_user user5 <function generate_user at 0x027087F0>
show_item_properties item1
buy
rename_user user2 <function generate_user at 0x027087F0>
create_folder folder3
show_item_properties item3
put item1
help cd
current_folder
show_item_properties item4
buy
pwd
sign_out
buy
put item4
cd folder2
sign_out
put item3
pwd
whoami
buy
ls_folders
cd folder2
ls_folders
ls
help show_users
show_folders
create_folder folder3
sign_in a1 pa1
which_group
ls
show_items
add_item item3 key1=val10 key7=val10 key7=val5 key6=val10 
add_item item1 key10=val7 key2=val10 key3=val2 key6=val2 
sign_in a4 pa4
add_item item4 key10=val7 key9=val8 key10=val8 key4=val5 
sign_out
cd folder3
register_user user8 pass8
show_items
whoami
whoami
show_users
show_users
ls
current_folder
buy
buy
show_folders
whoami
help add_item
sign_in a2 pa2
sign_in a3 pa3
add_item item1 key9=val2 key6=val1 key7=val6 key7=val5 
show_users
show_items
register_admin user8 pass8
sign_in user4 pass4
buy
add_item item5 key10=val9 key6=val6 key6=val7 key6=val8 
sign_in a3 pa3
sign_out
show_users
add_item_property item1 key5=val2 key8=val7 key8=val10 key10=val2 
ls
cd folder2
current_folder
pwd
help ls_folders
register_admin user7 pass7
current_folder
register_user user3 pass3
rename_user user9 <function generate_user at 0x027087F0>
register_admin user3 pass3
pwd
put item4
register_admin user7 pass7
put item4
sign_in a5 pa5
show_items
add_item item4 key1=val1 key1=val7 key4=val9 key5=val5 
pwd
put item4
ls_folders
show_items
add_item_property item4 key6=val1 key5=val2 key9=val6 key2=val7 
add_item item3 key6=val3 key10=val7 key5=val1 key9=val5 
show_items
ls_folders
whoami
put item2
register_user user7 pass7
cd folder4
show_item_properties item4
pwd
ls_folders
add_item_property item5 key9=val10 key2=val7 key9=val2 key6=val8 
show_users
ls
ls
put item1
ls
pwd
whoami
show_users
add_item item1 key10=val5 key6=val10 key3=val3 key9=val1 
pwd
show_users
show_users
cd folder2
show_items
whoami
sign_in user9 pass9
current_folder
rename_user user3 <function generate_user at 0x027087F0>
buy
register_admin user5 pass5
sign_in a4 pa4
sign_in admin admin
pwd
show_items
rename_user user7 <function generate_user at 0x027087F0>
ls
register_user user8 pass8
help show_item_properties
put item3
ls_folders
sign_in a5 pa5
whoami
put item1
current_folder
cd folder4
show_items
cd folder3
whoami
show_folders
cd folder4
sign_in user2 pass2
sign_out
register_admin user3 pass3
sign_out
register_admin user5 pass5
pwd
pwd
put item3
show_items
help which_group
whoami
current_folder
show_folders
create_folder folder5
sign_in user7 pass7
add_item_property item5 key4=val7 key4=val4 key1=val3 key10=val6 
sign_out
sign_in a1 pa1
sign_in user6 pass6
which_group
register_admin user2 pass2
register_user user8 pass8
cd folder3
pwd
cd folder2
register_user user1 pass1
ls_folders
register_admin user4 pass4
ls_folders
add_item_property item2 key6=val10 key6=val4 key10=val6 key4=val5 
cd folder1
whoami
put item3
buy
create_folder folder5
sign_out
add_item_property item3 key8=val9 key1=val8 key3=val3 key10=val10 
rename_user user3 <function generate_user at 0x027087F0>
create_folder folder5
rename_user user9 <function generate_user at 0x027087F0>
rename_user user2 <function generate_user at 0x027087F0>
put item1
help register_admin
show_items
which_group
add_item item4 key4=val4 key7=val9 key1=val10 key3=val2 
sign_in a2 pa2
ls_folders
add_item item3 key6=val8 key6=val2 key8=val2 key10=val5 
pwd
register_user user8 pass8
show_users
current_folder
show_items
show_items
create_folder folder4
sign_in a1 pa1
show_users
pwd
cd folder2
ls
whoami
current_folder
show_folders
add_item item5 key8=val4 key10=val1 key5=val6 key4=val5 
put item1
show_folders
register_admin user2 pass2
whoami
register_admin user6 pass6
register_user user7 pass7
register_admin user8 pass8
register_user admin admin
whoami
register_admin user2 pass2
put item4
whoami
rename_user user7 <function generate_user at 0x027087F0>
which_group
sign_in admin admin
which_group
ls_folders
put item3
show_folders
put item2
ls_folders
register_admin user3 pass3
show_item_properties item1
register_user user5 pass5
sign_out
show_folders
buy
ls_folders
sign_in a2 pa2
which_group
add_item item4 key8=val5 key9=val5 key8=val1 key10=val3 
ls_folders
sign_in a4 pa4
put item2
ls_folders
sign_in a5 pa5
create_folder folder5
put item3
show_items
show_items
ls_folders
create_folder folder1
whoami
add_item_property item4 key6=val5 key3=val1 key10=val10 key10=val4 
current_folder
buy
help ls
sign_out
buy
show_folders
ls
whoami
sign_in a4 pa4
put item4
buy
ls
show_folders
cd folder3
current_folder
show_items
show_items
rename_user user1 <function generate_user at 0x027087F0>
show_items
create_folder folder1
show_users
sign_in a1 pa1
sign_out
put item1
pwd
put item4
show_item_properties item5
ls_folders
show_items
show_users
put item4
register_user user2 pass2
pwd
show_users
show_folders
sign_in a5 pa5
ls_folders
register_admin user7 pass7
pwd
register_user user6 pass6
sign_out
show_items
current_folder
pwd
put item3
show_users
ls
ls_folders
add_item item4 key10=val10 key6=val4 key9=val7 key2=val7 
add_item item5 key7=val2 key10=val6 key1=val7 key9=val10 
add_item item5 key8=val7 key9=val2 key6=val5 key5=val5 
create_folder folder2
pwd
show_folders
register_admin user1 pass1
show_folders
show_folders
register_admin user8 pass8
sign_in a2 pa2
sign_in a3 pa3
register_admin user6 pass6
cd folder1
help register_admin
ls_folders
buy
show_users
which_group
create_folder folder4
whoami
create_folder folder5
put item1
show_items
show_items
ls_folders
whoami
create_folder folder5
sign_in user6 pass6
register_user user7 pass7
cd folder1
show_users
ls
register_user user3 pass3
show_item_properties item1
pwd
register_user user1 pass1
sign_in user2 pass2
sign_out
add_item_property item4 key5=val1 key1=val5 key2=val3 key5=val8 
which_group
rename_user user9 <function generate_user at 0x027087F0>
help show_item_properties
add_item_property item1 key10=val4 key2=val4 key3=val3 key3=val2 
register_user user9 pass9
add_item item2 key10=val4 key5=val3 key1=val1 key4=val2 
register_admin user5 pass5
which_group
ls
add_item_property item5 key10=val7 key2=val5 key4=val4 key3=val3 
register_user user9 pass9
ls_folders
register_user user4 pass4
help history
sign_out
show_users
help pwd
add_item item1 key9=val5 key6=val10 key10=val5 key6=val4 
buy
ls
register_user user7 pass7
sign_in user8 pass8
pwd
put item3
ls
show_item_properties item4
show_items
show_item_properties item1
sign_in a3 pa3
ls_folders
create_folder folder1
show_item_properties item4
which_group
sign_in a4 pa4
show_folders
show_items
add_item_property item5 key3=val9 key7=val6 key5=val6 key7=val10 
show_folders
rename_user user7 <function generate_user at 0x027087F0>
show_item_properties item2
sign_in user3 pass3
add_item_property item2 key7=val9 key5=val6 key4=val5 key5=val1 
whoami
rename_user user9 <function generate_user at 0x027087F0>
register_admin user4 pass4
put item5
put item4
register_user user6 pass6
help delete_user
put item2
whoami
sign_out
show_items
ls
pwd
cd folder2
whoami
register_admin admin admin
register_admin user2 pass2
register_user user9 pass9
whoami
put item5
help help
show_users
whoami
show_folders
ls_folders
add_item_property item3 key6=val6 key10=val1 key1=val5 key10=val1 
sign_in a5 pa5
whoami
ls_folders
show_items
sign_in a2 pa2
ls
show_items
ls
register_user user8 pass8
sign_in a4 pa4
cd folder1
ls_folders
show_users
help pwd
which_group
sign_in user6 pass6
sign_in a4 pa4
sign_out
rename_user user8 <function generate_user at 0x027087F0>
ls_folders
register_admin user3 pass3
buy
add_item_property item2 key8=val1 key3=val3 key5=val1 key4=val10 
put item4
rename_user user4 <function generate_user at 0x027087F0>
register_user user3 pass3
show_users
register_user admin admin
put item3
ls
ls_folders
create_folder folder4
register_user admin admin
show_items
show_folders
show_folders
pwd
whoami
put item2
show_folders
buy
sign_in user3 pass3
buy
help cd
ls
current_folder
sign_in admin admin
current_folder
pwd
ls_folders
ls_folders
show_users
show_item_properties item4
which_group
which_group
whoami
add_item_property item4 key10=val9 key7=val10 key10=val8 key3=val2 
add_item item3 key9=val8 key6=val8 key3=val5 key3=val7 
sign_in a2 pa2
ls_folders
register_user user7 pass7
ls_folders
sign_in a2 pa2
sign_in a2 pa2
current_folder
ls_folders
pwd
show_users
sign_out
register_admin admin admin
register_user user7 pass7
show_users
add_item item5 key6=val3 key3=val10 key8=val2 key9=val4 
show_items
register_user user2 pass2
register_admin user1 pass1
add_item item3 key4=val5 key7=val7 key5=val7 key6=val8 
which_group
ls
whoami
ls
sign_in user2 pass2
sign_out
register_admin user6 pass6
whoami
create_folder folder3
whoami
sign_in user9 pass9
buy
add_item item2 key8=val2 key10=val9 key2=val7 key2=val1 
show_items
show_folders
create_folder folder5
add_item item5 key5=val6 key2=val4 key4=val6 key5=val7 
help show_users
show_users
pwd
rename_user user1 <function generate_user at 0x027087F0>
create_folder folder4
show_users
help which_group
rename_user user8 <function generate_user at 0x027087F0>
rename_user user4 <function generate_user at 0x027087F0>
show_folders
which_group
register_admin user7 pass7
sign_out
register_user user6 pass6
show_items
show_item_properties item3
ls_folders
ls
sign_out
ls_folders
which_group
show_folders
help add_item
ls
whoami
show_items
buy
sign_out
show_items
pwd
add_item_property item2 key5=val3 key6=val3 key8=val9 key1=val6 
whoami
rename_user user1 <function generate_user at 0x027087F0>
rename_user user5 <function generate_user at 0x027087F0>
rename_user user8 <function generate_user at 0x027087F0>
put item2
current_folder
help show_items
sign_in user3 pass3
which_group
sign_out
cd folder3
sign_out
which_group
register_user user7 pass7
add_item_property item5 key6=val3 key9=val4 key2=val3 key2=val2 
create_folder folder3
show_items
sign_out
show_folders
pwd
show_users
current_folder
add_item item3 key1=val8 key2=val7 key10=val7 key3=val5 
sign_out
ls
whoami
whoami
put item5
cd folder1
which_group
whoami
buy
show_item_properties item3
show_items
add_item item1 key6=val7 key10=val5 key5=val6 key6=val4 
register_user admin admin
ls
register_admin user9 pass9
show_item_properties item1
add_item item2 key10=val4 key10=val3 key8=val3 key5=val9 
rename_user user9 <function generate_user at 0x027087F0>
ls
pwd
buy
buy
put item4
show_users
buy
put item4
show_item_properties item5
ls_folders
add_item_property item1 key3=val1 key6=val5 key6=val8 key6=val7 
help buy
whoami
ls
show_folders
rename_user user5 <function generate_user at 0x027087F0>
whoami
whoami
put item4
add_item_property item4 key4=val7 key8=val3 key6=val8 key10=val3 
help delete_user
register_user user1 pass1
buy
show_item_properties item3
add_item item2 key2=val2 key9=val2 key1=val9 key9=val7 
create_folder folder5
show_folders
pwd
register_user user9 pass9
pwd
rename_user user1 <function generate_user at 0x027087F0>
show_items
sign_out
sign_in a5 pa5
show_item_properties item2
buy
sign_in a1 pa1
buy
register_user user7 pass7
create_folder folder2
cd folder4
show_users
ls
cd folder3
sign_in a4 pa4
show_item_properties item4
cd folder3
help ls_folders
put item3
register_admin user9 pass9
add_item_property item5 key6=val6 key2=val1 key9=val9 key4=val6 
cd folder1
pwd
register_user user6 pass6
put item4
put item2
show_items
create_folder folder3
show_users
ls
ls
add_item item1 key4=val4 key5=val6 key3=val7 key9=val1 
add_item item1 key3=val4 key6=val1 key9=val6 key4=val5 
help exit
ls_folders
show_folders
show_users
pwd
add_item item4 key4=val8 key5=val2 key5=val8 key2=val10 
cd folder5
whoami
add_item_property item2 key8=val4 key1=val6 key6=val6 key3=val4 
register_admin user4 pass4
sign_in a4 pa4
show_item_properties item2
create_folder folder2
which_group
create_folder folder5
cd folder2
show_item_properties item4
current_folder
help sign_out
sign_in user4 pass4
show_item_properties item2
show_item_properties item5
register_admin user5 pass5
pwd
sign_in a5 pa5
sign_in user5 pass5
which_group
add_item_property item1 key2=val7 key6=val4 key2=val3 key4=val3 
sign_in user7 pass7
pwd
which_group
which_group
add_item_property item2 key8=val1 key2=val9 key9=val4 key9=val5 
which_group
add_item item5 key8=val4 key7=val7 key3=val9 key1=val2 
put item4
pwd
ls
create_folder folder3
create_folder folder1
help rename_user
show_items
buy
sign_in a2 pa2
add_item item1 key4=val8 key1=val10 key2=val4 key7=val1 
show_folders
cd folder1
which_group
show_users
buy
register_user admin admin
register_admin user1 pass1
sign_in a5 pa5
pwd
help ls_folders
rename_user user4 <function generate_user at 0x027087F0>
sign_in admin admin
whoami
sign_in user7 pass7
sign_in user8 pass8
ls_folders
cd folder1
whoami
show_folders
show_folders
show_items
current_folder
show_item_properties item3
rename_user user1 <function generate_user at 0x027087F0>
show_items
put item2
show_folders
whoami
add_item item5 key6=val1 key5=val9 key6=val1 key8=val2 
pwd
add_item item5 key5=val8 key2=val4 key4=val5 key5=val7 
register_admin user5 pass5
cd folder5
sign_out
show_items
register_admin user9 pass9
show_folders
register_admin admin admin
cd folder3
current_folder
sign_out
show_folders
add_item_property item3 key4=val5 key5=val9 key1=val9 key2=val9 
add_item_property item5 key6=val7 key10=val3 key5=val1 key4=val10 
show_users
add_item item1 key1=val8 key5=val1 key7=val3 key3=val9 
current_folder
add_item item4 key6=val5 key9=val7 key1=val7 key1=val10 
sign_out
help pwd
sign_out
ls_folders
create_folder folder3
rename_user user4 <function generate_user at 0x027087F0>
current_folder
sign_out
which_group
cd folder4
register_admin user9 pass9
buy
current_folder
add_item_property item4 key4=val3 key4=val4 key1=val6 key1=val2 
show_users
create_folder folder1
sign_in a1 pa1
add_item item4 key8=val3 key9=val5 key4=val1 key4=val8 
ls_folders
help add_item_property
rename_user user3 <function generate_user at 0x027087F0>
add_item_property item1 key6=val4 key10=val5 key9=val8 key10=val10 
ls_folders
register_admin user4 pass4
create_folder folder4
register_admin user8 pass8
which_group
whoami
ls
cd folder2
show_users
rename_user user4 <function generate_user at 0x027087F0>
pwd
ls_folders
show_items
which_group
current_folder
sign_in a3 pa3
rename_user user5 <function generate_user at 0x027087F0>
sign_in a5 pa5
buy
buy
show_folders
show_folders
add_item_property item3 key2=val5 key9=val5 key1=val2 key9=val4 
show_users
sign_in a3 pa3
put item3
add_item item4 key8=val5 key2=val5 key1=val1 key2=val7 
sign_in a4 pa4
ls
sign_in a3 pa3
which_group
add_item_property item3 key3=val9 key2=val9 key6=val4 key9=val7 
sign_in user4 pass4
pwd
buy
ls
rename_user user0 <function generate_user at 0x027087F0>
show_folders
put item3
ls_folders
sign_in a3 pa3
ls_folders
ls_folders
help register_user
sign_in a1 pa1
help current_folder
put item1
pwd
pwd
sign_in a3 pa3
add_item item4 key3=val9 key1=val9 key4=val10 key3=val10 
show_users
pwd
sign_out
whoami
create_folder folder1
whoami
current_folder
ls_folders
whoami
pwd
show_items
which_group
sign_in user5 pass5
create_folder folder1
cd folder5
register_user admin admin
ls_folders
sign_in a1 pa1
show_item_properties item3
cd folder4
help pwd
whoami
which_group
show_items
show_folders
which_group
help delete_user
add_item_property item1 key5=val2 key7=val10 key8=val10 key7=val3 
add_item item2 key4=val1 key8=val7 key4=val3 key8=val5 
sign_in a3 pa3
show_folders
create_folder folder1
create_folder folder5
add_item_property item4 key10=val10 key10=val9 key10=val3 key10=val10 
sign_in a1 pa1
show_item_properties item5
create_folder folder2
show_items
sign_in a2 pa2
put item3
put item2
pwd
cd folder1
help register_admin
ls
sign_in a3 pa3
add_item item2 key6=val7 key1=val8 key3=val8 key3=val3 
register_admin admin admin
whoami
buy
register_user user4 pass4
sign_in user4 pass4
create_folder folder5
buy
rename_user user9 <function generate_user at 0x027087F0>
show_items
cd folder2
sign_out
sign_in user1 pass1
sign_in user3 pass3
current_folder
show_items
show_folders
add_item item3 key7=val7 key6=val10 key1=val1 key7=val9 
sign_in user2 pass2
create_folder folder5
help sign_in
current_folder
add_item item5 key1=val5 key6=val2 key6=val7 key5=val4 
pwd
add_item_property item3 key2=val1 key6=val2 key9=val8 key2=val9 
sign_in user2 pass2
register_user user8 pass8
put item4
sign_in a4 pa4
register_admin user8 pass8
pwd
show_users
show_folders
sign_out
show_users
register_admin admin admin
sign_in user8 pass8
show_items
put item2
show_item_properties item4
buy
put item4
current_folder
register_user admin admin
current_folder
buy
help exit
register_admin user2 pass2
register_user user2 pass2
show_folders
show_folders
sign_in user7 pass7
show_item_properties item4
whoami
ls
add_item item1 key5=val5 key2=val7 key9=val3 key3=val9 
rename_user user1 <function generate_user at 0x027087F0>
ls_folders
whoami
show_users
cd folder4
cd folder3
ls_folders
sign_in a1 pa1
sign_in a4 pa4
sign_out
show_items
ls
whoami
show_folders
show_folders
ls_folders
sign_out
show_item_properties item1
cd folder4
put item4
pwd
show_folders
add_item_property item4 key5=val1 key5=val1 key8=val6 key4=val5 
put item3
show_folders
show_folders
show_users
which_group
rename_user user6 <function generate_user at 0x027087F0>
put item4
sign_in user9 pass9
pwd
register_admin user3 pass3
show_item_properties item2
register_admin user4 pass4
add_item item1 key2=val2 key10=val6 key7=val7 key7=val3 
which_group
show_folders
sign_in a4 pa4
sign_out
current_folder
register_user admin admin
sign_in user7 pass7
show_folders
add_item item2 key4=val9 key6=val7 key6=val9 key7=val8 
cd folder2
show_item_properties item1
add_item item1 key3=val8 key6=val10 key9=val5 key1=val1 
ls_folders
sign_in a4 pa4
create_folder folder1
show_item_properties item1
add_item_property item5 key6=val7 key2=val1 key2=val9 key10=val4 
sign_out
whoami
current_folder
sign_in user4 pass4
buy
pwd
add_item_property item3 key3=val5 key6=val10 key5=val4 key8=val6 
buy
help add_item_property
rename_user user3 <function generate_user at 0x027087F0>
show_items
sign_in a4 pa4
help buy
create_folder folder2
add_item item1 key8=val3 key9=val2 key5=val3 key9=val7 
cd folder5
register_admin user5 pass5
add_item item4 key2=val3 key8=val3 key10=val6 key1=val6 
show_users
show_item_properties item3
which_group
ls
cd folder2
register_user user5 pass5
add_item item4 key8=val10 key2=val1 key3=val10 key8=val8 
create_folder folder2
sign_out
pwd
show_users
register_user user5 pass5
cd folder5
register_admin user6 pass6
create_folder folder4
create_folder folder3
help sign_out
sign_in user6 pass6
whoami
register_admin admin admin
pwd
ls
sign_in a5 pa5
ls_folders
sign_in user5 pass5
sign_out
put item2
create_folder folder2
buy
register_admin user7 pass7
help show_folders
show_folders
current_folder
buy
sign_in a5 pa5
pwd
buy
show_users
ls_folders
sign_in user9 pass9
show_folders
add_item item1 key6=val6 key8=val3 key6=val2 key3=val3 
whoami
which_group
sign_out
create_folder folder4
show_folders
show_items
add_item_property item4 key6=val2 key3=val6 key5=val10 key2=val7 
show_item_properties item2
sign_out
show_users
add_item item2 key8=val3 key1=val2 key2=val7 key5=val9 
create_folder folder1
ls_folders
show_item_properties item4
ls
show_items
help show_folders
which_group
whoami
show_folders
help show_item_properties
show_folders
show_folders
pwd
sign_out
show_folders
show_item_properties item2
sign_in user1 pass1
sign_out
create_folder folder5
rename_user user2 <function generate_user at 0x027087F0>
add_item_property item4 key2=val10 key4=val5 key5=val1 key2=val1 
sign_in user8 pass8
cd folder4
sign_out
which_group
ls_folders
put item3
show_users
register_admin user8 pass8
pwd
sign_in a3 pa3
rename_user user9 <function generate_user at 0x027087F0>
ls
ls
pwd
put item5
put item3
register_user user2 pass2
put item2
ls_folders
register_user admin admin
show_users
show_items
put item2
sign_in user6 pass6
sign_out
show_item_properties item3
add_item item1 key10=val9 key10=val3 key10=val5 key8=val4 
cd folder2
buy
whoami
show_folders
whoami
ls
register_admin user7 pass7
register_admin user3 pass3
sign_in user5 pass5
sign_out
which_group
help view_order
help ls
whoami
create_folder folder3
buy
show_items
ls_folders
put item4
create_folder folder1
pwd
show_users
show_item_properties item3
add_item item5 key6=val10 key7=val1 key10=val9 key5=val3 
ls
ls_folders
rename_user user9 <function generate_user at 0x027087F0>
cd folder1
register_user user9 pass9
sign_in a5 pa5
sign_in a5 pa5
sign_in user1 pass1
sign_in a3 pa3
register_admin user4 pass4
show_users
show_items
ls
whoami
current_folder
ls_folders
rename_user user9 <function generate_user at 0x027087F0>
ls
cd folder4
show_users
sign_in user9 pass9
ls
whoami
whoami
show_items
add_item_property item3 key6=val4 key8=val7 key5=val3 key9=val1 
create_folder folder5
add_item_property item5 key5=val2 key6=val10 key6=val6 key5=val4 
ls_folders
whoami
create_folder folder3
register_admin user3 pass3
sign_in a4 pa4
help buy
add_item_property item1 key3=val5 key4=val6 key8=val3 key6=val8 
which_group
create_folder folder3
cd folder5
sign_in a3 pa3
sign_in a5 pa5
show_item_properties item5
add_item item3 key3=val8 key1=val5 key8=val9 key8=val9 
current_folder
ls_folders
help delete_user
pwd
sign_out
buy
create_folder folder2
create_folder folder3
whoami
show_folders
show_folders
register_admin user8 pass8
sign_in a1 pa1
sign_in user3 pass3
ls_folders
current_folder
show_folders
ls_folders
sign_in a4 pa4
show_users
sign_in user2 pass2
sign_out
register_admin user3 pass3
put item1
ls
current_folder
buy
buy
whoami
cd folder3
cd folder5
ls_folders
show_items
show_items
add_item item4 key3=val5 key2=val9 key1=val6 key9=val1 
register_admin user1 pass1
ls
ls
which_group
help add_item_property
sign_in user4 pass4
show_items
cd folder5
ls
sign_out
current_folder
ls
show_items
show_users
buy
pwd
cd folder2
show_users
register_user user5 pass5
current_folder
put item5
register_user user7 pass7
register_admin user6 pass6
whoami
help pwd
add_item item3 key6=val5 key9=val7 key9=val4 key6=val4 
ls_folders
add_item item1 key8=val5 key3=val10 key3=val6 key10=val1 
help create_folder
pwd
register_user user8 pass8
sign_in a1 pa1
add_item item2 key5=val5 key2=val5 key4=val4 key7=val5 
put item1
create_folder folder5
ls
register_admin user1 pass1
ls
sign_out
show_folders
add_item item1 key9=val2 key10=val5 key4=val8 key9=val6 
pwd
ls_folders
ls
add_item item2 key8=val6 key9=val1 key3=val6 key1=val4 
show_users
current_folder
sign_in user2 pass2
show_users
create_folder folder4
add_item_property item2 key9=val5 key7=val9 key8=val8 key10=val7 
put item3
sign_in admin admin
show_items
current_folder
current_folder
add_item_property item2 key5=val3 key8=val9 key10=val7 key1=val1 
sign_out
register_user user4 pass4
register_admin user4 pass4
add_item item3 key7=val5 key1=val10 key5=val3 key1=val3 
add_item item2 key9=val8 key1=val3 key3=val9 key3=val9 
sign_in a5 pa5
show_items
create_folder folder2
show_items
register_user user5 pass5
show_folders
show_users
show_users
show_items
sign_in a2 pa2
which_group
show_items
help rename_user
add_item_property item4 key3=val8 key4=val1 key7=val7 key7=val5 
sign_in a1 pa1
whoami
current_folder
buy
add_item_property item4 key10=val3 key10=val9 key10=val8 key8=val5 
create_folder folder3
show_item_properties item5
add_item item1 key10=val7 key10=val5 key2=val1 key5=val1 
ls
register_admin user3 pass3
ls_folders
ls
sign_in user9 pass9
add_item_property item3 key2=val8 key6=val1 key5=val2 key5=val4 
current_folder
register_user user8 pass8
ls
sign_in user3 pass3
buy
help view_order
current_folder
current_folder
show_folders
put item4
register_admin user1 pass1
pwd
sign_in a1 pa1
whoami
ls
create_folder folder1
help whoami
cd folder2
show_folders
put item4
add_item item1 key4=val7 key3=val4 key1=val3 key7=val3 
whoami
add_item_property item2 key1=val10 key5=val2 key3=val7 key8=val5 
show_users
ls_folders
add_item item4 key5=val10 key10=val3 key1=val5 key10=val6 
register_user user4 pass4
whoami
which_group
show_users
ls
register_admin user5 pass5
show_items
buy
sign_in user9 pass9
cd folder3
buy
cd folder4
show_users
create_folder folder4
help register_user
show_item_properties item5
help register_user
ls
whoami
sign_in user4 pass4
current_folder
put item3
rename_user user6 <function generate_user at 0x027087F0>
whoami
show_users
put item3
cd folder4
create_folder folder5
current_folder
ls_folders
help which_group
which_group
sign_out
show_users
pwd
add_item item4 key3=val2 key3=val2 key4=val8 key7=val1 
show_items
rename_user user2 <function generate_user at 0x027087F0>
show_folders
register_user user2 pass2
show_item_properties item2
whoami
put item3
cd folder4
create_folder folder5
put item3
whoami
pwd
put item3
register_admin user4 pass4
show_items
current_folder
ls
current_folder
show_items
add_item_property item2 key7=val9 key6=val9 key4=val4 key4=val9 
add_item item3 key2=val7 key8=val7 key7=val8 key8=val9 
register_user admin admin
register_admin user9 pass9
register_admin user6 pass6
whoami
register_user user6 pass6
put item5
ls_folders
sign_out
put item1
show_items
rename_user user9 <function generate_user at 0x027087F0>
ls_folders
add_item item5 key3=val2 key8=val4 key8=val8 key10=val6 
create_folder folder1
show_items
show_item_properties item3
ls_folders
which_group
add_item_property item1 key5=val6 key2=val1 key2=val7 key3=val3 
pwd
ls
sign_in user1 pass1
cd folder1
register_admin user3 pass3
help show_items
which_group
sign_in user3 pass3
sign_out
help put
help sign_in
help sign_out
show_item_properties item1
create_folder folder2
pwd
cd folder1
pwd
show_items
current_folder
buy
current_folder
which_group
sign_in user2 pass2
buy
sign_in user9 pass9
add_item item1 key6=val7 key10=val5 key3=val10 key3=val1 
current_folder
create_folder folder1
ls_folders
show_users
help show_items
ls_folders
show_users
add_item_property item1 key5=val5 key4=val4 key4=val3 key4=val7 
sign_in a2 pa2
add_item item3 key9=val7 key4=val9 key8=val10 key5=val8 
register_admin user9 pass9
show_folders
sign_in a2 pa2
sign_in a3 pa3
add_item_property item4 key10=val10 key8=val7 key8=val10 key1=val9 
ls
current_folder
sign_in user4 pass4
ls_folders
add_item item2 key10=val8 key8=val8 key9=val7 key10=val5 
show_folders
add_item_property item3 key2=val4 key8=val1 key10=val3 key5=val7 
help register_user
show_item_properties item4
register_admin admin admin
add_item item3 key10=val6 key10=val8 key8=val4 key4=val1 
sign_out
show_folders
whoami
show_items
put item5
show_item_properties item4
show_items
register_user user5 pass5
show_item_properties item1
show_items
register_user user1 pass1
show_items
show_items
create_folder folder1
create_folder folder2
register_user user6 pass6
show_folders
register_user user5 pass5
show_items
whoami
ls
help add_item
show_item_properties item4
sign_in user6 pass6
cd folder1
add_item item5 key5=val6 key10=val1 key6=val8 key2=val8 
ls_folders
whoami
cd folder2
which_group
add_item_property item5 key5=val10 key8=val9 key3=val6 key4=val8 
create_folder folder1
sign_out
pwd
which_group
create_folder folder5
sign_out
show_users
add_item_property item1 key3=val10 key6=val5 key6=val1 key7=val8 
register_user user3 pass3
ls
put item5
create_folder folder4
register_user user6 pass6
rename_user user2 <function generate_user at 0x027087F0>
put item5
add_item_property item2 key4=val3 key2=val5 key10=val6 key1=val10 
help add_item_property
buy
create_folder folder5
whoami
sign_in user6 pass6
current_folder
whoami
pwd
pwd
sign_in a5 pa5
ls_folders
rename_user user8 <function generate_user at 0x027087F0>
put item5
show_users
whoami
ls_folders
show_item_properties item3
sign_in user7 pass7
which_group
show_folders
show_users
show_users
which_group
add_item_property item5 key7=val5 key4=val7 key4=val1 key4=val1 
add_item_property item3 key6=val4 key1=val1 key6=val4 key10=val6 
buy
ls
register_user user7 pass7
cd folder3
show_items
whoami
register_admin user8 pass8
sign_in user8 pass8
show_folders
ls
cd folder5
register_user user2 pass2
help show_folders
show_folders
show_folders
pwd
register_user user9 pass9
buy
cd folder2
buy
ls
current_folder
cd folder5
put item5
add_item item2 key10=val9 key1=val2 key4=val4 key2=val7 
pwd
sign_in a3 pa3
show_users
put item4
show_users
buy
add_item_property item1 key3=val1 key5=val2 key1=val9 key4=val6 
buy
ls_folders
cd folder2
register_user admin admin
ls_folders
pwd
sign_in a4 pa4
pwd
show_folders
show_users
show_items
show_folders
help current_folder
add_item item4 key9=val9 key10=val4 key3=val2 key7=val3 
sign_in a2 pa2
add_item item4 key4=val4 key1=val9 key10=val8 key3=val9 
cd folder3
show_folders
sign_out
ls
add_item item3 key4=val10 key8=val6 key6=val10 key3=val2 
add_item item1 key1=val4 key8=val7 key8=val5 key9=val5 
rename_user user4 <function generate_user at 0x027087F0>
register_admin user2 pass2
sign_out
register_admin user2 pass2
show_users
add_item_property item4 key6=val4 key1=val3 key1=val7 key4=val1 
put item3
show_items
cd folder5
show_items
show_items
current_folder
sign_out
which_group
show_users
cd folder3
show_items
ls
pwd
which_group
show_item_properties item5
cd folder2
register_user user1 pass1
show_item_properties item1
sign_in a5 pa5
which_group
buy
sign_in user2 pass2
sign_out
add_item item3 key1=val3 key8=val2 key4=val3 key7=val10 
current_folder
show_users
show_users
show_folders
sign_in user6 pass6
cd folder3
rename_user user0 <function generate_user at 0x027087F0>
help history
ls_folders
show_item_properties item4
put item4
sign_in a5 pa5
add_item_property item5 key7=val1 key3=val5 key10=val8 key10=val5 
pwd
register_user user7 pass7
ls
ls_folders
which_group
pwd
pwd
put item5
whoami
buy
pwd
show_users
show_item_properties item5
which_group
ls
show_item_properties item3
show_item_properties item4
sign_in a5 pa5
register_user user2 pass2
show_folders
show_users
show_item_properties item1
show_items
register_admin user9 pass9
cd folder1
ls
register_user user8 pass8
which_group
sign_in a4 pa4
buy
ls
pwd
cd folder5
create_folder folder2
sign_in a2 pa2
register_user user1 pass1
show_items
help view_order
pwd
sign_in user5 pass5
show_users
ls_folders
help register_user
show_items
rename_user user4 <function generate_user at 0x027087F0>
sign_in a3 pa3
whoami
current_folder
help sign_out
ls_folders
create_folder folder4
ls
rename_user user1 <function generate_user at 0x027087F0>
add_item_property item3 key7=val1 key8=val6 key8=val7 key1=val7 
show_item_properties item3
buy
help add_item
rename_user user4 <function generate_user at 0x027087F0>
sign_in a5 pa5
sign_out
whoami
create_folder folder4
help sign_out
add_item_property item3 key1=val5 key2=val1 key5=val8 key5=val6 
register_user user5 pass5
sign_in a5 pa5
whoami
sign_in user7 pass7
show_users
show_item_properties item3
current_folder
register_admin user7 pass7
show_folders
rename_user user6 <function generate_user at 0x027087F0>
sign_out
add_item_property item3 key7=val3 key2=val2 key5=val4 key3=val2 
register_admin user3 pass3
rename_user user2 <function generate_user at 0x027087F0>
show_item_properties item3
cd folder2
rename_user user2 <function generate_user at 0x027087F0>
help add_item
sign_in a1 pa1
ls_folders
whoami
which_group
add_item_property item5 key7=val7 key8=val7 key2=val6 key8=val7 
add_item_property item4 key6=val5 key10=val4 key3=val3 key4=val9 
register_user user9 pass9
rename_user user0 <function generate_user at 0x027087F0>
sign_out
cd folder4
add_item_property item3 key5=val10 key9=val1 key10=val8 key1=val7 
which_group
pwd
buy
show_users
register_admin user6 pass6
show_item_properties item2
register_user admin admin
ls
register_admin admin admin
pwd
buy
ls
help which_group
which_group
put item4
show_folders
cd folder5
show_users
rename_user user2 <function generate_user at 0x027087F0>
ls_folders
sign_out
sign_in user7 pass7
show_folders
pwd
show_item_properties item2
ls
ls
sign_out
register_admin user2 pass2
show_item_properties item4
add_item_property item2 key3=val8 key3=val8 key8=val9 key4=val3 
buy
ls
ls
register_user user3 pass3
sign_in a2 pa2
add_item item4 key1=val7 key7=val5 key4=val6 key3=val1 
pwd
register_admin user9 pass9
register_admin user6 pass6
which_group
register_user user7 pass7
help cd
show_item_properties item3
which_group
pwd
cd folder2
ls_folders
rename_user user6 <function generate_user at 0x027087F0>
register_admin user4 pass4
sign_in user8 pass8
current_folder
rename_user user6 <function generate_user at 0x027087F0>
buy
rename_user user6 <function generate_user at 0x027087F0>
add_item item3 key8=val1 key9=val4 key3=val10 key7=val8 
rename_user user5 <function generate_user at 0x027087F0>
ls
show_item_properties item3
put item2
ls
show_items
which_group
ls_folders
show_items
add_item item1 key6=val4 key1=val8 key10=val1 key1=val1 
rename_user user2 <function generate_user at 0x027087F0>
which_group
show_item_properties item3
show_folders
put item4
sign_out
register_admin user6 pass6
ls
cd folder5
show_item_properties item5
register_admin user9 pass9
put item2
add_item item3 key7=val6 key5=val2 key3=val1 key6=val1 
show_users
buy
put item1
current_folder
buy
ls_folders
sign_in user2 pass2
help which_group
ls
ls
which_group
ls
put item2
pwd
sign_in a5 pa5
cd folder3
sign_in a3 pa3
sign_out
help rename_user
cd folder4
which_group
show_folders
cd folder3
sign_in a5 pa5
put item4
rename_user user1 <function generate_user at 0x027087F0>
rename_user user1 <function generate_user at 0x027087F0>
show_items
add_item_property item1 key10=val6 key5=val4 key1=val9 key8=val8 
help exit
whoami
show_folders
add_item_property item1 key4=val5 key2=val3 key2=val4 key7=val5 
ls
ls
add_item_property item1 key10=val8 key10=val3 key8=val8 key4=val10 
current_folder
sign_in a4 pa4
add_item item4 key2=val2 key5=val9 key4=val1 key5=val5 
buy
show_users
add_item item1 key9=val3 key6=val4 key9=val10 key3=val1 
add_item_property item1 key1=val9 key4=val3 key1=val8 key10=val9 
register_admin user3 pass3
show_folders
ls_folders
register_admin user4 pass4
whoami
help cd
sign_in user4 pass4
which_group
show_item_properties item2
buy
whoami
rename_user user8 <function generate_user at 0x027087F0>
add_item item4 key7=val3 key4=val4 key5=val3 key8=val1 
show_users
register_user user9 pass9
ls_folders
show_item_properties item3
sign_in a1 pa1
sign_out
sign_in user2 pass2
show_folders
create_folder folder4
rename_user user5 <function generate_user at 0x027087F0>
add_item item3 key9=val9 key8=val7 key10=val9 key1=val1 
ls
add_item item5 key8=val8 key2=val3 key2=val2 key7=val3 
cd folder3
pwd
rename_user user0 <function generate_user at 0x027087F0>
sign_in user8 pass8
add_item item2 key5=val4 key10=val6 key4=val8 key7=val8 
ls_folders
show_item_properties item1
which_group
register_user user4 pass4
sign_in user6 pass6
show_folders
show_users
ls
create_folder folder3
show_item_properties item4
ls_folders
ls_folders
whoami
current_folder
buy
sign_out
register_admin user4 pass4
whoami
show_folders
rename_user user8 <function generate_user at 0x027087F0>
show_folders
pwd
sign_in user7 pass7
create_folder folder1
show_items
add_item item5 key6=val2 key4=val1 key2=val5 key2=val8 
create_folder folder4
sign_in user5 pass5
put item2
buy
current_folder
add_item_property item2 key2=val3 key8=val9 key9=val6 key10=val5 
add_item item3 key3=val1 key6=val8 key5=val5 key8=val10 
show_users
put item5
show_items
create_folder folder3
sign_in a2 pa2
sign_in a1 pa1
show_folders
rename_user user0 <function generate_user at 0x027087F0>
cd folder3
show_item_properties item2
cd folder4
help create_folder
rename_user user1 <function generate_user at 0x027087F0>
pwd
show_items
show_items
register_admin user8 pass8
buy
buy
buy
help cd
rename_user user2 <function generate_user at 0x027087F0>
register_admin user5 pass5
create_folder folder4
sign_in user8 pass8
register_admin user3 pass3
sign_in a4 pa4
sign_in a5 pa5
show_items
whoami
register_user user2 pass2
buy
current_folder
cd folder2
buy
add_item item1 key5=val10 key3=val3 key3=val1 key2=val10 
sign_out
which_group
sign_out
current_folder
show_items
create_folder folder4
sign_in a3 pa3
rename_user user4 <function generate_user at 0x027087F0>
ls_folders
which_group
sign_in admin admin
show_users
which_group
add_item item4 key8=val2 key8=val8 key6=val9 key10=val2 
sign_out
rename_user user0 <function generate_user at 0x027087F0>
show_folders
create_folder folder2
show_item_properties item3
show_items
which_group
ls_folders
register_user user3 pass3
put item2
buy
add_item item1 key5=val3 key4=val2 key5=val6 key7=val2 
ls_folders
current_folder
show_items
show_item_properties item4
show_items
create_folder folder4
help add_item
show_folders
sign_in a1 pa1
buy
show_items
ls
cd folder2
sign_in user7 pass7
show_users
show_items
cd folder3
sign_in a3 pa3
ls_folders
register_admin admin admin
register_admin user9 pass9
buy
buy
show_folders
register_user user5 pass5
sign_out
ls_folders
add_item item1 key2=val9 key9=val1 key9=val6 key6=val6 
whoami
whoami
sign_in user3 pass3
cd folder3
rename_user user8 <function generate_user at 0x027087F0>
show_folders
register_admin user6 pass6
add_item_property item3 key8=val2 key4=val2 key8=val6 key3=val3 
cd folder5
sign_in user2 pass2
which_group
ls
sign_out
show_item_properties item4
buy
help put
help show_folders
buy
cd folder3
sign_in a1 pa1
current_folder
show_users
pwd
show_users
ls_folders
help add_item
buy
create_folder folder2
put item2
current_folder
rename_user user4 <function generate_user at 0x027087F0>
ls
ls
help history
ls
create_folder folder2
sign_in admin admin
sign_in user2 pass2
pwd
rename_user user9 <function generate_user at 0x027087F0>
sign_out
register_user user2 pass2
register_admin user6 pass6
whoami
help current_folder
show_items
pwd
sign_in a5 pa5
register_user user9 pass9
show_item_properties item5
put item3
ls_folders
add_item item1 key5=val5 key5=val6 key9=val6 key6=val9 
show_items
put item5
whoami
show_folders
cd folder5
register_user user3 pass3
help register_user
current_folder
sign_in user8 pass8
ls_folders
show_folders
show_folders
current_folder
register_admin user6 pass6
show_items
register_admin user9 pass9
whoami
show_item_properties item4
sign_in user5 pass5
sign_in a1 pa1
create_folder folder2
ls
help register_admin
rename_user user9 <function generate_user at 0x027087F0>
buy
show_item_properties item4
ls
help show_item_properties
sign_out
register_user user5 pass5
current_folder
help buy
show_folders
pwd
ls
rename_user user3 <function generate_user at 0x027087F0>
create_folder folder1
sign_in user2 pass2
ls
register_admin admin admin
which_group
whoami
put item1
show_users
show_items
show_items
sign_out
rename_user user8 <function generate_user at 0x027087F0>
show_items
create_folder folder5
show_item_properties item1
add_item_property item1 key2=val6 key8=val1 key7=val7 key2=val7 
buy
sign_out
sign_in a5 pa5
add_item item3 key8=val2 key7=val7 key8=val6 key8=val1 
rename_user user2 <function generate_user at 0x027087F0>
ls
create_folder folder5
sign_out
current_folder
cd folder4
help show_folders
which_group
show_item_properties item2
add_item_property item2 key2=val1 key4=val6 key6=val7 key2=val8 
pwd
show_folders
pwd
whoami
rename_user user1 <function generate_user at 0x027087F0>
add_item_property item1 key2=val3 key2=val3 key1=val8 key2=val6 
show_folders
show_folders
sign_out
register_user admin admin
ls
sign_out
create_folder folder2
ls_folders
current_folder
show_folders
register_admin user8 pass8
which_group
which_group
rename_user user4 <function generate_user at 0x027087F0>
current_folder
rename_user user3 <function generate_user at 0x027087F0>
add_item item1 key5=val3 key5=val4 key10=val10 key9=val3 
buy
show_item_properties item5
which_group
help whoami
register_admin user3 pass3
show_items
create_folder folder1
add_item_property item4 key4=val2 key7=val3 key9=val10 key3=val1 
sign_out
pwd
buy
current_folder
register_user admin admin
register_admin user5 pass5
rename_user user6 <function generate_user at 0x027087F0>
register_admin user6 pass6
cd folder4
cd folder2
register_admin user2 pass2
sign_out
help show_item_properties
cd folder3
ls_folders
ls_folders
help add_item
sign_out
rename_user user7 <function generate_user at 0x027087F0>
pwd
show_item_properties item5
pwd
buy
register_user user2 pass2
cd folder3
sign_in a3 pa3
rename_user user4 <function generate_user at 0x027087F0>
ls
create_folder folder4
pwd
show_folders
ls_folders
sign_in user7 pass7
sign_in user2 pass2
sign_out
whoami
ls_folders
sign_out
register_user user8 pass8
current_folder
buy
register_user admin admin
register_admin user8 pass8
rename_user user5 <function generate_user at 0x027087F0>
sign_out
show_folders
add_item item3 key5=val4 key8=val3 key5=val8 key6=val5 
show_users
current_folder
rename_user user3 <function generate_user at 0x027087F0>
add_item item3 key2=val4 key4=val3 key2=val7 key1=val7 
register_admin admin admin
ls
ls
help sign_out
show_item_properties item5
sign_in user4 pass4
whoami
which_group
show_folders
show_users
sign_in a2 pa2
show_users
show_item_properties item4
sign_in user5 pass5
show_item_properties item2
show_users
current_folder
buy
help whoami
show_item_properties item4
sign_in a4 pa4
add_item_property item2 key8=val2 key3=val4 key3=val4 key7=val10 
current_folder
create_folder folder4
show_item_properties item5
show_item_properties item4
sign_out
put item1
rename_user user1 <function generate_user at 0x027087F0>
ls_folders
sign_out
add_item item5 key5=val3 key5=val3 key9=val7 key7=val2 
sign_in a2 pa2
register_user user9 pass9
create_folder folder1
cd folder3
create_folder folder4
show_items
sign_in a2 pa2
register_user user7 pass7
show_item_properties item5
ls_folders
register_user user4 pass4
current_folder
show_items
put item5
show_items
sign_in a2 pa2
sign_in a3 pa3
create_folder folder3
which_group
ls
show_users
show_item_properties item3
show_users
register_user admin admin
ls
help show_item_properties
whoami
show_items
pwd
current_folder
buy
ls_folders
whoami
sign_out
sign_in user2 pass2
show_item_properties item3
pwd
sign_in a2 pa2
register_user user3 pass3
ls
pwd
show_items
ls_folders
put item4
register_user user4 pass4
sign_in user7 pass7
show_items
help put
sign_in a5 pa5
register_admin user1 pass1
register_admin user7 pass7
register_admin user1 pass1
pwd
sign_out
show_folders
rename_user user5 <function generate_user at 0x027087F0>
sign_in user2 pass2
show_items
show_item_properties item3
buy
show_item_properties item2
sign_in user5 pass5
add_item item4 key6=val4 key8=val9 key5=val10 key6=val6 
show_users
show_folders
show_users
sign_in user2 pass2
show_folders
show_users
put item4
current_folder
sign_out
current_folder
show_item_properties item4
put item4
show_users
sign_in a1 pa1
which_group
buy
ls
sign_in a1 pa1
put item3
show_folders
rename_user user1 <function generate_user at 0x027087F0>
which_group
whoami
sign_out
put item3
current_folder
show_users
create_folder folder1
register_user user2 pass2
show_items
show_users
put item1
sign_out
create_folder folder2
register_admin user5 pass5
help create_folder
create_folder folder4
buy
put item1
cd folder4
show_users
which_group
show_users
add_item item1 key6=val9 key2=val4 key7=val9 key5=val6 
sign_in user3 pass3
put item3
ls
show_items
show_items
show_item_properties item5
current_folder
pwd
current_folder
show_items
rename_user user5 <function generate_user at 0x027087F0>
create_folder folder4
put item1
register_admin user4 pass4
register_user user8 pass8
show_users
rename_user user2 <function generate_user at 0x027087F0>
ls
show_item_properties item4
put item2
sign_in admin admin
put item2
rename_user user8 <function generate_user at 0x027087F0>
pwd
show_item_properties item3
cd folder1
show_users
whoami
rename_user user8 <function generate_user at 0x027087F0>
help which_group
show_folders
sign_out
sign_out
show_users
whoami
put item5
show_items
sign_in a4 pa4
sign_in user8 pass8
buy
add_item item3 key4=val9 key9=val7 key5=val3 key5=val3 
cd folder1
ls_folders
ls_folders
show_folders
show_users
show_users
register_admin user1 pass1
current_folder
sign_in a4 pa4
ls
pwd
ls_folders
create_folder folder5
sign_in user3 pass3
ls
sign_in user6 pass6
show_item_properties item3
ls
register_admin user9 pass9
add_item item3 key6=val5 key8=val6 key8=val10 key3=val8 
which_group
which_group
register_user admin admin
pwd
buy
pwd
show_items
whoami
whoami
show_items
sign_out
register_admin user4 pass4
add_item item4 key4=val9 key4=val6 key10=val8 key3=val9 
register_admin user2 pass2
current_folder
help which_group
show_item_properties item1
pwd
cd folder5
create_folder folder2
which_group
sign_in user1 pass1
sign_in a3 pa3
sign_in a5 pa5
pwd
which_group
which_group
create_folder folder3
pwd
show_item_properties item1
sign_in a1 pa1
cd folder1
sign_in user1 pass1
whoami
sign_in a1 pa1
buy
add_item item1 key4=val7 key8=val6 key3=val4 key5=val3 
sign_out
help show_item_properties
sign_out
ls
show_item_properties item3
sign_in user2 pass2
pwd
cd folder4
help put
show_items
add_item_property item1 key7=val9 key10=val9 key1=val1 key5=val5 
pwd
show_users
show_items
sign_in a5 pa5
cd folder1
ls
ls_folders
buy
register_user user8 pass8
sign_out
show_folders
sign_out
help delete_user
create_folder folder4
rename_user user7 <function generate_user at 0x027087F0>
sign_in user7 pass7
buy
rename_user user0 <function generate_user at 0x027087F0>
current_folder
cd folder1
ls_folders
put item1
ls
sign_in user7 pass7
show_users
current_folder
ls_folders
show_items
help help
buy
create_folder folder3
pwd
help delete_user
register_admin user3 pass3
sign_out
show_folders
rename_user user9 <function generate_user at 0x027087F0>
which_group
which_group
show_items
help sign_out
help register_admin
sign_in a4 pa4
ls
cd folder5
add_item item4 key4=val3 key3=val3 key4=val8 key7=val8 
pwd
ls_folders
sign_in admin admin
current_folder
cd folder5
show_item_properties item1
show_folders
show_item_properties item2
show_folders
cd folder1
put item3
register_user user3 pass3
which_group
add_item_property item1 key3=val2 key3=val4 key6=val1 key5=val8 
ls
sign_in a1 pa1
show_folders
put item4
current_folder
show_item_properties item4
show_items
show_users
create_folder folder5
register_user user9 pass9
current_folder
register_admin user8 pass8
show_users
whoami
put item3
add_item_property item3 key3=val5 key8=val10 key10=val3 key6=val4 
current_folder
pwd
help create_folder
rename_user user2 <function generate_user at 0x027087F0>
register_admin user1 pass1
add_item item3 key5=val7 key5=val2 key1=val1 key5=val1 
buy
create_folder folder3
register_admin user7 pass7
add_item_property item2 key8=val2 key7=val5 key4=val6 key5=val5 
show_items
show_item_properties item4
ls_folders
current_folder
ls
put item4
rename_user user9 <function generate_user at 0x027087F0>
sign_in a1 pa1
create_folder folder3
which_group
whoami
show_folders
rename_user user4 <function generate_user at 0x027087F0>
cd folder5
whoami
show_items
pwd
show_folders
rename_user user2 <function generate_user at 0x027087F0>
put item5
sign_in a4 pa4
create_folder folder2
sign_in a1 pa1
cd folder5
rename_user user8 <function generate_user at 0x027087F0>
show_users
show_folders
sign_in user5 pass5
help rename_user
which_group
create_folder folder4
register_admin user5 pass5
show_folders
show_folders
ls
sign_in a5 pa5
show_items
create_folder folder4
cd folder1
ls
register_admin user6 pass6
put item4
show_items
sign_in a2 pa2
sign_in user2 pass2
create_folder folder5
whoami
cd folder1
show_item_properties item3
help buy
buy
show_item_properties item1
which_group
sign_out
add_item item5 key10=val5 key5=val9 key1=val6 key5=val10 
buy
create_folder folder2
create_folder folder2
add_item_property item3 key6=val10 key3=val6 key9=val9 key1=val9 
show_folders
current_folder
ls_folders
register_admin user3 pass3
show_items
whoami
sign_in a1 pa1
add_item_property item1 key1=val9 key4=val2 key10=val7 key9=val10 
show_folders
buy
register_user user3 pass3
whoami
register_user user2 pass2
sign_in user9 pass9
register_admin user8 pass8
add_item item4 key8=val2 key8=val4 key2=val3 key5=val5 
whoami
register_user user7 pass7
sign_out
sign_out
add_item item1 key3=val2 key8=val3 key6=val3 key7=val7 
current_folder
which_group
register_admin user4 pass4
show_folders
pwd
whoami
register_user admin admin
which_group
put item2
show_item_properties item3
register_user user7 pass7
add_item_property item2 key4=val2 key2=val2 key1=val9 key10=val2 
sign_in a1 pa1
show_items
add_item item5 key9=val7 key8=val2 key9=val3 key5=val5 
help exit
help sign_in
show_users
register_admin admin admin
cd folder1
which_group
show_users
register_admin user6 pass6
sign_in a4 pa4
show_users
add_item item4 key9=val1 key6=val6 key4=val3 key7=val8 
put item5
whoami
sign_in a5 pa5
help ls_folders
show_items
register_admin user2 pass2
show_items
buy
show_items
help exit
put item4
whoami
which_group
show_items
ls_folders
cd folder2
ls_folders
add_item_property item1 key8=val2 key7=val9 key1=val9 key9=val8 
ls
current_folder
buy
create_folder folder3
whoami
sign_in a3 pa3
show_folders
add_item item4 key5=val7 key8=val7 key5=val1 key5=val8 
register_admin admin admin
register_admin user2 pass2
ls
current_folder
register_user user9 pass9
sign_in user7 pass7
sign_in user2 pass2
put item4
show_folders
help show_users
show_item_properties item3
pwd
whoami
ls_folders
register_user user4 pass4
sign_out
ls
cd folder2
help help
add_item item5 key5=val3 key4=val9 key2=val7 key5=val3 
add_item_property item5 key9=val4 key8=val7 key7=val4 key9=val10 
show_users
ls
ls
sign_out
pwd
which_group
create_folder folder3
show_folders
buy
ls
sign_out
help pwd
cd folder2
sign_out
put item4
show_item_properties item3
register_user user9 pass9
ls
add_item_property item4 key5=val3 key1=val8 key8=val9 key6=val4 
ls_folders
sign_out
buy
sign_in user9 pass9
show_items
add_item item2 key10=val8 key3=val10 key1=val10 key8=val5 
which_group
sign_in a1 pa1
cd folder3
sign_in user9 pass9
buy
show_items
whoami
create_folder folder5
rename_user user8 <function generate_user at 0x027087F0>
show_users
create_folder folder1
register_user user8 pass8
add_item_property item1 key7=val6 key4=val3 key1=val3 key3=val2 
sign_in a1 pa1
sign_in user3 pass3
help add_item_property
whoami
sign_in user4 pass4
create_folder folder3
current_folder
register_user user4 pass4
add_item_property item3 key10=val10 key8=val10 key1=val7 key3=val9 
whoami
rename_user user6 <function generate_user at 0x027087F0>
whoami
show_item_properties item4
which_group
put item1
add_item item1 key2=val2 key3=val8 key4=val6 key3=val3 
pwd
register_user admin admin
show_folders
register_user user5 pass5
rename_user user0 <function generate_user at 0x027087F0>
create_folder folder2
sign_out
add_item_property item2 key6=val3 key8=val3 key4=val3 key8=val9 
help show_items
buy
ls
ls_folders
add_item item2 key8=val9 key3=val1 key2=val1 key3=val5 
show_item_properties item2
cd folder3
register_user user9 pass9
whoami
sign_out
add_item_property item2 key6=val6 key8=val4 key6=val10 key10=val2 
add_item item3 key4=val4 key9=val3 key8=val5 key8=val5 
show_item_properties item1
register_user user8 pass8
add_item_property item5 key4=val9 key5=val5 key6=val5 key5=val2 
whoami
ls
rename_user user5 <function generate_user at 0x027087F0>
cd folder1
sign_in admin admin
rename_user user0 <function generate_user at 0x027087F0>
sign_in a4 pa4
which_group
cd folder5
show_users
sign_in a1 pa1
create_folder folder3
add_item_property item3 key1=val5 key10=val4 key2=val7 key10=val6 
cd folder5
sign_out
sign_in a4 pa4
register_user user5 pass5
register_user user5 pass5
ls
sign_out
sign_in user8 pass8
register_admin user9 pass9
whoami
show_folders
cd folder2
buy
which_group
current_folder
sign_in a2 pa2
register_user user6 pass6
cd folder4
register_user user9 pass9
cd folder5
help history
show_folders
rename_user user8 <function generate_user at 0x027087F0>
ls_folders
help register_user
show_users
show_items
ls
pwd
register_admin user2 pass2
current_folder
put item2
ls
sign_in a5 pa5
rename_user user4 <function generate_user at 0x027087F0>
pwd
show_item_properties item2
sign_in user7 pass7
sign_in admin admin
help history
register_user user2 pass2
sign_in user2 pass2
rename_user user1 <function generate_user at 0x027087F0>
create_folder folder1
sign_in a4 pa4
sign_in a2 pa2
register_admin user3 pass3
which_group
register_user user2 pass2
ls
add_item_property item4 key1=val7 key7=val6 key9=val4 key6=val8 
add_item_property item3 key5=val2 key3=val1 key1=val3 key6=val5 
sign_in user4 pass4
sign_in a1 pa1
cd folder5
put item3
add_item_property item5 key3=val3 key3=val2 key10=val5 key4=val3 
rename_user user5 <function generate_user at 0x027087F0>
current_folder
cd folder4
show_users
add_item item1 key9=val2 key7=val6 key2=val1 key2=val7 
show_item_properties item3
create_folder folder4
ls
buy
create_folder folder2
put item4
ls_folders
sign_in user9 pass9
add_item item1 key10=val3 key4=val9 key5=val5 key9=val8 
buy
show_folders
rename_user user3 <function generate_user at 0x027087F0>
help sign_in
pwd
add_item item5 key6=val3 key5=val7 key5=val7 key9=val9 
whoami
help sign_out
ls
sign_in a3 pa3
cd folder1
sign_in a1 pa1
help sign_out
sign_out
show_items
cd folder1
which_group
whoami
show_item_properties item5
show_items
show_users
rename_user user0 <function generate_user at 0x027087F0>
show_users
whoami
cd folder3
show_folders
help register_admin
sign_out
help help
put item5
register_user user9 pass9
add_item_property item3 key6=val6 key7=val4 key6=val9 key10=val2 
register_user user4 pass4
ls
register_user user8 pass8
which_group
current_folder
rename_user user6 <function generate_user at 0x027087F0>
sign_in user3 pass3
sign_in a5 pa5
create_folder folder3
register_admin user3 pass3
whoami
sign_out
show_folders
show_items
cd folder5
put item2
show_item_properties item2
add_item_property item3 key8=val4 key10=val10 key10=val3 key3=val1 
ls
sign_out
show_folders
add_item item5 key4=val8 key9=val5 key4=val6 key5=val8 
put item3
show_item_properties item3
help help
ls
cd folder3
create_folder folder3
add_item_property item1 key1=val9 key8=val7 key8=val4 key5=val4 
whoami
put item1
show_item_properties item2
sign_in user2 pass2
show_folders
ls_folders
show_item_properties item4
put item5
add_item_property item4 key8=val1 key4=val4 key4=val3 key9=val9 
whoami
rename_user user9 <function generate_user at 0x027087F0>
register_user user7 pass7
sign_in user2 pass2
register_user user8 pass8
pwd
sign_out
ls
sign_out
pwd
create_folder folder1
add_item_property item1 key4=val2 key6=val5 key5=val5 key7=val5 
add_item item5 key2=val3 key3=val9 key3=val2 key6=val4 
add_item item3 key2=val1 key8=val7 key6=val1 key8=val9 
current_folder
current_folder
ls
sign_out
ls_folders
sign_out
whoami
current_folder
buy
cd folder2
rename_user user0 <function generate_user at 0x027087F0>
sign_in a3 pa3
help whoami
sign_in a5 pa5
cd folder5
sign_in a4 pa4
sign_in a3 pa3
help put
show_item_properties item2
create_folder folder1
buy
pwd
cd folder4
register_admin user8 pass8
add_item_property item3 key6=val4 key2=val8 key5=val3 key4=val2 
rename_user user0 <function generate_user at 0x027087F0>
current_folder
sign_out
cd folder2
show_users
current_folder
add_item_property item2 key6=val4 key7=val4 key9=val3 key2=val10 
show_item_properties item5
ls_folders
show_item_properties item3
cd folder5
which_group
cd folder4
add_item item4 key1=val10 key3=val3 key1=val5 key8=val4 
add_item item5 key3=val5 key10=val9 key7=val1 key2=val2 
help show_items
create_folder folder2
sign_in a4 pa4
pwd
add_item item4 key7=val3 key5=val8 key2=val2 key1=val8 
show_items
create_folder folder1
cd folder1
help show_users
buy
current_folder
show_folders
register_user admin admin
sign_in a5 pa5
register_admin user9 pass9
sign_in admin admin
create_folder folder5
sign_out
show_folders
pwd
sign_in a1 pa1
put item2
add_item_property item3 key1=val9 key2=val8 key10=val8 key5=val8 
create_folder folder5
sign_out
create_folder folder1
rename_user user0 <function generate_user at 0x027087F0>
put item5
create_folder folder2
ls_folders
show_folders
add_item item2 key4=val1 key4=val6 key8=val6 key6=val1 
sign_in a2 pa2
which_group
which_group
which_group
sign_in user4 pass4
put item3
ls_folders
whoami
put item4
which_group
ls_folders
show_folders
which_group
buy
pwd
show_items
pwd
put item1
ls_folders
show_item_properties item2
sign_in user9 pass9
show_folders
show_items
sign_out
cd folder5
show_folders
rename_user user1 <function generate_user at 0x027087F0>
sign_in user2 pass2
show_folders
sign_out
show_folders
ls_folders
show_items
ls_folders
pwd
add_item_property item5 key3=val2 key4=val6 key9=val9 key6=val8 
add_item_property item2 key7=val4 key3=val9 key5=val8 key1=val2 
pwd
cd folder3
show_items
create_folder folder4
cd folder2
help current_folder
cd folder5
register_admin user2 pass2
buy
register_admin user8 pass8
register_admin user3 pass3
sign_out
show_items
put item4
ls
register_admin user7 pass7
pwd
sign_in user2 pass2
show_items
put item4
show_users
sign_out
show_item_properties item4
show_item_properties item3
show_users
which_group
show_item_properties item1
help cd
cd folder3
show_items
whoami
put item3
show_users
ls_folders
add_item_property item2 key2=val1 key1=val8 key2=val7 key3=val4 
buy
ls_folders
which_group
buy
show_folders
sign_in user5 pass5
buy
ls
show_items
show_users
ls
show_folders
create_folder folder4
current_folder
help sign_out
register_user user6 pass6
which_group
create_folder folder5
show_item_properties item4
register_user user1 pass1
buy
show_users
current_folder
which_group
rename_user user7 <function generate_user at 0x027087F0>
sign_in user2 pass2
ls_folders
cd folder4
buy
sign_out
show_items
help register_user
whoami
whoami
cd folder2
put item4
pwd
add_item item5 key6=val3 key6=val10 key1=val10 key3=val10 
create_folder folder2
rename_user user1 <function generate_user at 0x027087F0>
rename_user user2 <function generate_user at 0x027087F0>
register_user user7 pass7
register_user user3 pass3
whoami
ls
sign_in a3 pa3
cd folder5
sign_in a3 pa3
cd folder2
help show_folders
ls_folders
which_group
sign_out
buy
pwd
cd folder1
show_item_properties item3
ls_folders
rename_user user6 <function generate_user at 0x027087F0>
sign_out
ls
register_user user3 pass3
create_folder folder4
ls
put item4
pwd
help pwd
pwd
register_admin user6 pass6
ls
sign_in a4 pa4
ls_folders
rename_user user5 <function generate_user at 0x027087F0>
show_users
sign_in user8 pass8
sign_in a5 pa5
pwd
buy
create_folder folder3
pwd
add_item item3 key8=val4 key7=val5 key8=val8 key7=val9 
sign_out
show_folders
help help
help show_folders
sign_out
register_user user5 pass5
help cd
ls
show_item_properties item5
current_folder
show_users
sign_in user4 pass4
ls
sign_in user2 pass2
add_item_property item5 key3=val7 key8=val8 key10=val3 key1=val2 
sign_out
whoami
whoami
create_folder folder2
whoami
show_item_properties item1
show_users
whoami
show_users
put item4
rename_user user5 <function generate_user at 0x027087F0>
ls
add_item item2 key7=val3 key6=val4 key1=val2 key2=val10 
help rename_user
show_item_properties item3
ls
current_folder
add_item_property item5 key10=val9 key2=val7 key3=val2 key4=val5 
sign_in a3 pa3
whoami
register_admin user6 pass6
show_users
rename_user user2 <function generate_user at 0x027087F0>
current_folder
register_user user5 pass5
current_folder
cd folder2
whoami
register_admin user8 pass8
buy
sign_in a2 pa2
create_folder folder2
buy
which_group
register_admin user6 pass6
current_folder
register_admin user7 pass7
ls
register_user user8 pass8
register_admin admin admin
which_group
add_item_property item5 key10=val6 key9=val6 key10=val9 key5=val4 
which_group
buy
show_users
sign_in user9 pass9
add_item_property item5 key6=val5 key6=val5 key5=val2 key7=val10 
add_item_property item4 key9=val4 key8=val8 key10=val6 key5=val9 
register_user user8 pass8
register_admin admin admin
register_user user5 pass5
show_folders
show_users
sign_in a4 pa4
create_folder folder4
whoami
rename_user user1 <function generate_user at 0x027087F0>
current_folder
show_item_properties item5
show_item_properties item4
show_users
register_user user8 pass8
sign_out
register_user user9 pass9
current_folder
which_group
sign_in a1 pa1
create_folder folder3
register_admin user8 pass8
put item5
help sign_out
create_folder folder3
ls
cd folder2
rename_user user5 <function generate_user at 0x027087F0>
add_item item3 key8=val1 key2=val3 key6=val1 key2=val1 
add_item_property item4 key5=val10 key10=val9 key3=val2 key6=val5 
pwd
buy
add_item_property item1 key1=val1 key8=val6 key5=val6 key6=val3 
show_item_properties item2
show_item_properties item5
which_group
ls_folders
rename_user user4 <function generate_user at 0x027087F0>
sign_out
whoami
ls_folders
sign_in user5 pass5
which_group
help ls
buy
whoami
current_folder
ls_folders
current_folder
whoami
add_item item2 key7=val5 key5=val4 key8=val9 key9=val9 
ls_folders
sign_in user8 pass8
add_item item2 key6=val2 key5=val10 key9=val9 key4=val8 
current_folder
add_item_property item4 key9=val5 key7=val3 key8=val8 key9=val3 
create_folder folder5
ls
add_item_property item2 key8=val10 key6=val1 key1=val2 key2=val5 
sign_out
cd folder2
ls_folders
show_items
ls
show_item_properties item1
current_folder
register_admin user1 pass1
sign_in user3 pass3
add_item item4 key6=val8 key6=val6 key3=val4 key5=val8 
rename_user user0 <function generate_user at 0x027087F0>
add_item_property item5 key2=val3 key10=val3 key4=val9 key10=val8 
add_item_property item2 key1=val5 key4=val10 key5=val7 key6=val1 
cd folder1
show_folders
put item5
which_group
which_group
sign_in a1 pa1
register_user user7 pass7
show_item_properties item5
current_folder
ls
register_admin user6 pass6
sign_out
put item1
sign_in user5 pass5
rename_user user8 <function generate_user at 0x027087F0>
add_item item2 key1=val7 key8=val3 key6=val4 key5=val5 
ls_folders
help register_admin
whoami
put item1
ls
register_admin user7 pass7
sign_in user7 pass7
add_item item5 key2=val5 key10=val4 key7=val10 key2=val9 
sign_out
create_folder folder5
help pwd
pwd
ls
register_user user8 pass8
which_group
add_item_property item3 key1=val10 key3=val9 key6=val10 key9=val8 
show_item_properties item3
rename_user user8 <function generate_user at 0x027087F0>
show_item_properties item5
create_folder folder1
ls_folders
create_folder folder1
sign_out
create_folder folder1
help show_users
register_admin user2 pass2
pwd
sign_out
rename_user user9 <function generate_user at 0x027087F0>
rename_user user6 <function generate_user at 0x027087F0>
add_item item3 key4=val10 key4=val7 key1=val6 key6=val10 
put item4
sign_out
show_folders
sign_in user6 pass6
show_folders
show_users
show_item_properties item2
add_item item2 key2=val3 key3=val1 key1=val1 key3=val1 
ls_folders
whoami
show_item_properties item2
cd folder5
show_folders
show_folders
rename_user user7 <function generate_user at 0x027087F0>
sign_out
show_folders
ls
add_item item5 key8=val7 key8=val7 key4=val6 key5=val1 
show_users
register_user user6 pass6
help register_user
buy
add_item_property item3 key8=val9 key3=val4 key4=val9 key3=val2 
help show_users
put item2
rename_user user7 <function generate_user at 0x027087F0>
show_users
current_folder
which_group
cd folder2
register_admin user3 pass3
ls_folders
add_item item2 key10=val6 key9=val1 key10=val9 key10=val3 
help register_user
show_users
show_users
ls_folders
whoami
which_group
show_folders
register_user user2 pass2
create_folder folder5
sign_out
show_item_properties item5
whoami
sign_in user6 pass6
put item5
rename_user user3 <function generate_user at 0x027087F0>
show_users
show_users
help put
whoami
add_item item3 key2=val3 key9=val6 key2=val1 key4=val4 
add_item item3 key9=val7 key2=val2 key1=val2 key10=val4 
pwd
ls
register_admin admin admin
pwd
ls
buy
register_admin user8 pass8
sign_in a5 pa5
current_folder
ls_folders
show_item_properties item5
put item5
create_folder folder1
put item2
create_folder folder1
register_user admin admin
show_item_properties item5
rename_user user9 <function generate_user at 0x027087F0>
show_item_properties item2
sign_in user4 pass4
show_items
ls
sign_out
rename_user user6 <function generate_user at 0x027087F0>
current_folder
ls_folders
which_group
ls_folders
cd folder1
sign_out
help ls
show_items
show_users
ls_folders
whoami
put item2
put item4
show_users
register_admin user1 pass1
cd folder1
show_folders
show_folders
add_item_property item3 key8=val8 key10=val3 key8=val3 key10=val10 
which_group
add_item_property item5 key10=val3 key5=val10 key10=val4 key3=val6 
ls
register_user user5 pass5
ls
show_items
register_user user2 pass2
sign_out
register_admin user8 pass8
add_item item5 key4=val3 key7=val1 key6=val9 key4=val9 
sign_in admin admin
show_item_properties item1
which_group
current_folder
add_item item3 key5=val4 key7=val5 key9=val4 key2=val4 
show_folders
show_users
ls_folders
cd folder1
add_item item2 key8=val10 key3=val3 key9=val6 key2=val4 
register_admin user2 pass2
register_admin user7 pass7
ls
register_admin admin admin
put item4
show_items
ls
put item4
create_folder folder5
which_group
add_item item5 key4=val5 key10=val9 key7=val7 key4=val4 
whoami
sign_in user8 pass8
put item5
show_item_properties item1
rename_user user4 <function generate_user at 0x027087F0>
ls
create_folder folder2
sign_in a2 pa2
ls_folders
help sign_in
show_users
which_group
add_item item5 key9=val1 key2=val1 key2=val1 key6=val8 
add_item_property item5 key1=val6 key3=val10 key9=val8 key8=val5 
show_item_properties item5
ls_folders
cd folder2
buy
sign_out
show_folders
sign_in a5 pa5
register_user user1 pass1
add_item_property item3 key9=val5 key6=val5 key3=val7 key10=val4 
show_users
register_user user1 pass1
show_items
register_user user6 pass6
add_item_property item4 key2=val5 key7=val10 key2=val4 key7=val9 
show_users
add_item item2 key6=val1 key3=val3 key2=val2 key2=val2 
show_users
put item3
show_items
create_folder folder4
which_group
register_admin user4 pass4
register_user user3 pass3
add_item_property item4 key1=val6 key3=val7 key4=val7 key6=val2 
ls_folders
put item3
ls_folders
whoami
show_users
pwd
create_folder folder3
rename_user user2 <function generate_user at 0x027087F0>
show_items
add_item item3 key6=val6 key10=val9 key8=val7 key3=val3 
add_item_property item4 key6=val5 key5=val9 key2=val1 key3=val6 
register_admin admin admin
sign_in user9 pass9
put item5
rename_user user5 <function generate_user at 0x027087F0>
which_group
whoami
create_folder folder4
buy
sign_in user1 pass1
whoami
create_folder folder1
rename_user user6 <function generate_user at 0x027087F0>
add_item item3 key3=val6 key9=val1 key4=val7 key10=val4 
ls
put item4
show_items
rename_user user7 <function generate_user at 0x027087F0>
current_folder
create_folder folder2
ls_folders
rename_user user6 <function generate_user at 0x027087F0>
register_admin admin admin
show_folders
put item4
rename_user user6 <function generate_user at 0x027087F0>
register_admin user3 pass3
show_folders
register_admin user3 pass3
add_item_property item3 key2=val2 key1=val4 key1=val1 key6=val3 
add_item item3 key7=val7 key7=val4 key3=val1 key4=val4 
current_folder
cd folder5
create_folder folder5
show_users
which_group
register_admin user1 pass1
ls
buy
cd folder3
show_items
sign_in user3 pass3
current_folder
show_items
pwd
add_item_property item3 key6=val2 key6=val7 key4=val6 key8=val2 
show_users
sign_in admin admin
show_items
ls_folders
sign_out
which_group
sign_in user2 pass2
register_admin user5 pass5
register_admin user5 pass5
buy
cd folder3
which_group
register_admin user8 pass8
whoami
put item5
sign_out
add_item item4 key7=val1 key7=val2 key7=val3 key8=val5 
ls_folders
show_items
cd folder2
current_folder
which_group
sign_in a3 pa3
create_folder folder3
buy
add_item_property item2 key10=val6 key1=val7 key2=val4 key3=val1 
cd folder3
sign_in a5 pa5
register_admin user8 pass8
show_item_properties item2
rename_user user2 <function generate_user at 0x027087F0>
put item5
cd folder3
register_user user1 pass1
cd folder1
which_group
pwd
pwd
show_items
sign_in a1 pa1
sign_in user6 pass6
register_admin user2 pass2
add_item item4 key8=val10 key7=val1 key6=val6 key10=val8 
ls_folders
current_folder
ls_folders
show_folders
ls
sign_in a5 pa5
register_user user9 pass9
add_item_property item5 key10=val4 key8=val5 key7=val4 key8=val7 
help history
sign_out
show_items
sign_in a5 pa5
put item1
buy
create_folder folder2
add_item item4 key1=val4 key5=val7 key10=val7 key4=val1 
add_item_property item1 key7=val7 key2=val6 key4=val2 key10=val9 
show_folders
add_item item5 key1=val6 key10=val9 key10=val1 key8=val1 
show_items
sign_out
pwd
show_users
add_item item2 key3=val5 key4=val7 key6=val7 key6=val6 
create_folder folder4
whoami
cd folder5
create_folder folder4
add_item_property item2 key8=val5 key2=val2 key1=val5 key9=val1 
ls
show_items
put item1
cd folder5
sign_out
which_group
current_folder
ls_folders
ls_folders
add_item_property item5 key8=val5 key9=val5 key5=val6 key2=val5 
rename_user user7 <function generate_user at 0x027087F0>
put item2
help register_admin
sign_in a3 pa3
sign_out
current_folder
add_item_property item4 key9=val10 key7=val5 key9=val10 key5=val9 
buy
show_folders
rename_user user5 <function generate_user at 0x027087F0>
rename_user user7 <function generate_user at 0x027087F0>
show_users
cd folder2
register_admin user3 pass3
put item3
ls_folders
cd folder4
ls
add_item_property item4 key9=val6 key3=val9 key2=val4 key6=val1 
whoami
show_folders
show_item_properties item1
current_folder
show_users
current_folder
pwd
register_admin user1 pass1
whoami
ls_folders
rename_user user1 <function generate_user at 0x027087F0>
put item1
add_item_property item5 key9=val3 key4=val2 key1=val4 key8=val1 
ls_folders
sign_out
which_group
show_folders
add_item item1 key5=val7 key2=val6 key4=val4 key1=val9 
buy
show_folders
create_folder folder2
create_folder folder1
help create_folder
whoami
create_folder folder3
sign_in a2 pa2
show_items
register_admin user3 pass3
add_item_property item3 key8=val8 key3=val5 key4=val8 key6=val4 
help history
show_folders
add_item_property item3 key9=val4 key3=val10 key7=val7 key1=val2 
sign_in a4 pa4
register_admin user8 pass8
register_admin user1 pass1
sign_in admin admin
add_item item1 key5=val4 key5=val6 key5=val8 key1=val5 
sign_out
register_admin admin admin
ls
sign_out
ls
help create_folder
which_group
add_item item1 key1=val3 key10=val8 key7=val2 key3=val8 
pwd
sign_in user6 pass6
help delete_user
sign_in user8 pass8
create_folder folder2
sign_in user4 pass4
current_folder
show_items
ls_folders
whoami
pwd
sign_in user7 pass7
show_users
whoami
add_item_property item2 key3=val4 key10=val4 key9=val3 key2=val5 
buy
whoami
current_folder
register_user user6 pass6
buy
ls_folders
buy
register_admin user4 pass4
show_items
register_admin user9 pass9
whoami
show_item_properties item4
sign_in user1 pass1
show_items
register_admin user6 pass6
whoami
help add_item
show_folders
buy
show_folders
add_item item3 key3=val8 key3=val4 key1=val3 key10=val4 
create_folder folder5
sign_out
help history
sign_in a5 pa5
show_users
show_items
show_items
rename_user user4 <function generate_user at 0x027087F0>
create_folder folder5
register_user user3 pass3
ls
show_items
help current_folder
sign_out
show_item_properties item4
cd folder4
register_admin admin admin
sign_in a1 pa1
show_folders
current_folder
ls_folders
pwd
whoami
register_user user8 pass8
help current_folder
show_item_properties item1
pwd
which_group
put item5
pwd
ls_folders
put item4
create_folder folder2
cd folder3
create_folder folder3
sign_in a1 pa1
which_group
which_group
ls_folders
add_item item3 key7=val3 key7=val3 key6=val3 key1=val4 
show_item_properties item1
show_item_properties item5
whoami
create_folder folder5
buy
add_item item2 key8=val5 key6=val1 key1=val8 key3=val9 
sign_in user3 pass3
cd folder2
whoami
register_admin user7 pass7
add_item item3 key7=val10 key3=val8 key9=val7 key6=val10 
rename_user user4 <function generate_user at 0x027087F0>
sign_in user4 pass4
rename_user user7 <function generate_user at 0x027087F0>
rename_user user1 <function generate_user at 0x027087F0>
whoami
show_items
add_item item1 key10=val9 key3=val10 key8=val10 key5=val2 
cd folder5
help create_folder
whoami
add_item_property item5 key10=val10 key1=val6 key7=val3 key6=val6 
add_item item2 key6=val2 key9=val10 key3=val3 key6=val6 
sign_in a5 pa5
help delete_user
put item4
create_folder folder1
add_item_property item5 key4=val5 key8=val8 key10=val5 key9=val7 
add_item_property item3 key10=val9 key4=val10 key6=val2 key5=val4 
rename_user user3 <function generate_user at 0x027087F0>
sign_out
pwd
ls
sign_out
cd folder1
show_folders
add_item item5 key4=val1 key9=val2 key5=val4 key8=val5 
sign_in admin admin
buy
show_items
show_items
current_folder
show_folders
show_users
add_item_property item2 key4=val4 key2=val5 key8=val3 key7=val4 
ls
register_admin user4 pass4
pwd
cd folder1
show_items
show_item_properties item4
sign_out
whoami
add_item_property item3 key2=val4 key1=val4 key4=val5 key2=val8 
cd folder3
sign_in a5 pa5
add_item_property item2 key5=val6 key4=val1 key10=val10 key7=val2 
create_folder folder2
show_items
whoami
rename_user user0 <function generate_user at 0x027087F0>
current_folder
help pwd
add_item item1 key4=val2 key9=val8 key3=val5 key4=val7 
add_item item4 key9=val6 key3=val8 key1=val1 key4=val6 
current_folder
show_items
sign_in admin admin
current_folder
register_user user4 pass4
show_item_properties item2
register_admin user9 pass9
add_item_property item1 key9=val5 key1=val10 key6=val5 key10=val8 
rename_user user5 <function generate_user at 0x027087F0>
add_item item5 key6=val5 key3=val9 key4=val2 key1=val3 
ls_folders
whoami
show_folders
sign_in a3 pa3
create_folder folder3
add_item item5 key5=val5 key3=val2 key2=val5 key7=val3 
put item4
cd folder4
sign_in user4 pass4
create_folder folder4
add_item item1 key5=val8 key1=val6 key7=val1 key3=val8 
ls_folders
sign_out
put item1
sign_out
cd folder5
add_item_property item5 key8=val6 key1=val7 key5=val9 key1=val4 
show_item_properties item2
pwd
sign_in user6 pass6
cd folder2
register_admin user2 pass2
cd folder3
whoami
show_item_properties item3
sign_out
rename_user user9 <function generate_user at 0x027087F0>
show_folders
sign_in a5 pa5
pwd
show_items
register_admin admin admin
create_folder folder3
create_folder folder4
sign_in a1 pa1
help show_item_properties
help exit
cd folder1
buy
cd folder1
sign_out
register_user admin admin
rename_user user0 <function generate_user at 0x027087F0>
sign_out
which_group
show_items
create_folder folder1
show_users
add_item_property item5 key9=val4 key5=val10 key3=val1 key8=val5 
pwd
show_users
add_item_property item3 key5=val5 key6=val6 key5=val1 key2=val1 
pwd
sign_in user8 pass8
cd folder4
register_user admin admin
put item5
ls
whoami
show_item_properties item1
ls
buy
buy
pwd
buy
register_user user6 pass6
show_item_properties item1
show_folders
current_folder
ls
show_folders
register_admin user9 pass9
sign_out
whoami
show_folders
buy
put item4
which_group
add_item_property item2 key1=val7 key1=val8 key9=val6 key7=val3 
show_folders
pwd
sign_in a5 pa5
sign_out
help whoami
register_admin user1 pass1
buy
show_item_properties item4
create_folder folder4
buy
sign_out
sign_out
which_group
register_user user1 pass1
add_item_property item3 key9=val10 key2=val1 key4=val4 key3=val1 
buy
sign_in a2 pa2
add_item_property item3 key6=val6 key7=val6 key7=val1 key6=val7 
buy
rename_user user4 <function generate_user at 0x027087F0>
create_folder folder1
cd folder4
ls
ls
ls
sign_in a5 pa5
pwd
register_user user2 pass2
current_folder
register_admin user9 pass9
show_items
register_user user6 pass6
ls_folders
current_folder
show_item_properties item2
pwd
sign_in a5 pa5
sign_in user5 pass5
cd folder3
put item2
sign_in admin admin
register_user user6 pass6
show_users
put item3
ls_folders
sign_in a1 pa1
sign_out
show_items
put item5
current_folder
sign_in user7 pass7
current_folder
add_item item5 key6=val7 key6=val9 key10=val1 key3=val10 
ls
current_folder
whoami
put item3
show_items
create_folder folder3
sign_out
which_group
ls_folders
sign_out
sign_in user9 pass9
add_item item1 key10=val10 key2=val8 key9=val8 key7=val8 
show_users
pwd
register_admin user1 pass1
show_folders
show_folders
current_folder
which_group
cd folder3
register_user user6 pass6
current_folder
register_user admin admin
whoami
show_items
ls
add_item item2 key3=val10 key10=val2 key9=val7 key1=val8 
rename_user user0 <function generate_user at 0x027087F0>
show_users
which_group
rename_user user1 <function generate_user at 0x027087F0>
sign_in a2 pa2
whoami
pwd
register_user user6 pass6
add_item item4 key1=val1 key3=val7 key1=val9 key10=val2 
create_folder folder1
rename_user user4 <function generate_user at 0x027087F0>
create_folder folder3
create_folder folder5
add_item item3 key4=val9 key6=val5 key10=val7 key9=val1 
sign_in user7 pass7
sign_in user9 pass9
help add_item_property
add_item_property item3 key3=val7 key2=val5 key1=val1 key3=val9 
sign_out
cd folder5
whoami
pwd
register_admin user1 pass1
whoami
pwd
sign_out
buy
help which_group
show_users
add_item_property item3 key6=val8 key4=val5 key10=val5 key1=val2 
register_user user1 pass1
show_items
pwd
ls_folders
create_folder folder4
create_folder folder5
register_user user1 pass1
show_item_properties item5
show_users
rename_user user6 <function generate_user at 0x027087F0>
show_folders
show_item_properties item4
buy
show_items
register_admin user4 pass4
current_folder
current_folder
add_item item5 key7=val1 key1=val5 key3=val6 key2=val1 
show_folders
register_admin user2 pass2
show_users
show_users
register_admin admin admin
add_item item1 key6=val5 key9=val1 key3=val6 key6=val2 
help current_folder
show_users
current_folder
show_users
sign_in a3 pa3
whoami
show_item_properties item4
cd folder5
ls_folders
which_group
whoami
rename_user user7 <function generate_user at 0x027087F0>
which_group
current_folder
add_item_property item1 key4=val6 key8=val1 key6=val2 key1=val10 
sign_in user3 pass3
sign_in admin admin
ls
sign_in admin admin
show_folders
sign_in user7 pass7
create_folder folder5
pwd
current_folder
create_folder folder2
put item3
whoami
show_items
rename_user user8 <function generate_user at 0x027087F0>
help view_order
sign_out
buy
show_folders
create_folder folder4
add_item item1 key10=val1 key8=val2 key1=val5 key1=val7 
show_folders
help put
ls_folders
cd folder5
sign_in user2 pass2
pwd
ls
cd folder3
buy
buy
add_item_property item3 key1=val5 key1=val1 key8=val1 key2=val6 
add_item_property item1 key8=val2 key1=val2 key10=val8 key4=val10 
help exit
help ls
show_users
show_folders
show_items
sign_out
register_user user1 pass1
ls
which_group
register_admin user7 pass7
register_admin user4 pass4
put item4
show_items
which_group
whoami
sign_out
sign_out
sign_in user4 pass4
ls
show_items
sign_out
show_users
add_item_property item4 key7=val6 key4=val6 key7=val1 key3=val1 
ls
add_item_property item4 key7=val9 key6=val5 key7=val1 key2=val2 
show_items
register_user user7 pass7
show_folders
register_user user8 pass8
ls
sign_in user8 pass8
current_folder
buy
ls_folders
register_user user8 pass8
sign_in user2 pass2
register_user user3 pass3
show_users
show_folders
ls_folders
show_items
register_admin user5 pass5
buy
show_items
whoami
rename_user user4 <function generate_user at 0x027087F0>
create_folder folder5
create_folder folder1
add_item item4 key4=val10 key3=val8 key10=val2 key9=val7 
whoami
rename_user user6 <function generate_user at 0x027087F0>
whoami
create_folder folder5
pwd
register_user user9 pass9
register_user user7 pass7
show_folders
create_folder folder5
put item5
sign_out
whoami
show_users
cd folder3
ls_folders
sign_in user9 pass9
show_item_properties item3
pwd
which_group
show_folders
show_item_properties item5
which_group
whoami
show_item_properties item3
current_folder
ls_folders
put item2
cd folder3
register_user user9 pass9
show_folders
show_folders
show_folders
register_user user1 pass1
sign_in a4 pa4
add_item item3 key8=val2 key5=val4 key8=val4 key1=val2 
sign_in user1 pass1
which_group
cd folder3
cd folder5
sign_in a5 pa5
sign_in user8 pass8
rename_user user6 <function generate_user at 0x027087F0>
put item5
sign_in admin admin
rename_user user6 <function generate_user at 0x027087F0>
current_folder
sign_out
sign_out
register_user admin admin
whoami
add_item_property item2 key2=val8 key7=val10 key7=val7 key7=val6 
help show_folders
add_item item3 key7=val7 key8=val6 key3=val3 key9=val2 
add_item_property item3 key2=val10 key8=val4 key2=val7 key4=val10 
put item2
register_user user6 pass6
sign_out
show_folders
show_items
sign_out
register_admin user4 pass4
create_folder folder1
help sign_out
cd folder4
whoami
which_group
current_folder
sign_in a5 pa5
show_items
add_item item1 key1=val6 key10=val9 key9=val9 key8=val4 
rename_user user2 <function generate_user at 0x027087F0>
which_group
sign_in user9 pass9
buy
ls_folders
ls_folders
whoami
whoami
show_items
whoami
sign_in a5 pa5
register_admin user2 pass2
show_item_properties item1
current_folder
add_item_property item2 key5=val10 key5=val4 key9=val10 key1=val2 
show_folders
cd folder3
show_folders
rename_user user0 <function generate_user at 0x027087F0>
whoami
show_item_properties item1
add_item item1 key7=val9 key9=val2 key4=val10 key3=val5 
show_item_properties item5
create_folder folder3
add_item_property item4 key1=val8 key1=val6 key6=val9 key2=val5 
buy
whoami
sign_in a1 pa1
ls_folders
register_user user1 pass1
current_folder
help show_folders
help view_order
register_admin user2 pass2
ls
help put
which_group
ls_folders
add_item item2 key6=val5 key4=val8 key9=val7 key3=val2 
rename_user user7 <function generate_user at 0x027087F0>
current_folder
show_folders
add_item_property item1 key9=val2 key6=val6 key1=val5 key2=val5 
show_folders
help exit
buy
ls_folders
pwd
put item2
put item1
sign_in user9 pass9
ls_folders
ls
sign_in user7 pass7
add_item_property item3 key7=val9 key10=val3 key3=val6 key8=val2 
sign_out
show_users
sign_in user6 pass6
current_folder
sign_in user8 pass8
register_user user9 pass9
sign_out
show_folders
pwd
help rename_user
ls_folders
which_group
which_group
show_item_properties item5
rename_user user1 <function generate_user at 0x027087F0>
sign_out
show_item_properties item3
ls
buy
sign_in a1 pa1
buy
add_item item1 key10=val10 key5=val6 key10=val5 key5=val8 
help delete_user
show_folders
current_folder
add_item_property item5 key8=val1 key1=val7 key8=val9 key1=val10 
add_item item5 key7=val5 key5=val6 key10=val4 key6=val2 
sign_out
cd folder2
register_user user2 pass2
register_admin user4 pass4
show_users
whoami
show_users
register_user user2 pass2
show_items
add_item_property item4 key7=val10 key7=val5 key5=val9 key3=val7 
ls
register_user user4 pass4
which_group
show_items
register_user user4 pass4
rename_user user4 <function generate_user at 0x027087F0>
whoami
sign_out
sign_in a4 pa4
which_group
cd folder1
register_admin user7 pass7
show_folders
ls
buy
sign_in a2 pa2
create_folder folder4
whoami
show_items
ls
create_folder folder4
rename_user user7 <function generate_user at 0x027087F0>
cd folder4
sign_in user8 pass8
register_admin user8 pass8
show_folders
cd folder3
sign_out
show_item_properties item4
cd folder5
pwd
show_users
add_item_property item2 key5=val6 key10=val9 key1=val10 key7=val10 
whoami
show_item_properties item3
current_folder
rename_user user1 <function generate_user at 0x027087F0>
sign_in user7 pass7
rename_user user4 <function generate_user at 0x027087F0>
create_folder folder5
sign_in user1 pass1
which_group
show_item_properties item4
which_group
show_item_properties item1
show_items
register_admin user6 pass6
whoami
ls
cd folder5
show_folders
put item3
register_admin user3 pass3
show_users
add_item_property item5 key6=val2 key5=val5 key3=val9 key5=val3 
sign_in a1 pa1
sign_in a2 pa2
register_admin user1 pass1
cd folder4
show_folders
ls_folders
which_group
rename_user user2 <function generate_user at 0x027087F0>
create_folder folder1
sign_in a5 pa5
add_item_property item2 key3=val9 key2=val6 key5=val4 key7=val3 
add_item_property item2 key1=val3 key7=val5 key6=val6 key10=val6 
show_users
register_user admin admin
register_admin user4 pass4
add_item_property item5 key5=val6 key2=val5 key7=val1 key2=val6 
show_users
sign_out
which_group
whoami
add_item item2 key8=val3 key6=val9 key2=val6 key10=val9 
buy
buy
current_folder
show_folders
register_user user5 pass5
sign_in user9 pass9
add_item item2 key9=val8 key10=val5 key4=val4 key4=val4 
show_item_properties item5
register_user user6 pass6
create_folder folder4
sign_out
pwd
ls
help create_folder
buy
show_folders
ls
show_users
cd folder4
put item4
add_item item2 key3=val3 key6=val6 key2=val4 key3=val7 
sign_in user3 pass3
buy
add_item_property item3 key3=val8 key3=val5 key1=val2 key2=val2 
put item4
buy
show_items
whoami
sign_in a1 pa1
whoami
help show_item_properties
ls_folders
ls_folders
current_folder
ls_folders
sign_out
register_user user7 pass7
show_users
buy
buy
put item3
cd folder3
register_user user4 pass4
rename_user user4 <function generate_user at 0x027087F0>
show_items
ls
add_item item1 key8=val3 key7=val8 key5=val1 key1=val8 
help show_users
ls
help which_group
show_item_properties item5
pwd
create_folder folder2
ls_folders
register_admin user9 pass9
show_folders
ls
pwd
cd folder5
current_folder
sign_in user9 pass9
register_admin admin admin
register_admin user8 pass8
add_item item5 key8=val9 key1=val9 key1=val2 key2=val3 
sign_in a5 pa5
whoami
add_item item1 key9=val8 key3=val10 key9=val10 key1=val6 
pwd
add_item_property item3 key5=val7 key1=val6 key2=val9 key3=val7 
which_group
which_group
ls_folders
show_item_properties item5
rename_user user9 <function generate_user at 0x027087F0>
current_folder
sign_out
ls
show_users
create_folder folder4
pwd
create_folder folder3
register_user user6 pass6
register_admin user9 pass9
show_items
show_users
rename_user user9 <function generate_user at 0x027087F0>
register_user user8 pass8
pwd
ls
register_user admin admin
show_users
ls
show_folders
cd folder5
sign_in user6 pass6
cd folder2
sign_in a3 pa3
sign_in user6 pass6
ls
rename_user user6 <function generate_user at 0x027087F0>
sign_in user5 pass5
whoami
ls_folders
buy
register_admin user4 pass4
whoami
ls
register_admin user7 pass7
show_folders
current_folder
sign_in a2 pa2
cd folder5
show_items
current_folder
register_admin user5 pass5
show_items
show_users
which_group
help delete_user
sign_in a4 pa4
current_folder
which_group
cd folder4
show_items
show_users
create_folder folder3
ls
show_users
current_folder
put item5
which_group
ls_folders
add_item item3 key3=val2 key2=val9 key10=val6 key7=val7 
put item3
current_folder
ls
help show_folders
sign_in user6 pass6
ls
add_item_property item4 key3=val9 key10=val4 key1=val8 key5=val9 
register_admin user1 pass1
add_item item3 key4=val10 key3=val7 key3=val8 key3=val7 
which_group
show_items
register_admin user4 pass4
show_folders
pwd
sign_in user5 pass5
register_admin user4 pass4
show_folders
help show_users
sign_in admin admin
whoami
buy
put item5
show_items
show_items
sign_in user9 pass9
add_item_property item5 key9=val7 key9=val5 key2=val4 key9=val5 
register_user admin admin
whoami
show_users
add_item_property item5 key9=val1 key4=val10 key3=val6 key6=val5 
add_item_property item1 key6=val4 key4=val7 key7=val6 key6=val10 
put item3
show_items
show_folders
current_folder
show_folders
buy
whoami
cd folder4
register_user user5 pass5
ls
show_item_properties item1
show_users
sign_in admin admin
which_group
ls
show_users
cd folder1
pwd
show_users
current_folder
ls
put item1
buy
rename_user user5 <function generate_user at 0x027087F0>
buy
create_folder folder3
whoami
put item3
ls
add_item item3 key1=val6 key5=val8 key3=val7 key6=val3 
buy
show_users
create_folder folder2
ls
which_group
whoami
create_folder folder5
show_items
put item5
pwd
register_admin user1 pass1
whoami
show_items
ls
sign_out
create_folder folder1
show_item_properties item3
add_item item1 key9=val10 key9=val3 key7=val3 key10=val1 
ls
pwd
put item3
show_users
ls
rename_user user4 <function generate_user at 0x027087F0>
current_folder
register_admin user4 pass4
put item1
add_item_property item4 key4=val8 key5=val5 key7=val5 key1=val2 
add_item item3 key2=val4 key3=val9 key4=val7 key1=val7 
show_item_properties item5
which_group
sign_out
which_group
ls
register_user user4 pass4
current_folder
sign_in admin admin
show_item_properties item5
sign_in user6 pass6
sign_in a1 pa1
ls
register_user user4 pass4
put item2
show_item_properties item5
show_item_properties item5
show_users
sign_in user1 pass1
ls
put item5
buy
show_folders
create_folder folder3
rename_user user4 <function generate_user at 0x027087F0>
show_users
register_admin user3 pass3
create_folder folder3
add_item item1 key1=val3 key6=val6 key6=val7 key6=val4 
current_folder
whoami
register_user user4 pass4
show_users
rename_user user5 <function generate_user at 0x027087F0>
register_user user8 pass8
show_users
ls
show_items
ls
add_item_property item5 key1=val9 key5=val4 key7=val10 key10=val2 
register_user user4 pass4
ls
rename_user user2 <function generate_user at 0x027087F0>
show_items
create_folder folder4
create_folder folder5
show_item_properties item1
ls
show_folders
add_item_property item5 key10=val6 key5=val3 key7=val7 key2=val7 
add_item item3 key9=val10 key10=val5 key5=val7 key6=val7 
sign_in a3 pa3
register_admin user6 pass6
add_item_property item1 key5=val7 key9=val1 key6=val1 key4=val5 
show_items
current_folder
ls_folders
sign_out
current_folder
add_item_property item2 key2=val10 key5=val7 key10=val5 key2=val5 
cd folder5
pwd
help exit
sign_out
create_folder folder2
which_group
whoami
register_admin user4 pass4
sign_in a1 pa1
which_group
cd folder3
add_item item5 key5=val10 key9=val5 key3=val9 key1=val2 
sign_in user8 pass8
add_item item4 key2=val10 key7=val4 key9=val7 key1=val5 
buy
add_item_property item5 key4=val4 key8=val3 key6=val8 key9=val5 
show_item_properties item3
add_item item1 key5=val5 key1=val10 key3=val4 key4=val7 
put item5
help exit
register_user user5 pass5
sign_out
current_folder
rename_user user6 <function generate_user at 0x027087F0>
add_item item5 key9=val4 key4=val10 key5=val3 key5=val8 
show_items
register_admin user7 pass7
rename_user user7 <function generate_user at 0x027087F0>
help exit
sign_out
ls_folders
add_item item5 key10=val4 key6=val6 key2=val10 key7=val3 
show_item_properties item5
sign_in user6 pass6
which_group
ls_folders
buy
add_item_property item5 key4=val10 key9=val5 key3=val3 key9=val6 
show_folders
help register_user
register_admin user6 pass6
current_folder
whoami
help show_items
add_item item3 key7=val3 key1=val7 key1=val10 key8=val2 
show_users
cd folder2
rename_user user2 <function generate_user at 0x027087F0>
pwd
sign_out
register_user admin admin
register_user user9 pass9
put item4
show_users
help current_folder
cd folder1
rename_user user2 <function generate_user at 0x027087F0>
show_item_properties item3
show_users
add_item_property item4 key5=val6 key3=val8 key10=val6 key2=val5 
current_folder
pwd
show_items
add_item item5 key7=val4 key2=val10 key7=val9 key1=val9 
cd folder1
put item5
add_item item2 key4=val4 key4=val4 key8=val8 key4=val6 
help rename_user
show_item_properties item4
whoami
register_admin user1 pass1
add_item_property item1 key8=val2 key7=val5 key6=val6 key4=val3 
current_folder
add_item_property item2 key9=val8 key2=val5 key1=val3 key5=val7 
current_folder
sign_out
pwd
register_admin user2 pass2
register_admin user1 pass1
which_group
add_item item1 key4=val4 key2=val7 key4=val7 key4=val2 
sign_out
show_folders
rename_user user6 <function generate_user at 0x027087F0>
ls_folders
ls
sign_in a2 pa2
which_group
show_folders
sign_in user6 pass6
put item1
help whoami
show_users
show_users
put item2
buy
help current_folder
sign_out
ls_folders
ls
add_item item4 key5=val7 key3=val7 key3=val7 key1=val2 
help create_folder
show_items
rename_user user9 <function generate_user at 0x027087F0>
ls
help whoami
add_item_property item2 key8=val4 key2=val2 key10=val10 key8=val9 
add_item item5 key4=val8 key6=val8 key7=val3 key5=val4 
register_user user2 pass2
help sign_in
ls
rename_user user9 <function generate_user at 0x027087F0>
add_item item1 key7=val5 key7=val6 key6=val1 key8=val3 
which_group
show_item_properties item4
show_items
help show_users
ls
show_users
whoami
show_folders
show_users
buy
help buy
add_item item1 key5=val9 key5=val1 key8=val4 key8=val2 
which_group
whoami
show_folders
sign_in a2 pa2
show_folders
sign_in a3 pa3
rename_user user7 <function generate_user at 0x027087F0>
add_item item2 key5=val4 key9=val1 key5=val6 key4=val2 
show_item_properties item1
show_item_properties item1
sign_in user1 pass1
pwd
sign_in user9 pass9
ls
register_admin user7 pass7
rename_user user3 <function generate_user at 0x027087F0>
show_items
show_folders
show_folders
sign_in a2 pa2
sign_out
put item2
register_user user4 pass4
show_items
sign_in a4 pa4
buy
whoami
show_users
sign_out
pwd
current_folder
register_admin user7 pass7
cd folder2
pwd
ls_folders
help current_folder
register_user user6 pass6
sign_in user1 pass1
show_item_properties item4
which_group
add_item item4 key1=val2 key4=val8 key5=val5 key5=val10 
show_users
ls_folders
create_folder folder3
sign_in a4 pa4
current_folder
which_group
show_users
current_folder
pwd
ls
pwd
ls_folders
buy
ls_folders
sign_in user1 pass1
ls
show_folders
current_folder
ls
ls
add_item item5 key2=val5 key1=val4 key8=val3 key7=val4 
show_folders
ls
ls_folders
pwd
whoami
add_item item2 key3=val5 key10=val2 key7=val4 key6=val7 
current_folder
cd folder2
put item2
current_folder
sign_out
ls_folders
add_item_property item5 key7=val4 key4=val3 key3=val7 key9=val6 
which_group
show_items
cd folder4
current_folder
which_group
add_item item2 key10=val3 key1=val1 key9=val1 key7=val7 
create_folder folder5
sign_in a4 pa4
cd folder3
sign_out
ls
ls
cd folder2
show_items
which_group
pwd
put item4
current_folder
sign_in a3 pa3
register_user user5 pass5
register_admin user5 pass5
add_item_property item4 key2=val7 key8=val8 key6=val9 key8=val3 
sign_out
put item3
current_folder
help whoami
ls_folders
register_admin user7 pass7
show_users
add_item_property item3 key1=val8 key6=val8 key3=val8 key9=val10 
register_admin user3 pass3
which_group
current_folder
create_folder folder2
show_items
register_user user8 pass8
show_folders
whoami
pwd
pwd
sign_in a1 pa1
show_items
buy
current_folder
register_admin user9 pass9
put item5
whoami
sign_in user2 pass2
show_users
help ls
create_folder folder1
rename_user user4 <function generate_user at 0x027087F0>
create_folder folder3
rename_user user9 <function generate_user at 0x027087F0>
create_folder folder4
buy
ls_folders
pwd
register_user user5 pass5
add_item item3 key5=val4 key5=val6 key10=val6 key3=val9 
show_item_properties item5
add_item_property item3 key6=val7 key2=val8 key6=val3 key5=val3 
show_folders
create_folder folder1
buy
show_item_properties item1
put item2
which_group
ls
whoami
whoami
add_item_property item2 key9=val6 key4=val2 key10=val5 key4=val5 
cd folder2
put item3
sign_out
show_folders
show_item_properties item3
buy
ls_folders
ls_folders
sign_in user9 pass9
which_group
ls
show_items
help register_admin
ls_folders
sign_in a5 pa5
add_item_property item4 key5=val4 key10=val5 key1=val4 key7=val6 
current_folder
whoami
sign_in a4 pa4
show_folders
sign_out
create_folder folder3
register_user user8 pass8
ls
sign_in a4 pa4
rename_user user4 <function generate_user at 0x027087F0>
help show_folders
ls_folders
current_folder
help sign_in
pwd
show_folders
sign_in a3 pa3
sign_in user1 pass1
cd folder1
register_admin user8 pass8
create_folder folder4
add_item_property item5 key1=val9 key4=val10 key3=val7 key9=val1 
whoami
pwd
pwd
put item4
current_folder
cd folder1
rename_user user0 <function generate_user at 0x027087F0>
create_folder folder1
sign_out
put item4
show_items
whoami
help ls
put item3
show_items
register_admin user6 pass6
ls_folders
which_group
buy
show_folders
register_user user5 pass5
ls_folders
buy
buy
cd folder4
show_item_properties item1
register_user user1 pass1
create_folder folder5
cd folder3
ls_folders
create_folder folder1
cd folder3
current_folder
rename_user user6 <function generate_user at 0x027087F0>
current_folder
sign_out
buy
add_item_property item2 key1=val7 key2=val1 key10=val8 key10=val9 
current_folder
show_folders
sign_out
whoami
show_item_properties item1
add_item_property item2 key8=val9 key10=val8 key1=val2 key3=val5 
show_folders
sign_in user9 pass9
buy
show_users
put item1
add_item_property item1 key7=val1 key6=val1 key2=val7 key6=val1 
show_users
rename_user user0 <function generate_user at 0x027087F0>
sign_out
create_folder folder2
help show_users
create_folder folder2
cd folder3
ls
pwd
ls_folders
ls
register_user user5 pass5
register_user user1 pass1
show_users
ls
cd folder2
show_items
add_item_property item2 key1=val10 key3=val10 key3=val6 key10=val7 
current_folder
create_folder folder5
show_users
ls
put item1
rename_user user6 <function generate_user at 0x027087F0>
show_items
sign_in user5 pass5
sign_out
rename_user user7 <function generate_user at 0x027087F0>
which_group
whoami
buy
help rename_user
sign_in a3 pa3
register_user admin admin
show_items
register_admin user6 pass6
register_user user5 pass5
show_folders
ls
create_folder folder3
put item2
buy
add_item item5 key2=val7 key6=val5 key7=val6 key2=val3 
buy
register_admin user2 pass2
ls_folders
show_users
help add_item
cd folder5
rename_user user0 <function generate_user at 0x027087F0>
cd folder3
rename_user user7 <function generate_user at 0x027087F0>
cd folder2
current_folder
pwd
sign_in user3 pass3
current_folder
add_item item3 key2=val1 key3=val2 key3=val5 key9=val3 
current_folder
show_folders
help put
show_items
help show_items
sign_in admin admin
sign_out
add_item_property item3 key3=val1 key3=val6 key9=val8 key8=val6 
cd folder5
show_users
ls_folders
ls_folders
show_items
pwd
cd folder1
show_users
register_user user3 pass3
current_folder
show_items
add_item_property item2 key6=val5 key9=val9 key4=val2 key8=val4 
ls
ls
show_items
sign_in a5 pa5
pwd
sign_in user5 pass5
cd folder5
current_folder
show_item_properties item1
which_group
cd folder2
create_folder folder5
show_item_properties item4
pwd
whoami
register_user admin admin
current_folder
show_folders
show_folders
register_admin admin admin
create_folder folder4
whoami
cd folder1
add_item item5 key9=val3 key3=val5 key10=val3 key5=val7 
ls_folders
show_item_properties item3
whoami
register_admin user3 pass3
ls
whoami
rename_user user3 <function generate_user at 0x027087F0>
sign_in user3 pass3
rename_user user4 <function generate_user at 0x027087F0>
ls
current_folder
ls
show_folders
add_item item1 key5=val6 key7=val7 key2=val4 key9=val1 
pwd
buy
help history
sign_out
show_items
put item2
ls_folders
show_folders
ls_folders
register_user user3 pass3
sign_in user9 pass9
sign_in user4 pass4
sign_in user7 pass7
show_item_properties item4
ls
sign_out
show_items
sign_in user6 pass6
buy
which_group
sign_out
buy
ls
ls
put item5
create_folder folder1
whoami
cd folder3
register_user user9 pass9
show_folders
which_group
add_item_property item2 key8=val4 key2=val10 key4=val8 key10=val1 
sign_in a3 pa3
put item2
cd folder1
sign_in a1 pa1
show_items
register_admin user8 pass8
register_user user4 pass4
current_folder
whoami
show_item_properties item2
help pwd
ls_folders
add_item item1 key9=val6 key10=val5 key10=val6 key3=val4 
which_group
show_folders
create_folder folder2
ls_folders
ls_folders
register_admin admin admin
add_item_property item4 key3=val3 key7=val8 key10=val6 key9=val4 
register_user user9 pass9
help show_folders
current_folder
help register_user
show_item_properties item4
put item2
sign_in a5 pa5
whoami
help show_users
cd folder5
rename_user user8 <function generate_user at 0x027087F0>
whoami
show_users
ls_folders
show_item_properties item3
pwd
buy
ls_folders
whoami
sign_out
show_folders
show_folders
whoami
show_items
show_items
put item1
register_admin user6 pass6
create_folder folder4
show_folders
sign_in a2 pa2
ls
sign_out
show_items
show_users
show_items
sign_in user4 pass4
whoami
create_folder folder5
which_group
sign_in user6 pass6
sign_in a3 pa3
ls
sign_in user6 pass6
whoami
help history
ls
cd folder5
which_group
show_items
whoami
show_folders
show_users
sign_in user3 pass3
which_group
sign_in user5 pass5
add_item_property item1 key8=val6 key3=val8 key8=val3 key10=val10 
add_item item4 key5=val10 key4=val4 key8=val3 key9=val7 
register_user user6 pass6
rename_user user7 <function generate_user at 0x027087F0>
ls
show_item_properties item1
ls_folders
sign_in a5 pa5
whoami
sign_in user5 pass5
register_user user4 pass4
current_folder
show_item_properties item1
help show_folders
rename_user user5 <function generate_user at 0x027087F0>
buy
sign_in a4 pa4
create_folder folder1
sign_out
sign_in user5 pass5
ls
whoami
current_folder
buy
show_items
whoami
buy
pwd
register_user user4 pass4
create_folder folder3
show_items
ls
ls_folders
show_users
pwd
show_folders
ls_folders
add_item item4 key8=val6 key7=val9 key1=val9 key7=val5 
show_items
sign_in user9 pass9
add_item_property item5 key2=val7 key4=val7 key4=val4 key1=val6 
cd folder1
sign_in admin admin
show_items
register_admin user5 pass5
current_folder
show_folders
show_item_properties item5
show_items
show_folders
sign_in a3 pa3
help sign_out
add_item item1 key2=val3 key2=val6 key7=val8 key8=val5 
ls_folders
cd folder3
show_items
current_folder
sign_in a4 pa4
show_items
buy
sign_in user6 pass6
sign_in a2 pa2
create_folder folder1
whoami
add_item_property item1 key1=val7 key9=val1 key2=val3 key8=val4 
help view_order
show_users
sign_in a3 pa3
pwd
show_folders
add_item item3 key8=val9 key9=val2 key5=val7 key4=val9 
show_items
add_item item3 key9=val8 key1=val10 key5=val6 key9=val6 
cd folder4
which_group
put item5
sign_in a5 pa5
rename_user user8 <function generate_user at 0x027087F0>
buy
pwd
show_folders
buy
create_folder folder3
cd folder4
help history
register_user user2 pass2
show_item_properties item5
register_admin user2 pass2
register_admin user9 pass9
which_group
whoami
sign_out
register_user user6 pass6
whoami
ls_folders
show_items
add_item_property item1 key3=val6 key5=val10 key4=val10 key1=val5 
whoami
ls_folders
which_group
ls
buy
put item2
show_items
sign_out
show_item_properties item2
sign_in a3 pa3
sign_in user4 pass4
which_group
ls_folders
sign_in a1 pa1
show_users
which_group
show_items
sign_in user4 pass4
show_item_properties item4
current_folder
show_users
sign_out
sign_in a5 pa5
show_users
register_user user3 pass3
add_item item1 key1=val9 key6=val4 key4=val2 key5=val7 
create_folder folder4
create_folder folder5
which_group
current_folder
register_admin user5 pass5
show_items
show_users
register_admin user3 pass3
show_item_properties item2
show_items
ls
whoami
show_folders
help exit
register_user user8 pass8
ls
register_user user2 pass2
rename_user user7 <function generate_user at 0x027087F0>
help show_folders
whoami
pwd
sign_in a2 pa2
put item1
show_items
show_users
ls_folders
sign_in a2 pa2
sign_in a5 pa5
ls
create_folder folder3
sign_in a4 pa4
buy
pwd
whoami
add_item_property item2 key4=val2 key3=val1 key4=val5 key2=val6 
add_item_property item2 key2=val4 key1=val8 key7=val3 key8=val3 
create_folder folder4
sign_in user7 pass7
add_item_property item4 key4=val9 key2=val1 key1=val2 key5=val2 
add_item item1 key8=val7 key7=val5 key3=val6 key6=val7 
which_group
whoami
register_user user5 pass5
sign_in user3 pass3
rename_user user5 <function generate_user at 0x027087F0>
add_item_property item3 key10=val8 key5=val7 key3=val7 key10=val5 
create_folder folder2
show_users
register_admin user7 pass7
help show_folders
ls
put item5
which_group
current_folder
help show_users
show_folders
cd folder4
register_admin admin admin
rename_user user6 <function generate_user at 0x027087F0>
rename_user user2 <function generate_user at 0x027087F0>
show_items
register_user admin admin
sign_in user6 pass6
register_user user7 pass7
show_folders
cd folder3
cd folder1
sign_in a2 pa2
ls_folders
cd folder1
show_users
add_item_property item2 key10=val2 key5=val7 key6=val3 key4=val7 
show_users
create_folder folder3
rename_user user2 <function generate_user at 0x027087F0>
register_user user3 pass3
whoami
show_folders
sign_in a3 pa3
help show_folders
show_items
current_folder
show_item_properties item2
buy
cd folder4
cd folder5
pwd
sign_in user1 pass1
current_folder
buy
rename_user user5 <function generate_user at 0x027087F0>
ls_folders
current_folder
sign_out
ls_folders
register_user user2 pass2
register_admin user5 pass5
show_item_properties item1
register_user user7 pass7
sign_out
pwd
pwd
ls
put item1
show_users
add_item_property item3 key8=val4 key4=val9 key2=val10 key3=val4 
sign_in a5 pa5
create_folder folder1
register_admin user8 pass8
create_folder folder2
show_users
ls
put item4
pwd
show_item_properties item3
pwd
add_item_property item5 key6=val2 key6=val3 key5=val10 key7=val7 
ls_folders
ls_folders
help ls
add_item_property item5 key10=val5 key10=val2 key6=val6 key6=val10 
ls
show_users
put item2
register_user user6 pass6
show_users
current_folder
ls
create_folder folder5
show_users
ls_folders
help ls
add_item_property item4 key9=val10 key1=val8 key9=val4 key2=val1 
show_item_properties item1
create_folder folder3
add_item_property item4 key10=val2 key8=val2 key10=val4 key7=val2 
ls
add_item_property item4 key4=val9 key2=val10 key7=val4 key4=val2 
sign_out
show_item_properties item5
show_folders
show_items
add_item item5 key4=val5 key6=val10 key10=val4 key5=val9 
add_item_property item5 key1=val9 key9=val5 key8=val6 key10=val2 
register_user user8 pass8
ls
sign_out
which_group
show_items
ls
show_item_properties item1
put item4
register_user user9 pass9
which_group
which_group
buy
show_folders
show_folders
put item3
sign_in user6 pass6
show_item_properties item3
ls_folders
whoami
buy
sign_out
whoami
add_item item2 key5=val3 key5=val8 key10=val6 key7=val1 
sign_in a1 pa1
register_user user2 pass2
put item3
rename_user user8 <function generate_user at 0x027087F0>
register_admin user3 pass3
sign_in user9 pass9
show_users
show_users
register_admin user9 pass9
put item2
ls
ls_folders
sign_in user8 pass8
show_users
sign_in a2 pa2
sign_in a5 pa5
cd folder1
put item1
show_item_properties item3
show_users
add_item item4 key1=val7 key6=val2 key3=val2 key10=val10 
pwd
register_user user5 pass5
current_folder
create_folder folder2
sign_in a2 pa2
put item4
ls_folders
create_folder folder1
current_folder
help help
sign_out
ls
create_folder folder5
which_group
which_group
cd folder2
which_group
add_item item4 key3=val9 key8=val1 key5=val6 key7=val2 
add_item item4 key10=val6 key10=val7 key2=val2 key8=val1 
current_folder
show_item_properties item2
sign_out
whoami
create_folder folder5
help buy
cd folder5
which_group
help add_item_property
show_users
current_folder
register_admin user8 pass8
whoami
add_item_property item2 key5=val8 key2=val3 key6=val9 key1=val9 
sign_out
show_item_properties item1
show_folders
sign_in a1 pa1
register_user user3 pass3
cd folder4
put item3
ls
rename_user user3 <function generate_user at 0x027087F0>
sign_in a4 pa4
show_folders
show_item_properties item1
rename_user user9 <function generate_user at 0x027087F0>
sign_in user6 pass6
show_folders
show_item_properties item3
add_item item2 key3=val4 key9=val3 key1=val9 key8=val4 
whoami
show_folders
cd folder4
sign_in user6 pass6
add_item item5 key3=val8 key7=val10 key7=val5 key3=val1 
current_folder
cd folder2
which_group
cd folder2
buy
ls
which_group
sign_in a2 pa2
whoami
show_items
show_items
sign_in a5 pa5
current_folder
help register_user
put item1
cd folder3
show_items
cd folder4
ls
whoami
show_items
put item4
ls_folders
add_item item1 key3=val1 key5=val1 key4=val7 key5=val2 
which_group
buy
show_folders
put item5
create_folder folder1
show_users
cd folder2
pwd
sign_in user2 pass2
buy
add_item_property item5 key8=val8 key9=val6 key7=val8 key5=val8 
help show_users
show_users
whoami
show_users
sign_in user5 pass5
add_item item5 key3=val1 key10=val5 key2=val8 key7=val5 
show_folders
show_folders
sign_in a3 pa3
sign_in user7 pass7
add_item item4 key5=val1 key10=val8 key7=val6 key9=val5 
whoami
sign_in user8 pass8
sign_in user9 pass9
sign_out
sign_out
rename_user user2 <function generate_user at 0x027087F0>
pwd
pwd
put item4
rename_user user7 <function generate_user at 0x027087F0>
show_item_properties item4
add_item item5 key3=val9 key8=val2 key7=val6 key10=val1 
sign_in admin admin
pwd
cd folder3
sign_in a3 pa3
add_item_property item5 key7=val9 key2=val1 key8=val4 key3=val4 
register_user user1 pass1
sign_in user3 pass3
sign_out
register_user user2 pass2
add_item_property item1 key3=val9 key3=val2 key4=val7 key4=val8 
show_items
show_items
which_group
sign_in a3 pa3
ls_folders
show_folders
whoami
show_users
put item1
register_user user4 pass4
show_folders
buy
which_group
whoami
rename_user user9 <function generate_user at 0x027087F0>
register_admin admin admin
add_item item3 key10=val9 key4=val10 key9=val2 key7=val5 
add_item item5 key9=val1 key2=val8 key8=val6 key1=val7 
pwd
add_item_property item5 key10=val2 key8=val10 key4=val1 key2=val6 
rename_user user6 <function generate_user at 0x027087F0>
buy
rename_user user3 <function generate_user at 0x027087F0>
which_group
sign_out
cd folder4
sign_out
show_users
show_folders
current_folder
register_user user4 pass4
put item3
rename_user user5 <function generate_user at 0x027087F0>
show_users
show_item_properties item1
which_group
put item5
whoami
sign_out
ls_folders
cd folder3
show_items
which_group
sign_in user9 pass9
show_item_properties item2
register_admin user1 pass1
whoami
show_users
register_admin admin admin
pwd
add_item_property item3 key8=val5 key4=val1 key2=val9 key7=val1 
which_group
sign_in user8 pass8
rename_user user8 <function generate_user at 0x027087F0>
buy
cd folder3
buy
cd folder4
sign_in a5 pa5
buy
which_group
show_users
add_item_property item2 key9=val10 key2=val9 key4=val9 key9=val9 
sign_out
buy
show_item_properties item3
register_admin user5 pass5
buy
ls_folders
sign_out
register_admin user7 pass7
create_folder folder2
show_folders
create_folder folder2
buy
help sign_in
which_group
whoami
sign_in a3 pa3
show_item_properties item4
current_folder
create_folder folder2
which_group
show_folders
help buy
show_users
sign_in user4 pass4
show_items
register_admin user4 pass4
add_item_property item2 key1=val8 key4=val4 key5=val6 key4=val3 
add_item item1 key8=val9 key8=val5 key5=val10 key6=val2 
register_user user8 pass8
add_item_property item3 key5=val1 key5=val1 key8=val3 key5=val9 
show_folders
rename_user user2 <function generate_user at 0x027087F0>
show_folders
ls
register_user user4 pass4
sign_in a1 pa1
current_folder
register_admin user5 pass5
show_item_properties item1
sign_out
show_users
add_item_property item1 key7=val1 key3=val9 key1=val3 key2=val8 
whoami
create_folder folder5
show_items
pwd
create_folder folder5
buy
cd folder5
help ls
buy
add_item item1 key10=val7 key4=val1 key2=val10 key4=val4 
register_admin user2 pass2
add_item item3 key2=val4 key6=val7 key10=val9 key3=val2 
show_item_properties item2
sign_out
show_users
which_group
current_folder
sign_in a1 pa1
register_admin user6 pass6
which_group
sign_in a1 pa1
which_group
add_item item3 key4=val4 key7=val1 key10=val2 key9=val10 
show_item_properties item3
sign_in user9 pass9
put item3
sign_in a2 pa2
current_folder
pwd
buy
add_item item3 key9=val3 key4=val1 key8=val1 key10=val10 
ls
add_item_property item5 key5=val1 key10=val7 key5=val10 key2=val10 
put item5
sign_in a3 pa3
rename_user user8 <function generate_user at 0x027087F0>
sign_out
add_item item4 key8=val6 key3=val1 key5=val7 key8=val1 
buy
help whoami
which_group
ls_folders
show_item_properties item2
whoami
sign_in user7 pass7
create_folder folder4
help pwd
sign_in user9 pass9
buy
rename_user user9 <function generate_user at 0x027087F0>
cd folder3
current_folder
add_item_property item1 key5=val4 key2=val9 key7=val9 key2=val3 
show_item_properties item2
create_folder folder1
register_user user4 pass4
current_folder
current_folder
pwd
ls
pwd
sign_out
register_admin user2 pass2
sign_in user5 pass5
sign_in user1 pass1
show_item_properties item3
which_group
whoami
ls
ls_folders
put item5
rename_user user7 <function generate_user at 0x027087F0>
rename_user user3 <function generate_user at 0x027087F0>
rename_user user8 <function generate_user at 0x027087F0>
cd folder3
rename_user user5 <function generate_user at 0x027087F0>
whoami
sign_in user6 pass6
pwd
put item3
pwd
cd folder3
help show_folders
help view_order
add_item item5 key3=val9 key7=val3 key9=val10 key10=val6 
pwd
pwd
show_item_properties item1
show_items
create_folder folder5
sign_in admin admin
ls_folders
add_item item1 key8=val8 key2=val5 key10=val6 key10=val6 
register_user user9 pass9
ls
add_item_property item3 key2=val10 key8=val9 key4=val4 key9=val5 
create_folder folder3
create_folder folder4
pwd
show_folders
sign_in user6 pass6
ls
ls_folders
show_items
current_folder
show_items
show_item_properties item5
ls_folders
whoami
add_item_property item3 key2=val10 key9=val8 key6=val1 key7=val2 
ls_folders
current_folder
cd folder1
add_item_property item4 key7=val10 key10=val5 key7=val8 key8=val8 
show_items
show_folders
cd folder5
pwd
current_folder
register_admin user6 pass6
add_item item2 key9=val2 key1=val8 key7=val2 key9=val5 
show_item_properties item1
show_items
whoami
which_group
add_item item1 key6=val1 key2=val6 key10=val1 key5=val10 
show_users
create_folder folder4
help buy
register_admin user3 pass3
current_folder
help register_admin
sign_in a3 pa3
register_admin user2 pass2
show_folders
help buy
show_users
put item5
show_users
register_admin user3 pass3
ls
sign_in user7 pass7
ls_folders
add_item item1 key10=val5 key6=val2 key10=val4 key5=val9 
show_items
pwd
cd folder2
show_item_properties item1
add_item item3 key6=val4 key7=val9 key7=val6 key6=val10 
help ls_folders
ls
show_users
sign_in user4 pass4
rename_user user0 <function generate_user at 0x027087F0>
add_item item1 key3=val6 key1=val8 key1=val2 key5=val5 
sign_in a1 pa1
cd folder5
help add_item
sign_out
buy
sign_in user4 pass4
sign_in a1 pa1
show_users
cd folder1
add_item item5 key8=val7 key6=val4 key7=val6 key4=val10 
rename_user user2 <function generate_user at 0x027087F0>
put item3
put item2
help create_folder
which_group
sign_in user8 pass8
add_item_property item3 key8=val2 key4=val3 key10=val4 key5=val9 
sign_in a5 pa5
sign_in a3 pa3
show_item_properties item2
whoami
show_folders
pwd
sign_out
put item1
help show_items
rename_user user9 <function generate_user at 0x027087F0>
buy
cd folder2
create_folder folder4
show_folders
add_item item5 key8=val9 key10=val8 key5=val8 key8=val1 
sign_in user7 pass7
create_folder folder1
ls
rename_user user1 <function generate_user at 0x027087F0>
pwd
add_item item5 key2=val7 key3=val5 key8=val2 key9=val7 
buy
put item2
put item4
whoami
whoami
ls
show_folders
register_user user6 pass6
buy
sign_in user5 pass5
whoami
show_users
create_folder folder4
buy
add_item_property item3 key1=val5 key2=val1 key4=val4 key10=val10 
add_item item5 key2=val6 key4=val4 key6=val7 key10=val9 
register_admin user3 pass3
show_users
rename_user user1 <function generate_user at 0x027087F0>
sign_in user4 pass4
put item5
ls_folders
add_item item1 key3=val7 key3=val5 key9=val5 key7=val5 
put item3
show_item_properties item2
register_user user1 pass1
show_item_properties item1
add_item item2 key9=val9 key7=val5 key9=val10 key2=val2 
add_item item1 key6=val10 key2=val8 key7=val10 key1=val1 
which_group
register_user user8 pass8
show_items
rename_user user4 <function generate_user at 0x027087F0>
which_group
show_items
sign_in user5 pass5
which_group
sign_in a2 pa2
cd folder5
show_users
add_item item2 key6=val6 key6=val1 key1=val4 key4=val10 
pwd
add_item item3 key6=val4 key7=val3 key8=val10 key10=val10 
put item1
show_users
register_admin user1 pass1
buy
put item2
add_item item1 key1=val8 key3=val7 key3=val4 key2=val8 
add_item item4 key10=val2 key5=val1 key4=val4 key7=val7 
show_item_properties item3
create_folder folder1
ls
ls_folders
sign_out
add_item item5 key5=val10 key2=val5 key4=val2 key1=val9 
buy
sign_in user3 pass3
show_items
ls
which_group
ls
cd folder4
which_group
show_items
current_folder
show_item_properties item2
sign_in a4 pa4
cd folder5
pwd
which_group
put item5
show_item_properties item3
show_folders
which_group
ls_folders
add_item_property item5 key3=val4 key5=val1 key2=val9 key6=val4 
sign_out
buy
ls
help register_admin
show_folders
sign_out
create_folder folder4
create_folder folder4
buy
ls_folders
help view_order
rename_user user1 <function generate_user at 0x027087F0>
sign_out
cd folder3
current_folder
whoami
pwd
show_folders
register_user user7 pass7
rename_user user6 <function generate_user at 0x027087F0>
sign_out
sign_out
sign_in user8 pass8
which_group
sign_in user4 pass4
show_items
ls_folders
show_users
show_item_properties item1
show_item_properties item2
show_users
rename_user user7 <function generate_user at 0x027087F0>
show_items
pwd
register_admin user9 pass9
show_folders
add_item_property item2 key4=val1 key6=val8 key1=val5 key6=val8 
add_item item3 key9=val3 key9=val6 key5=val9 key3=val3 
current_folder
buy
sign_in a5 pa5
show_folders
put item3
sign_in a4 pa4
put item3
which_group
which_group
ls
show_users
register_admin user5 pass5
current_folder
cd folder1
buy
create_folder folder3
register_admin user4 pass4
show_users
register_user user5 pass5
add_item item2 key9=val6 key1=val7 key10=val6 key6=val3 
whoami
sign_in a2 pa2
show_folders
cd folder4
ls_folders
which_group
sign_out
add_item item4 key6=val7 key5=val7 key7=val9 key10=val9 
put item2
rename_user user7 <function generate_user at 0x027087F0>
ls_folders
show_folders
show_users
show_users
sign_in user8 pass8
current_folder
help ls_folders
sign_in a2 pa2
buy
help help
register_user admin admin
sign_in a1 pa1
show_folders
register_user user5 pass5
pwd
rename_user user3 <function generate_user at 0x027087F0>
show_items
which_group
pwd
help which_group
put item3
create_folder folder3
show_folders
ls_folders
put item4
help show_users
cd folder5
show_folders
sign_in a4 pa4
show_users
add_item item1 key2=val1 key10=val4 key7=val5 key7=val2 
show_items
sign_in a5 pa5
cd folder3
whoami
register_user admin admin
buy
show_users
whoami
cd folder4
show_users
which_group
create_folder folder5
put item2
current_folder
pwd
register_admin user1 pass1
put item3
put item5
show_items
rename_user user7 <function generate_user at 0x027087F0>
add_item item4 key6=val9 key3=val8 key4=val3 key5=val2 
which_group
register_user user1 pass1
add_item_property item2 key5=val9 key6=val5 key6=val1 key2=val7 
add_item item2 key9=val9 key10=val9 key3=val8 key2=val4 
show_item_properties item3
pwd
buy
create_folder folder4
show_folders
show_users
register_admin admin admin
register_user user2 pass2
create_folder folder2
whoami
show_items
register_user user6 pass6
sign_out
register_user user7 pass7
put item1
ls
sign_out
add_item_property item2 key1=val10 key10=val7 key7=val9 key5=val6 
register_user user7 pass7
create_folder folder3
cd folder1
show_item_properties item1
register_admin user4 pass4
register_user user8 pass8
show_items
show_users
pwd
which_group
which_group
rename_user user4 <function generate_user at 0x027087F0>
which_group
add_item item4 key3=val2 key6=val2 key2=val8 key8=val7 
show_item_properties item4
show_items
sign_in a1 pa1
create_folder folder1
which_group
put item2
create_folder folder2
cd folder4
register_user user4 pass4
create_folder folder1
add_item_property item2 key3=val7 key1=val3 key7=val5 key4=val2 
ls_folders
ls_folders
sign_in user8 pass8
register_user user4 pass4
which_group
sign_out
pwd
buy
ls
register_user user2 pass2
whoami
put item3
add_item_property item5 key3=val8 key5=val9 key9=val1 key3=val4 
help delete_user
register_user user7 pass7
ls
help ls
sign_in user6 pass6
help register_user
show_items
ls
show_items
show_folders
current_folder
register_user user3 pass3
register_admin user5 pass5
rename_user user2 <function generate_user at 0x027087F0>
ls_folders
help ls_folders
ls_folders
sign_in user1 pass1
sign_out
which_group
show_items
cd folder3
ls_folders
which_group
whoami
current_folder
show_users
sign_in a4 pa4
which_group
pwd
show_item_properties item4
register_admin user9 pass9
register_user user2 pass2
register_admin user5 pass5
sign_out
cd folder5
add_item item5 key6=val9 key5=val1 key8=val3 key6=val3 
which_group
register_user user2 pass2
whoami
ls_folders
rename_user user8 <function generate_user at 0x027087F0>
register_admin user6 pass6
show_item_properties item5
add_item item3 key3=val5 key4=val1 key2=val1 key5=val4 
register_admin user7 pass7
buy
show_items
register_user user6 pass6
buy
show_users
register_user user8 pass8
buy
pwd
add_item_property item4 key1=val7 key4=val7 key9=val8 key1=val6 
add_item_property item5 key9=val2 key10=val6 key7=val4 key3=val10 
cd folder3
show_users
ls_folders
pwd
register_user user2 pass2
help help
help history
show_item_properties item3
whoami
current_folder
add_item item4 key6=val6 key6=val10 key4=val3 key7=val3 
show_items
show_item_properties item1
rename_user user6 <function generate_user at 0x027087F0>
which_group
sign_in user3 pass3
ls_folders
create_folder folder4
show_folders
show_users
register_user user9 pass9
buy
ls
help show_folders
current_folder
cd folder5
pwd
put item4
register_admin user8 pass8
current_folder
which_group
rename_user user6 <function generate_user at 0x027087F0>
rename_user user7 <function generate_user at 0x027087F0>
show_item_properties item3
add_item item3 key8=val6 key8=val7 key1=val8 key4=val6 
ls
add_item_property item3 key3=val2 key1=val3 key3=val3 key5=val8 
buy
ls_folders
show_item_properties item1
sign_in a5 pa5
sign_in admin admin
put item1
show_item_properties item3
show_items
which_group
cd folder2
show_users
rename_user user8 <function generate_user at 0x027087F0>
register_admin user4 pass4
put item2
cd folder1
ls
current_folder
help register_user
show_users
add_item item3 key4=val8 key5=val3 key5=val9 key2=val3 
show_items
show_users
ls
ls
show_users
rename_user user9 <function generate_user at 0x027087F0>
add_item item5 key7=val10 key10=val1 key5=val6 key5=val10 
which_group
show_item_properties item4
register_user user5 pass5
create_folder folder4
add_item item3 key2=val8 key10=val1 key7=val7 key2=val1 
ls
rename_user user8 <function generate_user at 0x027087F0>
ls_folders
whoami
buy
show_folders
ls_folders
sign_out
cd folder4
pwd
ls
help ls_folders
show_item_properties item1
show_item_properties item2
buy
help pwd
register_user admin admin
add_item item1 key1=val4 key8=val1 key7=val6 key5=val10 
current_folder
which_group
buy
add_item item2 key8=val1 key8=val10 key3=val9 key5=val2 
cd folder3
ls
which_group
show_item_properties item3
cd folder4
show_items
sign_out
sign_out
register_user user1 pass1
cd folder3
cd folder1
sign_in admin admin
whoami
sign_in user1 pass1
show_folders
cd folder4
put item3
pwd
which_group
help exit
add_item item1 key7=val7 key3=val4 key8=val1 key8=val2 
sign_in a3 pa3
sign_out
add_item item2 key7=val9 key7=val10 key7=val7 key3=val1 
ls
sign_out
ls
help ls_folders
which_group
show_item_properties item5
show_items
help delete_user
show_items
sign_in user3 pass3
whoami
show_folders
whoami
show_items
ls_folders
ls_folders
add_item item4 key9=val3 key10=val3 key3=val6 key9=val4 
rename_user user2 <function generate_user at 0x027087F0>
create_folder folder5
sign_out
rename_user user0 <function generate_user at 0x027087F0>
add_item_property item2 key3=val6 key6=val9 key10=val6 key7=val1 
cd folder2
current_folder
help register_admin
ls_folders
show_folders
put item4
ls
ls
buy
which_group
sign_out
put item3
create_folder folder1
rename_user user0 <function generate_user at 0x027087F0>
register_user user3 pass3
ls
sign_in a4 pa4
show_item_properties item2
create_folder folder5
cd folder4
pwd
sign_in user7 pass7
cd folder1
sign_in a1 pa1
show_folders
sign_out
ls
pwd
show_folders
add_item item5 key5=val3 key9=val7 key10=val2 key2=val2 
whoami
sign_in a1 pa1
show_users
show_users
register_admin user6 pass6
whoami
which_group
show_folders
rename_user user6 <function generate_user at 0x027087F0>
create_folder folder2
add_item_property item4 key5=val1 key8=val10 key10=val7 key5=val5 
show_item_properties item3
register_admin user1 pass1
whoami
whoami
add_item item4 key3=val9 key9=val2 key6=val3 key6=val5 
ls
add_item_property item2 key3=val8 key10=val6 key1=val8 key5=val2 
sign_in a5 pa5
show_item_properties item4
create_folder folder3
put item5
sign_in user9 pass9
put item5
rename_user user3 <function generate_user at 0x027087F0>
add_item item3 key6=val9 key5=val3 key1=val7 key9=val4 
cd folder5
show_items
sign_out
create_folder folder4
sign_in user2 pass2
cd folder3
ls_folders
add_item_property item2 key4=val2 key9=val9 key9=val3 key9=val1 
current_folder
current_folder
show_users
current_folder
which_group
whoami
sign_out
show_items
sign_out
show_users
which_group
register_user user5 pass5
ls
create_folder folder2
buy
show_folders
show_folders
register_admin user5 pass5
add_item item3 key1=val2 key6=val4 key4=val6 key7=val10 
which_group
sign_in a3 pa3
register_admin user2 pass2
current_folder
cd folder2
put item4
register_admin user8 pass8
which_group
buy
put item2
add_item item5 key8=val10 key3=val9 key5=val6 key1=val8 
sign_in user8 pass8
show_item_properties item4
pwd
sign_in a1 pa1
ls
ls_folders
put item5
put item3
current_folder
rename_user user5 <function generate_user at 0x027087F0>
show_users
ls
show_folders
sign_out
sign_in user7 pass7
whoami
create_folder folder5
sign_in user1 pass1
which_group
whoami
put item2
ls
cd folder5
show_folders
cd folder5
sign_out
register_user user6 pass6
create_folder folder5
create_folder folder5
add_item_property item1 key8=val5 key6=val2 key4=val4 key10=val3 
create_folder folder5
ls
sign_out
whoami
sign_in a1 pa1
sign_in user7 pass7
help add_item
rename_user user6 <function generate_user at 0x027087F0>
sign_out
rename_user user3 <function generate_user at 0x027087F0>
pwd
sign_in a3 pa3
current_folder
rename_user user8 <function generate_user at 0x027087F0>
buy
cd folder3
add_item_property item3 key8=val10 key2=val8 key10=val1 key6=val3 
sign_out
show_users
ls
put item4
put item5
sign_out
which_group
register_user user7 pass7
rename_user user7 <function generate_user at 0x027087F0>
register_admin user5 pass5
current_folder
put item5
add_item item3 key10=val4 key2=val2 key5=val7 key4=val6 
ls
which_group
which_group
help put
ls
sign_in user4 pass4
show_folders
sign_out
buy
show_items
buy
help show_users
pwd
rename_user user7 <function generate_user at 0x027087F0>
show_folders
buy
create_folder folder4
show_items
rename_user user5 <function generate_user at 0x027087F0>
sign_in a5 pa5
register_admin user1 pass1
add_item item1 key7=val2 key10=val9 key6=val5 key8=val9 
add_item item1 key4=val9 key6=val8 key5=val4 key4=val10 
current_folder
rename_user user5 <function generate_user at 0x027087F0>
sign_out
whoami
add_item item1 key4=val2 key9=val9 key2=val5 key10=val2 
pwd
help rename_user
add_item item4 key9=val7 key4=val5 key10=val9 key7=val6 
create_folder folder1
rename_user user4 <function generate_user at 0x027087F0>
register_admin user2 pass2
show_items
help which_group
add_item_property item5 key3=val4 key5=val10 key10=val7 key6=val1 
show_folders
add_item item2 key3=val9 key6=val4 key4=val1 key1=val7 
current_folder
add_item_property item2 key9=val3 key9=val4 key1=val10 key8=val2 
add_item item4 key3=val8 key5=val8 key2=val4 key2=val4 
whoami
sign_in admin admin
show_users
show_item_properties item2
buy
cd folder3
sign_out
add_item item5 key2=val6 key1=val8 key10=val8 key10=val7 
whoami
sign_in user9 pass9
show_item_properties item2
put item4
current_folder
rename_user user4 <function generate_user at 0x027087F0>
show_items
show_items
create_folder folder4
ls
show_folders
buy
show_folders
register_user user5 pass5
sign_out
sign_in user2 pass2
sign_out
create_folder folder3
which_group
current_folder
pwd
add_item_property item2 key8=val8 key8=val7 key3=val10 key6=val1 
show_items
put item2
show_items
rename_user user4 <function generate_user at 0x027087F0>
whoami
which_group
show_folders
create_folder folder5
show_items
show_item_properties item1
whoami
show_item_properties item1
show_items
sign_out
cd folder3
add_item_property item3 key4=val10 key8=val1 key3=val8 key8=val6 
register_admin user7 pass7
cd folder2
show_item_properties item3
register_admin user6 pass6
whoami
ls_folders
put item1
create_folder folder3
pwd
sign_in a4 pa4
sign_out
buy
current_folder
pwd
register_user user4 pass4
whoami
help register_admin
add_item_property item3 key1=val6 key9=val10 key6=val6 key3=val4 
show_items
put item5
buy
register_user user1 pass1
show_item_properties item1
show_users
register_user user6 pass6
add_item_property item3 key8=val6 key10=val10 key3=val9 key8=val1 
sign_in a1 pa1
register_user user8 pass8
cd folder3
show_items
ls_folders
sign_in a2 pa2
whoami
whoami
register_admin user9 pass9
register_user user2 pass2
rename_user user1 <function generate_user at 0x027087F0>
create_folder folder4
show_items
show_folders
show_folders
show_folders
cd folder3
sign_in a2 pa2
ls_folders
which_group
show_items
ls_folders
put item4
help add_item_property
create_folder folder5
ls_folders
buy
register_admin user8 pass8
create_folder folder5
put item5
ls_folders
buy
current_folder
ls
show_item_properties item3
sign_in user8 pass8
put item2
register_user admin admin
sign_out
show_users
put item5
sign_in a1 pa1
help delete_user
ls_folders
sign_out
sign_in a5 pa5
pwd
whoami
show_folders
sign_in a3 pa3
sign_out
whoami
current_folder
sign_in a4 pa4
ls
sign_in a3 pa3
create_folder folder1
pwd
ls
register_user user4 pass4
sign_in a1 pa1
whoami
put item1
show_items
show_users
show_folders
register_user user3 pass3
show_folders
rename_user user2 <function generate_user at 0x027087F0>
pwd
rename_user user1 <function generate_user at 0x027087F0>
add_item item4 key10=val5 key6=val8 key4=val6 key5=val8 
add_item item3 key4=val9 key6=val8 key10=val10 key8=val7 
show_item_properties item2
show_folders
whoami
sign_out
sign_in a1 pa1
ls
show_folders
ls
add_item item4 key8=val7 key2=val9 key2=val10 key10=val6 
sign_out
pwd
put item3
show_folders
cd folder1
help rename_user
show_folders
current_folder
ls
which_group
ls_folders
pwd
ls
add_item_property item4 key4=val5 key6=val10 key7=val9 key6=val2 
current_folder
sign_in user4 pass4
register_user user4 pass4
add_item_property item3 key8=val3 key1=val8 key10=val2 key10=val5 
help create_folder
ls
add_item_property item5 key2=val2 key4=val10 key3=val3 key2=val3 
sign_in user2 pass2
create_folder folder4
create_folder folder2
sign_in a5 pa5
register_admin user7 pass7
which_group
show_item_properties item5
show_items
cd folder3
show_users
show_items
cd folder1
show_folders
add_item item3 key9=val5 key10=val5 key1=val1 key10=val10 
help sign_out
pwd
pwd
rename_user user9 <function generate_user at 0x027087F0>
show_item_properties item4
create_folder folder5
help create_folder
add_item_property item2 key3=val6 key1=val10 key1=val9 key4=val9 
show_folders
ls_folders
sign_out
cd folder1
show_users
cd folder1
register_admin user1 pass1
help show_items
sign_in user7 pass7
create_folder folder3
help create_folder
register_user admin admin
sign_in user8 pass8
buy
current_folder
register_user user4 pass4
current_folder
sign_out
add_item item5 key10=val4 key6=val3 key2=val6 key7=val8 
buy
add_item item2 key5=val1 key4=val5 key5=val3 key1=val9 
sign_in user9 pass9
show_users
register_admin user2 pass2
create_folder folder5
register_user user9 pass9
show_items
show_items
sign_out
show_folders
rename_user user6 <function generate_user at 0x027087F0>
register_admin user5 pass5
sign_in a3 pa3
pwd
help delete_user
add_item_property item4 key9=val3 key4=val3 key8=val4 key8=val7 
rename_user user0 <function generate_user at 0x027087F0>
sign_in user7 pass7
which_group
create_folder folder5
add_item_property item1 key8=val2 key7=val8 key5=val2 key1=val1 
sign_out
create_folder folder2
add_item item1 key6=val9 key9=val5 key1=val4 key9=val2 
put item1
add_item item1 key10=val4 key9=val4 key2=val6 key6=val2 
rename_user user0 <function generate_user at 0x027087F0>
show_items
pwd
show_folders
show_items
sign_in user8 pass8
current_folder
pwd
current_folder
which_group
sign_in user4 pass4
show_item_properties item4
help history
whoami
cd folder3
show_folders
put item4
pwd
sign_in a1 pa1
sign_in a3 pa3
show_item_properties item5
add_item item3 key9=val6 key3=val10 key10=val2 key9=val8 
add_item_property item5 key10=val10 key3=val9 key2=val7 key5=val4 
show_users
whoami
register_user user6 pass6
rename_user user5 <function generate_user at 0x027087F0>
show_users
current_folder
show_users
ls
which_group
pwd
current_folder
whoami
add_item item3 key5=val1 key3=val5 key7=val10 key4=val6 
show_users
whoami
show_users
register_admin user7 pass7
show_item_properties item2
create_folder folder1
register_admin user6 pass6
put item1
ls
create_folder folder3
help sign_out
register_admin user6 pass6
cd folder3
sign_in user1 pass1
register_admin user6 pass6
ls_folders
show_folders
buy
cd folder3
sign_in a5 pa5
current_folder
rename_user user4 <function generate_user at 0x027087F0>
pwd
add_item_property item3 key1=val4 key4=val10 key4=val9 key7=val3 
add_item_property item2 key8=val8 key5=val5 key7=val5 key10=val9 
register_admin user6 pass6
show_folders
ls
ls_folders
help put
help put
show_items
help sign_out
register_user user1 pass1
sign_in user5 pass5
show_users
ls_folders
show_folders
sign_in a2 pa2
show_folders
show_users
pwd
whoami
help help
put item1
rename_user user1 <function generate_user at 0x027087F0>
sign_in user1 pass1
sign_in user1 pass1
sign_in a5 pa5
current_folder
register_user user2 pass2
rename_user user0 <function generate_user at 0x027087F0>
ls_folders
show_item_properties item2
current_folder
register_admin user8 pass8
add_item item1 key1=val9 key4=val9 key8=val2 key9=val9 
rename_user user6 <function generate_user at 0x027087F0>
show_item_properties item5
put item5
whoami
whoami
sign_out
show_folders
sign_in a4 pa4
put item4
show_users
add_item_property item4 key1=val1 key2=val8 key6=val1 key3=val4 
show_users
put item1
rename_user user4 <function generate_user at 0x027087F0>
whoami
add_item item5 key10=val9 key6=val4 key7=val2 key2=val5 
register_admin user4 pass4
register_admin user8 pass8
ls_folders
sign_in a3 pa3
show_items
register_admin user8 pass8
help exit
show_users
register_user user3 pass3
register_admin admin admin
sign_in user8 pass8
show_items
pwd
buy
sign_out
create_folder folder4
show_item_properties item4
add_item_property item3 key2=val10 key1=val10 key6=val8 key10=val8 
show_items
put item4
which_group
show_folders
add_item_property item3 key8=val9 key10=val4 key5=val7 key5=val6 
ls_folders
put item2
cd folder5
add_item_property item4 key8=val8 key10=val3 key10=val10 key7=val3 
show_folders
register_admin user2 pass2
register_admin user9 pass9
sign_in user5 pass5
cd folder1
help register_user
whoami
add_item_property item3 key9=val2 key5=val2 key8=val6 key3=val2 
show_folders
create_folder folder3
sign_out
ls_folders
add_item_property item1 key8=val8 key7=val4 key9=val5 key9=val2 
sign_out
help which_group
cd folder3
show_items
whoami
ls_folders
show_items
rename_user user3 <function generate_user at 0x027087F0>
ls
add_item_property item3 key5=val6 key8=val10 key7=val7 key4=val7 
help current_folder
show_item_properties item1
register_admin user3 pass3
register_user user2 pass2
sign_in a4 pa4
show_item_properties item2
show_folders
sign_out
cd folder4
whoami
create_folder folder3
ls
create_folder folder3
cd folder5
register_admin user4 pass4
cd folder1
rename_user user8 <function generate_user at 0x027087F0>
buy
show_item_properties item2
show_folders
ls_folders
sign_in a1 pa1
sign_in user7 pass7
show_users
buy
current_folder
show_folders
cd folder1
buy
help add_item_property
put item1
add_item_property item3 key1=val4 key4=val9 key1=val1 key7=val6 
add_item item4 key8=val7 key3=val7 key1=val5 key2=val5 
help ls
sign_in user6 pass6
sign_in a5 pa5
add_item_property item5 key3=val4 key7=val2 key8=val10 key9=val10 
show_folders
whoami
ls_folders
rename_user user2 <function generate_user at 0x027087F0>
pwd
cd folder1
sign_in a1 pa1
show_item_properties item5
show_items
sign_out
rename_user user7 <function generate_user at 0x027087F0>
register_user user5 pass5
add_item item1 key1=val9 key1=val5 key4=val6 key9=val10 
register_admin user6 pass6
ls_folders
rename_user user9 <function generate_user at 0x027087F0>
sign_in user6 pass6
put item3
create_folder folder1
ls_folders
register_admin user7 pass7
rename_user user9 <function generate_user at 0x027087F0>
register_admin user7 pass7
register_user user6 pass6
current_folder
ls_folders
show_items
buy
which_group
add_item_property item4 key7=val9 key7=val1 key8=val9 key8=val3 
which_group
buy
register_user user1 pass1
create_folder folder3
current_folder
show_item_properties item5
sign_in a1 pa1
ls_folders
whoami
cd folder4
ls
sign_out
ls
add_item item5 key10=val4 key3=val3 key6=val5 key2=val8 
current_folder
show_item_properties item5
show_users
rename_user user2 <function generate_user at 0x027087F0>
sign_out
show_item_properties item1
show_folders
show_users
current_folder
ls_folders
sign_out
ls
ls_folders
rename_user user2 <function generate_user at 0x027087F0>
help history
put item5
create_folder folder2
sign_out
ls
whoami
sign_in a5 pa5
register_user user6 pass6
show_folders
register_admin user8 pass8
sign_in user9 pass9
current_folder
show_users
show_users
help add_item
buy
buy
show_folders
add_item item4 key4=val6 key1=val7 key7=val10 key6=val5 
buy
sign_in a5 pa5
show_item_properties item5
create_folder folder5
which_group
show_folders
ls_folders
sign_in user1 pass1
rename_user user7 <function generate_user at 0x027087F0>
sign_in user9 pass9
current_folder
help rename_user
put item3
sign_in a3 pa3
show_users
show_items
sign_in admin admin
show_items
buy
ls
whoami
add_item item4 key4=val6 key9=val4 key6=val1 key8=val4 
buy
rename_user user6 <function generate_user at 0x027087F0>
register_admin user2 pass2
which_group
buy
create_folder folder5
register_user user2 pass2
whoami
add_item_property item2 key9=val9 key6=val7 key9=val1 key4=val5 
whoami
show_items
add_item item4 key4=val5 key10=val10 key9=val7 key10=val5 
cd folder1
show_folders
sign_in a1 pa1
register_admin user9 pass9
sign_out
sign_out
pwd
whoami
register_user user1 pass1
sign_out
rename_user user0 <function generate_user at 0x027087F0>
pwd
show_items
put item3
pwd
current_folder
show_items
help sign_in
whoami
pwd
sign_in user3 pass3
rename_user user8 <function generate_user at 0x027087F0>
show_folders
register_user user7 pass7
sign_in admin admin
register_admin user8 pass8
help delete_user
which_group
show_item_properties item1
cd folder5
show_folders
whoami
show_item_properties item2
which_group
add_item_property item3 key5=val5 key6=val2 key6=val6 key2=val3 
sign_out
sign_out
show_users
ls
register_user user7 pass7
add_item item4 key6=val3 key7=val4 key6=val3 key6=val10 
show_items
whoami
put item5
buy
rename_user user8 <function generate_user at 0x027087F0>
show_folders
whoami
show_items
show_folders
add_item item1 key3=val10 key9=val10 key7=val2 key5=val1 
whoami
sign_in a1 pa1
add_item item2 key10=val10 key8=val9 key7=val10 key2=val10 
add_item item3 key3=val9 key8=val7 key7=val7 key10=val8 
help sign_out
show_folders
add_item item2 key10=val8 key10=val7 key1=val3 key5=val6 
help which_group
put item2
sign_in user6 pass6
put item5
add_item item2 key1=val6 key6=val3 key6=val2 key6=val3 
whoami
register_admin user2 pass2
show_item_properties item1
sign_in user8 pass8
sign_out
register_admin user1 pass1
show_folders
current_folder
rename_user user5 <function generate_user at 0x027087F0>
add_item_property item5 key9=val1 key2=val2 key5=val6 key10=val6 
show_users
sign_in user9 pass9
show_item_properties item1
show_users
whoami
show_folders
show_users
pwd
register_admin user5 pass5
sign_in user1 pass1
create_folder folder4
whoami
which_group
current_folder
show_item_properties item4
cd folder4
add_item item4 key7=val10 key5=val4 key5=val7 key10=val9 
cd folder3
sign_in user6 pass6
cd folder3
current_folder
add_item_property item5 key1=val8 key10=val3 key4=val2 key9=val5 
pwd
create_folder folder3
pwd
register_user admin admin
create_folder folder1
sign_out
sign_in a5 pa5
rename_user user4 <function generate_user at 0x027087F0>
pwd
add_item item1 key10=val3 key5=val9 key4=val2 key10=val7 
current_folder
ls
ls
which_group
which_group
register_user user3 pass3
ls
put item5
buy
ls
sign_in a1 pa1
sign_in a1 pa1
ls
sign_in user4 pass4
register_admin user8 pass8
rename_user user8 <function generate_user at 0x027087F0>
sign_out
add_item item3 key2=val4 key2=val10 key3=val5 key10=val9 
add_item item1 key7=val1 key2=val9 key10=val3 key7=val6 
which_group
which_group
sign_out
cd folder1
show_users
sign_out
ls_folders
show_items
add_item_property item4 key7=val9 key1=val2 key4=val10 key8=val3 
add_item_property item5 key9=val10 key10=val10 key7=val3 key5=val7 
current_folder
ls
ls
rename_user user8 <function generate_user at 0x027087F0>
cd folder3
sign_in a5 pa5
sign_out
add_item item2 key3=val1 key5=val3 key8=val5 key1=val8 
sign_in user3 pass3
show_items
create_folder folder1
register_admin user5 pass5
add_item_property item2 key2=val10 key3=val1 key3=val7 key8=val9 
show_items
show_item_properties item4
pwd
which_group
which_group
add_item item5 key1=val3 key3=val1 key7=val8 key1=val6 
rename_user user3 <function generate_user at 0x027087F0>
ls
pwd
show_items
put item4
whoami
add_item_property item4 key10=val2 key1=val7 key10=val7 key5=val5 
put item1
show_users
register_user user6 pass6
cd folder4
sign_in a1 pa1
whoami
show_folders
ls
whoami
buy
put item4
create_folder folder2
show_items
cd folder1
which_group
which_group
register_admin user8 pass8
sign_out
rename_user user5 <function generate_user at 0x027087F0>
add_item item1 key10=val2 key5=val1 key10=val7 key3=val7 
which_group
buy
ls
register_user user7 pass7
add_item item5 key10=val10 key2=val8 key2=val4 key2=val9 
show_users
register_user user4 pass4
register_admin admin admin
register_user user4 pass4
sign_out
put item1
sign_out
help exit
current_folder
sign_out
rename_user user7 <function generate_user at 0x027087F0>
sign_out
show_items
cd folder5
register_admin user3 pass3
show_items
which_group
show_item_properties item4
put item2
register_user user5 pass5
add_item_property item3 key9=val7 key9=val7 key3=val6 key9=val4 
add_item_property item1 key4=val7 key1=val1 key5=val5 key3=val5 
sign_in user8 pass8
register_user user7 pass7
add_item item2 key7=val9 key7=val6 key5=val2 key4=val7 
buy
current_folder
which_group
register_admin admin admin
which_group
show_users
current_folder
rename_user user3 <function generate_user at 0x027087F0>
pwd
put item5
cd folder5
ls_folders
help register_user
pwd
show_items
pwd
ls
create_folder folder4
current_folder
ls
register_admin user4 pass4
current_folder
rename_user user1 <function generate_user at 0x027087F0>
pwd
current_folder
rename_user user8 <function generate_user at 0x027087F0>
create_folder folder3
whoami
add_item item4 key6=val7 key8=val3 key2=val3 key5=val3 
add_item_property item2 key4=val1 key2=val6 key9=val7 key5=val3 
rename_user user2 <function generate_user at 0x027087F0>
buy
sign_out
show_users
ls_folders
pwd
put item5
show_users
add_item item4 key5=val2 key10=val2 key5=val3 key6=val6 
cd folder3
help history
sign_in user4 pass4
ls_folders
sign_in a5 pa5
add_item_property item4 key3=val9 key6=val2 key4=val4 key5=val5 
ls_folders
register_user user3 pass3
cd folder5
show_item_properties item1
buy
buy
pwd
ls
sign_in a4 pa4
put item1
sign_in a2 pa2
ls_folders
current_folder
register_user user9 pass9
put item3
show_item_properties item4
which_group
sign_in a3 pa3
current_folder
create_folder folder2
register_admin user9 pass9
add_item_property item3 key8=val4 key3=val7 key10=val8 key5=val3 
cd folder3
pwd
current_folder
create_folder folder1
sign_in a3 pa3
help help
create_folder folder3
sign_in a2 pa2
ls
register_user user1 pass1
show_item_properties item1
show_items
current_folder
show_items
register_user user5 pass5
ls_folders
ls_folders
show_item_properties item1
sign_in a5 pa5
help sign_in
sign_out
pwd
pwd
whoami
sign_out
sign_in admin admin
show_items
register_user user9 pass9
which_group
sign_in a2 pa2
buy
ls
pwd
sign_in a4 pa4
sign_out
show_users
show_users
pwd
show_users
buy
rename_user user4 <function generate_user at 0x027087F0>
cd folder1
ls
sign_in a5 pa5
register_user user4 pass4
which_group
pwd
help register_admin
register_user user2 pass2
current_folder
show_users
show_items
show_items
show_items
buy
ls_folders
create_folder folder3
add_item_property item5 key2=val10 key10=val5 key1=val1 key8=val1 
cd folder4
show_item_properties item5
register_admin user8 pass8
rename_user user1 <function generate_user at 0x027087F0>
whoami
help view_order
help exit
ls
create_folder folder2
sign_in a3 pa3
add_item_property item4 key7=val3 key4=val3 key8=val3 key5=val1 
buy
whoami
register_user user5 pass5
show_items
buy
sign_out
show_users
sign_in a3 pa3
show_users
buy
help sign_in
sign_in a2 pa2
current_folder
add_item_property item2 key5=val7 key3=val10 key4=val7 key6=val6 
show_folders
register_admin user3 pass3
sign_out
sign_out
which_group
sign_in user8 pass8
add_item_property item2 key3=val10 key2=val5 key10=val7 key10=val6 
whoami
create_folder folder3
whoami
show_folders
put item3
put item2
show_users
register_admin user7 pass7
which_group
register_admin admin admin
show_item_properties item5
put item4
show_folders
sign_in user6 pass6
show_users
sign_out
whoami
sign_in user4 pass4
whoami
show_folders
sign_out
register_user user6 pass6
add_item item4 key5=val9 key5=val6 key10=val8 key9=val6 
ls
pwd
cd folder2
ls
show_item_properties item1
whoami
sign_in a4 pa4
cd folder1
register_user user6 pass6
register_admin user2 pass2
sign_out
sign_in a3 pa3
register_admin user5 pass5
which_group
rename_user user5 <function generate_user at 0x027087F0>
register_user admin admin
sign_out
add_item item2 key7=val6 key1=val9 key3=val5 key10=val5 
sign_in a4 pa4
show_users
buy
sign_out
cd folder2
show_item_properties item2
ls_folders
create_folder folder1
add_item_property item2 key5=val5 key3=val9 key2=val8 key4=val6 
ls_folders
rename_user user5 <function generate_user at 0x027087F0>
show_users
help add_item
show_users
cd folder2
show_folders
sign_in a4 pa4
show_items
which_group
rename_user user8 <function generate_user at 0x027087F0>
buy
buy
ls_folders
sign_in a2 pa2
current_folder
add_item_property item1 key1=val1 key9=val5 key6=val7 key7=val10 
add_item item3 key9=val1 key9=val5 key6=val8 key7=val4 
ls_folders
create_folder folder4
show_items
sign_out
add_item_property item3 key4=val2 key6=val6 key9=val10 key5=val6 
cd folder4
create_folder folder3
register_admin user2 pass2
show_users
sign_in a3 pa3
sign_in user5 pass5
show_items
cd folder4
show_folders
show_users
which_group
sign_in a4 pa4
whoami
register_user user9 pass9
put item4
ls_folders
sign_in user6 pass6
register_user user2 pass2
show_item_properties item5
create_folder folder2
current_folder
whoami
pwd
add_item item1 key5=val10 key1=val7 key2=val6 key10=val4 
show_folders
help create_folder
cd folder3
buy
create_folder folder3
pwd
ls_folders
whoami
help register_admin
help add_item_property
sign_in a5 pa5
help history
cd folder5
create_folder folder1
sign_in a3 pa3
show_item_properties item2
current_folder
add_item_property item2 key10=val1 key5=val9 key5=val8 key2=val7 
ls
ls
sign_in a5 pa5
register_admin user1 pass1
show_items
ls
which_group
create_folder folder1
create_folder folder5
rename_user user0 <function generate_user at 0x027087F0>
help register_admin
show_users
help history
show_item_properties item5
rename_user user1 <function generate_user at 0x027087F0>
show_item_properties item5
add_item item4 key4=val9 key2=val7 key9=val5 key3=val4 
register_admin user9 pass9
show_users
ls_folders
register_user user6 pass6
add_item_property item3 key10=val6 key7=val6 key1=val4 key6=val4 
create_folder folder5
help show_items
help history
cd folder2
show_items
ls_folders
rename_user user3 <function generate_user at 0x027087F0>
buy
create_folder folder1
show_folders
register_admin user5 pass5
add_item_property item1 key2=val5 key2=val9 key6=val2 key3=val7 
add_item item2 key8=val7 key1=val2 key9=val5 key6=val7 
create_folder folder4
help register_user
buy
put item4
create_folder folder2
show_users
show_items
help sign_out
sign_out
put item4
whoami
show_users
buy
register_admin user8 pass8
add_item_property item1 key3=val2 key9=val10 key4=val2 key7=val9 
rename_user user2 <function generate_user at 0x027087F0>
create_folder folder2
sign_out
show_users
register_admin user8 pass8
show_folders
help sign_in
pwd
buy
rename_user user0 <function generate_user at 0x027087F0>
buy
add_item_property item3 key1=val2 key3=val2 key6=val10 key5=val5 
cd folder2
help help
pwd
add_item_property item3 key7=val3 key5=val6 key1=val6 key4=val8 
put item1
rename_user user7 <function generate_user at 0x027087F0>
show_folders
register_user user9 pass9
register_admin user6 pass6
sign_out
add_item_property item4 key8=val7 key9=val3 key3=val1 key10=val2 
register_admin user8 pass8
ls
current_folder
register_user user1 pass1
help exit
register_user user1 pass1
create_folder folder5
add_item item5 key3=val7 key3=val5 key6=val2 key6=val8 
create_folder folder3
add_item item5 key2=val5 key9=val7 key5=val3 key7=val3 
rename_user user6 <function generate_user at 0x027087F0>
add_item item3 key4=val4 key6=val3 key6=val4 key3=val4 
sign_in a1 pa1
rename_user user0 <function generate_user at 0x027087F0>
rename_user user2 <function generate_user at 0x027087F0>
buy
sign_in a5 pa5
put item5
buy
create_folder folder1
pwd
sign_in admin admin
buy
sign_in admin admin
cd folder2
show_folders
current_folder
current_folder
sign_in user4 pass4
sign_in user6 pass6
register_user user7 pass7
whoami
add_item_property item3 key7=val4 key10=val9 key7=val6 key8=val7 
help show_item_properties
help show_items
add_item_property item2 key9=val7 key3=val10 key6=val8 key4=val8 
ls
show_folders
add_item_property item3 key6=val7 key1=val1 key8=val4 key2=val3 
show_items
sign_in a3 pa3
register_user user7 pass7
whoami
buy
sign_in user6 pass6
show_items
register_admin user1 pass1
show_users
register_admin user2 pass2
register_user user4 pass4
add_item_property item3 key5=val2 key9=val3 key1=val9 key1=val6 
sign_in a2 pa2
sign_in a2 pa2
which_group
ls_folders
cd folder4
buy
pwd
which_group
help show_items
create_folder folder1
register_admin user2 pass2
sign_in a3 pa3
show_item_properties item1
pwd
create_folder folder5
ls_folders
show_item_properties item4
current_folder
cd folder3
register_user user2 pass2
add_item_property item1 key4=val10 key7=val8 key7=val8 key3=val1 
put item4
sign_out
whoami
show_folders
cd folder1
sign_in user3 pass3
ls
show_item_properties item1
register_user user4 pass4
show_items
help sign_in
ls
sign_in user7 pass7
add_item item2 key10=val8 key8=val6 key5=val3 key4=val1 
sign_out
ls
buy
ls_folders
show_users
add_item item5 key5=val1 key4=val3 key4=val6 key10=val1 
pwd
cd folder2
show_users
rename_user user4 <function generate_user at 0x027087F0>
create_folder folder4
sign_out
create_folder folder2
put item3
sign_out
show_users
buy
rename_user user9 <function generate_user at 0x027087F0>
sign_out
pwd
cd folder5
sign_in a5 pa5
help put
put item3
register_admin user1 pass1
register_admin user5 pass5
which_group
ls
sign_in user4 pass4
pwd
show_folders
sign_in a5 pa5
current_folder
rename_user user7 <function generate_user at 0x027087F0>
show_folders
buy
sign_out
rename_user user9 <function generate_user at 0x027087F0>
add_item_property item4 key5=val5 key10=val3 key4=val10 key9=val4 
rename_user user9 <function generate_user at 0x027087F0>
register_user user2 pass2
show_item_properties item4
buy
current_folder
sign_in user9 pass9
sign_in user7 pass7
rename_user user2 <function generate_user at 0x027087F0>
ls_folders
help history
ls_folders
register_admin user1 pass1
rename_user user6 <function generate_user at 0x027087F0>
sign_out
add_item item5 key8=val2 key10=val2 key8=val2 key5=val6 
add_item item3 key4=val4 key5=val8 key7=val2 key1=val7 
show_users
sign_in user4 pass4
sign_in a1 pa1
add_item item4 key10=val6 key8=val10 key7=val7 key9=val8 
put item3
add_item item4 key1=val10 key4=val7 key4=val4 key9=val8 
sign_out
put item2
put item2
pwd
show_item_properties item5
add_item_property item4 key7=val2 key9=val2 key1=val10 key4=val9 
add_item item3 key6=val10 key4=val8 key3=val10 key6=val9 
show_folders
ls
add_item_property item4 key7=val1 key3=val7 key4=val5 key9=val6 
sign_in a5 pa5
sign_in a5 pa5
show_folders
sign_out
add_item_property item2 key7=val8 key2=val1 key3=val3 key1=val1 
show_items
create_folder folder1
create_folder folder1
create_folder folder4
show_item_properties item1
which_group
add_item_property item4 key7=val9 key10=val8 key7=val9 key3=val5 
current_folder
buy
ls
buy
buy
add_item item5 key1=val10 key7=val8 key7=val9 key3=val8 
pwd
ls
ls_folders
rename_user user2 <function generate_user at 0x027087F0>
create_folder folder4
ls
ls
ls_folders
sign_in a5 pa5
add_item item4 key5=val2 key4=val4 key2=val6 key7=val10 
current_folder
buy
register_user user6 pass6
which_group
show_users
which_group
show_users
cd folder1
ls
add_item item5 key10=val6 key1=val3 key5=val5 key1=val6 
buy
cd folder4
ls_folders
put item4
add_item_property item5 key8=val8 key2=val10 key10=val2 key7=val3 
add_item_property item3 key1=val6 key5=val4 key2=val6 key5=val2 
add_item_property item5 key6=val10 key5=val1 key6=val8 key6=val2 
add_item item5 key6=val5 key6=val1 key8=val2 key3=val8 
ls_folders
buy
register_admin user4 pass4
buy
current_folder
ls_folders
register_admin user9 pass9
sign_out
register_admin user1 pass1
sign_in user2 pass2
rename_user user4 <function generate_user at 0x027087F0>
sign_in user7 pass7
show_users
show_users
show_item_properties item1
register_admin admin admin
show_folders
create_folder folder4
sign_in a3 pa3
current_folder
show_item_properties item1
ls
cd folder4
show_users
sign_out
put item1
show_items
pwd
pwd
add_item_property item4 key5=val4 key4=val10 key4=val9 key3=val8 
register_user user2 pass2
current_folder
buy
show_users
sign_in user8 pass8
cd folder4
sign_in a5 pa5
add_item item2 key5=val7 key1=val8 key2=val10 key7=val3 
whoami
create_folder folder3
pwd
whoami
put item3
register_admin user4 pass4
add_item_property item2 key8=val9 key1=val7 key7=val2 key3=val5 
add_item_property item2 key9=val3 key10=val2 key7=val7 key6=val1 
show_users
current_folder
ls
help show_items
put item3
pwd
sign_out
show_item_properties item1
add_item item2 key2=val4 key1=val5 key2=val8 key5=val3 
show_folders
add_item item2 key4=val9 key1=val10 key10=val6 key7=val10 
show_items
whoami
help whoami
add_item item1 key2=val4 key6=val5 key3=val3 key7=val2 
whoami
register_admin user9 pass9
register_admin user9 pass9
sign_out
show_users
put item3
which_group
current_folder
sign_out
add_item item5 key9=val6 key3=val10 key7=val8 key8=val3 
add_item item5 key8=val9 key3=val3 key2=val1 key10=val8 
put item4
register_user user4 pass4
current_folder
current_folder
help delete_user
which_group
show_items
create_folder folder4
buy
add_item item5 key10=val5 key6=val10 key7=val10 key4=val2 
show_folders
register_user user2 pass2
ls
show_folders
create_folder folder5
cd folder4
ls_folders
create_folder folder3
help current_folder
show_item_properties item1
sign_in user1 pass1
add_item_property item3 key4=val9 key1=val9 key1=val3 key10=val6 
show_folders
cd folder1
which_group
show_item_properties item4
ls
rename_user user8 <function generate_user at 0x027087F0>
show_item_properties item1
register_admin user7 pass7
help buy
add_item_property item3 key3=val1 key8=val9 key5=val3 key3=val6 
show_users
sign_in user4 pass4
show_users
sign_out
pwd
help pwd
current_folder
create_folder folder4
ls_folders
buy
register_admin user8 pass8
buy
whoami
sign_in a1 pa1
add_item_property item2 key8=val5 key8=val5 key10=val7 key9=val8 
current_folder
pwd
which_group
which_group
ls
put item5
ls
rename_user user2 <function generate_user at 0x027087F0>
which_group
create_folder folder4
register_user user8 pass8
which_group
show_users
register_admin user4 pass4
sign_in user2 pass2
sign_in a2 pa2
cd folder1
which_group
put item3
sign_out
put item2
help buy
show_item_properties item3
show_users
show_users
add_item_property item5 key3=val9 key7=val5 key5=val8 key5=val4 
sign_in a5 pa5
show_users
ls
register_admin admin admin
cd folder1
which_group
which_group
cd folder5
ls_folders
add_item item1 key4=val4 key6=val3 key6=val7 key9=val4 
sign_out
add_item_property item4 key5=val6 key1=val8 key1=val10 key5=val2 
put item5
sign_in user7 pass7
sign_out
pwd
cd folder2
register_user user7 pass7
register_user user4 pass4
show_item_properties item3
buy
sign_out
rename_user user5 <function generate_user at 0x027087F0>
create_folder folder5
pwd
current_folder
put item1
whoami
show_folders
sign_out
cd folder5
sign_in a2 pa2
register_user user4 pass4
ls
current_folder
create_folder folder4
rename_user user4 <function generate_user at 0x027087F0>
show_users
which_group
sign_in a3 pa3
cd folder4
show_folders
sign_in user2 pass2
buy
register_admin user2 pass2
show_items
add_item item5 key10=val7 key8=val8 key2=val8 key9=val4 
rename_user user9 <function generate_user at 0x027087F0>
pwd
sign_in a5 pa5
show_items
create_folder folder2
rename_user user4 <function generate_user at 0x027087F0>
add_item item5 key4=val2 key4=val3 key3=val3 key1=val2 
show_folders
ls_folders
show_item_properties item1
register_admin user5 pass5
ls
put item3
which_group
sign_out
help sign_out
register_user user1 pass1
ls_folders
register_user user4 pass4
buy
put item1
buy
help register_admin
sign_out
help register_admin
add_item_property item4 key4=val3 key8=val8 key3=val9 key6=val3 
help register_admin
whoami
sign_in user4 pass4
help pwd
buy
put item4
rename_user user2 <function generate_user at 0x027087F0>
add_item_property item2 key10=val1 key1=val4 key3=val9 key2=val4 
show_item_properties item4
register_admin user7 pass7
help whoami
show_folders
ls_folders
add_item_property item3 key9=val1 key10=val6 key7=val5 key7=val2 
help create_folder
current_folder
rename_user user7 <function generate_user at 0x027087F0>
ls
show_items
help show_users
show_folders
sign_out
sign_out
register_user user9 pass9
show_folders
whoami
create_folder folder5
pwd
show_items
whoami
show_items
show_users
show_item_properties item5
buy
pwd
show_items
show_items
put item3
add_item_property item5 key4=val1 key7=val7 key4=val7 key4=val8 
sign_out
buy
show_items
help whoami
which_group
register_user user9 pass9
current_folder
pwd
current_folder
rename_user user8 <function generate_user at 0x027087F0>
show_folders
cd folder1
show_users
add_item_property item4 key5=val9 key1=val6 key8=val5 key3=val1 
add_item_property item4 key1=val4 key10=val7 key4=val6 key5=val4 
which_group
show_folders
sign_in a4 pa4
sign_in user2 pass2
show_item_properties item3
whoami
add_item_property item5 key1=val7 key1=val2 key10=val2 key6=val8 
whoami
ls_folders
cd folder3
buy
add_item_property item3 key3=val3 key9=val2 key6=val8 key1=val2 
help buy
show_folders
show_users
buy
add_item_property item3 key2=val5 key10=val10 key1=val7 key7=val9 
sign_in user5 pass5
create_folder folder5
add_item_property item2 key3=val3 key4=val9 key8=val8 key3=val8 
pwd
sign_in admin admin
add_item item3 key7=val8 key9=val3 key1=val3 key6=val10 
show_folders
rename_user user6 <function generate_user at 0x027087F0>
rename_user user6 <function generate_user at 0x027087F0>
help view_order
add_item_property item2 key8=val6 key8=val3 key9=val2 key7=val8 
ls_folders
whoami
rename_user user0 <function generate_user at 0x027087F0>
register_admin user8 pass8
cd folder3
show_items
ls_folders
register_user user7 pass7
show_folders
which_group
ls
rename_user user8 <function generate_user at 0x027087F0>
sign_in user7 pass7
put item3
ls
buy
register_admin user8 pass8
show_folders
ls
which_group
buy
ls_folders
show_items
show_users
add_item_property item5 key7=val5 key2=val5 key1=val5 key6=val2 
current_folder
show_folders
ls_folders
register_admin user8 pass8
which_group
cd folder5
show_item_properties item3
add_item_property item4 key4=val5 key9=val10 key8=val9 key2=val4 
put item5
which_group
show_item_properties item2
sign_in a3 pa3
register_admin admin admin
add_item_property item4 key6=val1 key8=val8 key5=val7 key2=val6 
register_user user5 pass5
sign_in a1 pa1
register_admin user5 pass5
show_users
register_admin user7 pass7
sign_out
show_users
add_item item2 key2=val1 key3=val4 key2=val5 key5=val3 
show_items
sign_in a1 pa1
help create_folder
whoami
sign_out
sign_in a3 pa3
sign_in user2 pass2
buy
ls_folders
show_items
register_admin user4 pass4
current_folder
create_folder folder1
cd folder2
show_folders
rename_user user9 <function generate_user at 0x027087F0>
ls_folders
buy
cd folder1
help sign_in
current_folder
add_item_property item5 key4=val8 key2=val8 key9=val5 key10=val10 
show_folders
sign_in a2 pa2
current_folder
create_folder folder1
ls
show_item_properties item2
which_group
show_users
sign_in user9 pass9
ls_folders
show_items
ls_folders
show_item_properties item3
